### ISSUE TITLE
Possible new feature similar to dnsmasq's --dnssec-no-timecheck

### ISSUE THREAD

**Issue by lancethepants** [jedisct1/dnscrypt-proxy#108]
Dnsmasq with the addition of dnssec also requires the correct time to be available when dnssec is enabled. 
Dnsmasq's solution for embedded devices adds a startup parameter "--dnssec-no-timecheck", which allows dnsmasq with dnssec enabled to function before the time is set.
Once the time has become available, sending a SIGHUP to the process tells the daemon to then starting validating dnssec queries against the time (and also clears dns cache).
I know dnscrypt has the hostip program to help with the time issue, but after I implemented dnssec in tomato firmware, I see this solution work very nice. It allows immediate internet access once wan connection is up. The hostip method delays everything until the ntp process realizes it can get the time, and finally sets it.
Would you consider implemented similar functionality in dnscrypt for use in embedded systems?

**Comment by jedisct1** [comment]
A `--ignore-timestamps` switch was added.
