### ISSUE TITLE
dnscrypt-proxy 1.4 broken on iOS

### ISSUE THREAD

**Issue by spas123** [jedisct1/dnscrypt-proxy#138]
Hello,
I'm using iOS 5.1.1 on iPhone 4.
I used dnscrypt-proxy 1.0 for years without any issues.
I've just updated dnscrypt-proxy for iOS from 1.0 to 1.4.0. It crashes instantly with "Segmentation fault". I also tried version 1.3.2 but the result is the same- "Segmentation fault". I added user "_dnscrypt-proxy" to the system but dnscrypt-proxy still crashes.
Any ideas what is going wrong? Where can I get version 1.0 from?
Thank you in advance!

Best regards,
Spas

**Comment by jedisct1** [comment]
`launchctl` logs to the syslog daemon, but unfortunately not on iOS.
Still, you should get some output in `/tmp/DNSCrypt.log` in your case. You can also add the `--logfile=` option to the `dnscrypt-proxy` command-line to get logs from the proxy.

I just tested on my good old iPad running iOS 5.1.1, with `dnscrypt-proxy 1.6.0` and it runs just fine, even via `launchd`.
Maybe I will add iOS binaries to the download section again, especially now that `libsodium` is statically linked.
