### ISSUE TITLE
Feature Request: dnscrypt-proxy should limit repeated log activity during lost net connections.

### ISSUE THREAD

**Issue by M-Shell** [jedisct1/dnscrypt-proxy#156]
Sometimes net connections are not always available. This is especially true
for wireless links where dnscrypt-proxy is particularly applicable.

When dnscrypt-proxy loses its connection the DNS server, it endlessly fills
the system log with messages such as:

Oct 27 23:17:25 localhost dnscrypt-proxy[32129]: Unable to retrieve server certificates
Oct 27 23:18:43 localhost dnscrypt-proxy[32129]: Refetching server certificates
Oct 27 23:18:58 localhost dnscrypt-proxy[32129]: Unable to retrieve server certificates
Oct 27 23:20:20 localhost dnscrypt-proxy[32129]: Refetching server certificates
.
.
.

After one or two such messages, dnscrypt-proxy should issue a message that
further error messages of this type will not be repeated until the connection
has been reestablished. Or at least provide an option to allow for such a
feature.

This way, if a connection goes down for a long period of time, dnscrypt-proxy
will limit itself to two or three log notices instead of filling the logs up.

  Cheers and thank you for creating dnscrypt-proxy,

  Mike Shell
  http://www.michaelshell.org

**Comment by michaelkeuter** [comment]
Or those messages 5 times a second, when the DSL connection was lost:

Mar  5 09:42:56 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:56 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:56 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:56 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:56 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:57 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:57 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:57 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:57 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]
Mar  5 09:42:57 localhost daemon.warn dnscrypt-proxy[1746]: sendto: [Network is unreachable]

I second the above wishes. Especially on embedded devices the growing logfile can cause some problems.

Michael Keuter
http://www.mksolutions.info

**Comment by jedisct1** [comment]
Even though the syslog server should take care of it, there is already a protection against repeated messages. c5f93c7592af532da4d521fb1b3b10926022d9af significantly reduces the allowed number of messages.
