### ISSUE TITLE
Description of --loglevel=<level> in doc

### ISSUE THREAD

**Issue by JeanEastcode** [jedisct1/dnscrypt-proxy#168]
Hi

I've had to debug dnscrypt a couple of time and always found myself struggling with the possible levels of ```--loglevel```, in the end had to look in the source to figure out the possibilities.

Would it be possible to add a short description in the man and readme.md ?

**Comment by taoeffect** [comment]
:+1:

**Comment by jedisct1** [comment]
Done in 9388db04344779a34e5c883da3c86ddff9eda93a
