### ISSUE TITLE
Unable to get server certificates 

### ISSUE THREAD

**Issue by amnesia112** [jedisct1/dnscrypt-proxy#174]
I can not  get this proxy to work I've changed resolver address tried different syntax and different port numbers I still get the error unable to retrieve server certificate I've been trying for the last week to get it work!

**Comment by jedisct1** [comment]
You shouldn't really have to change resolver addresses and ports. Giving a provider name should be enough:

    dnscrypt-proxy -R okturtles

What does the following command return on your system?

    drill -p 443 txt 2.dnscrypt-cert.fr.dnscrypt.org @212.47.228.136

Or if you just have `dig`:

   dig -p 443 txt  2.dnscrypt-cert.fr.dnscrypt.org @212.47.228.136

**Comment by amnesia112** [comment]
The first command returns saner error unable to retrieve certificates Don't have drillDig command returns connection timed out I'm using tails debain Linux system Thank you so much for your reply Sent using CloudMagicOn Mon, Jan 5, 2015 at 16:37,  Frank Denis <notifications@github.com> wrote:            You shouldn't really have to change resolver addresses and ports. Giving a provider name should be enough:

dnscrypt-proxy -R okturtles


What does the following command return on your system?

drill -p 443 txt 2.dnscrypt-cert.fr.dnscrypt.org @212.47.228.136


Or if you just have dig:

dig -p 443 txt  2.dnscrypt-cert.fr.dnscrypt.org @212.47.228.136

**Comment by jedisct1** [comment]
Are you running it over Tor? As far as I know, Tor doesn't support UDP.

**Comment by amnesia112** [comment]
Yes I am but I'm using tcp only and port 443 so that should work?Sent using CloudMagicOn Mon, Jan 5, 2015 at 18:27,  jedisct1/dnscrypt-proxy <reply@reply.github.com> wrote:            Are you running it over Tor? As far as I know, Tor doesn't support UDP.

**Comment by jedisct1** [comment]
It might change at some point but unfortunately, UDP is still required to retrieve the certificates. So you should not block port 443/UDP, at least for packets sent to the DNS resolver you are using.

**Comment by oldsharp** [comment]
Hi @jedisct1 ,

Is it possible to force dnscrypt-proxy to fetch server certificates over TCP?

I tried `--tcp-only`, but it still failed when retrieving server certificates.

I'm behind my company's firewall and UDP over port 443 is not allowed, and it's not possible to ask administrator to open the port for me.

However, TCP over port 443 is allowed:
```
$ dig +tcp -p 443 txt 2.dnscrypt-cert.opendns.com @208.67.222.222

; <<>> DiG 9.9.5-3ubuntu0.5-Ubuntu <<>> +tcp -p 443 txt 2.dnscrypt-cert.opendns.com @208.67.222.222
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37891
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 16384
;; QUESTION SECTION:
;2.dnscrypt-cert.opendns.com.   IN      TXT

;; ANSWER SECTION:
2.dnscrypt-cert.opendns.com. 3257 IN    TXT     "DNSC\000\001\000\000\220\160\175\185-\005\152\030`\228\150\168\145)\236[\155\205\019\166e\184bh\204\165\197\230M\026,\255\145\021?~Qtz\196t\2444\169\170Yf X\228\218a\020]\132\208\223I\140E\170\190}\002\237\025\191\186\250\252\146W\223\220h\199i\191\172$\148\205t?<\029If\019M\254,K\220\243\021qwDPeEcZU\149\181\191U\149\181\191Wv\233?"

;; Query time: 61 msec
;; SERVER: 208.67.222.222#443(208.67.222.222)
;; WHEN: Mon Oct 19 13:43:23 CST 2015
;; MSG SIZE  rcvd: 193
```
