### ISSUE TITLE
Please update windows binary

### ISSUE THREAD

**Issue by Cattze2015** [jedisct1/dnscrypt-proxy#175]
download.dnscrypt.org/dnscrypt-proxy/

dnscrypt-proxy-win32-full-1.4.1.zip 

where is 1.4.3?
or at least, pleae release working 1.4.3 .sln files(so I can build it under VS 2008.)

**Comment by jedisct1** [comment]
It currently requires msys2 and mingw, and the build script is `dist-build/msys2-win32.sh`.

Issues with some plugins were reported, so I want to investigate these before releasing new Windows binaries.

**Comment by Cattze2015** [comment]
1.4.3 windows zip found.
Thanks! Keep up a g00d w0rk! :)
