### ISSUE TITLE
Compile on QNX

### ISSUE THREAD

**Issue by heri16** [jedisct1/dnscrypt-proxy#179]
Do you have instructions to compile on Qt QNX or BB10? Or maybe hints on similar systems?

**Comment by jedisct1** [comment]
Hi!

It might work on QNX but I don't think anybody reported having done it before.

Did you try to compile at least libsodium on it? How did it end up? If the process didn't complete, please post some logs, and I'll do my best to understand how to make it compile and work on QNX.

**Comment by jedisct1** [comment]
Ping?
