### ISSUE TITLE
关于http://download.dnscrypt.org/dnscrypt-proxy/ 下载链接的问题

### ISSUE THREAD

**Issue by ZaneNiu** [jedisct1/dnscrypt-proxy#180]
开发者，你好！

      非常喜欢dnscrypt-proxy这个软件，我在 一个Goagent辅助工具中直接用批处理自动调用了http://download.dnscrypt.org/dnscrypt-proxy/里面的windows版下载地址，但每次版本更新，该链接就会失效，需要重新更改并打包，我想是否能在http://download.dnscrypt.org/dnscrypt-proxy/下载目录里，增加一个dnscrypt-proxy-win32-full-last.zip 文件或软连接，始终指向最新版本，这样再用第三方软件或脚本调用下载链接就不用总更改了。
      小小建议，不知能否满足，多谢！

**Comment by jedisct1** [comment]
The dnscrypt.org domain name is blocked by the GFW. But you can use http://download.dnscrypt.ovh/dnscrypt-proxy/ instead.

**Comment by Cattze2015** [comment]
How about adding /release folder on this GitHub, and move files to it?
I assume China can't block Github, right?

**Comment by nodje** [comment]
Don't assume, Chinese government can choose to block entirely Github if it sees it fit...

**Comment by jedisct1** [comment]
They did block Github already.
