### ISSUE TITLE
DNSCrypt-enabled resolvers reliability issue 

### ISSUE THREAD

**Issue by nodje** [jedisct1/dnscrypt-proxy#185]
This is not directly linked to dnscrypt-proxy software itself, but I think it would be good to provide a solution for a real case scenario for people to whom it really matters: typically when you live in a place where DNS is censored through poisoning.

This is my case and I've been using dnscrypt-proxy successfully to circumvent censorship.
I've had to block all DNS request through a local firewall except one IP:port to make sure I was resolving DN only through dnscrypt. (it turned out many pieces of software try to resolve DN on their own)

Unfortunately, for some reason, it often stops working (every couple of days). At first I thought it was censorship being able to detect encrypted connection. It turned out it wasn't, the main problem it seems is that open DNSCrypt-enabled resolvers are often victims of DOS attacks which makes them inaccessible, which in turn makes your whole LAN unable to access internet.

It could also be due to network problems, but generally what I do in this cases, is manually stop the dnscrypt daemon and try another resolver. Highly inconvenient and time consuming but it works. (I gave up long ago to try to get the lowest latency resolver, these days I'm just trying to get one that works!)

There's no solution in the near future to prevent DOS attacks. Hosting a private resolver in a non censored place, secured to answer only requests coming from a fixed IP or a range of IP could be the ultimate solution, but it's probably out of the scope for most people.

When one want to use DNSCrypt for a small organization, it has to used in combination with a DNS cache. Unbound is the one given as example on http://dnscrypt.org/.
I'm thinking a pragmatic solution would be to have fail-over between resolvers.
I haven't been able to configure unbound for this. Simply adding forward-zone didn't seem to work:
```
forward-zone:
  name: "."
  forward-addr: 127.0.0.1@40
  forward-addr: 127.0.0.1@41
```
Is there a way to add a timeout option like for /etc/resolv.conf so that Unbound would fail-over to the next resolver?

This is just an idea, I'd be glad to have it working, possibly with another DNS cache, but other ideas are welcome. In any cases, a working solution should be hinted at on http://dnscrypt.org/.

**Comment by arabesc** [comment]
Hi!
I had the same issue some time ago. It seems that you run Unbound version which has a bug. There is one workaround and one solution for this issue.
Workaround. Run your dnscrypt-proxy services on different ip-addresses instead of different ports. Make several aliases for 127.0.0.1.
Solution. Update your Unbound to a version which will include [this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=194954) fix.

**Comment by nodje** [comment]
nice, good news!

I've [found this option](https://unbound.net/pipermail/unbound-users/2012-July/002483.html) that could also be helpful to make sure unbound get an answer if all dnscrypt-proxy fail (be it poisonned or not):
```
forward-zone:
  name: "."
  forward-addr: 127.0.0.1@40
  forward-addr: 127.0.0.1@41
  forward-addr: 127.0.0.1@42
  forward-first: yes
```
but apparently this may needs a timeout of several seconds. (it falls back on the root server if all else fails)

So this could then become a reliable solution, provided unbound can do a proper load-balancing or fail-over between forwards.

Other than that using the highly convenient dnsmasq could probably help. I'm thinking of putting it between a DNS caching server and dnscrypt-proxy. I'll do some research in this direction.
