### ISSUE TITLE
Long restart with GUI 1.0.5 DNSCrypt 1.4.3 on OS X 10.10.2

### ISSUE THREAD

**Issue by genimac** [jedisct1/dnscrypt-proxy#186]
I have noticed, after installing the gui and DNSCrypt, that when restarting or shutdown my MacBook Pro retina (late 2013) it takes near one minute to do. It keeps with a dark screen many seconds, then it appears the spin for long and finally it restarts or shutdown.
If I disable the DNSCrypt on the menu then both options are immediate.
Its only me, or have anyone experienced it? If someone have experienced and solved can share the info?
Thanks.

**Comment by justtemp** [comment]
This also happens for me too. The dark screen with a spinner shows up after shutdown and takes quite a while before it actually turns off.

**Comment by jedisct1** [comment]
Hi,

DNSCrypt itself doesn't change anything to your system. The GUI for OSX is a distinct project that I don't maintain and that I don't use any more.

Maybe ask on that project page: https://github.com/alterstep/dnscrypt-osxclient

Thanks,

-Frank.
