### ISSUE TITLE
Adding a couple of DNSCrypt servers to dnscrypt-resolvers.csv

### ISSUE THREAD

**Issue by Fusl** [jedisct1/dnscrypt-proxy#187]
Hi,

I replied [here](https://github.com/jedisct1/dnscrypt-proxy/issues/167#issuecomment-74358767) that all my servers can be added back. I wanted to make sure that someone notices my response and the servers find their way into the list, so I'm opening this issue now.

The list of servers can be found here: http://meo.ws/dnsrec.php

**Comment by Fusl** [comment]
In case you need a CSV file, I generated one:
https://scr.meo.ws/paste/2015-02-19-17-06-22-gmPcPUCZ.txt

**Comment by jedisct1** [comment]
Hi Fusl,

Looks like the server IP addresses are missing from the CSV file :(

You can check by adding the records to `dnscrypt-resolvers.csv` and run the proxy with your server names.

**Comment by justtemp** [comment]
@Fusl I hope that you can get the server IPs added soon! And by the way @jedisct1 the server IPs are available at a link that was posted earlier, http://meo.ws/dnsrec.php, but it probably would require some manual work putting them in, but it is very well worth it. I just can't wait to get these running, as they will be such a big contribution to the DNSCrypt project, and helps out many of us who need more privacy and security - the more servers the better. It's been nearly 2 weeks since anything has happened with this, I hope that these will soon be added to the resolvers list. Lets get this thing rolling soon! Thanks!

**Comment by ZimTester** [comment]
Wow do you even realize how much is it?.. (40 IPv4 + 68 IPv6) * 7 ports = **756** records for **dnscrypt-resolvers.csv**! Isn't it too much for the same servers? Maybe @jedisct1 have to decide to cut some ports and/or IPv6... And/or also have to rename all records with different ports and IPv6.
Anyway, it's a huge contribution, thank you @Fusl!

**Comment by Fusl** [comment]
> In this way, for fvz-rec-at-vie-01 server it will be opennic-at-vie-ns5 for IPv4 and opennic-at-vie-ns6 (or opennic-at-vie-ns6-ipv6) for IPv6. And so on.

That would be a real mess for me since I automatically generate this list from my deploy tool that only has fvz-rec-**-**-** stored as name and not the opennic-* one :(

Anyway... Looks like I missed the "Comment" button last time I wanted to update this, but here is the new list with IPv4-Adresses added: https://scr.meo.ws/paste/2015-03-05-11-16-01-HjBrDIlS.txt

**Comment by ZimTester** [comment]
Ah ok, it seems we have the same situation with **d0wn** servers, which is OpenNIC servers too.
I still think it's a good idea to mention this in a server Full name / Description, but thank @Fusl he already made it.
Thanks for new list!

**Comment by jedisct1** [comment]
Thanks for the updated list!

The way d0wn servers were named was actually a mistake; I had no idea that they were OpenNIC servers. And it's too late to change the names without breaking backward compatibility.

For the @Fusl servers, maybe we can still do something like `s/^fvz-rec-/opennic-/` for consistency with (most) other OpenNIC servers.

**Comment by Fusl** [comment]
If you want, I can prefix "fvz-rec-XX-XX-XX" with "opennic-" so it looks like "opennic-fvz-rec-XX-XX-XX"?

**Comment by jedisct1** [comment]
Sure.

**Comment by Fusl** [comment]
Updated list with a new server in Ireland and "opennic-" prefix for Full name: https://scr.meo.ws/paste/2015-03-08-02-58-52-LghAdsn1.txt

**Comment by jedisct1** [comment]
Merged, thanks a lot!

Too bad none of the OpenNIC servers seem to support DNSSEC :(

**Comment by Fusl** [comment]
> DNSSEC

Eww DNSSEC... http://sockpuppet.org/blog/2015/01/15/against-dnssec/

**Comment by jedisct1** [comment]
Always the same rants against DNSSEC by the same people. Meanwhile, responses signed with DNSSEC are still a security improvement over non-signed responses. ECC for DNSSEC is becoming widely supported, thanks to Cloudflare. Checking SSH server public keys with DNS without DNSSEC doesn't work. The argument that DDoS rely on DNSSEC is moot, even more with dnscrypt for the transport.
It's not perfect, one can dream about better solutions being deployed some day, but DNSSEC is available now, and provides benefits that just ranting about it doesn't provide.
