### ISSUE TITLE
Not protected with dnscrypt-osxclient-1.0.5 

### ISSUE THREAD

**Issue by benyola** [jedisct1/dnscrypt-proxy#188]
I am just installed the dnscrypt-osxclient-1.0.5.dmg. After the installation the client set the DNS-Server to fe80::1 (My Router I think) and the DNS-Crypt Staus is Backup. With tshark I see the DNS-Packets are not encrypted. I tried to disable IPv6, but then I haven't got any working DNS. Whats my problem and how to solve it?

![screen shot 2015-02-23 at 8 00 08 pm](https://cloud.githubusercontent.com/assets/11164422/6334739/e9f0787e-bb96-11e4-995e-31d690398a23.png)

![screen shot 2015-02-23 at 8 02 07 pm](https://cloud.githubusercontent.com/assets/11164422/6334758/ffd35e0e-bb96-11e4-9f2b-055d162ecd58.png)

**Comment by jedisct1** [comment]
Hi,

The screenshot you attached comes from a distinct project called OSX Client.

I don't maintain or use this any more, so you should open an issue on that project page instead: https://github.com/alterstep/dnscrypt-osxclient

Thanks.
