### ISSUE TITLE
Cannot build dnscrypt-proxy for arm64 architecture

### ISSUE THREAD

**Issue by pmo-19** [jedisct1/dnscrypt-proxy#190]
I have successfully build dnscrypt-proxy for amd64, i386 and armhf architecture in a Debian Ubuntu Launchpad PPA @ https://launchpad.net/~anton+/+archive/ubuntu/dnscrypt/+packages

However I can't build for the arm64 architecture. It looks like there is something weird in the configure (coming from configure.ac) script. The full build log is available at https://launchpadlibrarian.net/199452753/buildlog_ubuntu-trusty-arm64.dnscrypt-proxy_1.4.3-0pmo9.5~oldconf2~trusty_BUILDING.txt.gz

Do you have any insight on this architecture specific error ?

Here is the excerpt showing the failure. A detailed log of config.log follows at the above mentioned link.
```
config.status: executing libtool commands
=== configuring in src/libevent-modified (/build/buildd/dnscrypt-proxy-1.4.3/src/libevent-modified)
configure: running /bin/bash ./configure --disable-option-checking '--prefix=/usr'  '--build=aarch64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=${prefix}/lib/aarch64-linux-gnu' '--libexecdir=${prefix}/lib/aarch64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' 'build_alias=aarch64-linux-gnu' 'CFLAGS=-g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -O3 -Wall' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' '--disable-thread-support' '--disable-dependency-tracking' '--disable-libevent-install' '--disable-openssl' '--disable-shared' '--enable-function-sections' 'CC=gcc -std=gnu99' 'CFLAGS=-g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -O3 -Wall -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector-all -Winit-self -Wwrite-strings -Wdiv-by-zero' 'CPP=gcc -std=gnu99 -E' 'CPPFLAGS=-D_FORTIFY_SOURCE=2 -D_FORTIFY_SOURCE=2 -I/usr/local/include' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -L/usr/local/lib' 'LIBS=-ldl -lsodium -ldl -lm ' --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/build/buildd/dnscrypt-proxy-1.4.3/src/libevent-modified':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
configure: error: ./configure failed for src/libevent-modified
==> config.log <==
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.
```

**Comment by jedisct1** [comment]
Can you paste the `config.log` file that has the actual error?

**Comment by pmo-19** [comment]
Well, the build occurred on the Launchpad servers (Official building machines for Debian / Ubuntu). All that I get is this gz file which contains all the detailed content, however there is no access to the real config.log

The link to download it is : https://launchpadlibrarian.net/199452753/buildlog_ubuntu-trusty-arm64.dnscrypt-proxy_1.4.3-0pmo9.5~oldconf2~trusty_BUILDING.txt.gz

Can you download it ?

The arm64 build for libsodium went fine.

I am not sure the error comes from the source code, as the error reported looks "generic". This error is commonly reported when configure has no execute access on the C / C++ files (e.g. file system not compatible with UNIX), however I don't think its the case here.

As there is a lot more errors like this one

Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libitm --disable-libsanitizer --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-arm64 --with-arch-directory=arm64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu/Linaro 4.8.2-19ubuntu1) 
configure:4165: $? = 0
configure:4154: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4165: $? = 4
configure:4154: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.

**Comment by pmo-19** [comment]
Well, I am investigating an answer from Colin Watson (from the Launchpad team) as he did set up an emulated arm64 build environment on his vivid system using "mk-sbuild --arch=arm64
vivid" and attempted to build the package inside it.

As I said before I don't think it is coming from your software. I have had sort of "generic" errors in the past for omitting package dependency.

I will give a try to the answer of Colin Watson.

**Comment by pmo-19** [comment]
Success. On his machine Colin Watson got "Exit status 139" which is signal 11, that is, a segmentation fault. This is explaining the "gcc: fatal error: no input files" and the associated generic error. He instructed me to disable PIE to avoids this problem.

I updated the debian/rules accordingly and the build is now successful. However, I had to skip the Testsuite for the amr64 architecture. On all other architecture the Testsuite is successful.

By the way I saw that your own source debian folder is not up to date. How can I commit a change to your debian folder ?

**Comment by jedisct1** [comment]
Good to know! So all you had is add `--disable-pie`?

The Debian folder indeed needs some update. It doesn't even compile support for plugins :(

A pull request is the best way to commit changes to it!

Thanks,

-Frank.

**Comment by pmo-19** [comment]
Yes indeed. Sorry for the delayed answer, as I was busy on another project.

I had to add this Dash code in the debian rules

# At least emulated arm64 builds have trouble with PIE, so disable it there.
DEB_HOST_ARCH ?= $(shell dpkg-architecture -qDEB_HOST_ARCH)
confflags :=
ifeq ($(DEB_HOST_ARCH),arm64)
confflags := --disable-pie
endif

Then add $(conflags) as argument to the dh_auto_configure

As well I had to skip the Testsuite (only for the arm64 architecture) as it fails on the Launchpad build server.

# Tests may fail on build servers and aren't useful in release builds anyway
# [NOTE]: Testsuite summary for libevent 2.0.22-stable (one test) is failing for arm64
override_dh_auto_test:
ifneq ($(DEB_HOST_ARCH),arm64)
	dh_auto_test
endif

That way the arm64 build is successful :-)

I will consider later an update on the debian folder here.

Pascal
