### ISSUE TITLE
CryptDNS automatically change DNS from OpenDNS to Provider DNS

### ISSUE THREAD

**Issue by fervi** [jedisct1/dnscrypt-proxy#192]
Hello!

I have a problem with DNSCrypt

I installed DNSCrypt-proxy with the Debian Sid repository, it works quite well in general, but I have a problem - after some time DNSCrypt switches from OpenDNS to DNS provider

Perhaps this is due to misconfiguration DNSCrypt, I do not know - so please contact me by private message, I will then XMPP address. Maybe it's not a bug, but something seems wrong to me:-)

I made a simple script that pings the address "www.google.pl" every minute.
* .static.ip.netia.com.pl Address is the address of my provider (213.241.87.18)
* cache.google.com (77.252.2.89) is at Google (OpenDNS)

Suddenly he DNSCrypt or any application (Wicd? DHCP Client?) Changes each DNS server on my provider, but in the settings Wicd and resolv.conf I set everything on 127.0.2.1, 127.0.0.1, 127.0.0.2

The first file is to ping the DNS server provider, the 110 line restarts dnscrypt-proxy (/etc/init.d/dnscrypt-proxy restart), the ping is redirected to cache.google.com. The 142 line again returns to the address of the provider. The 160 line again restarts the server to the 181 line was redirected again

http://gmclan.org/up6184_0_skryptb4fb6.html

**Comment by fervi** [comment]
Ok, it's WICD fault, when i change it to Network manager - DNSCrypt start working propertly

**Comment by fervi** [comment]
Reopen, this isn't WICD issue, on NM i have it also

**Comment by jedisct1** [comment]
Hi Fervi,

`dnscrypt-proxy` doesn't change anything to the network configuration. It listens to a local port and forward the queries, but it doesn't have the ability to touch anything to the running system and it doesn't interact with WICD or Network Manager in any way.

You need to make sure that the IP address of your DNS is being set to `127.0.0.1` or to whatever you configured for the local resolver or for the proxy.

Presumably what is reverting the changes is a DHCP client, retrieving this information from the router.

**Comment by fervi** [comment]
@jedisct1 I have no idea what is wrong, so i close this thread.
