### ISSUE TITLE
Magic string in query and response

### ISSUE THREAD

**Issue by mcmallar** [jedisct1/dnscrypt-proxy#195]
Hi,

I am sorry if I am posting to wrong forum but this is the only part that I could find to ask my question. I am doing some research about the DNSCurve and I have run Wireshark to capture the dnscrypt-proxy traffic between the client and server. What is bugging me is the so called magic string in queries and responses. As per the IETF memo (https://tools.ietf.org/id/draft-dempsky-dnscurve-00.txt) and DNSCurve page (http://dnscurve.org/in-implement.html), the magic string in the query should be Q6fnvWj8 and in the response R6fnvWJ8.

However, Wireshark shows different data. While reply from the server is similar (being r6fnvWj8), the queries are completely different and vary whether I use dnscrypt-proxy in Windows or Linux. I'd be grateful if someone can shed some light on why this is so and how can I make sure the packet really contains DNSCrypt data or something else using only network sniffing tools.

Thanks.

**Comment by jedisct1** [comment]
DNSCrypt and DNSCurve are different protocols, with different purposes.

DNSCurve authenticates responses sent by an authoritative servers to a recursive server, whereas DNSCrypt authenticates responses sent by a recursive server to a client (local/stub resolver).

DNSCurve "magic" sequence is not hardcoded. For a given provider, each certificate has a different "magic" sequence. This is useful for key rollovers, where 2 or more certificates can be used at the same time.
So, each certificate includes a public key, supported versions, and the magic to be sent by the client when sending a query using this certificate.

The protocol is described here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/TECHNOTES

**Comment by mcmallar** [comment]
Thanks. That was quick...

Sorry, I've mixed things a bit  - I thought DNSCrypt was directly linked to DNSCurve project. This makes some things clearer for me now. Since the query magic string is basically random (based on the client key that is always different for every runtime), is there any way of detecting DNSCrypt through the packet information?

**Comment by jedisct1** [comment]
There is no easy way to do so, and the intent is to eventually make it ever more difficult to fingerprint.

**Comment by mcmallar** [comment]
OK, thank you for your time and responses. I'll close the issue now.
