### ISSUE TITLE
Wrong location name in dnscrypt-resolvers.csv

### ISSUE THREAD

**Issue by fourzerofour** [jedisct1/dnscrypt-proxy#197]
`d0wn-ch-ns1,d0wn server in Switzerland,Server provided by Martin 'd0wn' Albus,Singapore,,https://dns.d0wn.biz,1,no,yes,yes,179.43.143.69:54,2.dnscrypt-cert.d0wn.biz,9970:E22D:7F6C:967F:8AED:CEEB:FBC1:94B9:AF54:376E:2BF7:39F1:F466:CBC9:AFDB:2A62,`

'Singapore' should be 'Switzerland'

**Comment by jedisct1** [comment]
Good catch. Fixed, thank you!
