### ISSUE TITLE
DNS request timed out. time out was 2 seconds.

### ISSUE THREAD

**Issue by nv-zs-aa** [jedisct1/dnscrypt-proxy#198]
Hi! I have problems with DNScrypt-proxy-win32. 
this is what i did :

![untitled](https://cloud.githubusercontent.com/assets/11894404/7099570/f88e7004-e01f-11e4-9ad7-f782de42db71.jpg)

then i changed my DNS to 127.0.0.7 after that i tried to nslookup reddit.com and then i got this one :

![untitled](https://cloud.githubusercontent.com/assets/11894404/7099585/5f12cb86-e020-11e4-8bea-61e19f761c96.jpg)

please help me to figure it out.

edit : i can access github.com without any single problem, but i cant open any other websites.

**Comment by jedisct1** [comment]
`127.0.0.7` is a bit unusual. I'm curious about why you chose that IP. Sure, it's reserved for local use, but I'm not sure if Windows handles it like `127.0.0.1` by default.

Did you try with `127.0.0.1`?

**Comment by nv-zs-aa** [comment]
i've tried to change the IP address from 127.0.0.1 - 127.0.0.9 but all of them have the same result.
i checked my router, i found that actually my machine have successfully made a connection to 208.67.220.220:443 (OpenDNS), but idk why my machine has not yet received the DNS queries.

**Comment by jedisct1** [comment]
Did you try with other DNS services?

**Comment by 1crossover** [comment]
i have the same problem, but when i Use Google DNS servers instead of 127.0.0.1 everything works. Please help.

**Comment by 1crossover** [comment]
do i need to open ports?

**Comment by jedisct1** [comment]
Yes, you need to make sure that port 443 is open, both on TCP and UDP. Check that you don't have anything blocking port 443, including over UDP.

**Comment by 1crossover** [comment]
To open port 443 do i have to go into my router settings?

**Comment by 1crossover** [comment]
Port 443 is open but 53 is blocked

**Comment by jedisct1** [comment]
Ok. Let's start by looking at what the proxy says when you are starting it. Can you try the following command in the proxy folder?

    dnscrypt-proxy -R dnscrypt.org-fr -t 0

**Comment by 1crossover** [comment]
E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>dnscrypt-proxy -R dnscrypt.org-fr -t 0
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate #808464433 received
[INFO] This certificate looks valid
[INFO] Server key fingerprint is 4A96:7AF8:6B84:922E:DF98:402A:57DE:DFFA:6EBB:FC
A7:9ABC:AFE2:E584:B14C:A9A0:1464

E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>

**Comment by jedisct1** [comment]
Excellent! Now try again without the `-t 0`:

    dnscrypt-proxy -R dnscrypt.org-fr

Keep the command line window open and change your DNS settings to `127.0.0.1`. Does the Internet work?

**Comment by 1crossover** [comment]
E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>dnscrypt-proxy -R dnscrypt.org-fr
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[ERROR] Unable to bind (UDP) [Address already in use [WSAEADDRINUSE ]]

E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>

**Comment by jedisct1** [comment]
These commands must be run in an elevated command prompt https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown#how-to-open-an-elevated-command-prompt

**Comment by 1crossover** [comment]
My internet works when i change it to 127.0.0.1 

i am running command prompt as administrator 

when i go to www.opendns.com/welcome it says

Oops…
You aren’t using OpenDNS yet.
Let’s fix that.
If you haven’t restarted your computer yet,
please do that now.

and internetbadguys.com is showing as a demonstration site not phishing

**Comment by jedisct1** [comment]
Great! So everything seem to work. Looks like you don't have any problems with anything blocking the required port.
Presumably, what happened is that you tried to install the service without being in an elevated command prompt.

So, let's try installing the service. Close the previous window, open a new elevated prompt and type:

    dnscrypt-proxy -R dnscrypt.org-fr --install

Does it work?

**Comment by 1crossover** [comment]
what if it is already installed?

E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>dnscrypt-proxy -R dnscrypt.org-fr --install
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[ERROR] Unable to install the service
[ERROR] Make sure that you are using an elevated command prompt and that the service hasn't been already installed

E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>

**Comment by jedisct1** [comment]
Run

    dnscrypt-proxy --uninstall

first.

**Comment by 1crossover** [comment]
E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>dnscrypt-proxy --uninstall
[INFO] The dnscrypt-proxy service has been removed from this system

**Comment by jedisct1** [comment]
Looks great. Now run the `--install` command again.

**Comment by 1crossover** [comment]
E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>dnscrypt-proxy --install
[ERROR] Resolver information required.
[ERROR] The easiest way to do so is to provide a resolver name.
[ERROR] Example: dnscrypt-proxy -R mydnsprovider
[ERROR] See the file [dnscrypt-resolvers.csv] for a list of compatible public re
solvers
[ERROR] The name is the first column in this table.
[ERROR] Alternatively, an IP address, a provider name and a provider key can be
supplied.
[ERROR] Consult http://dnscrypt.org and https://github.com/jedisct1/dnscrypt-pro
xy/blob/master/README-WINDOWS.markdown for details.





E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>--install
'--install' is not recognized as an internal or external command,
operable program or batch file.

E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>

**Comment by 1crossover** [comment]
this is what i have written 

dnscrypt-proxy.exe -R "fvz-rec-ch-zu-01" -L "E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0\dnscrypt-resolvers.csv" --test=0
                                          
dnscrypt-proxy.exe -R "fvz-rec-ch-zu-01" -L "E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0\dnscrypt-resolvers.csv"  --install

**Comment by jedisct1** [comment]
The command you just typed before:

https://github.com/jedisct1/dnscrypt-proxy/issues/198#issuecomment-129692446

**Comment by 1crossover** [comment]
E:\DNSCrypt\dnscrypt-proxy-win32 1.6.0>--install
'--install' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jedisct1** [comment]
If you want to use the `fvz-rec-ch-zu-01` OpenNIC server:

    dnscrypt-proxy.exe -R fvz-rec-ch-zu-01 --install

See the documentation here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown#the-windows-service

All you have to do is:

    dnscrypt-proxy --uninstall
    dnscrypt-proxy -R <name> --install

With `<name>` being the name of the resolver you want to use, such as `cisco`, `dnscrypt.org-fr` or `fvz-rec-ch-zu-01`.

**Comment by 1crossover** [comment]
E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>dnscrypt-proxy.exe -R fvz-rec-ch-zu-01 --install
[INFO] - [fvz-rec-ch-zu-01] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[INFO] The dnscrypt-proxy service has been installed and started
[INFO] The registry key used for this service is SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameters
[INFO] Now, change your resolver settings to 127.0.0.1:53

**Comment by jedisct1** [comment]
So, if you can access the internet now, you're all set!

**Comment by 1crossover** [comment]
do i change my primary DNS in IPv4  to 127.0.0.1

**Comment by jedisct1** [comment]
Yes.

**Comment by clst** [comment]
I had the same issue with nslookup. It seems like a bug. dig from cygwin works fine yet nslookup claims timeout. DNS is working fine, btw. Manually setting the server to 127.0.0.1 also works with nslookup.

Example on Windows 7:

```
C:\>nslookup github.com
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  127.0.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out

C:\>nslookup github.com 127.0.0.1
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
Name:    github.com
Addresses:  192.30.253.113
          192.30.253.112


C:\>
```
