### ISSUE TITLE
Plugin path on windows

### ISSUE THREAD

**Issue by TheTaLlesT** [jedisct1/dnscrypt-proxy#200]
After cross compiling on Linux for Windows using mingw.
The program insists on trying to load the plugins from the path I compiled the program in on linux. 
Obviously this Linux path does not work on Windows. 
As I don't know how to properly fix this I just changed line -DPLUGINS_ROOT=\"$(pkglibdir)/\" to -DPLUGINS_ROOT=\"\" in the make files.
Now plugins load from the running dir on windows just fine.
How would you properly fix this?

**Comment by jedisct1** [comment]
Hi,

`./configure --libdir=...` should do the trick.

**Comment by TheTaLlesT** [comment]
Thanks for the fast reply!
I see pkglibdir is based off of libdir but I am only able to set it to an absolute path.
<code>configure: error: expected an absolute directory name for --libdir</code>
Though I suppose I could do this, being able to use a retaliative path is very convenient.

**Comment by jedisct1** [comment]
Done in 1.6.0.

On Windows, relative paths to the list of resolvers and to plugins are now relative to the application directory.
