### ISSUE TITLE
Server key fingerprint

### ISSUE THREAD

**Issue by th3m** [jedisct1/dnscrypt-proxy#201]
I try to test different servers before the installation of the service in windows, and while i am getting "this certificate looks valid", the server key fingerprint, i get in the end, is not the same with the "Provider Key-Public key" of the server i am using. The "Provider Key-Public key" that is provided in the dnscrypt-resolvers.csv file.

Am i doing something wrong, should i worry? Or there are just different values.

**Comment by jedisct1** [comment]
Hi,

This is totally expected, as these are different keys.

The provider public key is a long-term key, used to verify another key, which is hopefully rotated more frequently. The later is the "fingerprint".
