### ISSUE TITLE
compile issue "configure: error: libsodium >= 0.5.0 not found"

### ISSUE THREAD

**Issue by leandroong** [jedisct1/dnscrypt-proxy#204]
using latest beta 
- libsodium with commit last date 04-26-15
-dnscrypt-proxy with commit last date 04-21-15

error compilation on dnscrypt-proxy

**Comment by jedisct1** [comment]
Hi @leandroong ,

What error are you getting exactly?

**Comment by leandroong** [comment]
configure: error: libsodium >= 0.5.0 not found"

**Comment by jedisct1** [comment]
If this is on Linux, did you type `ldconfig` after installing libsodium?

**Comment by leandroong** [comment]
i compiled on ubuntu using static binary, source code for compilation available at https://github.com/lancethepants/dnscrypt-mipsel-static.
Lat successful compilation made on dnscrypt-proxy commit dated 04-21-15

Note: I don't do ldconfig

**Comment by leandroong** [comment]
BTW, it uses entware toolchain for compilation

**Comment by leandroong** [comment]
oops, I made successful dnscrypt comipilation on 04-19-15

**Comment by jedisct1** [comment]
This is weird.

There hasn't been any changes (except to `.travis.yml`) in dnscrypt-proxy since April 11. 
And the script you are running hasn't been touched since January 15.
Can you paste the `config.log` file?

**Comment by leandroong** [comment]
https://www.dropbox.com/s/n99nqsy0sds7xfu/config.log?dl=0

**Comment by jedisct1** [comment]
`/opt/entware-toolchain/lib/gcc/mipsel-linux-uclibc/4.6.4/../../../../mipsel-linux-uclibc/bin/ld: cannot find -lsodium`

Looks like sodium is not installed, at least not the mips version.

**Comment by leandroong** [comment]
Sudden change in compilation source code provided by lancetheparts. Looks like I have to wait for him to edit it. Thanks again
