### ISSUE TITLE
Problems with dnscrypt across 2 Users

### ISSUE THREAD

**Issue by hidden40** [jedisct1/dnscrypt-proxy#205]
I have dnscrypt installed on my Windows 7 machine and it works just fine under my user login. When I log off and my wife logs in the dns entry is not being transferred to her login and she can't get to the internet. I have to manually go into the TCP/IP settings and manually set the dns to 127.0.0.1 and then she's good to go.

Is there any workaround for this. I installed the program under my user login. The program is running when my wife logs in, but the dns is not being set. The field is blank.

**Comment by jedisct1** [comment]
Hi,

`dnscrypt-proxy` never changes your DNS settings.

This is a Windows configuration issue rather that something related to dnscrypt. Unfortunately I don't know much about Windows and I only have a Windows 10 virtual machine.

Maybe asking on a forum for Windows users would immediately get you an answer from people with more expertise.

Did you try setting the TCP/IP settings as an administrator? Maybe the administrator's configuration the one unprivileged users inherit from.

**Comment by hidden40** [comment]
My issue was resolved by turning on DHCP instead of using a fixed IP for my network card. It appears that 127.0.0.1 would not bind to another user's login, if I was using a fixed IP address. Everything is good now.
