### ISSUE TITLE
Dualstack incompatibility

### ISSUE THREAD

**Issue by Mikaela** [jedisct1/dnscrypt-proxy#206]
I have both IPv4 and IPv6 address. When I use dnscrypt-proxy, it appears that I am using only one OpenDNS server which is IPv4.

What if my IPv4 or IPv6 connectivity goes down and only the other stays up? This has happened to me once when my ISP cut important cable preventing IPv4 connectivity to other side of Finland and outside world and my IPv6 tunnel stayed up and had no issues.

Currently the workaround appears to be running multiple instances of dnscrypt-proxy, but I don't consider that as solution as there appears to be only one systemd service.

I think that the best solution would be allowing multiple DNS resolvers to be use with one instance (as opposed to /etc/resolv.conf that only allows three).

**Comment by jedisct1** [comment]
Hi Mikaela,

Running multiple instances is not that bad, if only because you may want to use different plugins with different providers or different IPs of the same provider.

Having a single instance manage multiple upstream providers would require the daemon to handle a failover mechanism, and this is really more of something that the caching server (or something like dnsdist) should do.

Do you know if the systemd service could be improved to handle multiple instances? Unfortunately I am not very familiar with systemd.

**Comment by Mikaela** [comment]
I am not very familiar with systemd either and I think multiple users also have issue with not knowing how to run multiple instances with it.

**Comment by jedisct1** [comment]
I awfully sorry, but honestly I don't know what do to about this, or what the exact problem is.

The proxy doesn't need systemd, and systemd can run the same service multiple times.

**Comment by Mikaela** [comment]
What to do with this might be easier to find out if someone who knew noticed this issue being open. The exact problem is documented in the original issue, dnscrypt-proxy is IPv4 or IPv6 -only and when either goes down, no DNS requets are made.

What does it help running the same service multiple times when they all only have the single resolver? I also think running the service multiple times fails, because the port is already in use.

**Comment by jedisct1** [comment]
Hi Mikaela,

Running multiple instances on the same port will indeed not work. Unlike the dnscrypt server, this client doesn't enable `TCP_REUSEPORT`.

Just use a different port and a different IP for each instance. The `--listen-address=` option let you set the local IP and port the proxy is going to listen to. That's without systemd. I don't know much about systemd, but I can't imagine it not allowing you to run the same application as 2 different services, listening to different ports.

In your Unbound configuration, use `<ip>@<port>` to forward queries to a specific port: http://dnscrypt.org/#dns-cache
