### ISSUE TITLE
Packaging: postrm does not call updaterc.d for init.d script (packages/debian/dnscrypt-proxy.init)

### ISSUE THREAD

**Issue by Shnatsel** [jedisct1/dnscrypt-proxy#208]
An /etc/init.d script which has been registered in the postinst script  is not de-registered in the postrm script.

Refer to Debian Policy Manual section 9.3.3.1 "Managing the links" (https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3) for details.

This is a complaint from lintian and affects sysvinit-based systems (i.e. Debian systems except Jessie).

**Comment by jedisct1** [comment]
Is it still relevant? Debian doesn't use sysvinit any more, does it?
