### ISSUE TITLE
Android armv7a warning

### ISSUE THREAD

**Issue by mosin** [jedisct1/dnscrypt-proxy#210]
When running the binary I compiled myself and running the binary I get the following warning:
[code]WARNING: linker: dnscrypt-proxy: unused DT entry: type 0x1d arg 0x5bd[/code]

Running Android 5.1.1 and used android ndk r10d and r10e - both produced the same result.

**Comment by jedisct1** [comment]
But does it work?

**Comment by mosin** [comment]
It works on my device but on the binary I posted on XDA, a user is having a "segmentation fault" and it exits.  I'm not sure if the two are related.  I confirmed the user is using the same architecture armv7a.
