### ISSUE TITLE
Running -t always gives invalid certificate grace period

### ISSUE THREAD

**Issue by adrnsoh** [jedisct1/dnscrypt-proxy#211]
For all servers in resolvers list

**Comment by jedisct1** [comment]
Hi!

Can you provide the full command-line you are using?

Here is an example of how `-t` should be used:

```bash
dnscrypt-proxy -R dnscrypt.org-fr -t 86400
```

**Comment by adrnsoh** [comment]
dnscrypt-proxy -t "opendns". My mistake

**Comment by jedisct1** [comment]
`-t <grace period>` checks if the certificate will still be valid in `<grace period>` seconds, which is useful when you are running your own server.
