### ISSUE TITLE
Unable to retrieve certificates

### ISSUE THREAD

**Issue by adrnsoh** [jedisct1/dnscrypt-proxy#212]
Could you add an option to change the local ports for dnscrypt? 

And an option to tunnel requests through SSH?

**Comment by jedisct1** [comment]
Hi,

The local port can already be changed, with the `--local-address` option:

    dnscrypt-proxy --local-address=127.0.0.1:5000 -R dnscrypt.org-fr

If you use a VPN or a SSH tunnel, dnscrypt is useless, as these already authenticate your traffic.

**Comment by adrnsoh** [comment]
I was unable to connect this morning with the error stated.

Assuming my ISP tried to block on their end, is there a way around it?

**Comment by jedisct1** [comment]
The error indeed means that the response to the initial DNS query didn't reach your network.
What provider are you using? Did you try other ones in the list?
Also make sure that you don't have a firewall blocking port 53 or 443 (UDP).

**Comment by adrnsoh** [comment]
All unblocked. Was a new Windows installation. Most likely the police / ISP was blocking it, trying to find a way around it.

**Comment by jedisct1** [comment]
Check your router...

I dont know of any ISP actually blocking it.
