### ISSUE TITLE
Can't access internet

### ISSUE THREAD

**Issue by calcu007** [jedisct1/dnscrypt-proxy#213]
I can't accces internet with dnscrypt disabled. I tried stopping it and uninstallling. The only way to use internet is enabling it. Anyway to fix it? I remember a error the first time I run it. It was about a JIT compilter. I am using win8.1

**Comment by jedisct1** [comment]
Go to the network preferences, look for the TCP/IP settings, and change the DNS server addresses.
You probably changed them to `127.0.0.1`. Use something else such as your ISP's DNS, or DHCP, or `8.8.8.8` (Google).

**Comment by calcu007** [comment]
Where I can check the TCP/IP settings? I have my router config with google servers

**Comment by jedisct1** [comment]
Check out https://iihelp.iinet.net.au/Manually_Setting_DNS_Server

**Comment by calcu007** [comment]
I have it in "obtain ip automatic"

**Comment by jedisct1** [comment]
Try manual and `8.8.8.8`
