### ISSUE TITLE
doc: man page is unclear of the loglevel settings

### ISSUE THREAD

**Issue by theking2** [jedisct1/dnscrypt-proxy#216]
The loglevel settings entry is unclear. LOG_INFO is not accepted as setting.

**Comment by jedisct1** [comment]
`LOG_INFO` refers to syslog log levels.

With rsyslog, `*.info` is going to match it. But there are many syslog systems (not to mention systemd) with a different syntax. `LOG_INFO` is the name as documented in `syslog(3)`.
