### ISSUE TITLE
Direct forward for localdomain.

### ISSUE THREAD

**Issue by huffery** [jedisct1/dnscrypt-proxy#217]
Direct forward for localdomain.

All my computers are in local domains. How can I do this:

*.localdomain1.com forward to 192.168.0.1

*.localdomain2.com forward to 10.1.1.1

(these addresses can not resolved by public dns servers)

Others to the public dnscrypt server.

Currently I use unbound to do this. Can I do it inside dnscrypt-proxy? 
Please add this function if not.

**Comment by jedisct1** [comment]
Using your local cache (unbound, dnsmasq, powerdns recursor, ...) is the correct way to do this, and duplicating this in dnscrypt-proxy doesn't really make sense.

On OSX, the OS has a built-in mechanism for this, documented in the `resolver(5)` man page.

You can create a file named `example.com` in `/etc/resolver` (you might have to create this directory first) with the following content:

    nameserver 10.1.1.1

And queries for `example.com` and `*.example.com` will use this name server.

You can have as many name servers as you want to each domain, and as many domains as needed; just create a file for each domain.
