### ISSUE TITLE
Commits are not being signed!

### ISSUE THREAD

**Issue by HacKanCuBa** [jedisct1/dnscrypt-proxy#220]
Since this is a security tool, ALL commits to this repo [**should** be _signed_](https://git-scm.com/book/es/v2/Git-Tools-Signing-Your-Work)!  

```
:~$ git log --pretty=format:"%h on %ad by %an (%G? 0x%GK): %s%d" --graph --date=short

* cf325f0 on 2015-06-03 by Frank Denis (N 0x): If compiled with --enable-plugins...
* 5921716 on 2015-06-03 by Frank Denis (N 0x): "Mobility" doesn't seem to be cal...
* bccfa2c on 2015-06-03 by Frank Denis (N 0x): Remove WARNING 
* 7f281d9 on 2015-06-03 by Frank Denis (N 0x): The IP address doesn't have to be...
* c5f93c7 on 2015-06-03 by Frank Denis (N 0x): Reduce the allowed burst of ident...
* 9388db0 on 2015-06-03 by Frank Denis (N 0x): Document log levels 
* 8c95ac0 on 2015-06-02 by Frank Denis (N 0x): Bump 
```
Where N indicate *no gpg signature*, and thus 0x remains empty.  This is critical, and it's free to implement :)  
We can then decide whether we trust on the coder signing it, but at least we can make sure who code what and when.  

Cheers!

**Comment by Mikaela** [comment]
I believe that signing tags is enough and signing all commits is widely disagreed about.

* http://stackoverflow.com/a/10166916
    * Linus Torvalds in second post http://git.661346.n2.nabble.com/GPG-signing-for-git-commit-td2582986.html
* On the other hand there is http://mikegerwitz.com/papers/git-horror-story.html

I would also trust the developers to make the choice whether to sign or not.

**Comment by HacKanCuBa** [comment]
Nice point, but:

```
git log --tags --show-notes --simplify-by-decoration --pretty="format:%ai %d %s (%G? 0x%GK)" 
2015-01-05 18:07:55 +0100  (tag: 1.4.3) Update ChangeLog (N 0x)
2014-12-03 15:02:27 -0800  (tag: 1.4.2) Update ChangeLog (N 0x)
2014-09-18 23:23:45 -0700  (tag: 1.4.1) Merge branch 'master' of github.com:jedi
2014-04-24 23:31:23 -0700  (tag: 1.4.0) Regen dnscrypt-resolvers.csv.sig (N 0x)
2013-08-13 20:39:50 -0700  (tag: 1.3.3) Regen man pages (N 0x)
```

Again, not even tags are being signed :S

**Comment by jedisct1** [comment]
Releases are signed, and I wouldn't encourage anyone to use the code in Git except if they are willing to contribute code.

But tags have been signed no matter what.
