### ISSUE TITLE
dnscrypt-proxy version identifier

### ISSUE THREAD

**Issue by bitbeans** [jedisct1/dnscrypt-proxy#224]
I`am looking for a way to determine the version for the currently installed dnscrypt-proxy.exe on windows.

There is no version in the binary description itself and also nothing in the used registry folder.
For client software which uses the binary, there should be a way to get the version.

**Comment by jedisct1** [comment]
Doesn't `dnscrypt-proxy -V` do what you want?

**Comment by bitbeans** [comment]
It does! Sorry i missed this parameter. :)

Close.
