### ISSUE TITLE
multiple listening addresses

### ISSUE THREAD

**Issue by raako71** [jedisct1/dnscrypt-proxy#225]
Is it possible to use two --local-address=127.0.0.1:53 fields? Hasn't worked for me. I want to use 127.0.0.1 and a LAN IP for remote LAN devices. My problem is the LAN address alone doesn't work when the LAN adapter isn't being used.

**Comment by jedisct1** [comment]
Sure, you can start multiple instances of dnscrypt-proxy, with different configurations.

**Comment by dnscrop** [comment]
You could use 0.0.0.0:53 for that.

**Comment by raako71** [comment]
I tried 0.0.0.0:53 which didn't work when I set my LAN DNS to my LAN IP. Also I tried using a second resolver as in the first solution with:
<pre>"C:\Program Files\DnsCrypt\bin\dnscrypt-proxy2.exe" -R opendns -L "C:\Program Files\DnsCrypt\bin\dnscrypt-resolvers.csv" --local-address=127.0.0.1:53 --install</pre>
but it didn't let me install the service twice. Not a problem though.. I'm just using the LAN IP which is sufficient, anything more would have been too complicated (auto switching to 127.0.0.1 when not on the LAN - currently the local DNS is set to auto as I have a DNS proxy on my LAN for WAN urls...)
