### ISSUE TITLE
DNS forwarded to dnscrypt-proxy from unbound with DNSSEC enabled fails

### ISSUE THREAD

**Issue by carbin** [jedisct1/dnscrypt-proxy#227]
This is on OpenBSD 5.8 GENERIC.MP#1097 amd64

unbound.conf

    server:
        interface: 127.0.0.1
        do-ip6: no

        do-not-query-localhost: no

        hide-identity: yes
        hide-version: yes

        # Uncomment to enable DNSSEC validation.
        #
        auto-trust-anchor-file: "/var/unbound/db/root.key"

    remote-control:
        control-enable: yes

    forward-zone:
        name: "."
        forward-addr: 127.0.0.1@5353

unbound-proxy launched with the command

    dnscrypt-proxy --local-address=127.0.0.1:5353 --resolver-name=opennic-fvz-rec-nz-auk-01 --plugin libdcplugin_example_logging.so --loglevel=1

When the command `dig example.com` is run, dnscrypt-proxy outputs:

    example.com	[A]
    example.com	[A]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]
    .	[0x30]

and `dig` returns:

    ; <<>> DiG 9.4.2-P2 <<>> example.com
    ;; global options:  printcmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 28733
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;example.com.			IN	A

    ;; Query time: 1127 msec
    ;; SERVER: 127.0.0.1#53(127.0.0.1)
    ;; WHEN: Thu Jun 25 10:13:55 2015
    ;; MSG SIZE  rcvd: 29

When the `auto-trust-anchor-file` is commented out of unbound.conf, everything just works as expected.

`dig example.com` causes dnscrypt-proxy to output:

    example.com	[A]

and `dig` returns:

    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46597
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;example.com.			IN	A

    ;; ANSWER SECTION:
    example.com.		5	IN	A	93.184.216.34

**Comment by jedisct1** [comment]
Hi Carbin,

`opennic-fvz-rec-nz-auk-01` doesn't support DNSSEC:

```
# dnscrypt-proxy  -R opennic-fvz-rec-nz-auk-01
[INFO] - [opennic-fvz-rec-nz-auk-01] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
```

Can you try with another one that actually supports DNSSEC such as `dnscrypt.org-fr`?

**Comment by carbin** [comment]
Yes, that would explain it. Sorry for wasting your time.

**Comment by carbin** [comment]
Just a side note though, it is a little counter-intuitive that the handy [INFO] note that would have answered my question for me is only displayed if logging is not enabled. When I was trying to figure out why it wasn't working I was trying to get more logs and never thought of running it with logging turned off...
