### ISSUE TITLE
Feature request: fallback to a multitude of resolvers

### ISSUE THREAD

**Issue by CrisBRM** [jedisct1/dnscrypt-proxy#228]
Usually, it's a matter of the resolver's server failing, which is in no way dnscrypt's fault, so I'd rather fallback to, dnscrypt.eu-dk, for instance, as opposed to an unencrypted, google backed dns.

**Comment by jedisct1** [comment]
Hi Cris,

Running multiple dnscrypt-proxy instances at the same time, with a different configuration, is totally fine.
So you can have one instance configured for `dnscrypt.eu-nl`, another one configured for `dnscrypt.eu-dk`, listening to different IPs (maybe `127.0.0.2` and `127.0.0.3`) and then configure your local caching server to use both IPs.

**Comment by CrisBRM** [comment]
I am aware, as I read the issue about parallelization, but it's not quite the same. Wouldn't that introduce some unecessary overhead?

**Comment by jedisct1** [comment]
It's unlikely to introduce any noticeable overhead. This is not going to require much extra memory either, as most pages will be shared across the processes.

**Comment by CrisBRM** [comment]
Fair enough. 
Is it possible on windows? I dualboot Funtoo and windows and have yet to try it on the latter.

**Comment by Mikaela** [comment]
Related: https://github.com/jedisct1/dnscrypt-proxy/issues/206

**Comment by hkmaly** [comment]
Still no progress? So, recommended way to use dnscrypt is to install several versions and then additional caching name server on top of them?

**Comment by licaon-kter** [comment]
Yep.
