### ISSUE TITLE
Can't build 1.5 on Debian Wheezy 

### ISSUE THREAD

**Issue by a9tm** [jedisct1/dnscrypt-proxy#230]
I'm trying to build 1.5 from source on Debian Wheezy x86_64, but it's failed at SYSTEMD checking

    # ./configure
    checking build system type... i686-pc-linux-gnu
    checking host system type... i686-pc-linux-gnu
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking how to create a ustar tar archive... gnutar
    checking whether to enable maintainer-specific portions of Makefiles... no
    ./configure: line 3264: syntax error near unexpected token `SYSTEMD,'
    ./configure: line 3264: `  PKG_CHECK_MODULES(SYSTEMD, libsystemd, have_systemd=yes,'

**Comment by jedisct1** [comment]
You need `pkg-config` to be installed!
