### ISSUE TITLE
Windows DNSCrypt doesn't work consistently

### ISSUE THREAD

**Issue by hamasakifanz** [jedisct1/dnscrypt-proxy#231]
I have used DNSCrypt on windows 8.1 for a while.
First time installing it didn't go smooth, and I had this problem for a while. Sometimes DNSCrypt works sometimes it doesnt.

Im using DNSCrypt 1.4.3 for my WIFI connection. I've tried installing using both command line and the GUI dnscrypt-winclient.exe. I've tried everything (restarting the dnscrypt-proxy service, modem, PC, my WIFI, ipconfig/flushdns, using different browsers) and it doesnt work. However sometime DNSCrypt miraculously works.

Can anyone help me troubleshooting here? I still can't open some blocked sites by my ISP such as reddit.com (it still redirects to internet-positif.org) . When it works, I can open the blocked sites.

nslookup reddit.com with DNSCrypt gives me this
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
Name:    reddit.com
Addresses:  198.41.209.139
          198.41.209.140
          198.41.208.137
          198.41.208.139
          198.41.208.142
          198.41.209.143
          198.41.208.140
          198.41.209.142
          198.41.209.138
          198.41.209.141
          198.41.208.143
          198.41.208.138
          198.41.209.136
          198.41.208.141
          198.41.209.137

without DNScrypt:
Server:  1.1.168.192.in-addr.arpa
Address:  192.168.1.1

Non-authoritative answer:
Name:    internet-positif.org
Address:  118.98.97.151
Aliases:  reddit.com

**Comment by jedisct1** [comment]
Hi,

The responses you get with dnscrypt are the correct ones, while the ones you get from Internet Positif are not Reddit's, but Internet Positif servers, as a way to block access.

So, at least, dnscrypt helps :)

Your browser may have cached the fake page from Internet Positif, returning it when you try to access Reddit, without even performing any DNS queries. So, try to flush the browser cache or run it in incognito mode to see if it helps.
On the DNS side, everything looks fine!

By the way, the current version of DNSCrypt is 1.5.0.

**Comment by hamasakifanz** [comment]
Thanks for the fast reply,

I've tried your solution in 2 different browsers (clearing browser cache in Firefox and IE, then try to open reddit.com in incognito) and both didn't work. Any other solutions? 
TBH, I'm confused by the fact that nslookup can get the IP of the DNS, but still redirected to internet-positif.org when browsing.

Thanks.

**Comment by jedisct1** [comment]
Another possibility is that you have a HTTP proxy configured. Can you check on https://www.whatismyip.com/ that the IP you get is your own external IP?

**Comment by hamasakifanz** [comment]
No I dont use proxy (neither on both browser and system)and yes that's my external IP address

**Comment by jedisct1** [comment]
Is `127.0.0.1` the *only* resolver listed for all the network interfaces?

**Comment by hamasakifanz** [comment]
Do you mean like this http://i.imgur.com/a9wT4vJ.png ?

**Comment by jedisct1** [comment]
At this point, I absolutely don't know what else to look for :(
Unless Internet Positif went a bit further than just hijacking DNS queries and are now also redirecting IP traffic.

**Comment by hamasakifanz** [comment]
My friend uses DNSCrypt and can bypass Internet Positif. Moreover sometimes after turning off both PC and modem for a while DNSCrypt works and I can bypass InternetPositif... That's why probably there's a bug or something

**Comment by jedisct1** [comment]
The only thing I can think about at this point is that InternetPositif is intercepting HTTP traffic.

Your best option in that case is to use a VPN.
