### ISSUE TITLE
Unable to resolve domain name 

### ISSUE THREAD

**Issue by peterwkc** [jedisct1/dnscrypt-proxy#232]
Dear all,

I had installed dnscrypt-proxy and unbound from packages on OpenBSD 5.7 release. 
The dnscryt-proxy was unable to resolve the domain name when it works together with unbound. I had tried several dns resolveds near to my location such as opendns, cloudns-syd, cloudns-can but it still cannot resolved the domain name. How ot troubleshoot this kind of error? 

dnscrypt-proxy command:
dnscrypt-proxy -a 127.0.0.1:444 -R "cloudns-syd" -l /var/log/dnscrypt-proxy.log -U "_dnscrypt-proxy" 

Unbound Configuration:
forward-zone:
name: "."
forward-addr: 127.0.0.1@444

Please help to diagnose this error. 

Thank.s

**Comment by jedisct1** [comment]
Hi,

If you are using `127.0.0.1`, the Unbound configuration also requires:

    do-not-query-localhost: no
