### ISSUE TITLE
Add SOCKS4/4A/5 Proxy support

### ISSUE THREAD

**Issue by espress0** [jedisct1/dnscrypt-proxy#234]
https://github.com/jedisct1/dnscrypt-proxy/issues/229

This is not about only Tor.
Please add SOCKS proxy support.

--proxy=socks5 --pserver=10.20.30.40:5678 --puser=company.proxy --ppass=aeyf79f4f7wbnyrg7s

**Comment by CHEF-KOCH** [comment]
_bump_ :laughing: :tongue:

**Comment by jedisct1** [comment]
This is unlikely to be added to the proxy in the near future. An independent TCP->Socks proxy such as Redsocks can probably do the job, so I don't think this is something that should be built-in.
