### ISSUE TITLE
Router w/ Shibby: Configuration

### ISSUE THREAD

**Issue by YeOldHinnerk** [jedisct1/dnscrypt-proxy#236]
Hi,
well, let me apologize first for my questions. I know they are fairly basic, but I have tried to read up on the issues a bit, including nut not limited to Wikipedia, Shibby-related forums and here. But I still don't understand properly and somehow feel that there are just too many closely related terms, where I'm never quite sure if two things are the same or not...

Ok, so here's my setup: I'm using a router with the latest Shibby firmware on it. This is only for my private home network, so nothing fancy. It includes dnscrypt and a graphical interface to it. But I'm never quite sure, how these setting stand in relation to the other DNS settings:

- If I use a dnscrypt-proxy (dnscrypt.en-nl), do I still need to configure static DNS? If so, can I choose any or am I limited in choice due to my choice of the dnscrypt-proxy? Even more basic, is the resolver something distinct from a DNS server with extra features?
- My understanding is that with the resolver I chose, it is ok to also enable DNSSEC.
- Shibby also employs dnsmasq. Settings can be found under Advanced->DHCP/DNS. Is there a conflict between dnsmasq and dnscrypt? What do I need to avoid?
- There are some checkboxes which DNS are to be used:
   * Use internal DNS	
   * Use received DNS with user-entered DNS	
   * Prevent DNS-rebind attacks	
   * Intercept DNS port (UDP 53)
I checked 1,3 and 4. Are these the proper choices?

Thank you,

YeOldHinnerk

**Comment by jedisct1** [comment]
Tomato Shibby offers really good support for dnscrypt-proxy, so:
- You don't need to add any extra static DNS
- If you use a resolver that supports DNSSEC, it's totally fine, and actually an excellent idea to enable it on the router as well. And yes, dnscrypt.en-nl does.
- No conflicts between dnsmasq and dnscrypt, thanks to the great integration work done in Tomato Shibby
- And you picked the proper choices :)

**Comment by YeOldHinnerk** [comment]
Thank you for the fast and excellent answer. And even without any taunting because the basic nature of my questions. Thank you.
