### ISSUE TITLE
Add OpenDNS at 208.67.222.222 to dnscrypt-resolvers.csv ?

### ISSUE THREAD

**Issue by abelbeck** [jedisct1/dnscrypt-proxy#237]
Should the dnscrypt-resolvers.csv include an entry for OpenDNS at 208.67.222.222 ?

It does work.

In our AstLinux project we recently added support for optionally running a second instance of dnscrypt-proxy and it would seem using both 208.67.220.220 and 208.67.222.222 would be a good thing.

Thoughts?

**Comment by jedisct1** [comment]
Useless. The extra IPs are just for routers that *require* 2 DNS servers, but they go exactly to the same load balancer, and if one is unreachable or is unable to resolve something, the other one is unlikely to be any different.

**Comment by davidu** [comment]
This is no longer entirely true.

I would advise 208.67.220.220 and 208.67.222.222 -- and for future
diversity, you can add: 208.67.220.222 and 208.67.222.220

-David

**Comment by abelbeck** [comment]
@davidu thank you for chiming in, much appreciated info.  Here is hoping OpenDNS's DNSCrypt will become ubiquitous with Cisco's involvement.
