### ISSUE TITLE
Add dns.watch

### ISSUE THREAD

**Issue by exodius48** [jedisct1/dnscrypt-proxy#238]
Can you add dns.watch support?

**Comment by jedisct1** [comment]
Do their servers support DNSCrypt? I couldn't find any informations about this on their web site.

If you know what the parameters are, they can of course be added (or feel free to submit a pull request an additional line for the CSV file).

**Comment by jedisct1** [comment]
dnswatch can be added, but they have to add support for the protocol.

It's really easy to do, see http://dnscrypt.org/#dnscrypt-server - But they have to do it.
