### ISSUE TITLE
FYI: CPU load with --ephemeral-keys

### ISSUE THREAD

**Issue by abelbeck** [jedisct1/dnscrypt-proxy#239]
Our project uses dnscrypt-proxy on embedded hardware, so how CPU intensive is enabling --ephemeral-keys ?

In an attempt to answer this question we use the combo of dnscrypt-proxy and dnsmasq as the local DNS server, running on an Intel Atom, 1.8 GHz class CPU.  The standard 208.67.220.220:443 OpenDNS server was used by dnscrypt-proxy.

Behind that we generate a lot of unique DNS requests using this test tool:

DNS Nameserver Spoofability Test
https://www.grc.com/dns/dns.htm

The CPU load of dnscrypt-proxy was observed via "top -d1".

Results:
“Ephemeral Keys” Enabled: 2.9% → 3.2% (peak) of the CPU (core) is used.
“Ephemeral Keys” Disabled: 0.1% → 0.2% (peak) of the CPU (core) is used.

**Comment by jedisct1** [comment]
Thanks for the benchmark!

A CPU increase when using ephemeral keys is expected, and this is why it is not being enabled by default.

Still, 3.2 % peak when running a benchmark doesn't seem terribly high. Hope it's acceptable for your use case!

Thanks again for providing these interesting numbers!

**Comment by abelbeck** [comment]
Yes, 3.2 % for Atom class CPU's is typically fine.  To be more clear, top's results would imply the particular core/thread would be 4x or 12.8 % for the core/thread dnscrypt-proxy is on,  3.2 % across all total cores/threads.

Though the older single core 500 MHz AMD Geode class would most likely be too expensive.

Disabled by default is a good choice.  I can't say enough how useful dnscrypt-proxy is.
