### ISSUE TITLE
--ephemeral-keys removed?

### ISSUE THREAD

**Issue by neocronx** [jedisct1/dnscrypt-proxy#241]
http://dnscrypt.org/

According to dnscrypt.org:

"sudo dnscrypt-proxy --ephemeral-keys --resolver-name=<resolver name>"

--ephemeral-keys is no longer recognized by dnscrypt-proxy software via Linux.

root@debian:/home/<redacted>/Desktop/dnscrypt-proxy-1.4.3# dnscrypt-proxy -R adamas --ephemeral-keys
dnscrypt-proxy: unrecognized option '--ephemeral-keys'
dnscrypt-proxy 1.4.3

Was this removal intentional? If so then please update the instructions via dnscrypt.org - thanks!

Thanks!

**Comment by jedisct1** [comment]
`--ephemeral-keys` didn't exist in version `1.4.3`. It was introduced in version `1.5.0`.

The current stable version os `1.6.0` and it still has it!

**Comment by neocronx** [comment]
Intesting, I was only able to find 1.4.3 via resp. Can you provide me the link? Thanks.

**Comment by jedisct1** [comment]
Via resp?

Releases are always available here: https://download.dnscrypt.org/dnscrypt-proxy/

**Comment by neocronx** [comment]
Sorry.. my fault.. I didn't scroll down enough to see 1.6.0 :(.
