### ISSUE TITLE
[FreeBSD] Shared object "libsodium.so.13" not found, required by "dnscrypt-proxy"

### ISSUE THREAD

**Issue by steakknife** [jedisct1/dnscrypt-proxy#242]
The issue is ldconfig rc.d script must run *before* dnscrypt-proxy, not after.

Fix is to modify `/usr/local/etc/rc.d/dnscrypt-proxy` to as follows to remove the circular dependency which breaks rcorder.

```shell
# PROVIDE: dnscrypt_proxy
# REQUIRE: cleanvar
# BEFORE: SERVERS
# KEYWORD: shutdown
```

**Comment by jedisct1** [comment]
Hi,

And thanks for reporting this.

Unfortunately, I don't maintained the FreeBSD port. Issues related to FreeBSD ports should be reported on the [FreeBSD's bug tracker](https://bugs.freebsd.org/bugzilla/) or directly to the port maintainer, which apparently is `freebsd [at] dns-lab.com`.

**Comment by steakknife** [comment]
Already did that.
