### ISSUE TITLE
DNSCrypt conflict with Spybot S&D

### ISSUE THREAD

**Issue by Greenmantle** [jedisct1/dnscrypt-proxy#243]
Hi, I have a problem that was highlighted by a situation which from my point of view is temporary and will be quickly overtaken by real time.  To give some context,I initially raised it with OpenDNS who I thought were maintaining the software, then, on their suggestion, I raised it with dnscrypt.org. My initial email read:

Hi, I've been using OpenDNSCrypt probably since it's early days (and regularly check for updates) along with other security tools Spyware Blaster, Spybot Search and Destroy, NoScript, AdblockPlus, Truesteer and OpenDNS along with my ESET AV, to safeguard my browsing. However, today I needed to access a website we are in the process of transferring to another hosting company, so we needed to temporarily edit the Hosts file to tell it where to find the new incarnation of the site. However, regardless of the browser (Firefox, Chrome, IE, Aviator, Ice Dragon) the page kept going to the existing site not its new incarnation, as if the Hosts file were being ignored. When I turned off OpenDNSCrypt and used Aviator (because I haven't loaded it with all the usual security extensions!) :)  I accessed the new incarnation of the site. I'm therefore concluding that OpenDNSCrypt bypasses the Hosts file. 
Is this correct? Should this happen? Spybot Search and Destroy edits the hosts file to prevent particular known sites redirecting them to the loopback adapter 127.0.0.1. The Hosts file edited by SS&D has a couple of hundred entries and begins:
Start of entries inserted by Spybot - Search & Destroy
This list is Copyright 2000-2010 Safer-Networking Ltd.
127.0.0.1	www.007guard.com
127.0.0.1	007guard.com
127.0.0.1	008i.com
127.0.0.1	www.008k.com
127.0.0.1	008k.com
127.0.0.1	www.00hq.com
127.0.0.1	00hq.com
127.0.0.1	010402.com
127.0.0.1	www.032439.com.......   and so on.
So if OpenDNSCrypt bypasses the file, SS&D is ineffectual. Do I then have a choice of encrypting my DNS traffic or blocking known sites using SS&D? 
The most recent version of OpenDNSCrypt is 0.0.6, so is this a product you are actively supporting, given the latest release was in 2012? 

If OpenDNSCrypt bypasses the Hosts file, is there a way it can be made to parse the file before encrypting the traffic? 

Their response was: 
"Thank you for getting in touch with us at OpenDNS. Although DNSCrypt was originally released by OpenDNS, we have released this project to be an open sourced project that is now supported and developed by its own community - you can find out more about this here: http://dnscrypt.org/
DNSCrypt will direct all DNS requests to the localhost, and direct them in an encrypted channel directly to OpenDNS. This will bypass your hosts file and essentially will "win" over other DNS related applications or hosts file.
Unfortunately at this time I don't believe DNSCrypt can be made to parse the file before encrypting the traffic, but I would suggest visiting https://dnscrypt.org/ to bring this up in the forums to see if there is a possible solution to your environment."

I raised the same issue with dnscrypt.org, and the salient part of his reply was: "That's an interesting question. I always thought that Windows was in charge of checking if there is a record in the hosts file for a request before sending it to the DNS resolver (whether it's a standard server or dnscrypt-proxy). That being said, I am by no means an expert on how it works, so my recommendation would be to ask on the Github repository and see what they say."

The comment was made that "I always thought that Windows was in charge of checking if there is a record in the hosts file for a request before sending it to the DNS resolver" and as I  understand it Spybot S&D must be following that process, but DNSCrypt seems to be bypassing it - at least circumstantially, from the behaviour I described at the beginning.

I realise I'm using version 0.0.6 and the latest version is 1.4.0, so I'll need to do an update, but is the way the current version works different from my version?

This week the site will go live with a new hosting company so the immediate need to resolve the issue effectively goes away - the work around being to turn off DNSCrypt, temporarily, so I can play around with the pages and get used to the new editing tools.  However, I am still left wondering whether I should turn off DNSCrypt permanently, so that Spybot S&D can do it's work properly.  Or maybe I remove SS&D and leave OpenDNSCrypt!

I await your thoughts because there may be a good number of folks like me who are trying to protect their PC's in the best way they understand, without being fully aware that one product may be making another ineffectual.  I certainly don't have an in-depth knowledge of what is happening, and feel out-of-my-depth just by being on this site and reading some of the other tickets!

Thanks for reading this

**Comment by jedisct1** [comment]
Hi,

I installed dnscrypt-proxy 1.6.0 on a vanilla Windows system, changed the DNS settings to use `127.0.0.1` and edited the `hosts` file to map a random to the IP of a valid web server.

The extra entry worked as expected, both from the command-line and from a web browser.

I then installed Spybot (free version), applied "immunization" and got a large `hosts` file. The dnscrypt-proxy service was still running, and I was still using `127.0.0.1` for my DNS settings. Entries from the `hosts` file were resolving to `127.0.0.1` as expected.

I don't know much about the version 0.0.6 you are referring to, but I would highly recommend completely uninstalling it, as it might be a fake package that actually contains malware.

The current stable version of the reference dnscrypt client is 1.6.0, and instructions are available here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown

Apparently, Spybot's `hosts` list was last updated 5 years ago, so it's probably not very effective any more, and it might prevent accessing legitimate sites.

I would highly recommend using the Blockulicious extension for Firefox and Chrome instead. Even the free version does a really good job at blocking ads, malware and phishing. It works a bit the same way as the `hosts` file but in a more reliable and less intrusive way. And Blockulicious list is constantly updated for current threats.

https://addons.mozilla.org/fr/firefox/addon/blockulicious/
https://chrome.google.com/webstore/detail/blockulicious/kngglkijfekbhidmchmlfmpkdffmedob?hl=fr

**Comment by Greenmantle** [comment]
Hi,
Thanks for the help.  I'll certainly look at the Blockulicious add-on. 
On reflection I wonder whether my problem might have been that version 0.0.6 doesn't use a proxy service, whereas the later versions do - I'm guessing, going from your remarks and that OpenDNS make no comment about it on their https://www.opendns.com/about/innovations/dnscrypt/ page. 

Incidentally the 0.0.6 version is completely valid (and has a release date of 2012), and as OpenDNS commented to me when I asked them: "DNSCrypt was originally released by OpenDNS, we have released this project to be an open sourced project that is now supported and developed by its own community".  My version is therefore a simply old GUI version, not fake.  I installed it before its release to the open source community sometime after 2012 and indeed it is still on your servers: https://github.com/opendns/dnscrypt-win-client and is shows "jason-opendns authored on 13 Aug 2012".

I have now downloaded the current version, and I want to thank you very much for the link to the instructions as stuff that installs via Command line can be outside the usual comfort zone.

Many thanks.

**Comment by jedisct1** [comment]
Instructions to install it from the command-line are available here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown

But if you prefer a user interface, you can use [DNSCrypt-WinClient](https://github.com/Noxwizard/dnscrypt-winclient), a nice user interface for Windows. It's opensource, it was actually released before the Open DNS one, but it's still supported, and it works well with recent versions of the client proxy.

**Comment by cubakcabak** [comment]
can please this issue be reopened?

i just realized that the hosts file on my linux workstations (ubuntu) and in my phone (AOSP kitkat) is ignored by dnscrypt-proxy instances.

in the hosts file is a lists of adsever and malware domain.

i would love to have adblocker extensions mentioned, but on my phone chrome (my preferable browser) dont have extensions support.

using the latest version of dnscrypt-proxy (1.6.0).

**Comment by jedisct1** [comment]
Hi,

That's weird. `dnscrypt-proxy` doesn't change anything to the way your system is resolving DNS queries, and it doesn't know anything about `/etc/hosts` files either. It just runs an alternative resolver listening to `127.0.0.1` that you can use in place of `8.8.8.8` or whatever resolver you previously used.
But just like Google doesn't know about and can't disable your `/etc/hosts` list, the resolver on `127.0.0.1`  cannot do anything related to this file either.

Did you actually change `/etc/hosts`? I think Ubuntu now installs dnsmasq by default, and that it uses a different location for the `hosts` file. If you removed dnsmasq, you may want to make sure that your entries are added to `/etc/hosts`.

That said, on Ubuntu there is a far better way to block things if you are using dnscrypt-proxy, using the ip/domain names blocking plugin: https://dnscrypt.org/#plugins

There are several advantages over `/etc/hosts`. First, queries for blocked things will return a standard DNS `REFUSED` response instead of a fake IP address, or worse, your local computer IP address such as `127.0.0.1`. Blocking malicious domains by redirecting the traffic to your own computer can introduce more security issues that it would prevent.

Next, the dnscrypt blocking plugin can block patterns. Instead of just blocking `example.com`, it lets you block `*.example.com` or `*.ru`. Or even keywords, such as any domain name containing the word "sex": `*sex*`.
Finally, it can also block IP addresses.

The Android binaries don't include plugins yet because I haven't looked at how to compile the required dependencies yet, but this is likely to be the case soon.

**Comment by cubakcabak** [comment]
a note i forgot to mention, i disable any dns resolver that the system installed, that including dnsmasq.

so i exclusively used dnscrypt-proxy as system dns resolver.

and yes like i mentioned above, the /etc/hosts file is modified by including ads and malware domain in it.

maybe i could use the dnscrypt-proxy plugins method as a solutions, but that only applicable on the pc. i cant implement that on my android phone, as i dont know how to compile the source into binary.

and on the phone, something that could be handled easily by hosts file, replaced by extra plugin, seems too excessive to me. considering limited resource on the phone (memory, processor).

**Comment by pysiak** [comment]
How about you:
- setup dnsmasq as your cache
- make it forward all queries to your local dnscrypt-proxy
- setup spoofed domains for malware in dnsmasq so that you get filtering by
sending NXDOMAIN
- use hosts only for legitimate hosts definitions you actually need

dnsmasq has a simple configuration directive for this:
server=/doubleclick.net/google-analytics.com/evil malware.com/etc/

Convert your malware rules to dnsmasq rules but keep on mind dnsmasq has a
limit of I think 1024 characters per line do you have to split them in
multiple directives if you've got more.

**Comment by cubakcabak** [comment]
i end up chaining the dnscrypt-proxy in front of dnsmasq.

simple standard setup on dnsmasq config, with no extra rule, just defining dnscrypt-proxy as forwarder dns.

the "/etc/hosts" file containt ads and malware domain, and it get "sourced" by dnsmasq default.

so my prefered working dnscrypt-proxy with ads and malware domain achieved.

its just a little bit "workout" to go thorough the loops, for wanting "a simple setup" dnscrypt-proxy + hostsfile.

not whining, just thinking outloud.

i still thankful for the dnscrypt existences and your great work.
