### ISSUE TITLE
DNSCrypt didn't get through transparent DNS

### ISSUE THREAD

**Issue by fuadhanif** [jedisct1/dnscrypt-proxy#244]
I was using dnscrypt 1.4.1 for windows for quite sometimes. I used it for bypassing transparent DNS that used by my ISP, called "internet positif"
suddenly around 3 months ago, i cant access website blocked by "internet positif" that usually accessible by help of dnscrypt, such as thepiratesbay, reddit, etc.
at the time i have no time to troubleshoot this, until now

now im on some dnscrypt tool by opendns. and here is something that i dont quite understand
I used nslookup from cmd, and it returned the real address.
but when I browse using chrome, or IE (yes i tried IE), it direct me to "internet positif" page as an action of blocking the access

please help me, free VPN gave super slow speed, i need to make this works again

**Comment by jedisct1** [comment]
Hi,

Can you try the current stable version, which is 1.6.0? Follow the instructions here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown

and try different providers from the list.

Maybe Internet Positif is now directly filtering by destination IP address, not just using DNS, in which case dnscrypt is not going to be useful any more.

**Comment by jedisct1** [comment]
Apparently, Speedy is now doing both DNS hijacking and IP hijacking. Some sites are blocked by the former, other sites are blocked using the later.

dnscrypt can help with DNS hijacking, but unfortunately not much with IP redirections. For that, your only option remains a VPN :(

Internet censorship is a terrible thing. In my country, they only use DNS hijacking for censorship, but it might also escalate to IP blocking at some point :(
