### ISSUE TITLE
dnscrypt-proxy complaining that brew installed libsodium out of date

### ISSUE THREAD

**Issue by xxdesmus** [jedisct1/dnscrypt-proxy#245]
Attempting to setup a provider for a server dnscrypt-server I just setup. When I try to add the provider I get this:

```
$ dnscrypt-proxy --provider-key=144C:5BB2:5474:AD4C:4A4F:026A:623E:5C1C:EF45:B950:1B1B:C0B2:3A1C:F3A0:B0AB:6422 --resolver-address=94.23.239.44 --provider-name=2.dnscrypt-cert.dns.spdysync.com
dyld: Library not loaded: /usr/local/lib/libsodium.13.dylib
  Referenced from: /usr/local/sbin/dnscrypt-proxy
  Reason: Incompatible library version: dnscrypt-proxy requires version 16.0.0 or later, but libsodium.13.dylib provides version 15.0.0
Trace/BPT trap: 5
```

libsodium was installed already via brew
```
$ brew install libsodium --universal
Warning: libsodium-1.0.2 already installed
```

```
$ which dnscrypt-proxy
/usr/local/sbin/dnscrypt-proxy
```
Specifying that full path doesn't fix the issue either.

```
$ /usr/local/sbin/dnscrypt-proxy --provider-key=144C:5BB2:5474:AD4C:4A4F:026A:623E:5C1C:EF45:B950:1B1B:C0B2:3A1C:F3A0:B0AB:6422 --resolver-address=94.23.239.44 --provider-name=2.dnscrypt-cert.dns.spdysync.com
dyld: Library not loaded: /usr/local/lib/libsodium.13.dylib
  Referenced from: /usr/local/sbin/dnscrypt-proxy
  Reason: Incompatible library version: dnscrypt-proxy requires version 16.0.0 or later, but libsodium.13.dylib provides version 15.0.0
Trace/BPT trap: 5
```

to note, the Mac app itself works and I'm able to connect to other providers ...it's just a matter of adding the new provider which runs into the error.

am I just doing something dumb?

**Comment by jedisct1** [comment]
Hi Justin!

Looks like the installed version of libsodium is old. Did you mix things compiled by hand with things compiled using Homebrew?

Make sure that you don't have duplicates, such as different libsodium or dnscrypt versions installed both in /usr and in /usr/local. Then try something like:

    brew update
    brew upgrade
    brew reinstall libsodium
    brew reinstall dnscrypt-proxy --with-plugins

**Comment by xxdesmus** [comment]
You're a genius.

All kinds of stuff was out of date in Brew.

I didn't compile things by hand. I used the Mac binary (for the GUI), and  then initially when I  got the error I tried manually installing libsodium via Brew. After the brew update, brew upgrade things are working.

**Comment by techraf** [comment]
Current stable dnscrypt-proxy 1.6.0 version has a very similar problem and the resolution method suggested above does not work.

It seems like `dnscrypt-proxy` has somehow hardcoded `/usr/local/lib/libsodium.13.dylib` path, while current `libsodium` is aready at `libsodium.18.dylib`.

```
ls -l /usr/local/Cellar/libsodium/1.0.8/lib/
total 3640
-r--r--r--  1 macraf  admin   763268 Mar  3 12:48 libsodium.18.dylib
-r--r--r--  1 macraf  admin  1091336 Mar  3 12:48 libsodium.a
lrwxr-xr-x  1 macraf  admin       18 Mar  3 12:48 libsodium.dylib@ -> libsodium.18.dylib
drwxr-xr-x  3 macraf  admin      102 Mar  3 12:48 pkgconfig/
```

dnscrypt-proxy fails with `image not found error`:
```
dyld: Library not loaded: /usr/local/lib/libsodium.13.dylib
  Referenced from: /usr/local/sbin/dnscrypt-proxy
  Reason: image not found
./dnscrypt-manual.sh: line 24: 67315 Trace/BPT trap: 5       /usr/local/sbin/dnscrypt-proxy --local-address=127.0.0.1:5355 --ephemeral-keys --resolvers-list=/usr/local/Cellar/dnscrypt-proxy/1.6.0/share/dnscrypt-proxy/dnscrypt-resolvers.csv --resolver-name=dnscrypt.eu-dk --user=nobody
```

**Comment by licaon-kter** [comment]
Tried with 1.6.1 too?

**Comment by techraf** [comment]
Yes, sorry, that was a typo.

````
# brew upgrade dnscrypt-proxy
Error: dnscrypt-proxy 1.6.1 already installed
````

**Comment by jedisct1** [comment]
dnscrypt-proxy doesn't have anything hardcoded, but Homebrew will install pre-compiled packages if available. And maybe the precompiled package you have is was linked to an old version of the library.

The current precompiled packages from Homebrew are fine. They include the last version of sodium, and dnscrypt-proxy properly linked to it.

So, maybe you still have an old version in cache. Try removing the Homebrew cached files (this will also free a lot of space on your disk):

```bash
    brew update
    brew prune
    brew cleanup
    rm -fr /Library/Caches/Homebrew/*
    brew uninstall dnscrypt-proxy
    brew uninstall minisign
    brew uninstall libsodium
    brew install 
    brew install libsodium
    brew link --overwrite libsodium
    brew install minisign
    brew link --overwrite minisign
    brew install dnscrypt-proxy
    brew link --overwrite dnscrypt-proxy
```
If Homebrew's precompiled packages still don't work on your system, you can always add the `--build-from-source` option to `brew` in order to build from source.

**Comment by techraf** [comment]
Chapeau bas! Worked like a charm (from bottles). Thank you.

**Comment by jedisct1** [comment]
You're welcome!
