### ISSUE TITLE
Update opennic-fvz-rec- servers in dnscrypt-resolvers.csv

### ISSUE THREAD

**Issue by Fusl** [jedisct1/dnscrypt-proxy#248]
Hi,

can you please update my listed servers in dnscrypt-resolvers.csv?

You can find an exported list of my servers here:

https://scr.meo.ws/paste/2015-08-02-05-57-10-6ix09oX9.txt

I had a couple of issues with all my DNSCrypt installations which forced me to rebuild my entire configuration and with that all the keys and certs.

Thanks in advance!

Regards,
Fusl

**Comment by jedisct1** [comment]
Hi,

Looks like none of them work any more :(

Trying any of them results in

    [ERROR] Unable to retrieve server certificates

Even with the ones that used to work.

Is the provider name correct?

For example, this should return the TXT record with the certificates but it doesn't:

    $ drill -p 443 txt 2.fvz-rec-at-vie-01.dnscrypt-cert.meo.ws @192.71.247.247
    ;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 38879

**Comment by Fusl** [comment]
Hi,

you were right, the provider name was incorrect in the exporter template, sorry for that.

Here is the updated list: https://scr.meo.ws/paste/2015-08-02-13-23-19-Fyr5mhlJ.txt

Thanks!

Regards,
Fusl

**Comment by jedisct1** [comment]
Done!

Everything looks great now!

Thanks!

**Comment by jedisct1** [comment]
```
+ fvz-rec-at-vie-01 - OK
+ fvz-rec-au-nsw-01 - OK
+ fvz-rec-au-sa-01 - OK
+ fvz-rec-au-vic-01 - OK
+ fvz-rec-au-wa-01 - OK
+ fvz-rec-be-vwv-01 - OK
+ fvz-rec-ca-on-01 - OK
+ fvz-rec-ch-zu-01 - OK
+ fvz-rec-de-fra-01 - OK
+ fvz-rec-de-fra-02 - OK
+ fvz-rec-de-sn-01 - OK
+ fvz-rec-fr-rbx-01 - OK
+ fvz-rec-fr-sxb-01 - OK
+ fvz-rec-gb-eng-01 - OK
+ fvz-rec-hk-nt-01 - OK
+ fvz-rec-hu-bu-01 - OK
+ fvz-rec-ie-du-01 - OK
+ fvz-rec-im-dgl-01 - OK
+ fvz-rec-is-hf-01 - OK
+ fvz-rec-jp-tk-01 - OK
+ fvz-rec-li-ba-01 - OK
- fvz-rec-lv-rix-01 - Failed
+ fvz-rec-nl-fl-01 - OK
+ fvz-rec-nl-nh-01 - OK
+ fvz-rec-nz-auk-01 - OK
+ fvz-rec-ru-mow-01 - OK
+ fvz-rec-se-ab-01 - OK
+ fvz-rec-sg-ea-01 - OK
+ fvz-rec-us-ca-01 - OK
+ fvz-rec-us-ca-02 - OK
+ fvz-rec-us-fl-01 - OK
+ fvz-rec-us-ga-01 - OK
+ fvz-rec-us-nj-01 - OK
+ fvz-rec-us-tx-01 - OK
+ fvz-rec-us-tx-02 - OK
+ fvz-rec-us-wa-01 - OK
- fvz-rec-za-wc-01 - Failed
```

**Comment by Fusl** [comment]
Hi,

thanks for letting me know.

Seems the default dnscrypt-wrapper on fvz-rec-lv-rix-01 crashed, I switched this to my kernel module implementation which should be more stable.

fvz-rec-za-wc-01 is currently being rebuilt after the disk RAID died a few hours ago.

Mind telling me what you have used for checking these? Would be useful for me to monitor all my instances.

Thanks!

Regards,
Fusl

**Comment by jedisct1** [comment]
Do you have a kernel module implementation of dnscrypt-wrapper? o_O

There is a simple script in the dnscrypt-proxy source tree that checks the health of all the listed resolvers:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/resolvers-check.sh

I have this run in a cron job to keep the CSV file clean with only working resolvers.

You can also just use `dnscrypt-proxy --test=...` in a cron job. This will alert you not only when it doesn't work but also when the current certificate is about to expire.

There is also this Docker image you can use: https://github.com/jedisct1/dnscrypt-server-docker

It set ups everything including scripts that constantly check the health of the cache and the proxy, and restart the services if required. No need to worry about expiring keys and having to generate new keys either, it's done automatically.
