### ISSUE TITLE
Windows 10 compatibility

### ISSUE THREAD

**Issue by AHrubik** [jedisct1/dnscrypt-proxy#250]
It would appear that the proxy is no longer able to redirect traffic in Windows 10. Is anyone else seeing this?

**Comment by looterz** [comment]
I have got it working on Windows 10 just fine. Try running it with a higher loglevel on the client and server and see where it is failing (--loglevel or -m).

**Comment by CHEF-KOCH** [comment]
:+1: works quite good on Windows 10.

**Comment by l2d4y3** [comment]
I'm having trouble with IPv6 on Windows 10.
nslookup www.youtube.com ::FFFF:127.0.0.1
Server:  UnKnown
Address:  127.0.0.1

*** UnKnown can't find www.youtube.com: No response from server

nslookup www.youtube.com 127.0.0.1
1.0.0.127.in-addr.arpa
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 600 (10 mins)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)
(root)  ??? unknown type 41 ???
Server:  UnKnown
Address:  127.0.0.1

Non-authoritative answer:
Name:    youtube-ui-china.l.google.com
Addresses:  2404:6800:4005:808::200e
          173.194.72.100
          173.194.72.139
          173.194.72.101
          173.194.72.138
          173.194.72.113
          173.194.72.102
Aliases:  www.youtube.com
          youtube-ui.l.google.com

**Comment by jedisct1** [comment]
Windows 10 is the Windows version it's being developed and tested on every since the very first public beta. 

Make sure that the service is running. Maybe try to remove and reinstall the service.

**Comment by AHrubik** [comment]
I seems I was having other problems with my Windows 10 upgrade. In an attempt to upgrade the NIC driver the OS ended up unbootable. Along with other issues (Nvidia I'm looking at you) I wiped the machine and installed Windows 8.1. I'm glad to hear it was just me.
