### ISSUE TITLE
cant run the provided binary 1.6.0 on AOSP kitkat

### ISSUE THREAD

**Issue by cubakcabak** [jedisct1/dnscrypt-proxy#252]
it comes with this error:

    CANNOT LINK EXECUTABLE: cannot locate symbol "signal" referenced by "dnscrypt-proxy"...

**Comment by jedisct1** [comment]
Indeed, the provided binary was for Lollipop.

I don't have any devices with an older Android version, but I recompiled dnscrypt-proxy with a different platform version, that should work with Kitkat.

Can you try to download the file again (same location) and confirm that it works on Kitkat?

**Comment by cubakcabak** [comment]
it works!

thank you very much, dnscrypt really help us internet users in indonesia.

if possible, please always provide the latest binary version for android in the website, because i'm not familiar with programming. i'm just an advance user.

you're the best!

**Comment by jedisct1** [comment]
Thanks for your report! Glad that it helps!
