### ISSUE TITLE
Internet (DNSCRypt) does not work when booting computer or waking up  

### ISSUE THREAD

**Issue by 1crossover** [jedisct1/dnscrypt-proxy#253]
So i have noticed that when booting up the computer or waking it up from sleep DNSCrypt is stopped in task manager and will not start, also can not connect to the internet.

However, in Command Prompt when i run 
dnscrypt-proxy -R dnscrypt.org-fr 

Then i get this output

E:\DNSCrypt\dnscrypt-proxy-win32  1.6.0>dnscrypt-proxy -R dnscrypt.org-fr
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate #808464433 received
[INFO] This certificate looks valid
[INFO] Server key fingerprint is 4A96:7AF8:6B84:922E:DF98:402A:57DE:DFFA:6EBB:FC
A7:9ABC:AFE2:E584:B14C:A9A0:1464
[NOTICE] Proxying from 127.0.0.1:53 to 212.47.228.136:443
[WARNING] recvfrom(client): [Connection reset by peer [WSAECONNRESET ]]

Then my internet works but task manager still saying service stopped

How can DNSCrypt work without me having to run CMD all the time.

**Comment by cubakcabak** [comment]
try this:

dnscrypt-proxy -R dnscrypt.org-fr --install

its set the process as windows service, and run it in the backgroud.

you could see all parameter by run: 

dnscrypt-proxy -h

**Comment by jedisct1** [comment]
Nod. You should run it as a service. See https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown
