### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by cocawater** [jedisct1/dnscrypt-proxy#255]
<img width="616" alt="screen shot 2015-08-11 at 4 39 31 pm" src="https://cloud.githubusercontent.com/assets/13756629/9213543/83801f54-4048-11e5-8f5f-3a524a475351.png">

I am using 1.0.10 version and Yosemite OS, and it seems that DNScrypt does not work at all. Please advise. Thank you !

**Comment by jedisct1** [comment]
Hi!

You should ask here: https://github.com/alterstep/dnscrypt-osxclient

This interface for Mac is a different project, and its author will probably be more helpful than me :)

**Comment by cocawater** [comment]
😄，thank you so much
