### ISSUE TITLE
systemd ordering cycle problem

### ISSUE THREAD

**Issue by AnAkIn1** [jedisct1/dnscrypt-proxy#256]
When enabling the systemd scripts, there is an error showing up on every boot, which seem to be a dependency problem:

systemd[1]: dnscrypt-proxy.socket: Found ordering cycle on dnscrypt-proxy.socket/start
systemd[1]: dnscrypt-proxy.socket: Found dependency on network.target/start
systemd[1]: dnscrypt-proxy.socket: Found dependency on firewalld.service/start
systemd[1]: dnscrypt-proxy.socket: Found dependency on basic.target/start
systemd[1]: dnscrypt-proxy.socket: Found dependency on sockets.target/start
systemd[1]: dnscrypt-proxy.socket: Found dependency on dnscrypt-proxy.socket/start
systemd[1]: dnscrypt-proxy.socket: Breaking ordering cycle by deleting job network.target/start
systemd[1]: network.target: Job network.target/start deleted to break ordering cycle starting with dnscrypt-proxy.socket/start

**Comment by jedisct1** [comment]
Does it help if you remove `After=network.target` from `dnscrypt-proxy.socket`?

**Comment by AnAkIn1** [comment]
Indeed, removing it resolves the issue.

**Comment by sjug** [comment]
Saw this same issue, useful issue.
