### ISSUE TITLE
README-WINDOWS.markdown update to integrate example registry entry

### ISSUE THREAD

**Issue by CHEF-KOCH** [jedisct1/dnscrypt-proxy#257]
Hey, how about adding an example file (.reg) or description in the Windows readme?

```bash
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\dnscrypt-proxy]
"Type"=dword:00000010
"Start"=dword:00000002
"ErrorControl"=dword:00000001
"ImagePath"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,\
  20,00,46,00,69,00,6c,00,65,00,73,00,5c,00,44,00,4e,00,53,00,43,00,72,00,79,\
  00,70,00,74,00,5c,00,64,00,6e,00,73,00,63,00,72,00,79,00,70,00,74,00,2d,00,\
  70,00,72,00,6f,00,78,00,79,00,2e,00,65,00,78,00,65,00,00,00
"DisplayName"="dnscrypt-proxy"
"WOW64"=dword:00000001
"ObjectName"="LocalSystem"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\dnscrypt-proxy\Parameters]
"ResolversList"="C:\\Program Files\\DNSCrypt\\dnscrypt-resolvers.csv"
"ResolverName"="Soltysiak"
"LocalAddress"="127.0.0.1:53"
"Plugins"=hex(7):6c,00,69,00,62,00,64,00,63,00,70,00,6c,00,75,00,67,00,69,00,\
  6e,00,5f,00,65,00,78,00,61,00,6d,00,70,00,6c,00,65,00,5f,00,6c,00,64,00,6e,\
  00,73,00,5f,00,61,00,61,00,61,00,61,00,5f,00,62,00,6c,00,6f,00,63,00,6b,00,\
  69,00,6e,00,67,00,2e,00,64,00,6c,00,6c,00,2c,00,6c,00,69,00,62,00,64,00,63,\
  00,70,00,6c,00,75,00,67,00,69,00,6e,00,5f,00,65,00,78,00,61,00,6d,00,70,00,\
  6c,00,65,00,5f,00,6c,00,64,00,6e,00,73,00,5f,00,6f,00,70,00,65,00,6e,00,64,\
  00,6e,00,73,00,5f,00,73,00,65,00,74,00,5f,00,63,00,6c,00,69,00,65,00,6e,00,\
  74,00,5f,00,69,00,70,00,2e,00,64,00,6c,00,6c,00,00,00,00,00
"ProviderKey"="25C4:E188:2915:4697:8F9C:2BBD:B6A7:AFA4:01ED:A051:0508:5D53:03E7:1928:C066:8F21"
"ProviderName"="2.dnscrypt-cert.soltysiak.com"
"ResolverAddress"="178.216.201.222:2053"
"EDNSPayloadSize"=dword:00001000
"MaxActiveRequests"=dword:00000096
"EphemeralKeys"=dword:00000000
```

Maybe this would a bit improve the product and could help non-tech persons. Of course this is only an example and the resolver/name/address/.. may needs to be changed but imho that's already well explained So the basic user can just extract the dns package, edit the .reg per needs and import it into windows and viola all should be running (after a restart).

**Comment by jedisct1** [comment]
Registry entries can be useful to people writing GUIs, but most users would be scared about touching the registry.

Right now, most of these registry entries are automatically set when installing the service.
So most people can just type

    dnscrypt-proxy -R resolver --install

And call it a day.

Editing the registry might still be required today, because some entries are not automatically set when installing the service. A major one and embarrassing one is the list of plugins.
This is not really by design, rather me having been too lazy to write code that updates `MULTI_SZ` entries, but this will eventually be fixed.

**Comment by CHEF-KOCH** [comment]
Okay thanks for the input, was just an idea. Of course all reg changes can be removed I don't see a problem modding the registry somehow, most Windows users doesn't often use the console (lazy GUI people ...) that was the main intent behind all this. And the reasons why there are so many examples and guides (and the GUI tool dnscrypt-winclient.exe needs to be updated). But personally I not care much about this, as you said, console works since the beginning. So everything fine here :+1:


/OT 
Btw I have a problem and question, if I want call <code>dnscrypt-proxy -R resolver</code> under Android I always get the error msg that the resolver-list can't be read. The strange part begins here, even if I set all stuff manually it wants to load the .csv file loading from a place that doesn't exist. Is there a way to fix this?

```
[ERROR] Unable to read [Users/j/src/DNSCrypt/dnscrypt-proxy/dnscrypt-android-armv7-a/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv]
```

Is there a way to hardcode only the /etc/dnscrypt-proxy/ path so that it only want's to grab the .csv from there? That would be nice.

**Comment by CHEF-KOCH** [comment]
Okay thanks for the input, was just an idea. Of course all reg changes can be removed I don't see a problem modding the registry somehow, most Windows users doesn't often use the console (lazy GUI people ...) that was the main intent behind all this. And the reasons why there are so many examples and guides (and the GUI tool dnscrypt-winclient.exe needs to be updated). But personally I not care much about this, as you said, console works since the beginning. So everything fine here :+1:


/OT 
Btw I have a problem and question, if I want call <code>dnscrypt-proxy -R resolver</code> under Android I always get the error msg that the resolver-list can't be read. The strange part begins here, even if I set all stuff manually it wants to load the .csv file loading from a place that doesn't exist. Is there a way to fix this?

```
[ERROR] Unable to read [Users/j/src/DNSCrypt/dnscrypt-proxy/dnscrypt-android-armv7-a/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv]
```

Is there a way to hardcode only the /etc/dnscrypt-proxy/ path so that it only want's to grab the .csv from there? That would be nice.

**Comment by jedisct1** [comment]
Hi!

The default path to `dnscrypt-resolvers.csv` can be changed, by defining an environment variable named `DEFAULT_RESOLVERS_LIST` when running the `./configure` script:

    env DEFAULT_RESOLVERS_LIST=/system/etc/dnscrypt-resolvers.csv ./configure ...
