### ISSUE TITLE
IPv6 DNS on Windows 10

### ISSUE THREAD

**Issue by l2d4y3** [jedisct1/dnscrypt-proxy#258]
The "fake" IPv6 DNS doesn't work on Windows 10, at least for nslookup. Why not listen on ::1?

nslookup www.youtube.com ::FFFF:127.0.0.1
Server:  UnKnown
Address:  127.0.0.1

*** UnKnown can't find www.youtube.com: No response from server

nslookup www.youtube.com 127.0.0.1
1.0.0.127.in-addr.arpa
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 600 (10 mins)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)
(root)  ??? unknown type 41 ???
Server:  UnKnown
Address:  127.0.0.1

Non-authoritative answer:
Name:    youtube-ui-china.l.google.com
Addresses:  2404:6800:4005:808::200e
          173.194.72.100
          173.194.72.139
          173.194.72.101
          173.194.72.138
          173.194.72.113
          173.194.72.102
Aliases:  www.youtube.com
          youtube-ui.l.google.com

**Comment by jedisct1** [comment]
Do not use `nslookup`. Windows applications use a totally different code than `nslookup`. `nslookup` is also very old and buggy, and is by no mean a tool one should use to diagnose DNS issues.

Enter `::FFFF:127.0.0.1` as an IPv6 resolver in your DNS configuration, and try to access a web site over IPv6 such as the Kame's dancing turtle.
