### ISSUE TITLE
AirPort Extreme and OS X v10.8.5

### ISSUE THREAD

**Issue by jonathansabrams** [jedisct1/dnscrypt-proxy#260]
Setup:  AirPort Extreme, firmware v7.6.4 and Mac OS X v10.8.5

Problem:  DNSCrypt cannot be enabled.

First Observation:  Entries in /var/logdnscrypt-osxclient-debug.log that read "The router hijacks HTTP queries - DNSCrypt is likely to be blocked".  Is this irrelevant?  Does the AirPort Extreme hijack HTTP queries?  Is there something in my AirPort configuration that needs to be changed?

Second Observation:  The first time I try to execute `/usr/local/sbin/dnscrypt-proxy -R soltysiak -a 127.0.0.1:4444`, I receive the following error.  dyld: Library not loaded: /usr/local/lib/libsodium.13.dylib
  Referenced from: /usr/local/sbin/dnscrypt-proxy
  Reason: image not found
Trace/BPT trap: 5

I then run export `DYLD_LIBRARY_PATH="/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/lib"`, followed by `/usr/local/sbin/dnscrypt-proxy -R soltysiak -a 127.0.0.1:4444`, and then I see the following output.
```
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate #808464433 received
[INFO] This certificate looks valid
[INFO] Chosen certificate #808464433 is valid from [2014-10-16] to [2019-10-15]
[INFO] Server key fingerprint is F0AD:8CEB:52C5:8DCD:0244:C28B:550A:BA4F:7BDB:4593:6F19:63DB:72D3:683A:30C0:0612
[NOTICE] Proxying from 127.0.0.1:4444 to 178.216.201.222:2053
```
This instance of Terminal never gets back to the $ prompt.  If I close the Terminal, I am warned that doing so will terminate dnscrypt-proxy.

Any assistance that can help me get DNSCrypt working would be appreciated.

Thanks for reading!

**Comment by cubakcabak** [comment]
add one parameter to that command line of yours:

"--daemonize", or just "-d" for short one

then the proccess will run in the background, and you can close the terminal window.

**Comment by jedisct1** [comment]
If you are not afraid by the command line, you can indeed get rid of the user interface, install dnscrypt-proxy with Homebrew, and just start it with `dnscrypt-proxy -R soltysiak -d`. 

There shouldn't be any issues with the Airport Extreme.

Do you have firewall rules or something such as Little Snitch that could prevent some apps from accessing the network?

The script that checks for hijacking is `/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts/check-hijacking.sh` and it does so by running two commands:

    alarmer 5 dig +tries=2 +time=3 +short google-public-dns-a.google.com | egrep '^8[.]8[.]8[.]8'

When using dnscrypt, does this command return `8.8.8.8`?

The other command checks that the Apple web site is not hijacked by a captive portal:

    alarmer 5 curl -L --max-redirs 5 -4 -m 5 --connect-timeout 5 -s http://www.apple.com | fgrep Apple

Does that one print a couple lines containing `Apple`?

**Comment by jonathansabrams** [comment]
cubakcabak - Thanks for the tip.

jedisct1 - "If you are not afraid by the command line, you can indeed get rid of the user interface, install dnscrypt-proxy with Homebrew"

I am not afraid of the command line.  I do not want to use Homebrew.  Can DNSCrypt be installed without Homebrew?

"The script that checks for hijacking is /Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts/check-hijacking.sh"

When I run that script, I see not output in the Terminal window, nor do I see anything related to it logged in /var/log/dnscrypt-osxclient-debug.log.  Should I be seeing output in either of these locations?

If I run /Library/PreferencePanes/DNSCrypt.prefPane//Contents/Resources/usr/bin/alarmer 5 dig +tries=2 +time=3 +short google-public-dns-a.google.com | egrep '^8[.]8[.]8[.]8', the output I see in the Terminal is 8.8.8.8.

If I run /Library/PreferencePanes/DNSCrypt.prefPane//Contents/Resources/usr/bin/alarmer 5 curl -L --max-redirs 5 -4 -m 5 --connect-timeout 5 -s http://www.apple.com | fgrep Apple, the output I see in the Terminal is as follows.

<meta name="Author" content="Apple Inc." />
	<title itemprop="name">Apple</title>
	<meta property="analytics-track" content="Apple - Index/Tab" />
	<meta name="Description" content="Apple leads the world in innovation with iPhone, iPad, Mac, Apple Watch, iOS, OS X, watchOS and more. Visit the site to learn, buy, and get support." />
	<meta property="og:site_name" content="Apple" />
				<a class="ac-gn-link ac-gn-link-apple" href="/" data-analytics-title="apple home" id="ac-gn-firstfocus-small"> <span class="ac-gn-link-text">Apple</span> </a>
				<a class="ac-gn-link ac-gn-link-apple" href="/" data-analytics-title="apple home" id="ac-gn-firstfocus"> <span class="ac-gn-link-text">Apple</span> </a>
		<h1>Apple Music</h1>
				>Learn more about Apple Music<span class="icon icon-more"></span></a>
		<h1>Apple Watch</h1>
			Diversity at Apple. Inclusion inspires innovation.
			<h2 class="ac-gf-label" id="ac-gf-label">Apple Footer</h2>
<nav class="ac-gf-directory with-5-columns" aria-label="Apple Directory" role="navigation">
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="/music/">Apple Music</a></li>
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="/appletv/">Apple TV</a></li>
				<h3 class="ac-gf-directory-column-section-title">Apple Store</h3> </label>
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="https://itunes.apple.com/app/apple-store/id375380948?mt=8">Apple Store App</a></li>
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="/education/">Apple and Education</a></li>
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="https://appleid.apple.com/us/">Manage Your Apple ID</a></li>
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="/us/shop/goto/account">Apple Store Account</a></li>
				<h3 class="ac-gf-directory-column-section-title">Apple Values</h3> </label>
				<h3 class="ac-gf-directory-column-section-title">About Apple</h3> </label>
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="/about/">Apple Info</a></li>
				<li class="ac-gf-directory-column-section-item"><a class="ac-gf-directory-column-section-link" href="/contact/">Contact Apple</a></li>
	<div class="ac-gf-footer-shop"> More ways to shop: Visit an <a href="/retail/">Apple Store</a>, <span class="nowrap">call 1-800-MY-APPLE, or <a href="https://locate.apple.com/">find a reseller</a></span>. </div>
		<div class="ac-gf-footer-legal-copyright">Copyright © 2015 Apple Inc. All rights reserved.</div>
	<meta content="Apple" property="name" />

**Comment by jedisct1** [comment]
You can install it without Homebrew, but it's way more complicated as you need to install Xcode and compile it and its dependencies.

But if you know how to compile software, here is what needs to be installed:

- The DNS library: http://www.nlnetlabs.nl/projects/ldns/
- The crypto library: https://download.libsodium.org/libsodium/releases/
- dnscrypt-proxy: https://download.dnscrypt.org/dnscrypt-proxy/

**Comment by jonathansabrams** [comment]
I installed Xcode along with its command line tools, followed by the components that @jedisct1 listed.  After much trial and error, the last few things I tried that ultimately led to DNSCrypt working properly were the following:
•set DNS fields in AirPort router to blank (ISP populates them with IPs in dim/gray text)
•set DNS server for my Wi-Fi using the following Terminal command - networksetup -setdnsservers "Wi-Fi" 127.0.0.54
•load DNSCrypt preference pane and click Enable

When I run either of the following Terminal commands, I now see the expected result:
•sudo /Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/bin/alarmer 5 dig +tries=2 +time=3 +short google-public-dns-a.google.com | egrep '^8[.]8[.]8[.]8' (result is 8.8.8.8.)
•sudo /Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/bin/alarmer 5 curl -L --max-redirs 5 -4 -m 5 --connect-timeout 5 -s http://www.apple.com | fgrep (result is a bunch of text from apple.com)
