### ISSUE TITLE
OSX 10.10.5 client standby if the original dns server is non-recursive

### ISSUE THREAD

**Issue by fred-chen** [jedisct1/dnscrypt-proxy#266]
The following function will never succeed if the original dns server is working with non-recursive mode. that causes the client stays in "standby" forever. MAC OSX 10.10.5. 

try_resolution() {
  exec alarmer 5 dig +tries=2 +time=3 +short google-public-dns-a.google.com \
    | egrep '^8[.]8[.]8[.]8' > /dev/null 2>&1
}

**Comment by jedisct1** [comment]
/cc @alterstep - I think this is about your project, not dnscrypt-proxy :)

The intent of `check-hijacking.sh` is to detect if you are behind a router that blocks/redirects all DNS queries. This is often the case in public Wifi access points, where you need to read some TOS and possibly watch some ads or fork over some money before you can actually use the network.

In such a situation, turning on DNSCrypt wouldn't work, and you wouldn't even be able to pass the captive portal.

If you use a resolver that can only respond to queries for local domains, the behavior is exactly the same as a captive portal that doesn't resolve anything but the airport web site domain. And I don't think there is anything we can do to make the distinction between both.

Using a resolver whose view is limited to local domains is not very common. But if it happens, and apparently it did for you, you can still change the script to use local domains. You need to change this query, but also the HTTP query for apple.com which is designed to detect another way captive portals hijack connections.

This app is now @alterstep's baby, but I don't think it's worth handling this very special case in this app.

**Comment by fred-chen** [comment]
Got it. I’d modify my local script for personal use. Thanks for the reply.

Regards,
Fred Chen
