### ISSUE TITLE
Problem with Starting DNSCrypt on Windows 8.1

### ISSUE THREAD

**Issue by ajay340** [jedisct1/dnscrypt-proxy#272]
Hi, so whenever I start DNSCrypt-proxy in my command prompt I get this ERROR:
![Error](https://i.imgur.com/FzRHS9x.png)
Help?

**Comment by jedisct1** [comment]
Did you use an elevated command prompt? https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown#how-to-open-an-elevated-command-prompt

**Comment by ajay340** [comment]
When I do that it brings me to the system32 folder, is it safe to put my DNScrypt proxy folder in there?

**Comment by ajay340** [comment]
So I moved it in the system32 folder and I run in administrator command prompt and ran dnscrypt-proxy but it says I'm missing libwinpthread-1.dll but when I checked in the folder, I had it. So I delete the dnscrypt folder and extract the zip again to system32 and ran dnscrypt-proxy again, and it gave me the same error saying I was missing it. I checked again it was still there. Please help.

**Comment by jedisct1** [comment]
Hi Ajay,

Maybe you can try to extract it somewhere else. Then in the command prompt, type `cd ` followed by a folder name in order to go there.

**Comment by CHEF-KOCH** [comment]
Try to execute it from <code>C:\Program Files</code> instead of <code>system32</code>, that should work without any problem. Also try to re-download the entire dnscrypt package, maybe something was wrong.

**Comment by jedisct1** [comment]
Also, I heard through the grapevine that a brand new GUI for Windows (written from scratch, easy to install, supports backup resolvers, embeds the proxy and verifies the resolvers list signatures) was going to be released soon. 

Stay tuned :)
