### ISSUE TITLE
File /system/xbin/dnscrypt is missed in the android 1.6.0 version

### ISSUE THREAD

**Issue by Tobyskernel** [jedisct1/dnscrypt-proxy#273]
I downloaded the armv7 version for android from https://download.dnscrypt.org/dnscrypt-proxy/. When I try to add a toggle-switch file in /system/xbin named "dnscrypt" for it, whichi method I copied from KyonLi , I find this name is already included in the updater-script and 75-dnscrypt.sh, but not in the xbin folder. I guess it's a misstake that you forgot to put it in.

**Comment by jedisct1** [comment]
Added in 3f28178550c97a629934ba8bbfb6881cb06c871b, thanks!
