### ISSUE TITLE
DNS resolution failing without apparent reason, switching to a second resolver?

### ISSUE THREAD

**Issue by grk-** [jedisct1/dnscrypt-proxy#281]
Last night dnscrypt stopped resolving internet hosts from my home network.
Analyzing syslog did not show evidence of apparent reason.
I had to restart dnscrypt-proxy service to regain DNS resolutions.

I'm using 1.4.3-4 from Debian stalbe. My current config is:

DNSCRYPT_PROXY_LOCAL_ADDRESS=127.0.2.1:53
DNSCRYPT_PROXY_RESOLVER_NAME=dnscrypt.org-fr

So I'm wondering how to use a secondary resolver in case the first one fails.

**Comment by jasker5183** [comment]
I second this using version 1.6.0 and sometimes it the morning when dnscrypt can't connect to a server it gives errors in chrome dns bad config or some such. Remove 127.0.0.1 from the proxy list aaaaaannnnnndddd it works. Looks like I'm using the server eu.nl. Is there no way to have it automatically change servers?

**Comment by jedisct1** [comment]
The recommended way to use it is behind a DNS cache, especially on Linux.
This also allows using multiple servers.

See the documentation: https://www.dnscrypt.org/#dns-cache
