### ISSUE TITLE
[Question] check DNS resolvers response time and command to restart service

### ISSUE THREAD

**Issue by Krysisx** [jedisct1/dnscrypt-proxy#284]
Hi,

I have 2 questions:
1) how can I restart `dnscrypt-proxy` process that is already running on my machine?
I have installed the program from `anton+` ppa: https://launchpad.net/~anton+/+archive/ubuntu/dnscrypt so I don't know how it's running in background.
2) is there a way to test the DNS resolvers response time? Like doing `dig microsoft.com` in unix.

Thanks

**Comment by jedisct1** [comment]
1) Looks like this package is using systemd.

So you can restart it with:

    systemctl restart dnscrypt-proxy

See https://wiki.ubuntu.com/SystemdForUpstartUsers to learn about 0.000000001% of what systemd does.

2) You can still use commands such as `dig` or `drill`. Anything you did that required a DNS resolver should keep running the same when accessing a resolver over DNSCrypt.

**Comment by Krysisx** [comment]
Ok great thanks.
But I tried `dig google.com @93.180.156.42` (I have got that IP address from the resolvers list) and it reports
`google.com @93.180.156.42
;; global options: +cmd
;; connection timed out; no servers could be reached`
So I thought that there was some difference between using `dig` and using `DNSCrypt`.

**Comment by jedisct1** [comment]
Just remove `@93.180.156.42`.

The query has to be sent to the IP address of the machine running `dnscrypt-proxy`.
I don't know what exact IP this package is asking the proxy to listen to, but it's likely to be `127.0.0.1`.

And the package probably changes `/etc/resolv.conf` or the dnsmasq configuration to use it, so everything on your system is using DNSCrypt to resolve DNS names already. So, no need to add an explicit IP to your `dig` command.

**Comment by Krysisx** [comment]
Yes, but the problem is that I was testing that IP while using DNSCrypt with onother resolver IP, so I can't test that IP using `dig` without `@93.180.156.42`.

**Comment by jedisct1** [comment]
You can always start another proxy on another IP or port. For example on port 5000:

    dnscrypt-proxy -R dnscrypt.org-fr -a 127.0.0.1:5000

Then send your query with:

    dig -p 5000 google.com @127.0.0.1

**Comment by Krysisx** [comment]
ok great thanks, and how can I stop it after that?

**Comment by jedisct1** [comment]
Hit Control-C.

**Comment by Krysisx** [comment]
thanks
