### ISSUE TITLE
Interested in IPv6 in dnscrypt-resolvers.csv?

### ISSUE THREAD

**Issue by Fusl** [jedisct1/dnscrypt-proxy#286]
Hi,

couple of my servers have IPv6 addresses, too. Please let me know if you would like me to add the IPv6 addresses of them to the dnscrypt-resolvers.csv file along with the IPv4 address (as a new entry).

**Comment by jedisct1** [comment]
Go for it!

More IPv6 resolvers would be great!

**Comment by Fusl** [comment]
What name would you prefer? Currently it is "fvz-rec-at-vie-01" for IPv4, would "fvz-rec-at-vie-01-v6" be fine?

**Comment by jedisct1** [comment]
Let's be explicit and go for a full "ipv6" suffix!

**Comment by Fusl** [comment]
So, like "fvz-rec-at-vie-01-ipv6"? (Just want to be sure about it)

**Comment by jedisct1** [comment]
Exactly!

**Comment by jedisct1** [comment]
Oh, just one
