### ISSUE TITLE
Presence of active .tcshrc renders DNSCrypt useless in Mac OS X Yosemite 10.10.5 

### ISSUE THREAD

**Issue by justPaulo** [jedisct1/dnscrypt-proxy#291]
Reproducibility: always, as long default shell is tcsh and a file .tcshrc exists.
![dnscrypt](https://cloud.githubusercontent.com/assets/1660842/10125278/b5350dd8-6565-11e5-8d96-4e5e8deeba85.png)

**Comment by jedisct1** [comment]
dnscrypt-proxy never uses a shell. It never spawns any other processes.
I hardly see how a .tcshrc file could have any impact on it o_O
Mind to clarify what you mean by "useless"?

**Comment by justPaulo** [comment]
Sure. By useless I mean the icon of DNSCrypt changes to an exclamation mark. Seems a fair indication that is not working properly. 
![screenshot 2015-09-28 00 50 47](https://cloud.githubusercontent.com/assets/1660842/10125863/4f980d34-657b-11e5-82f9-c0d2e1fd92d5.png)
What do you mean by "o_O" ? (not familiar with that lingo/sign)
Actually what is seen in "Current DNS settings" is the partial output of the ncal UNIX command inside the tcsh startup script.

**Comment by jedisct1** [comment]
I see.

dnscrypt-proxy (this project) has no user interface, so I think you are talking about a different project called OXClient and maintained by someone else: https://github.com/alterstep/dnscrypt-osxclient

Do you mind filing your bug report there?

**Comment by justPaulo** [comment]
It has been done.
