### ISSUE TITLE
Feature request: HA option

### ISSUE THREAD

**Issue by yvoinov** [jedisct1/dnscrypt-proxy#295]
Hi.

I would like to request one useful feature.

High Availability.

I use dnscrypt as clean DNS source in business-centre. And from time to time single dnscrypt server goes down long time. With is force me to change config manually and restart daemon.

In this case will be useful HA feature - like NTPD - some dnscrypt servers specified, which will be daemon selected by ping/availability by auto. This will suppress manual interventions.

WBR, Yuri

**Comment by jedisct1** [comment]
Hi Yuri,

The recommended way to run the client is behind a caching DNS resolver, as documented here: https://dnscrypt.org/#dns-cache

Not only it will be everything faster, it will also automatically fall back to another upstream resolver if one is not reachable any more.

**Comment by yvoinov** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256
 
My unbound cache is behind dnscrypt proxy, because our ISP is censored
DNS by usind transparent 53 port interception. And often poisoned DNS.
So, I forced to use dnscrypt as clean DNS source. Otherwise my users
can't use Google Apps, Youtube, archive.org, and more. Completely.

Also, Google DNS or OpenDNS is also intercepted in my country by ISP's
and spoofed.

As I understand, I must configure two or more services with different
configs?

07.10.15 21:00, Frank Denis пишет:
> Hi Yuri,
>
> The recommended way to run the client is behind a caching DNS
resolver, as documented here: https://dnscrypt.org/#dns-cache
>
> Not only it will be everything faster, it will also automatically fall
back to another upstream resolver if one is not reachable any more.
>
> ---
> Reply to this email directly or view it on GitHub:
>
https://github.com/jedisct1/dnscrypt-proxy/issues/295#issuecomment-146221888

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2
 
iQEcBAEBCAAGBQJWFTSkAAoJENNXIZxhPexG6v8IAKP2pjMK/v6g0mEKnYItOtxo
xdb7ynoPx4rFk1PMxPJhf0EPOhZF1jfgASxszIegnP1M3mgUzAgKjt1QglbbC2yq
sJvWBuwcRIJEEdsaTqHKfoGIao2hInL0Ul4mmExzCgBuHM24axwC9SMOHMbJ8gVC
j2O1OxP3gUUS4Bz+J+58DQr0B3LQ5trKogtIgG1P5UTcloDoHqOwY+gQmv9sjoN1
jegkUT9EfkFd2x8ez31Y1/1KlvuzSfWH4mZX+o9qSp3fh2tfrhph28Nu7h7eVgCt
xAHYTnQpcsTPWQx1qXGbPasacGIZfx2pFBX64HD6vYezZL7leGKDxxvdZkA5tHc=
=sryT
-----END PGP SIGNATURE-----

**Comment by jedisct1** [comment]
Run one dnscrypt instance per upstream dnscrypt resolver you want to use, and use a single Unbound instance in front of them, forwarding queries to them.

**Comment by yvoinov** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256
 
Does this functional available for Windows?

07.10.15 21:07, Frank Denis пишет:
> Run one dnscrypt instance per upstream dnscrypt resolver you want to use, and use a single Unbound
instance in front of them, forwarding queries to them.
>
> ---
> Reply to this email directly or view it on GitHub:
>
https://github.com/jedisct1/dnscrypt-proxy/issues/295#issuecomment-146223868

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2
 
iQEcBAEBCAAGBQJWFTZMAAoJENNXIZxhPexGcdYH/i+YUssAmhnekOneYRcoR4mS
XCoEzqBkzuCGY6KJiIERaNff6RZUe4NBQgMOzS/FPEzQ4BJIUUwpskcAE1Qln6A5
3H5McvdK1qWChcJSU1Krf7WAtERvzOCWUSoheI0R1YOzHMvu4CqNbRMygCaLP6cv
CmwIVFC6f5+RDwudP1XXJGkpF6IXGsNzcGhec8kQmgy7VkdcUKwScbfBTrS6ZHWg
UH0kdSOmOPYW60p8lagjgfFFmMfuBRskDXFAW0D58ZuIrsFMIkeAYDlGw8ZQc/m5
EJ2OIEwF8m+cC2jvdMdV7lNHXYnPShcrXh42f263uHIYyl+GrLjQVwAsbcmDJqU=
=rqJS
-----END PGP SIGNATURE-----

**Comment by jedisct1** [comment]
You can make it work on Windows, if you don't run the proxy as a service.

https://simplednscrypt.org/ will also soon handle it, as soon as I find some time to allow different registry keys.

**Comment by yvoinov** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256
 
With different registry keys dnscrypt will allow run as a services
itself, isn't it?

07.10.15 21:19, Frank Denis пишет:
> You can make it work on Windows, if you don't run the proxy as a service.
>
> https://simplednscrypt.org/ will also soon handle it, as soon as I
find some time to allow different registry keys.
>
> ---
> Reply to this email directly or view it on GitHub:
>
https://github.com/jedisct1/dnscrypt-proxy/issues/295#issuecomment-146227879

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2
 
iQEcBAEBCAAGBQJWFVXdAAoJENNXIZxhPexGu7oH/jXPnmEH/BkCZgsv3Kk70GB+
jqtAHgeBL72khE/ERtvy1UNFToZPe3YPYG2b4i2Ybc5mPJ0GRkmtkzXy26mZvJvP
1od5B+XgvOzEdsMAzV4PEGNsZmh+jHzY8j09JT9DqHq+id+TKBwmxFo8SshRUU6i
Cxa2zuqydEAScduZpaY/pvs0YS5EmaChSYPdrGiis58j8Y+Eod+ojXEWBkpbYNfb
RRdezIWft/Kqb+ZBZtC1JJErte1fumMq07d2cc7roTSzqvYSQv5YAW3iAve4tUhV
05LIprqruGcEWtXmDTLb84nRFffAbgxpYzlUvC/q26FSy1v/AtXlub/LBqnhUVE=
=ju2Y
-----END PGP SIGNATURE-----

**Comment by jedisct1** [comment]
Yes
