### ISSUE TITLE
The latest version always stops on windows 10

### ISSUE THREAD

**Issue by yangzhaofeng** [jedisct1/dnscrypt-proxy#297]
The exit information is "Assertion failed" and an error in udp_request.c(in line 194). But the 1.5.0 version is fine.

**Comment by jedisct1** [comment]
Are you using plugins? Which ones?

**Comment by yangzhaofeng** [comment]
I don't use any plugins.

**Comment by yangzhaofeng** [comment]
And now the 1.5.0 version also stops.
File: udp_request.c, Line 406
Expression: dns_query_len > (size_t) 0U && dns_query_len <= max_query_size && dns_query_len <= max_query_size_for_filter 

Is it due to a wild pointer?

**Comment by QUATO1** [comment]
Me too. Using Vuze, ExpressVPN and just upgraded to Windows 10.
Testing so far:
- Does not fail during normal downloading.
- Does not fail with ExpressVPN turned on.
- DNSCrypt turned on, loses internet connection and computer goes into hiberation mode randomly after 60 mins or more.

**Comment by QUATO1** [comment]
Update on testing. It seems to be stable now using the following steps:
1. Enable dnscrypt.
2. Start VPN.
3. Start and complete downloading.
4. Stop VPN.
5. Disable dnscrypt.
6. Change DNS settings to another DNS for normal work eg. Google, Opendns.
Does this sound right?

**Comment by jedisct1** [comment]
Do not use DNSCrypt and a VPN at the same time.

Your VPN is already authenticating everything, *including* your DNS queries.

Using both a VPN and DNSCrypt at the same time is likely to weaken your security and privacy.
