### ISSUE TITLE
DNScrypt in iPhone 6

### ISSUE THREAD

**Issue by eborjalopez** [jedisct1/dnscrypt-proxy#303]
Hi all, 

would you mind to can to support on the installation of the app in my iphone 6? My provider is blocking me everything on the 3G/4G connection.

Thanks in advance!

**Comment by jedisct1** [comment]
Is your phone jailbroken?

**Comment by CrisBRM** [comment]
https://wiki.installgentoo.com/index.php/DNSCrypt#iOS
