### ISSUE TITLE
not working when connected to VPN...

### ISSUE THREAD

**Issue by mathisonrichard** [jedisct1/dnscrypt-proxy#304]
greetings,

[see attached] i use PIA http://www.privateinternetaccess.com as my VPN. when connected to Vpn, dnscrypt icon shows exclamation mark. when not connected to VPN, dnscrypt icon shows locked. how do i configure dnscrypt to show locked when using VPN?

i am looking forward to hearing from you soon. thank you.
![screen shot 2015-10-20 at 10 26 37 am](https://cloud.githubusercontent.com/assets/15216159/10612436/70aa9bb6-7716-11e5-9d43-6d0ec374e9d9.png)
![screen shot 2015-10-20 at 10 25 06 am](https://cloud.githubusercontent.com/assets/15216159/10612443/78768c92-7716-11e5-88f1-7e5b07b525e2.png)

**Comment by jedisct1** [comment]
You don't :)

If you are using a VPN, you don't need DNSCrypt, as the VPN service already authenticates all your traffic, including your DNS queries.
