### ISSUE TITLE
Most providers don't work in Indonesia

### ISSUE THREAD

**Issue by w13** [jedisct1/dnscrypt-proxy#306]
I'm using Simon Clausen's Windows Service Manager for DNSCrypt. It works perfectly, except that I've noticed that Indonesia has blocked many of the providers: all OpenDNS, all OpenNIC, all d0wn, all CloudNS, and all DNSCrypt. So I'm using okTurtles right now.

My IP: 118.96.148.144

**Comment by jedisct1** [comment]
Sorry to hear that :(

But if the Indonesian government decided to block public DNSCrypt servers, there's not much that can (and should) be done in the protocol.

**Comment by pysiak** [comment]
Sad to hear that about Indonesia.

A side note:
This actually adds to my idea to have web page with a global dnscrypt
dashboard showing a world map of servers, with availability checked from
browser's location, with metadata, etc.

And on top of that: storing the data for reporting on timelines.

Perhaps doing a global latency check on dnscrypt protocol could be used to
see if we start to see throttling down of encrypted traffic.


One of the things I'll come up with but never have the time to do :-|

**Comment by jedisct1** [comment]
That would be totally awesome

**Comment by bitbeans** [comment]
:+1:
