### ISSUE TITLE
No custom recovery for Android device

### ISSUE THREAD

**Issue by c-gabri** [jedisct1/dnscrypt-proxy#307]
I'm following the instructions at https://dnscrypt.org/#dnscrypt-android to install DNSCrypt on my Android device, a Meizu M2 Note. Unfortunately I'm stuck at step 4, because neither TWRP recovery nor other custom recoveries seem to be available for my device.
Is there something I can do or should I just give up? If so, do you know any other program that accomplishes what DNSCrypt does and which does not require a custom recovery?
Note that apps like DNS Changer are not enough to do the trick, as my ISP overrides the DNS addresses I specify.

**Comment by jedisct1** [comment]
For rooting Android devices, http://www.xda-developers.com/ is probably better a place to ask. There might be a different way to root your device.

If not, your only hope is a VPN.

**Comment by c-gabri** [comment]
The device is already rooted, there's just no custom recovery installed.
