### ISSUE TITLE
DNSCrypt stops working if I set up the local network ip, the DNSCrypt bind ip and the dns-nameserver ip the same

### ISSUE THREAD

**Issue by Hugo14** [jedisct1/dnscrypt-proxy#309]
I have a small headless home server running ubuntu 14.04 and was trying to set up dnscrypt-proxy in it. This server is also the dhcp server and needs to access the internet itself (dns included) for other tasks.

I have set up dnscrypt-proxy and bind it to the local network ip of my server 192.168.1.1 . It works fine and can be accessed by machines in the local network. I have set up the dhcp server to pass this address and everything works. I have even tested it with the dig command. Everything is working as expected.

The problem comes when I try to have the server itself use 192.168.2.1 as dns server. On reboot, dnscrypt-proxy stops working for everybody.

I have set up the ip of the server static in interfaces like this:

iface eth0 inet static
    address 192.168.1.1
    network 192.168.1.0
    netmask 255.255.255.0
    broadcast 192.168.1.255
    gateway 192.168.1.75
    dns-nameservers 192.168.2.1

If I set up everything the same, but with dns-nameservers "some.internet.dns.server", everything works, except that my home server is not using dnscrypt-proxy. As soon as I change the configuration of dns-nameservers to the ip of the server and reboot, dnscrypt-proxy stops working.

How can I configure dnscrypt-proxy so the local network machines and the server itself can access it?

**Comment by jedisct1** [comment]
Does the `dnscrypt-proxy` process run after a reboot?

**Comment by jedisct1** [comment]
Timeout.
