### ISSUE TITLE
help me with plugin setup please

### ISSUE THREAD

**Issue by alex3026** [jedisct1/dnscrypt-proxy#310]
I can't make ipv6 blocking plugin to work, I did as main page instructions says but getting errors in cmd. Can you show here the exact command how to use aaaa blocking plugin on windows 7 64 bit.

Also I see in Currports that dnscrypt uses both TCP and UDP protocols on port 53, I heard that TCP is slower, should I use it only with UDP? if yes, how to do that?

**Comment by CHEF-KOCH** [comment]
TCP is as fallback in case (because some ISP's possible locking this), yes it's slower and UDP should be preferred if possible. UDP will be used by default if you want TCP then you need TCPOnly into your registry.

**Comment by jedisct1** [comment]
Version 1.8.0 can be configured on Windows using a config file: https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown#advanced-configuration

This includes plug-ins, that are way easier to use.
