### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#313]
```
Secure Connection Failed

An error occurred during a connection to download.dnscrypt.org. Invalid OCSP signing certificate in OCSP response. (Error code: sec_error_ocsp_invalid_signing_cert)

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by jedisct1** [comment]
Wosign's revocation server apparently blocks some IP ranges. Tor exit nodes are probably part of the block list.

I removed OCSP stapling.

**Comment by CNMan** [comment]
i do not use tor but DigitalOcean proxy.
you can apply a free one-year COMODO Positive SSL Certificate follow [this guide](http://www.mujj.cn/archives/150.txt)

**Comment by jedisct1** [comment]
I can hardly trust a CA with a terrible security history. But I am going to switch to Letsencrypt as soon as the minor issues with their software and OpenBSD have been solved.
