### ISSUE TITLE
Automatic update of resolver list

### ISSUE THREAD

**Issue by notDavid** [jedisct1/dnscrypt-proxy#314]
Hi, do you have any plans to automatically update the resolver list as dnscrypt-osxclient does?

alterstep/dnscrypt-osxclient@a364d88326b806807b98a799f0f237af9b88b989

(for example when downloading the latest release tar, you end up with an outdated/not working resolver list.)

**Comment by jedisct1** [comment]
Problably not, as this is very dependant on the operating system/distribution and on how and where the software was installed. So, that's better left to package maintainers.

That said, it's super simple to do. This is how dnscrypt-osxclient does it:

```bash
#! /bin/sh

RESOLVERS_UPDATES_BASE_URL=https://download.dnscrypt.org/dnscrypt-proxy
RESOLVERS_LIST_BASE_DIR=/tmp
RESOLVERS_LIST_PUBLIC_KEY="RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"

curl -L --max-redirs 5 -4 -m 30 --connect-timeout 30 -s \
  "${RESOLVERS_UPDATES_BASE_URL}/dnscrypt-resolvers.csv" > \
  "${RESOLVERS_LIST_BASE_DIR}/dnscrypt-resolvers.csv.tmp" &&
curl -L --max-redirs 5 -4 -m 30 --connect-timeout 30 -s \
  "${RESOLVERS_UPDATES_BASE_URL}/dnscrypt-resolvers.csv.minisig" > \
  "${RESOLVERS_LIST_BASE_DIR}/dnscrypt-resolvers.csv.minisig" &&
minisign -Vm ${RESOLVERS_LIST_BASE_DIR}/dnscrypt-resolvers.csv.tmp \
  -x "${RESOLVERS_LIST_BASE_DIR}/dnscrypt-resolvers.csv.minisig" \
  -P "$RESOLVERS_LIST_PUBLIC_KEY" -q &&
mv -f ${RESOLVERS_LIST_BASE_DIR}/dnscrypt-resolvers.csv.tmp \
  ${RESOLVERS_LIST_BASE_DIR}/dnscrypt-resolvers.csv
```

Pretty straightforward.

**Comment by notDavid** [comment]
@jedisct1 I see, thanks!
