### ISSUE TITLE
Unable to bind (UDP) address already in use [WSAEADDRINUSE ]]

### ISSUE THREAD

**Issue by amrgul** [jedisct1/dnscrypt-proxy#320]
I'm running Dnscrypt-proxy client as admin but still  receiving this error when use dnscrypt-proxy -R cloudns-syd \--plugin libdcplugin_example_ldns_aaaa_blocking.la  

![capture](https://cloud.githubusercontent.com/assets/16084462/11475515/436bca20-9797-11e5-8fa5-07bdd205f721.JPG)

I think plugin works, should I ignore "Unable to bind (UDP)" error?

**Comment by CrisBRM** [comment]
Try dnscrypt-proxy --local-address=127.0.0.2 instead.

**Comment by jedisct1** [comment]
Do you already have something listening on port 53? Maybe the dnscrypt proxy already running as a service?

**Comment by amrgul** [comment]
@CrisBRM    i tried 127.0.0.2 but lost internet.

@jedisct1    dnscrypt-proxy is installed already and running and after that I activated the plugin, so, is it normal then?

**Comment by CrisBRM** [comment]
> i tried 127.0.0.2 but lost internet
That's because you have to go into network settings, advanced, and change the name server (DNS) to 127.0.0.2.
Alternatively, you could look into using https://simplednscrypt.org/

**Comment by amrgul** [comment]
@CrisBRM   ok but maybe this error means nothing, i would prefer to leave everything to default.

**Comment by CrisBRM** [comment]
You do realise you still need to do this, even if you use the default settings, right?

**Comment by amrgul** [comment]
@CrisBRM  I will leave loopback to 127.0.0.1, as for simplednscrypt, i won't hurry installing it, those gui interfaces may trigger additional security risk. 
I will also wait for jedisct1 advice and then decide how to do, of course thank you for helping me.

**Comment by jedisct1** [comment]
If you had a previous instance running as a service, you can't start another one at the same time, or at least not on the same port and same ip.

Try:

```bash
dnscrypt-proxy --uninstall
```

In order to stop and uninstall the previous instance if there was one.

SimpleDNSCrypt is a great UI. It just starts the service the same way you would do manually, and even the way it updates the list of resolvers is fine (checking the signature before installing a new version). I don't think it introduces any security risk.

**Comment by amrgul** [comment]
@jedisct1  I already did exactly you say-first uninstalled dnscrypt-proxy, then installed again (setting also 127.0.01) and after this installed plugin and got this error. What I need to know is that is this error makes something not to work correctly? why it occurs? I have done every steps correctly I think.

**Comment by jedisct1** [comment]
You are trying to install it twice. Give it the list of plugins you want to activate when you are installing the service:
```
dnscrypt-proxy --install -R cloudns-syd --plugin libdcplugin_example_ldns_aaaa_blocking.la
```

**Comment by amrgul** [comment]
ill try this now...

**Comment by amrgul** [comment]
i got this;

![capture](https://cloud.githubusercontent.com/assets/16084462/11484514/cab8589c-97c7-11e5-8a47-9a79388f711b.JPG)

but doesn't say anything if plugin is installed and working?

**Comment by jedisct1** [comment]
If it doesn't complain, it means that it worked :)

**Comment by amrgul** [comment]
ok, thank you, I will use this. 
Just my opinion is that it would be great if simplednscrypt had portable version also.

**Comment by Ghostboy-287** [comment]
i got the same error and i just modified `dnscrypt-proxy.conf` file and it works 

- uncomment  `LocalAddress 127.0.0.1:53` in **## Network/protocol settings ## section**

- change 127.0.0.**1**:53    ===>    127.0.0.**2**:53  as said on the top
(do not forget to do that as root) and this solution (i think) is permanent and no need to add --local-address... each time

**Comment by jedisct1** [comment]
The thread you are replying to is 2 years old, and there was no config file back then.

**Comment by Ghostboy-287** [comment]
ah ok, sorry 
but it can helps persons who have or will have the same problem 
they will probably find this issue by searching on google...; and nothing will please them than finding two possible solutions in one place :D 
--close--
