### ISSUE TITLE
Request: update d0wn's servers?

### ISSUE THREAD

**Issue by umbrageous** [jedisct1/dnscrypt-proxy#321]
I see https://dns.d0wn.biz/ has others servers, including another randomizer, not currently in the resolvers list. Might they be included in the next update, please?

**Comment by onmyouji** [comment]
+1 to this.

This server (Singapore) ns1.sg.dns.d0wn.biz - 128.199.248.105 is not in the list yet.

**Comment by jedisct1** [comment]
Would it be possible to submit a pull request?

**Comment by onmyouji** [comment]
I'm not quite sure what's the current status of the server.

From the csv history (https://github.com/jedisct1/dnscrypt-proxy/commit/0574c65948e7433232ef713642a5b93c98f6c71e?diff=unified)
That server was removed back in 15 October, but I'm not sure for what reason. The title says "Bring back the Fusl servers that have been kept alive"

**Comment by jedisct1** [comment]
Working entries have been added. Dead ones have been removed.
