### ISSUE TITLE
dnscrypt not encrypting

### ISSUE THREAD

**Issue by elpirata15** [jedisct1/dnscrypt-proxy#324]
`# uname -a`
`Linux debian01 4.2.0-1-amd64 #1 SMP Debian 4.2.5-1 (2015-10-27) x86_64 GNU/Linux`

`# dnscrypt-proxy -V`
`dnscrypt-proxy 1.6.0`

I'm using

`# dnscrypt-proxy --ephemeral-keys --resolver-name=d0wn-bg-ns1`

Getting this

```
[INFO] - [d0wn-bg-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Ephemeral keys enabled - generating a new seed
[INFO] Done
[INFO] Server certificate #808464433 received
[INFO] This certificate looks valid
[INFO] Chosen certificate #808464433 is valid from [2015-02-12] to [2016-02-12]
[INFO] Server key fingerprint is EB60:C492:AB1B:EEDF:4A1C:F774:6EE1:3051:84A8:5CD1:926E:69EA:3C88:CD95:3228:3F16
[NOTICE] Proxying from 127.0.0.1:53 to 217.12.203.133:54
```

My /etc/resolv.conf is set with 127.0.0.1

`dig 127.0.0.1`

```
; <<>> DiG 9.9.5-12+b1-Debian <<>> 127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 16478
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;127.0.0.1.			IN	A

;; AUTHORITY SECTION:
.			3124	IN	SOA	ns0.opennic.glue. hostmaster.opennic.glue. 2015120401 1800 900 604800 3600

;; Query time: 39 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Dec 08 10:37:30 CET 2015
;; MSG SIZE  rcvd: 89
```

But when I'm looking in Wireshark, I can see the dns petition unencrypted.

![untitled](https://cloud.githubusercontent.com/assets/15010089/11652662/d7ce9126-9d90-11e5-9f70-50c64805d2bd.png)

**Comment by jedisct1** [comment]
You're looking at the wrong interface :)

127.0.0.1 receives the regular unauthenticated queries from your applications. What gets authenticated and encrypted are the queries going to the external network!

**Comment by elpirata15** [comment]
Thanks for your reply,

Just to confirm, now I'm filtering my interface and targeting the dnscrypt server address. 

These are the encrypted packages, right?

![untitled](https://cloud.githubusercontent.com/assets/15010089/11653673/978b4fa8-9d97-11e5-8d5d-e82f21dce890.png)

**Comment by jedisct1** [comment]
Yes! Looks like it's working :)
