### ISSUE TITLE
Official Matrix Chat created

### ISSUE THREAD

**Issue by CHEF-KOCH** [jedisct1/dnscrypt-proxy#326]
I created an official room on the [Matrix.org](https://github.com/matrix-org/synapse) server. @jedisct1 you can contact me and I hand-over you the room key. Of course I would hand over the keys to anyone which want to help / moderate. For those who are new to Matrix, [here is a full Riot usage Guide](https://edgeryders.eu/t/using-matrix-riot-instant-messaging/6430).

![dnscrypt](https://user-images.githubusercontent.com/727123/38461088-cf2b3782-3ac7-11e8-9a61-17430eb97bf2.png)

- The room is encrypted by default (m.megolm.v1.aes-sha2), it used the matrix protocol and is (even in his earlier stage promising). 
- The official URL / Link is: [#dnscrypt-proxy:matrix.org](https://matrix.org/#/#dnscrypt-proxy:matrix.org).
- The chat could give basic help on several question, tips or tricks. It also can be used to discussion beta relevant [topics](https://github.com/jedisct1/dnscrypt-proxy/issues/323).
- if there is a wish/need I also can provide a bridge to IRC, Telegram or Signal so that you can get a grap between other clients to see/join/read the chat/discussion.
- I would see this as a community driven room.

The room is basically created for people which don't want to login into GitHub, Reddit etc in order to ask a question or to get help. Matrix or the room etc. doesn't collect any personal information.

**Comment by antonsamoziv** [comment]
Nice, I like it. This should bridge with freenode too right?

**Comment by CHEF-KOCH** [comment]
Yep. I'll close my own 'ticket' here (_soon_) and merge it within the readme or wiki once I have more time. Since this is (as already correctly labeled) an announcement rather than a 'issue'.

Keep in mind that the bridges can be bugged from time to time but the guys working constantly on it to fix it.

**Comment by iWARR** [comment]
**[Matrix]** is a good choice. It's very modern and end-to-end encrypted using rescent standards.

Also it have excellent client for it - **Riot.im**
Developer:	Vector Creations Limited

You may use it on Desktop and Mobile without any phone number, any personal data or even email (If you want, your can register email, so your friends which know it, will have ability find you somehow). Or stay unsearchable and completely anonimous (using Nickname only)

-------------------------------------------------------

_**Some useful links (**Riot.im**):**_

[Recommended by PRISM BREAK](https://prism-break.org/ru/categories/windows/)

[Homepage](https://riot.im)
[NEWS (Medium)](https://medium.com/@RiotChat)

[Chat | Regiser](https://riot.im/app)
[BRIDGES](https://about.riot.im/apps-bots-and-bridges/)

_**GitHub:**_
[Source Code (Android)](https://github.com/vector-im/riot-android)
[Changelog](https://github.com/vector-im/riot-android/blob/HEAD/CHANGES.rst)
[Download (source)](https://github.com/vector-im/riot-android/releases)

[Desktop](https://riot.im/desktop.html)

[Google Play](https://play.google.com/store/apps/details?id=im.vector.alpha#)
[F-Droid (download *.apk)](https://f-droid.org/packages/im.vector.alpha/)

**Comment by CHEF-KOCH** [comment]
Some people contacted me or wrote it into the chat so I try to keep it short and answer it for everyone here.

- Why is everyone shown as offline?
- Why is there no history?
- Why is encryption enabled - shouldn't it be open same like the dnscrypt-proxy project on GitHub?
- Why isn't there an IRC/Slack etc

1. Please see this [issue](https://github.com/vector-im/riot-web/issues/2667), all official servers including our one (matrix.org) one disabled it (for now) in order to take less pressure on the service performance. You only see the status - for now - if you host it on your own server. But this might get fixed officially once there is a better solution for everyone. 

2. I was able to enable chat-history myself with a hacky webhook. It should be visible for everyone now, even if you're a new visitor or re-join the chat.

3. Encryption is enabled because it's not my server. I simply want to protect the room or that someone interference into it from outside (MITM). That's all, you still can copy & paste the history conversations or screenshot it. 

4. I wasn't able to integrate the bridge to IRC etc for now, I'm working on it, it seems you need to approve the bridge from the other side first. Since I'm not an active member on IRC, Slack etc anymore I simply need some time to re-create new accounts etc. I hope I have enough time over the next 4 weeks (yes I know sounds much but I'm busy).  

I added an RSS Bot if you don't like security messages from Reddit.com/r/netsec and bleepingcomputer.com you can click on the Bot and press 'ignore' this will hide it's messages. 

GitHub changes, comments etc. are handled by an GitHub Bot, so that you can see new commits, releases, issue tickets etc in the near future. The webhook is already running but I need to debug the problems now since he seems inactive for no reasons. 

I think that the matrix protocol (electron) is the future and a full IRC/Slack/ICQ/WhatsApp/discord replacement and that's why I decided to use it, it has huge potential. It also has, in my opinion, the best privacy policy and works across all operating systems and everyone can see the source code etc.

Sorry for the long text. If there some wishes please feel free to contact me over my eMail, Blog or directly through Riot.
