### ISSUE TITLE
Unable to load plugins; File not found

### ISSUE THREAD

**Issue by prov3it** [jedisct1/dnscrypt-proxy#331]
Hi,

Im confused. Im trying to run: 
```
dnscrypt-proxy --local-address=127.0.0.1:5353 --resolver-name=ipredator --resolver-address=194.132.32.32:443 --provider-name=2.dnscrypt-cert.ipredator.se --provider-key=C44C:566A:A8D6:46C4:32B1:04F5:3D00:961B:32DC:71CF:1C04:BD9E:B013:E480:E7A4:7828 --tcp-only --max-active-requests=1024 --plugin=/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la,--domains=/path/to/file
```
output:
```
[INFO] - [ipredator] does not support DNS Security Extensions
[INFO] - [ipredator] does not support Namecoin domains
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Loading plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la]
[ERROR] Unable to load [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la]: [file not found]
[ERROR] Unable to load plugins

ls -lah /usr/local/lib/dnscrypt-proxy:
drwxr-sr-x 2 root staff 4.0K Dec 11 17:11 .
drwxrwsr-x 4 root staff 4.0K Dec 12 15:19 ..
-rwxr-xr-x 1 root staff 1.1K Dec 11 17:03 libdcplugin_example.la
-rwxr-xr-x 1 root staff 1.1K Dec 11 17:11 libdcplugin_example_ldns_blocking.la
-rwxr-xr-x 1 root staff  34K Dec 11 17:11 libdcplugin_example_ldns_blocking.so
-rwxr-xr-x 1 root staff 1.1K Dec 11 17:03 libdcplugin_example_logging.la
-rwxr-xr-x 1 root staff  20K Dec 11 17:03 libdcplugin_example_logging.so
-rwxr-xr-x 1 root staff  12K Dec 11 17:03 libdcplugin_example.so
```
dnscrypt is compiled with plugins enabled. Can you help me out?

**Comment by jedisct1** [comment]
Replace `/path/to/file` with a real path to a file with the list of domains to block :)

Also, you don't need the resolver name, IP, provider name and key. The resolver name is enough:

```bash
dnscrypt-proxy --local-address=127.0.0.1:5353 --resolver-name=ipredator --max-active-requests=1024 --plugin=/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la,--domains=...
```

Giving just the resolver name will keep working after the way certificates are retrieved changes. Other parameters will probably not exist any more.
```

**Comment by prov3it** [comment]
Hi jedisct1, thanks for your reply. Ofcourse i provided a list. now i tried:
dnscrypt-proxy --local-address=127.0.0.1:5353 --resolver-name=ipredator --max-active-requests=1024 --plugin=/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la,--domains=/root/lists/urlblacklist/ads/domains

output:
[INFO] - [ipredator] does not support DNS Security Extensions
[INFO] - [ipredator] does not support Namecoin domains
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Loading plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la]
[ERROR] Unable to load [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la]: [file not found]
[ERROR] Unable to load plugins

**Comment by prov3it** [comment]
Using (also tried another list):
strace dnscrypt-proxy --local-address=127.0.0.1:5353 --resolver-name=soltysiak --max-active-requests=1024 --plugin libdcplugin_example_ldns_blocking.la,--domains="/tmp/list"

i figured out what files are not found:
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)

Read on the internet you could just make an empty file (not sure if this is a good solution in this case):
echo "" > /etc/ld.so.nohwcap
echo "" > /etc/ld.so.preload

Looks ok:
access("/etc/ld.so.nohwcap", F_OK)      = 0
access("/etc/ld.so.preload", R_OK)      = 0

tried it again, still file not found, only lines i could find explaining the error (again using strace):
write(1, "[ERROR] Unable to load [/usr/loc"..., 110) = 110
gettimeofday({1450272448, 376756}, NULL) = 0
write(1, "[ERROR] Unable to load plugins\n", 31) = 31
exit_group(2)                           = ?

What am i missing?

**Comment by CrisBRM** [comment]
Maybe check the file permissions?

**Comment by jedisct1** [comment]
Or try the `ldd` command on the libraries (`.so` files) to see if there are no unresolved dependencies.

**Comment by prov3it** [comment]
Hi CrisBRM, thanks for your reply.

I must say im not an expert on this. So i tried:
```
stat -c '%a' /usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.la
stat -c '%a' /usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so
```
The files are 755. The folders are 2775.

Hi jedisct1 i think you meant the libdcplugin_example_ldns_blocking.so file so i tried:
```
ldd -v /usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so
```

output:
```
linux-vdso.so.1 (0x7efdf000)
	libsodium.so.17 => /usr/local/lib/libsodium.so.17 (0x76f71000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76f5d000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76ee2000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76da5000)
	/lib/ld-linux-armhf.so.3 (0x54b75000)

	Version information:
	/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so:
		ld-linux-armhf.so.3 (GLIBC_2.4) => /lib/ld-linux-armhf.so.3
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
	/usr/local/lib/libsodium.so.17:
		ld-linux-armhf.so.3 (GLIBC_2.4) => /lib/ld-linux-armhf.so.3
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
	/lib/arm-linux-gnueabihf/libdl.so.2:
		ld-linux-armhf.so.3 (GLIBC_PRIVATE) => /lib/ld-linux-armhf.so.3
		libc.so.6 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
	/lib/arm-linux-gnueabihf/libm.so.6:
		libc.so.6 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
	/lib/arm-linux-gnueabihf/libc.so.6:
		ld-linux-armhf.so.3 (GLIBC_2.4) => /lib/ld-linux-armhf.so.3
		ld-linux-armhf.so.3 (GLIBC_PRIVATE) => /lib/ld-linux-armhf.so.3
```

I have to add that dnscrypt previously was installed on debian wheezy instead of jessy. Could that be the issue? Again, unfortunately im not the expert here.

**Comment by CrisBRM** [comment]
755 is good (executable, only you can change it) and so is 2755... I was just wondering because gentoo's ebuild, for instance, creates a new user with no permissions and no home folder, that can only run dnscrypt (only belongs to the dnscrypt group).
It's most likely not this, but it was worth a try. Good luck.

**Comment by prov3it** [comment]
I dont understand it at all. I went back to Dietpi (Wheezy instead of Jessy) and it works. Issue not solved, but you can close it.

**Comment by jedisct1** [comment]
Weird, but good to know that it's working again!
