### ISSUE TITLE
Problem with the dnscrypt.org-fr DNS server

### ISSUE THREAD

**Issue by Angristan** [jedisct1/dnscrypt-proxy#332]
The **dnscrypt.org-fr** server gives wrong records for some domains.
At this moment I have problems with : 
* torcache.net
* imirhil.fr

When querying these domain, the server answers with some `127.42.0.x` adresses.

**Comment by jedisct1** [comment]
That's very unlikely. How did you check that?
Can you send the output of `drill -T torcache.net @<your dnscrypt client proxy IP>`?

**Comment by Angristan** [comment]
Oh... Maybe I'm wrong. On linux, no problem : ![linux](https://lut.im/cabiLZNhkV/aTo7ICtt7Bf35rWv.PNG)

But on Windows... :(
![windows](https://lut.im/GK5ZeyYHaG/ls92j7Ga6kbbgKQz.PNG)

**Comment by jedisct1** [comment]
Are you sure that the queries on Windows sent to the dnscrypt proxy and not being redirected to some antivirus junk?

**Comment by Angristan** [comment]
That's probably it.
