### ISSUE TITLE
libsystemd not found on Debian 8

### ISSUE THREAD

**Issue by Angristan** [jedisct1/dnscrypt-proxy#333]
Hi, I want to comple dnscrypt-proxy on Debian 8 but I have this error when compiling with `./configure --with-systemd`

`checking for SYSTEMD... no`
`checking for SYSTEMD_DAEMON... no`
`configure: error: systemd expected but libsystemd not found`

I installed libsystemd-dev but no success

**Comment by Angristan** [comment]
Okay, solved by installing other dependenicies (wtf is the link with systemd ??)

**Comment by andsens** [comment]
Just for others, that may find this issue through google. The "other dependencies" is simply `pkg-config`, which `configure` uses to check for systemd presence. It just doesn't distinguish between `pkg-config` failing to find `libsystemd-dev` and `PKG_CHECK_MODULES` not working ([here](https://github.com/jedisct1/dnscrypt-proxy/blob/b0cbca279451df864b9fbb6f394de5fe9196fe09/configure.ac#L108))

**Comment by Ardakilic** [comment]
For others, I've added these dependencies to compile on Debian 8 successfully:

```
sudo apt-get -y install build-essential tcpdump dnsutils libsodium-dev 
sudo apt-get -y install locate bash-completion libsystemd-dev pkg-config
```

Source for the guide I'm following: https://github.com/pi-hole/pi-hole/wiki/DNSCrypt

**Comment by jedisct1** [comment]
Keep in mind that compiling with systemd is only useful if you want to use socket activation (delegate socket handling to systemd).

This is not necessary, even if you are using systemd, that can be used just to spawn the service.
