### ISSUE TITLE
how do I install dnscrypt on linux mint 

### ISSUE THREAD

**Issue by Leon8200** [jedisct1/dnscrypt-proxy#335]
I downloaded the tar.gz and compiled it, I could not find an .exe in the mint menu so then I downloaded the dnscrypt-loader and tried to connect, it said it was connected to a dns but if I go to dnsleak test I only see my isp's dns so I dont know what to do, how do I get it set up?

**Comment by jedisct1** [comment]
This video explains everything: https://www.youtube.com/watch?v=7-IM-VqD4uk
