### ISSUE TITLE
 how do I install dnscrypt on linux mint/ what do I do to get it working?

### ISSUE THREAD

**Issue by Leon8200** [jedisct1/dnscrypt-proxy#336]
![screenshot - 12192015 - 02 28 22 am](https://cloud.githubusercontent.com/assets/16346096/11912018/33ee68fe-a5f8-11e5-9ea0-d48b104a249e.png)

**Comment by jedisct1** [comment]
[https://github.com/GortCodex/DNSCrypt-Loader](DNSCrypt-Loader) is an independant project. You should ask there!
