### ISSUE TITLE
do I need dnscrypt loader? or dnscrypt? 

### ISSUE THREAD

**Issue by Leon8200** [jedisct1/dnscrypt-proxy#337]
how do I get dnscrypt runing on mint I watched the video  https://www.youtube.com/watch?v=7-IM-VqD4uk

I dont know what to do after changing my dns to local host, what do I do to start dnscrypt

**Comment by jedisct1** [comment]
Hi Leon,

You only need `dnscrypt-proxy`, but `dnscrypt loader` is a nice addition, if only to get an up-to-date list of available resolvers.

According to the video, it looks like the proxy is started automatically. If not, you can try a command such as

```
/usr/sbin/dnscrypt-proxy -R dnscrypt.org-fr
```

**Comment by Leon8200** [comment]
I got this error  

/usr/sbin/dnscrypt-proxy -R dnscrypt.org-fr
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[ERROR] Unable to bind (UDP) [Permission denied]

**Comment by jedisct1** [comment]
Try with `sudo`:

```bash
sudo /usr/sbin/dnscrypt-proxy -R dnscrypt.org-fr
```

**Comment by Leon8200** [comment]
now I get this error

sudo /usr/sbin/dnscrypt-proxy -R dnscrypt.org-fr
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[ERROR] Unable to bind (UDP) [Address already in use]

**Comment by Leon8200** [comment]
thank's for the help Jedisct1 I got it working now
