### ISSUE TITLE
dnscrypt-proxy needs over 5 seconds to start

### ISSUE THREAD

**Issue by morfikov** [jedisct1/dnscrypt-proxy#342]
I don't know why, but dnscrypt-proxy on my debian sid needs over 5 seconds to start in the boot phase. I think it's a way to long so I've tried to debug the issue, but unfortunately I didn't solve it.

First of all, I use a little bit different setup. I have also dnsmasq, which caches the DNS requests and then it sends them to the dnscrypt-proxy. The whole service works just fine:

    # ps aux | grep dns
    _dnscry+   1520  0.0  0.1  28676  3004 ?        S<Ls 18:39   0:00 /usr/sbin/dnscrypt-proxy --local-address=127.0.2.1:5353 --resolver-name=soltysiak
    dnsmasq    1669  0.0  0.1  53688  3228 ?        S    18:39   0:00 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service

Here's the `.service` file:

	# cat /etc/systemd/system/dnscrypt-proxy.service
	[Unit]
	Description=DNSCrypt proxy
	Documentation=man:dnscrypt-proxy(8)
	Requires=dnscrypt-proxy.socket
	After=network-online.target
	Before=nss-lookup.target

	[Service]
	Type=notify
	NonBlocking=true
	User=_dnscrypt-proxy
	ExecStart=/usr/sbin/dnscrypt-proxy \
		--local-address=127.0.2.1:5353 \
		--resolver-name=soltysiak
	Restart=always

	OOMScoreAdjust=-500
	Nice=-10
	IOSchedulingClass=best-effort
	IOSchedulingPriority=0

	[Install]
	WantedBy=multi-user.target
	Also=dnscrypt-proxy.socket

And the `.socket` file:

	# cat /etc/systemd/system/dnscrypt-proxy.socket
	[Unit]
	Description=dnscrypt-proxy listening socket
	Documentation=man:dnscrypt-proxy(8)

	[Socket]
	ListenStream=127.0.2.1:5353
	ListenDatagram=127.0.2.1:5353

	[Install]
	WantedBy=sockets.target

And services:

	# systemctl list-unit-files| grep dns
	dnscrypt-proxy-resolvconf.service          disabled
	dnscrypt-proxy.service                     enabled
	dnsmasq.service                            enabled
	dnscrypt-proxy.socket                      enabled

The `.service` file of dnsmasq is the standard one, but I ordered it after dnscrypt-proxy.

This is the log from the boot phase:

	Dec 31 18:26:00 morfikownia systemd[1]: Starting DNSCrypt proxy...
	Dec 31 18:26:00 morfikownia dnscrypt-proxy[1493]: [INFO] + DNS Security Extensions are supported
	Dec 31 18:26:00 morfikownia dnscrypt-proxy[1493]: [INFO] + Namecoin domains can be resolved
	Dec 31 18:26:00 morfikownia dnscrypt-proxy[1493]: [INFO] + Provider supposedly doesn't keep logs
	Dec 31 18:26:00 morfikownia dnscrypt-proxy[1493]: [NOTICE] Starting dnscrypt-proxy 1.6.0
	Dec 31 18:26:00 morfikownia dnscrypt-proxy[1493]: [INFO] Generating a new session key pair
	Dec 31 18:26:00 morfikownia dnscrypt-proxy[1493]: [INFO] Done
	Dec 31 18:26:05 morfikownia systemd[1]: Started DNSCrypt proxy.
	Dec 31 18:26:05 morfikownia dnscrypt-proxy[1493]: [INFO] Server certificate #808464433 received
	Dec 31 18:26:05 morfikownia dnscrypt-proxy[1493]: [INFO] This certificate looks valid
	Dec 31 18:26:05 morfikownia dnscrypt-proxy[1493]: [INFO] Chosen certificate #808464433 is valid from [2014-10-16] to [2019-10-15]
	Dec 31 18:26:05 morfikownia dnscrypt-proxy[1493]: [INFO] Server key fingerprint is F0AD:8CEB:52C5:8DCD:0244:C28B:550A:BA4F:7BDB:4593:6F19:63DB:72D3:683A:30C0:0612
	Dec 31 18:26:05 morfikownia dnscrypt-proxy[1493]: [NOTICE] Proxying from 127.0.2.1:5353 to 178.216.201.222:2053

As you can see there's 5 secs delay, and I have no idea why. I've tried to change the resolver to other ones, but without any luck. When I restart the service, there's no delay:

	Dec 31 18:26:53 morfikownia systemd[1]: Stopping DNSCrypt proxy...
	Dec 31 18:26:53 morfikownia systemd[1]: Stopped DNSCrypt proxy.
	Dec 31 18:26:53 morfikownia systemd[1]: Starting DNSCrypt proxy...
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] + DNS Security Extensions are supported
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] + Namecoin domains can be resolved
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] + Provider supposedly doesn't keep logs
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [NOTICE] Starting dnscrypt-proxy 1.6.0
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] Generating a new session key pair
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] Done
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] Server certificate #808464433 received
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] This certificate looks valid
	Dec 31 18:26:53 morfikownia dnscrypt-proxy[1721]: [INFO] Chosen certificate #808464433 is valid from [2014-10-16] to [2019-10-15]
	Dec 31 18:26:53 morfikownia systemd[1]: Started DNSCrypt proxy.
	Dec 31 18:26:54 morfikownia dnscrypt-proxy[1721]: [INFO] Server key fingerprint is F0AD:8CEB:52C5:8DCD:0244:C28B:550A:BA4F:7BDB:4593:6F19:63DB:72D3:683A:30C0:0612
	Dec 31 18:26:54 morfikownia dnscrypt-proxy[1721]: [NOTICE] Proxying from 127.0.2.1:5353 to 178.216.201.222:2053

This is the relevant boot sequence:

![plot](https://cloud.githubusercontent.com/assets/3797768/12067401/b1a45e1a-aff9-11e5-830a-5389d9a0e14c.png)

Both of the services (dnsmasq and dnscrypt-proxy) start after `network-online.target` and before `nss-lookup.target`. I think it's the right place for them. The order of the two services is also good.

Do you know why in the boot stage dnscrypt-proxy is so slow?

**Comment by morfikov** [comment]
I didn't have the time lately, but I've managed to fix this issue. I had to change a little bit the systemd service files. In short, I disabled the `.socket` file entirely and changed the `.service` file so now it looks like this:

	[Unit]
	Description=DNSCrypt proxy
	Documentation=man:dnscrypt-proxy(8)
	After=network-online.target
	Before=nss-lookup.target

	[Service]
	Type=forking
	User=_dnscrypt-proxy
	ExecStart=/usr/sbin/dnscrypt-proxy \
		--local-address=127.0.2.1:5353 \
		--resolver-name=cisco \
		--daemonize \
		--loglevel=10
	Restart=always

	OOMScoreAdjust=-500
	Nice=-10
	IOSchedulingClass=best-effort
	IOSchedulingPriority=0

	[Install]
	WantedBy=multi-user.target

The over 5 secs delay disappeared:

![plot](https://cloud.githubusercontent.com/assets/3797768/12127578/54e9e890-b3f8-11e5-91fb-39627a63a89b.png)

**Comment by jedisct1** [comment]
Thanks!

You know systemd way better than I do.

The `After` and `Before` statements have been added to the sample systemd configuration.
