### ISSUE TITLE
Request: bring back cloudns-can

### ISSUE THREAD

**Issue by Aractus** [jedisct1/dnscrypt-proxy#343]
It was removed here:

https://github.com/jedisct1/dnscrypt-proxy/commit/f4d6137352ec0361a627a38be9236340342ce396

According to the website (cloudns.com.au) the Canberra server is the primary server and the Sydney server is the secondary one. Thus it might also be a good idea to change the description to reflect this (i.e. "CloudNS Canberra" ---> "CloudNS primary server (Canberra)" & "CloudNS Sydney" ---> "CloudNS secondary server (Sydney)").

**Comment by jedisct1** [comment]
It's back :)
