### ISSUE TITLE
No resolver named [] found in the on ANdroid

### ISSUE THREAD

**Issue by gerroon** [jedisct1/dnscrypt-proxy#344]
Hi

I am not sure if this an error or not but after changing the provider to dnscrypt.eu-dk I wnated to test the new provider but getting these messages. Am I doing it the wrong way? Am I supposed to restart Android?

Btw /system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv exists and it is filled with providers names.

localhost / # /etc/init.d/99dnscrypt
[ERROR] No resolver named [] found in the
No resolver named [] found in the [/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv] list
[ERROR] Resolver information required.
[ERROR] The easiest way to do so is to provide a resolver name.
[ERROR] Example: dnscrypt-proxy -R mydnsprovider
[ERROR] See the file [/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv] for a list of compatible public resolvers
[ERROR] The name is the first column in this table.
[ERROR] Alternatively, an IP address, a provider name and a provider key can be supplied.
[ERROR] Please consult http://dnscrypt.org and the dnscrypt-proxy(8) man page for details.

**Comment by gerroon** [comment]
I found the issue. THe android app that is recommended (which is Universal init.d) messes with the script if the script is edited within that app. 

It keeps removing the bash variable from the script and I ended up recreating the script in the terminal.

**Comment by jedisct1** [comment]
Do you know a way to fix this?

**Comment by gerroon** [comment]
Hi

The app does not mess with the script as long as you do not press on "edit" button at the top. The second you start editing in it it removes "$RESOLVER_NAME" from the dns script. I tried it multiple times and it did it constantly. No idea about the kind of bug that can do this.

Anyway the users should not edit in it. They should just use it to enable or disable the startup script.
