### ISSUE TITLE
“messy code”  

### ISSUE THREAD

**Issue by minkaka** [jedisct1/dnscrypt-proxy#346]
i follow this tutorial http://ispeakl33t.com/install-dnscrypt-centos/

Centos 5.5  64bit  
/usr/local/sbin/dnscrypt-proxy

![temp](https://cloud.githubusercontent.com/assets/16591394/12168271/0cc38e66-b56c-11e5-96bb-1544590db229.jpg)

 help me！ THX

**Comment by paragonie-scott** [comment]
That's not a code, it's a binary file. (Read: Compiled binary *from* the code.)

**Comment by minkaka** [comment]
Where Will the configuration file？

**Comment by minkaka** [comment]
Where can I find the configuration file？  THX

![temp1](https://cloud.githubusercontent.com/assets/16591394/12169676/3d0b0672-b575-11e5-9020-310b8802691b.jpg)

**Comment by CrisBRM** [comment]
Centos has systemdicks, so use the included .socket and .unit files included with the source. Refer to [this](https://wiki.installgentoo.com/index.php/DNSCrypt) article if you want.

**Comment by minkaka** [comment]
thanks

**Comment by jedisct1** [comment]
Or take a look at [dnscrypt loader](https://github.com/gortcodex/dnscrypt-loader) which configures everything for you.
