### ISSUE TITLE
Android version without needing to flash ?

### ISSUE THREAD

**Issue by gerroon** [jedisct1/dnscrypt-proxy#347]
Hi

Is it possible to have binaries that does not require flashing? The thing is that not everyone has boot managers and some devices are harder to install boot managers (lack of support). So I think that it would be more beneficial if the Android binaries are somewhat usable/installable on the terminal at least, maybe some kind of static binary. There are many terminals that run in user space like Termux. Maybe it can be packaged into their repo. Just thinking out loud here.

thanks

**Comment by jedisct1** [comment]
Hi gerroon,

This is likely to be achievable using the VpnService framework. Unfortunately, I am running out of spare time to work on this, so this is unlikely to happen in a near future without help.
