### ISSUE TITLE
dnscrypt-proxy port change results in no DNS

### ISSUE THREAD

**Issue by eelstrebor** [jedisct1/dnscrypt-proxy#352]
The daemon works on port 53 but not any other port. In this case, port 40 was used. 

user@xps15:~$ sudo /usr/sbin/dnscrypt-proxy -a 127.0.2.1:40 -R cisco -d
user@xps15:~$ cat /var/log/syslog | grep dns
Jan 20 20:09:59 xps15 dnscrypt-proxy: - [cisco] does not support DNS Security Extensions
Jan 20 20:09:59 xps15 dnscrypt-proxy: - [cisco] does not support Namecoin domains
Jan 20 20:09:59 xps15 dnscrypt-proxy: - [cisco] logs your activity - a different provider might be better a choice if privacy is a concern
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: Starting dnscrypt-proxy 1.6.0
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: Generating a new session key pair
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: Done
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: Server certificate #1435874751 received
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: This certificate looks valid
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: Chosen certificate #1435874751 is valid from [2015-07-03] to [2016-07-02]
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: Server key fingerprint is ED19:BFBA:FAFC:9257:DFDC:68C7:69BF:AC24:94CD:743F:3C1D:4966:134D:FE2C:4BDC:F315
Jan 20 20:09:59 xps15 dnscrypt-proxy[7438]: Proxying from 127.0.2.1:40 to 208.67.220.220:443
user@xps15:~$ dig google.com

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
user@xps15:~$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.2.1
user@xps15:~$ uname -a
Linux xps15 3.19.0-47-generic #53~14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

zenmap shows udp port 40 open

Ubuntu 14.04, 64 bit

**Comment by CrisBRM** [comment]
Run ```hostip -r 127.0.2.1:40 www.example.com```, and without ```-r ip:port```.
If it works, you need fix your resolv.conf and lock it with ```chattr +i /etc/resolv.conf```

**Comment by eelstrebor** [comment]
Based on what I've read, my /etc/resolv.conf is configured the way it should be. As for /etc/dnsmasq.conf, it was already setup appropriately. But, I'm unable to use any other port address.

user@xps15:~$ cat /etc/resolv.conf
nameserver 127.0.2.1
user@xps15:~$ cat /etc/dnsmasq.conf
no-resolv
server=127.0.2.1#40
listen-address=127.0.2.1

**Comment by CrisBRM** [comment]
Can you run the hostip command? Also ```sudo netstat -anp | grep 127.0.2.1:40```.

**Comment by eelstrebor** [comment]
user@xps15:~$ hostip -r 127.0.2.1:40 google.com
162.250.119.230
162.250.119.219
162.250.119.222
162.250.119.236
162.250.119.241
162.250.119.207
162.250.119.234
162.250.119.226
162.250.119.251
162.250.119.211
162.250.119.237
162.250.119.245
162.250.119.221
162.250.119.215
162.250.119.249
user@xps15:~$ hostip google.com
162.250.119.251
162.250.119.241
162.250.119.236
162.250.119.226
162.250.119.237
162.250.119.215
162.250.119.234
162.250.119.207
162.250.119.249
162.250.119.219
162.250.119.211
162.250.119.221
162.250.119.230
162.250.119.222
162.250.119.245
user@xps15:~$ sudo netstat -anp | grep 127.0.2.1:40
tcp        0      0 127.0.2.1:40            0.0.0.0:*               LISTEN      18900/dnscrypt-prox
udp        0      0 127.0.2.1:40            0.0.0.0:*                           18900/dnscrypt-prox
user@xps15:~$ dig google.com

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
user@xps15:~$ nslookup google.com
;; connection timed out; no servers could be reached

**Comment by CrisBRM** [comment]
hostip returned an IP, that means DNSCrypt is working...

**Comment by eelstrebor** [comment]
Well, no domain names are getting resolved when specifying any other port than 53. No web surfing, no IRC, no Skype, etc unless I use the default port 53. It seems that everything is configured properly so I don't understand why I can't get name resolution with any other port. Googling doesn't provide an answer. And the howto's don't even give a hint as to what the problem could be.

**Comment by rampageX** [comment]
if DNSCrypt ***can*** work on port 53, i think the dnsmasq daemon not start success, because if dnsmasq running, the port 53 will be used, DNSCrypt can not start with port 53.

As i know, if not specifically set `-r` with `hostip`, it is use google's DNS Server 8.8.8.8, so you have try:
`hostip google.com`
and
`hostip -r 127.0.2.1:40 google.com`
All these two command can not prove the system dns server is work. If not specifically, `dig` and `nslookup` always use the system default dns server, in your cast, it is ***127.0.2.1:53***.

So, i suggest you should check why your system dns server not work: 

`sudo netstat -anp | grep 53`

Does any daemon like dnsmasq listening on port 53?

**Comment by eelstrebor** [comment]
dnsmasq wasn't in use until I edited NetworkManager.conf to change dns=none to dns=dnsmasq. After restarting the network dnsmasq was listening but it's using 127.0.1.1:53 instead of using the listen-address=127.0.2.1 that's in /etc/dnsmasq.conf. Anyway, I still can't change the port and still have DNS.

**Comment by Mikaela** [comment]
`dns=dnsmasq` launches dnsmasq-base or something small which you cannot configure and that is why I used to just comment the line.

Currently I use `dns=unbound` and dnssec-trigger as dnscrypt haven't become enough easy to use for me (multiple resolvers in one systemd service and dnssec-capable resolver in Finland or Sweden).

**Comment by CrisBRM** [comment]
If what Mikaela said is true, you should comment that out and make systemd start dnsmasq instead.

**Comment by eelstrebor** [comment]
Do I need to install dnsmasq or is dnsmasq-base adequate? Anyway, dns=unbound failed. Apparently, it's not a recognized plugin for NetworkManager according to the manpages. After a lot of reasearch, I found that NetworkManager hardcodes the dnsmasq cache to 0 (zero) but I found a workaround where you can set a cache value by creating the file /etc/NetworkManager/dnsmasq.d/cachedns and entering cache-size=<whatever>. According to the logs it seems to work. Anyway, I still haven't found a solution to my port issue. To complicate matters, all of the info that I found says to setup NetworkManager to use 127.0.0.2 but /etc/default/dnscrypt-proxy gets installed to use 127.0.2.1. Also, Ubuntu 14.04 changed localhost from 127.0.0.1 to 127.0.1.1. There are several files that interact with each other in getting this stuff to work. I tried manually editing these files but I have not been able to get things to work the way I would like. I'm not sure if I should even worry about using port 53 since it isn't exposed to the public network. This stuff sure takes a lot of work.

**Comment by CrisBRM** [comment]
You need to stop using networkmanager to launch it, from what I gathered, and get systemd to do it.

**Comment by eelstrebor** [comment]
I'm not sure if this is correct but I got something different. According to tcpdump I'm still connecting to the appropriate DNS-crypt server. But specifying 127.0.2.1:40 in /etc/default/dnscrypt-proxy gives no errors but I can't resolve names so I restored it to 127.0.2.1 (thus using default port 53):

user@xps15:~$ sudo netstat -anp | grep dns
tcp        0      0 127.0.1.1:40            0.0.0.0:*               LISTEN      1273/dnsmasq    
tcp        0      0 127.0.2.1:40            0.0.0.0:*               LISTEN      1273/dnsmasq    
tcp        0      0 127.0.2.1:53            0.0.0.0:*               LISTEN      3500/dnscrypt-proxy
udp        0      0 0.0.0.0:40566           0.0.0.0:*                           3500/dnscrypt-proxy
udp        0      0 127.0.1.1:40            0.0.0.0:*                           1273/dnsmasq    
udp        0      0 127.0.2.1:40            0.0.0.0:*                           1273/dnsmasq    
udp        0      0 127.0.2.1:53            0.0.0.0:*                           3500/dnscrypt-proxy
unix  3      [ ]         STREAM     CONNECTED     20175    3500/dnscrypt-proxy 
unix  2      [ ]         DGRAM                    22692    3496/dnscrypt-proxy 
unix  2      [ ]         DGRAM                    15584    1273/dnsmasq        
unix  3      [ ]         STREAM     CONNECTED     20174    3500/dnscrypt-proxy

**Comment by Mikaela** [comment]
> Do I need to install dnsmasq or is dnsmasq-base adequate?

If you want to use dnsmasq, you must install dnsmasq. dnsmasq-base only works for NetworkManager plugin.

>  Anyway, dns=unbound failed. Apparently, it's not a recognized plugin for NetworkManager according to the manpages. 

You are using old NetworkManager.

```
       dns
           Set the DNS (resolv.conf) processing mode.

           default: The default if the key is not specified. NetworkManager
           will update resolv.conf to reflect the nameservers provided by
           currently active connections.

           dnsmasq: NetworkManager will run dnsmasq as a local caching
           nameserver, using a "split DNS" configuration if you are connected
           to a VPN, and then update resolv.conf to point to the local
           nameserver.

           unbound: NetworkManager will talk to unbound and dnssec-triggerd,
           providing a "split DNS" configuration with DNSSEC support. The
           /etc/resolv.conf will be managed by dnssec-trigger daemon.

           none: NetworkManager will not modify resolv.conf.

```

But in case of dnscrypt-proxy, you want to set that line as *none* and restart NetworkManager so it frees UDP port 53 for the actual DNS server you want to use.

**Comment by eelstrebor** [comment]
Looks like I've got the latest stable package of network-manager installed but I do see a version 1.1 at https://download.gnome.org/sources/NetworkManager/.

user@xps15:~$ sudo dpkg -l | grep network-manager
ii  network-manager                                       0.9.8.8-0ubuntu7.2                                       amd64        network management framework (daemon and userspace tools)
ii  network-manager-gnome                                 0.9.8.8-0ubuntu4.4                                       amd64        network management framework (GNOME frontend)
ii  network-manager-openvpn                               0.9.8.2-1ubuntu4                                         amd64        network management framework (OpenVPN plugin core)
ii  network-manager-openvpn-gnome                         0.9.8.2-1ubuntu4                                         amd64        network management framework (OpenVPN plugin GNOME GUI)

[QUOTE]But in case of dnscrypt-proxy, you want to set that line as none and restart NetworkManager so it frees UDP port 53 for the actual DNS server you want to use.[/QUOTE]

I did set it to dns=none and installed and configured dnsmasq. Can I have both dnsmasq and dnscrypt listening on port 40? Or do they have to be listening on separate ports?

**Comment by Mikaela** [comment]
> Can I have both dnsmasq and dnscrypt listening on port 40? Or do they have to be listening on separate ports?

**Comment by eelstrebor** [comment]
Well, it's working so I'll just leave it as is. dnscrypt tests indicate it's working OK. But, even with dnsmasq the best DNS resolution time is 40 ms.

**Comment by eelstrebor** [comment]
Another question, how does one test dnscrypt if one is not using an opendns server? I see tests for opendns but not for any of the other "certified by opendns" servers.

**Comment by jedisct1** [comment]
Stop `dnscrypt-proxy`. If DNS resolution stops working, it means that you were using it!

There are no dnscrypt tests specific to open dns; don't trust bad advices from unrelated websites.
The method above works no matter what the resolver is.

**Comment by eelstrebor** [comment]
Thanks. It appears that I have dnscrypt working on desktops and laptops running Ubuntu but I really need to get it working on my router since I have some devices (i.e. Roku, smartTV, set-top boxes, etc) that don't have dnscrypt-proxy as an option. There seems to be a lot of bad instructions out there - especially for implementation on routers running dd-wrt. My goal is to have the laptops running dnscrypt-proxy but I want the home-bound stuff to use dnscrypt-proxy that's running on the router. I followed the instructions at https://www.dd-wrt.com/phpBB2/viewtopic.php?t=151293 for the router but it doesn't make dnscrypt-proxy work.

**Comment by jedisct1** [comment]
Install Tomato instead: http://tomato.groov.pl/

It supports dnscrypt and DNSSEC validation by default. All you have to do is check a box in the web interface.

**Comment by eelstrebor** [comment]
I'm considering doing the following wiki but I'm wondering if I should rollback dd-wrt to the version he's talking about.

http://www.linksysinfo.org/index.php?threads/asuswrt-merlin-tomato-shibby-or-toastman-dd-wrt-on-linksys-ea6900.71718/
