### ISSUE TITLE
Integrity check

### ISSUE THREAD

**Issue by morfikov** [jedisct1/dnscrypt-proxy#355]
I just wanted to check the hash, but the `dig`'s answer didn't have it:

This is for the previous version:

	$ dig +dnssec TXT dnscrypt-proxy-1.6.0.tar.gz.download.dnscrypt.org

	; <<>> DiG 9.9.5-12.1-Debian <<>> +dnssec TXT dnscrypt-proxy-1.6.0.tar.gz.download.dnscrypt.org
	;; global options: +cmd
	;; Got answer:
	;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34185
	;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

	;; OPT PSEUDOSECTION:
	; EDNS: version: 0, flags:; udp: 4096
	;; QUESTION SECTION:
	;dnscrypt-proxy-1.6.0.tar.gz.download.dnscrypt.org. IN TXT

	;; ANSWER SECTION:
	dnscrypt-proxy-1.6.0.tar.gz.download.dnscrypt.org. 9667 IN TXT "7703a41a1040fc30b19fdfbbaba36b411e66d998584b0e2fa5088f734f4f86be"

	;; Query time: 19 msec
	;; SERVER: 127.0.0.1#53(127.0.0.1)
	;; WHEN: Wed Feb 03 18:01:20 CET 2016
	;; MSG SIZE  rcvd: 155

And for the new one:

	$ dig +dnssec TXT dnscrypt-proxy-1.6.1.tar.gz.download.dnscrypt.org

	; <<>> DiG 9.9.5-12.1-Debian <<>> +dnssec TXT dnscrypt-proxy-1.6.1.tar.gz.download.dnscrypt.org
	;; global options: +cmd
	;; Got answer:
	;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 55150
	;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

	;; OPT PSEUDOSECTION:
	; EDNS: version: 0, flags:; udp: 4096
	;; QUESTION SECTION:
	;dnscrypt-proxy-1.6.1.tar.gz.download.dnscrypt.org. IN TXT

	;; AUTHORITY SECTION:
	dnscrypt.org.           1993    IN      SOA     free.ns.c9x.org. hostmaster.dnscrypt.org. 1220000307 16384 2048 1048576 2560

	;; Query time: 23 msec
	;; SERVER: 127.0.0.1#53(127.0.0.1)
	;; WHEN: Wed Feb 03 18:03:58 CET 2016
	;; MSG SIZE  rcvd: 152

**Comment by jedisct1** [comment]
The DNS records hadn't been added yet.

Done!

```
$ drill -D dnscrypt-proxy-1.6.1.tar.gz.download.dnscrypt.org
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 42688
;; flags: qr rd ra ad ; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 0
;; QUESTION SECTION:
;; dnscrypt-proxy-1.6.1.tar.gz.download.dnscrypt.org.	IN	A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
dnscrypt.org.	2560	IN	SOA	free.ns.c9x.org. hostmaster.dnscrypt.org. 1220000308 16384 2048 1048576 2560
dnscrypt.org.	2560	IN	RRSIG	SOA 13 2 2560 20160302174707 20160203174707 41278 dnscrypt.org. fv6HICN2gkalVZvofvYXPlsWGHWKD2LfGRUYh/fpXcNKjix+pGv0okaP9IGwbC7o+dTADIFQck6p9I2Y4pH7hA==
elkq47gsubkvi8m18hdjvu5iadiv1tqn.dnscrypt.org.	2560	IN	NSEC3	1 0 1 -  emc9tm77ir06ejg0tt6ah3eb96vt2c2i TXT RRSIG
elkq47gsubkvi8m18hdjvu5iadiv1tqn.dnscrypt.org.	2560	IN	RRSIG	NSEC3 13 3 2560 20160302174715 20160203174715 41278 dnscrypt.org. vZV6OgOjyM7zop/1h8XZaANoJcllV6bgNU1kXztKi0FNmS8qm7zQ5726/A3iNzBuFJ8l1FppA9HWfA3UohpJog==

;; ADDITIONAL SECTION:

;; Query time: 34 msec
;; EDNS: version 0; flags: do ; udp: 4096
;; SERVER: 2a01:e00::2
;; WHEN: Wed Feb  3 18:58:35 2016
;; MSG SIZE  rcvd: 432
```

**Comment by morfikov** [comment]
Ok, now it works. :)
