### ISSUE TITLE
Why does the list of supported DNS servers not include this one from OpenNIC?

### ISSUE THREAD

**Issue by mindstormer12** [jedisct1/dnscrypt-proxy#356]
This [dns server](http://servers.opennicproject.org/edit.php?srv=ns8.ga.us.dns.opennic.glue) shows that it supports DNSCrypt but DNSCrypt's list of supported servers doesn't include this server with the name "2.dnscrypt-cert.gemma.zee.li". Does that mean I can't use this server when I specify the server name?

**Comment by jedisct1** [comment]
This server is not in the list because nobody ever submitted a pull request in order to have it included :)

You can add the entry yourself to the CSV file, or specify all the parameters in the command-line.
