### ISSUE TITLE
config dnscrypt-proxy

### ISSUE THREAD

**Issue by dontspamm** [jedisct1/dnscrypt-proxy#360]
what options from the file are required ?

is a config like this correct  ?

```
config dnscrypt-proxy
        option address '127.0.0.1'
        option port '5353'
#        option resolver 'opendns'
#       option resolvers_list '/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv'
```

**Comment by jedisct1** [comment]
`dnscrypt-proxy` doesn't read any configuration files.

But after a bit of Googling, what you pasted looks like a configuration file introduced by scripts specific to OpenWRT: https://wiki.openwrt.org/inbox/dnscrypt

`port` and `resolver` are probably the only options you need. For the rest, the OpenWRT page looks pretty good.

**Comment by dontspamm** [comment]
so their wiki is bad resolver it is required
