### ISSUE TITLE
binary without source in the tree: dist-build/android-files/META-INF/com/google/android/update-binary

### ISSUE THREAD

**Issue by zedinosaur** [jedisct1/dnscrypt-proxy#362]
There is a binary file in the tree that doesn't have the corresponding source code. It appears to be for the android build. This is a bit problematic for distributions like Debian that don't want to include binaries without corresponding source code. We have ways around that but it would be more convenient if this file could be removed or could have the corresponding source included as well.

**Comment by jedisct1** [comment]
This file is not in the tarball any more, and is downloaded from Github instead.

**Comment by jedisct1** [comment]
Thanks!

**Comment by zedinosaur** [comment]
Awesome, thanks!

**Comment by zedinosaur** [comment]
This doesn't actually appear to be fixed in the 1.7.0 release.
