### ISSUE TITLE
dnscrypt still use udp 443 port retrieve server certificates with (--tcp-only) parameter

### ISSUE THREAD

**Issue by b39181** [jedisct1/dnscrypt-proxy#363]
my company block outgoing udp 443 port
so it will show "unable to retrieve server certificates" message
can retrieve server certificates using tcp 443 port?

**Comment by pysiak** [comment]
dnscrypt-proxy has a parameter to use TCP only:
-T    --tcp-only

Try it out. Hope they don't do intrusive HTTPS inspection.

On Mon, Feb 15, 2016 at 3:04 PM, b39181 <notifications@github.com> wrote:

> my company block outgoing udp 443 port
> so it will show "unable to retrieve server certificates" message
> can retrieve server certificates using tcp 443 port?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jedisct1/dnscrypt-proxy/issues/363>.
>



-- 
Pysiak

**Comment by jedisct1** [comment]
The initial query to retrieve the certificates uses UDP, but it should use the regular DNS port (53) in addition to port 443. If it doesn't, that's a bug :/
