### ISSUE TITLE
list of addresses and ports

### ISSUE THREAD

**Issue by 1-61803** [jedisct1/dnscrypt-proxy#370]
Dnscrypt doesn't seem to work on a host with restricted outbound connections. For example, if apple:80 is blocked it doesn't work at all. I thought allowing dnscrypt on 443 would do, but it doesn't. In fact, besides 80 and 443 other ports need access and whole bunch of other addresses, even for one DNS service, when I'd actually expect 2 IPs per service on 443.

Could you explain this and provide a thorough list?
Can apple:80 be set to something else?

**Comment by jedisct1** [comment]
Hi,

It only requires the port configured for your DNSCrypt server, and optionally, the regular DNS port (53).
But you need the DNSCrypt port to be accessible both using UDP and TCP.

It doesn't require apple.com. That must be a different application.

**Comment by 1-61803** [comment]
I use DNSCrypt 1.0.10 for OS X. That must be it.
I'll head there with this problem. Or start using dnscrypt without GUI.
