### ISSUE TITLE
Android build with JNI interface and static link with libsodium

### ISSUE THREAD

**Issue by SuppSandroB** [jedisct1/dnscrypt-proxy#371]
Trying to use dnscrypt-proxy as android library in process through jni interface. Looking how to link static libsodium instead of shared library libsodium.so. Can you please give some hints, looks to me that was done static linking some time ago.

**Comment by jedisct1** [comment]
You can just remove the `libsodium.so` file. It will pick up the `libsodium.a` static library instead.

**Comment by SuppSandroB** [comment]
Not working. 
Moved libsodium.so to backup.bin 
Make fresh git clone dnscrypt-proxy

libtool: link: arm-linux-androideabi-gcc -std=gnu99 -Os -mthumb -marm -march=armv6 -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector-all -Winit-self -Wwrite-strings -Wdiv-by-zero -Wall -fno-strict-aliasing -pie -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,noexecstack -o time-test time-test.o  -L/media/verbatim/work/libsodium-1.0.8/libsodium-android-armv6//lib -L/usr/local/lib ../.libs/libevent.a /media/verbatim/git/dnscrypt-proxy/android-toolchain-armv6/sysroot/media/verbatim/work/libsodium-1.0.8/libsodium-android-armv6/lib/libsodium.so -lm -Wl,-rpath -Wl,/media/verbatim/git/dnscrypt-proxy/android-toolchain-armv6/sysroot/media/verbatim/work/libsodium-1.0.8/libsodium-android-armv6/lib -Wl,-rpath -Wl,/media/verbatim/work/libsodium-1.0.8/libsodium-android-armv6/lib
arm-linux-androideabi-gcc: error: /media/verbatim/git/dnscrypt-proxy/android-toolchain-armv6/sysroot/media/verbatim/work/libsodium-1.0.8/libsodium-android-armv6/lib/libsodium.so: No such file or directory
make[4]: *** [time-test] Error 1
make[4]: *** Waiting for unfinished jobs....

**Comment by jedisct1** [comment]
Remove the `cp "${SODIUM_ANDROID_PREFIX}/lib/libsodium.so" "${PREFIX}/system/lib" && \` line, maybe?

**Comment by SuppSandroB** [comment]
This is after building binary, probably will not help.
It fails building before even trying to copy lib to output folder.

./dist-build/android-build.sh:

bash $MAKE_TOOLCHAIN --platform="${NDK_PLATFORM:-android-16}" \
    --arch="$ARCH" --install-dir="$TOOLCHAIN_DIR" && \
./configure \
    --bindir="${PREFIX}/system/xbin" \
    --datadir="${PREFIX}/system/etc" \
    --disable-soname-versions \
    --disable-plugins \
    --enable-relaxed-plugins-permissions \
    --host="${HOST_COMPILER}" \
    --prefix="${PREFIX}/system" \
    --sbindir="${PREFIX}/system/xbin" \
    --sysconfdir="${PREFIX}/system/etc" \
    --with-sysroot="${TOOLCHAIN_DIR}/sysroot" && \
make clean && \
make -j3 install && \
rm -fr "${PREFIX}/system/include" "${PREFIX}/system/share" "${PREFIX}/system/man" && \
mkdir -p "${PREFIX}/system/lib" && \
cp "${SODIUM_ANDROID_PREFIX}/lib/libsodium.so" "${PREFIX}/system/lib" && \

**Comment by jedisct1** [comment]
Try removing `libsodium.la` as well.

**Comment by jedisct1** [comment]
Worked for me after removing `libsodium.so` and `libsodium.la` :)

**Comment by SuppSandroB** [comment]
That worked! Thank's a lot. You saved me a lot of time.
Is there anyone already done something about android JNI interface?
Will try first just with starting new process with binary but would be nice to have jni.
Also another question about tcp mode. Connection must be always closed? Some security reason?

**Comment by jedisct1** [comment]
Sweet!

Unfortunately, I'm not familiar enough with Android to help with a JNI interface. What are the requirements to turn an application into a JNI interface?

The TCP connection has to be closed after every query. The intent was to keep the number of open TCP connections down to a minimum on the server-side, but this might be revisited in the third revision of the protocol.

**Comment by SuppSandroB** [comment]
Will try to do jni and let you know. Thanks again.

**Comment by jedisct1** [comment]
Anytime.
