### ISSUE TITLE
Android init script test issue

### ISSUE THREAD

**Issue by licaon-kter** [jedisct1/dnscrypt-proxy#372]
What's the point of the first test? Or better yet, why does it always fail although the device works ok?

```
dnscrypt-proxy \
  --resolver-name="$RESOLVER_NAME" \
  --resolvers-list=/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv \
  --test=3600 && \
dnscrypt-proxy \
  --daemonize \
...
```

`[ERROR] Unable to retrieve server certificates` (no matter what server I choose) hence `dnscrypt-proxy` will never start.
Commenting that first command let's it start ok though.

**Comment by jedisct1** [comment]
The purpose of the first test is to ensure that the certificates can be retrieved, and that at least one of them will remain valid for the next hour.

Check that you can access port 443 of the chosen resolver, over UDP, and that your device's clock is properly set.

**Comment by licaon-kter** [comment]
The init script (in its current form) is run just at the start, so if the network is not available (reboot with data/Wi-Fi off; AFWall start leak plugged; etc) it will fail and it will just stop right there.

Some retries are needed, my current idea (with a backup server):
```
#!/system/bin/sh

while true
do
#check first server
        RESOLVER_NAME=first_server
        dnscrypt-proxy \
        --resolver-name="$RESOLVER_NAME" \
        --resolvers-list=/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv \
        --test=3600
        case "$?" in
                0 ) break;;
        esac
        sleep 1

# check second server 
        RESOLVER_NAME=second_server
        dnscrypt-proxy \
        --resolver-name="$RESOLVER_NAME" \
        --resolvers-list=/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv \
        --test=3600
        case "$?" in
                0 ) break;;
        esac
        sleep 1
done

dnscrypt-proxy \
--daemonize \
--loglevel=3 \
--resolver-name="$RESOLVER_NAME" \
--resolvers-list=/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv
```

If this looks reasonable I'll make a PR too.

**Comment by jedisct1** [comment]
Sounds like a good idea!
