### ISSUE TITLE
Still being poisoned by ISP ads even using DNScrypt, how to fix it?

### ISSUE THREAD

**Issue by xros** [jedisct1/dnscrypt-proxy#373]
On local PC, it runs dnscrypt-proxy which connects to the dnscrypt-server, a VPS.
Ubuntu 14.04 AMD64, ISP China, Using Dnscrypt servers from OpenDNS.
It shows it uses the encrypt connection to the VPS.

![snapshot180](https://cloud.githubusercontent.com/assets/2342412/13378742/9fda4094-de4a-11e5-9219-24f98e0a98bd.png)

But there still are some ads from ISP popping out when you open random web pages as followings:
![snapshot179](https://cloud.githubusercontent.com/assets/2342412/13378747/cf93876e-de4a-11e5-9d31-9d38a00cdd02.png)

Does this mean, the ISP in China is listening the DNS traffic even if it is still encrypted?

How to fix it?

**Comment by jedisct1** [comment]
Hi,

It probably means that your ISP is hijacking HTTP traffic, not (just) DNS traffic.

Your only hope in that case is a VPN.
