### ISSUE TITLE
Make it work where is just upper proxy that allows just tcp connections to 443

### ISSUE THREAD

**Issue by SuppSandroB** [jedisct1/dnscrypt-proxy#374]
Found this similar issue.
 #174 
Looking at code and hacked to make it work:
For fetching initial certificate libevent evdns is used that works just with udp.
Hacked with this forgotten pull to make it work with tcp.
https://github.com/libevent/libevent/pull/99
But it doesn't work with all servers? Used _cisco_ resolver that works.
Used tcp mode that udp response is truncated. Then tcp requests are performed.

**Comment by jedisct1** [comment]
Hi Sandro,

[dnscrypt-wrapper](https://github.com/Cofyc/dnscrypt-wrapper) doesn't send certificates over TCP yet, so this is not going to work with most resolvers.

But sending regular DNS queries to port 53 doesn't work for you?

**Comment by SuppSandroB** [comment]
Enviroment with just upper proxy with no other traffic allowed. Will look also at https://github.com/Cofyc/dnscrypt-wrapper

https://github.com/Cofyc/dnscrypt-wrapper/issues/72

**Comment by SuppSandroB** [comment]
https://github.com/Cofyc/dnscrypt-wrapper/pull/73

**Comment by SuppSandroB** [comment]
@Cofyc  @jedisct1 
Protocol used for libevent dns is argument to public functions
https://github.com/SuppSandroB/dnscrypt-proxy/commit/76ede30cfe223e2079f06ce6fcb273bdfdac1001

Still some hardcoded values in src/libevent-modified/evdns.c  :
evdns_getaddrinfo
nameserver_prod_callback

**Comment by KrasnayaPloshchad** [comment]
I think this is useful if some ISPs is making DNS hijacking over UDP connections. See these comments:
https://v2ex.com/t/264619#reply32

Let me translate:
_移动是不是所有 UDP 协议都屏蔽或劫持？_
_Is it (China) Mobile blocking or hijacking the whole UDP protocols?_

_上海移动 2G ， 4G ，想问很久了。
劫持 UDP 是为了劫持 DNS 吧。但是 ss （Android版）的 UDP 转发也无法使用， ikev2, anyconnect 之类如果设置成 UDP 连接的话根本就连不上。电信和联通都是没问题的。
移动这是对 UDP 协议无脑劫持 /屏蔽了吗？_
_Shanghai Mobile 2G, 4G, (I) want ask for a long time.
UDP hijacking may is intend to DNS hijacking. But SS (Shadowsocks) (Android version) also cannot use the UDP forwarding, ikev2, anyconnect cannot connect at all if setting UDP connecting. Both China Telecom and China Unicom have no problem.
Is it (China) Mobile blocking or hijacking the whole UDP protocols?_

**Comment by SuppSandroB** [comment]
@Cofyc @jedisct1
I integrate changed dnscrypt-proxy into new version of Drony (1.3.102) 
so it can be used on non rooted android devices.
https://github.com/SuppSandroB/dnscrypt-proxy/tree/android_jni
It is used as external process, not over jni as intent to do at beginning.
When tcp-only is used, it tries to fetch server certificate first over tcp, if it fails, it tries also over udp.
There is some simple gui to select resolver or create custom one.
Debug messages are shown in device log.

**Comment by Opensourcecommunitydevelopment** [comment]
hi 	SuppSandroB. this is a known issue for years. So there exist the outdated real TCP-ONLY fork called gfw (for china users)

i hope the tcp hack for TCP-ONLY Parameter can be ready to come in next version :)
i see you use it on android, nice. i would love to test that in future. But you may have windows compiled binary too? may i can check the tcp certificate checks :) to speed this issue somewhat up.

**Comment by SuppSandroB** [comment]
Sorry no windows binary was build but you can build it from 
https://github.com/SuppSandroB/dnscrypt-proxy/tree/android_jni
Seems to me that you miss some facts. 
Drony uses binary that uses tcp requests for certificate checks.
https://github.com/SuppSandroB/dnscrypt-proxy/commit/76ede30cfe223e2079f06ce6fcb273bdfdac1001
Problem is that at the time dnscrypt-wrapper also needed some changes to support it. 
I change that but not know if it hits some public release. 
https://github.com/cofyc/dnscrypt-wrapper/pull/73
Find out that cisco servers support this already so first choice in drony is cisco dns server :)

**Comment by SuppSandroB** [comment]
This makes also original to work with getting cert over tcp?
https://github.com/jedisct1/dnscrypt-proxy/commit/678dfb59fb79e773e822885629f864cdb959991d

**Comment by Opensourcecommunitydevelopment** [comment]
@SuppSandroB  yes, the gfw branch is obsolete now
