### ISSUE TITLE
Can't resolve rutracker.org through dnscrypt

### ISSUE THREAD

**Issue by GCRaistlin** [jedisct1/dnscrypt-proxy#380]
nslookup returns "Request timed-out". After switching DNS back to provider's one it can be resolved OK. Tried a few resolvers from the list - no luck.
BTW (as there's no forum where to ask this) - does dnscrypt use dnscrypt-resolvers.csv during its working? Or it is used only during the configuration process? I saw recommendations like "download the fresh version of dnscrypt-resolvers.csv regularly" but I just don't understand what is it for.

**Comment by licaon-kter** [comment]
Take a look: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv
You only specify a name, dnscrypt uses the file to find the rest (adress, IP, sig etc), some servers go down so having an updated list is a must.

BTW, that site resolves fine here.

**Comment by GCRaistlin** [comment]
Thanks, got it.

> that site resolves fine here
What resolver do you use?

Is there a way to make the name resolving faster? DNS cache is being used, already.

**Comment by licaon-kter** [comment]
Try to use UDP instead of TCP maybe: https://github.com/jedisct1/dnscrypt-proxy#queries-using-nonstandard-ports--over-tcp

**Comment by GCRaistlin** [comment]
You may call me dumb but I can't get how to download a new copy of the list. If I choose "Save as" for your link I get a html file, not csv.

**Comment by GCRaistlin** [comment]
Found myself: https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv
(GitHub is really something beyond my understanding. No, really, why so unfriendly?)

**Comment by licaon-kter** [comment]
It is very (developer) friendly, once you learn how to use it, press RAW in the link that I gave you, and then Save from your browser. ;)

Do close this issue.

**Comment by GCRaistlin** [comment]
Still no luck with rutracker.org. Reinstalling the service with --tcp-only switch and updating the resolver list didn't help. Can you please tell me what resolver do you use if you have no trouble with resolving rutracker.org through dnscrypt?

**Comment by jedisct1** [comment]
What DNS resolver are you using?

**Comment by williclarkam** [comment]
I can resolve http://rutracker.org/ with DNSCrypt-Proxy, so I think there has to be something wrong with your configurations!

**Comment by jedisct1** [comment]
@GCRaistlin Since you seem to be using Windows, you can install https://simplednscrypt.org - It will take care of safely updating the CSV file for you.

**Comment by GCRaistlin** [comment]
The cause was the enabled DNS forwarding service in Kerio Control (dnscrypt is installed on the same machine). What I really don't understand is how it worked before - I didn't change KC configuration recently. Maybe it's the matter of which service is started first. Also, dnscrypt worked WITHOUT allowing of UDP outgoing traffic. Yes, it was my fault, I just forgot to allow it, but it worked. Now they fail if I revert KC traffic rules to the previous state.
Anyway, thanks to all of you guys for the help!
