### ISSUE TITLE
not issue, just a Mac (Yosemite) question

### ISSUE THREAD

**Issue by zaphodd** [jedisct1/dnscrypt-proxy#381]
I normally use a local proxy on my machines (Privoxy) which i point my apps to at 127.0.0.1  port 8118.
so now i install Dnscrypt 1.0.11, the Yosemite 10.10.5 (gui) firewall asks for "dnscrypt-proxy" and "hostip" which i allow, and i must untick all proxies in network settings to get any connections outside .. where i had my proxy set up it now looks like there is no proxying set up... is this correct or am i misunderstanding what Yosemite's network GUI is telling me ?
DNScrypt says it is using a couple of it's current resolvers, but the menubar icon is an X

I understand that i probably can't use both Privoxy 127.0.0.1 :81118  *and* DNScrypt's proxying at the same time,but it looks like none are being used at the moment. Can anyone shed a little light please ?

**Comment by zaphodd** [comment]
PS - if you block apple.com in your Mac's HOSTS file, DNScrypt errors, and displays 'X' and keeps trying to respawn. Is dnscrypt pinging Apple.com ?   and why ? i think poss privacy error perhaps ?

**Comment by jedisct1** [comment]
I think you are referring to a different project: https://github.com/alterstep/dnscrypt-osxclient

dnscrypt-proxy doesn't have a GUI and doesn't ping anything.

**Comment by zaphodd** [comment]
My apologies jedisct1 .. i am indeed meaning the GUI, my apologies sir
