### ISSUE TITLE
How to get dnscrypt-proxy to enable EphemeralKeys everytime win7 starts

### ISSUE THREAD

**Issue by BackSpace373** [jedisct1/dnscrypt-proxy#383]
I have sucessfully installed the dnscrypt-proxy service using the command:  dnscrypt-proxy -R ns0.dnscrypt.is --ephemeral-keys --install , but is there any way to check if ephemeral-keys is actually running and permanently enabled everytime windows reboots?

**Comment by jedisct1** [comment]
If you installed the service with `--ephemeral-keys`, this will be automatically enabled every time.

You can check this with the `EphemeralKeys` key in the registry.

**Comment by BackSpace373** [comment]
The reason why Im posting here is that ephemeral-keys is not included in the dnscrypt-proxy/parameters after installing the service...

**Comment by jedisct1** [comment]
Hi,

What exactly is `dnscrypt-proxy/parameters`? Are you referring to some documentation?

**Comment by BackSpace373** [comment]
Im referring to the guide and documentation in this link below:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown

The problem is that In RegEdit I cant see ephemeral-keys anywhere in the dnscrypt-proxy/parameter.

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameters

**Comment by jedisct1** [comment]
Sorry, you're absolutely correct; this is not automatically set when you install the service.

I'll try to fix this for the next release. Meanwhile, you have to add the registry key manually.

**Comment by BackSpace373** [comment]
Can you guide me thru it?

**Comment by bitbeans** [comment]
![ek](https://cloud.githubusercontent.com/assets/1482102/13842814/8ef8c1f8-ec30-11e5-8c3d-cb3488cd0b6e.PNG)

**Comment by BackSpace373** [comment]
Thank you very much.
