### ISSUE TITLE
1.6.1 configure: error

### ISSUE THREAD

**Issue by tannx** [jedisct1/dnscrypt-proxy#384]
I had tried to update the dnscrypt-proxy client 1.6.0 to 1.6.1 on debian 8 testing,
I ran the ./configure as root, it shows the error like this:

`configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
configure: error: ./configure failed for src/libevent-modified`

here is  config.log
[config_log.txt](https://github.com/jedisct1/dnscrypt-proxy/files/178355/config_log.txt)

please help me to find out the what happened.

**Comment by licaon-kter** [comment]
You need to be able to compile stuff as a normal user ( http://www.cyberciti.biz/faq/debian-linux-install-gnu-gcc-compiler/ ), libsodium first (only install as root) and then dnscrypt-proxy (same).

**Comment by tannx** [comment]
@licaon-kter 
yes, thank you for your help, just update it from the debian sources.
![screenshot from 2016-03-18 02-45-52](https://cloud.githubusercontent.com/assets/5285684/13857422/d3e2c302-ecb4-11e5-8920-0d2b2d593a96.png)

**Comment by licaon-kter** [comment]
So close this.
