### ISSUE TITLE
Android dnscrypt script minor error

### ISSUE THREAD

**Issue by aschereT** [jedisct1/dnscrypt-proxy#385]
dnscrypt-proxy/dist-build/android-files/system/xbin/dnscrypt

At line 4, 
> "Enbling dnscrypt-proxy..."

should be
> "En**a**bling dnscrypt-proxy..."

Also, iptables never seem to work, maybe try 
`setprop net.dns1 127.0.0.1` ?
.

**Comment by licaon-kter** [comment]
Changing DNS is tricky: https://github.com/ukanth/afwall/wiki/DNS#changing-default-dns

You can just comment those `iptables` lines and use [NetGuard](https://github.com/M66B/NetGuard/) -> enable filter->port forwarding -> 53/127.0.0.1/<dnscrypt-proxy-port>/nobody
