### ISSUE TITLE
[resolvers list] make webpage for resolvers list + add extra info to csv

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [jedisct1/dnscrypt-proxy#386]
**Part 1.**
Currently, it seems that there are only 2 ways to view the entire resolvers list in a browser.  
- [the actual csv file](https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv) - hard to read
- [the github preview](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv) - limited to a little frame which is hard to scroll in both directions

_Proposed solution:_
have a page on [dnscrypt.org](http://dnscrypt.org/) e.g. `/resolvers`, which parses the csv and displays it as nice as possible for users to easily view in browser. i quickly created a [basic php+html+css version over here](https://berr.yt/h/dnscrypt-resolvers/) which is a lot easier to read and navigate than the github preview because it uses the full width and length of the browser window. even then its still annoying because of how wide the list is. i think a perfect version would be one which uses javascript and allows for toggling columns from being shown and allows the list to be sorted by different columns. i will start working on that for myself but im interested to hear if you plan to create a page like this on your own or if you would want to use my finished product if you like it

**Part 2.**
I was researching different types of DNS servers and learnt more about [dnschain (and okTurtles)](https://github.com/okTurtles/dnschain/blob/master/docs/How-do-I-use-it.md#Servers), [Namecoin](https://namecoin.info/), [Emercoin](http://emercoin.com/EMCDNS_and_NVS), [OpenNIC](https://servers.opennicproject.org/). It looks like a bunch of DNSCrypt servers already support more than just Namecoin. `soltysiak` for example supports dnschain, which means it possibly supports `Namecoin` AND `KeyID` and `NXT`. And if you look at that OpenNIC servers list, many of them support DNSCrypt. So basically what I'm trying to say is, right now, resolvers.csv only has a column for `namecoin`, but I think more columns should be added which can hilight other features of the resolvers. Maybe an `opennic` column? OpenNIC DNSCrypt servers would allow users to resolve many more tlds. Maybe replace the `namecoin` column with `dnschain` or `blockchain` and make the value a list of supported blockchain DNS'? e.g. `dnschain` = `namecoin, nxt, emc`. Or maybe keep the `namecoin` column and just add columns for the other known blockchain DNS' which resolvers support? I'll leave that up to you to decide. But it seems DNSCrypt resolvers have many more features now than just Namecoin, and showing that to users in the list would allow them to choose more advanced servers if they so wish. Oh, and also maybe a column for tor/onion support? [CloudNS](https://cloudns.com.au/) for example has onion addresses which users can connect to instead of regular IP addresses.

Would love to hear your thoughts on these issues :)

**Comment by berrythesoftwarecodeprogrammar** [comment]
still ugly but ive added toggling of columns. this is a lot nicer for comparing features:  
![dnscrypt_resolvers_-_2016-03-19_16 45 49](https://cloud.githubusercontent.com/assets/6548571/13896888/5103ad54-edf2-11e5-8a11-e6491fbf6f1d.png)

**Comment by williclarkam** [comment]
wow, pretty nice Sir, keep it up

**Comment by jedisct1** [comment]
This is very nice!

CORS headers can be added so that the CSV file can be retrieved in Javascript, and we can get rid of PHP.

Adding an `opennic` columns is a good idea!

Regarding the `namechain` column: renaming existing columns can break apps. On the other hand, having one column per blockchain-based app can quickly become ugly. Not sure what's the best thing to do is. Maybe check what existing GUIs are doing with that field right now.
Thanks for the suggestion!

**Comment by licaon-kter** [comment]
A per column sorting option (no-log, namecoin, dnsssec, country) would be nice, if possible.

**Comment by berrythesoftwarecodeprogrammar** [comment]
thanks for the replies. i think i will rewrite it in complete javascript then and have the browser download the csv, because that will make it easier to manipulate the list in the browser for sorting etc.

and you're right, we dont need too many more columns because its already so wide. opennic would be nice though. it seems some providers already list their extra features in the `description` column. what about a single column which contains all features in json format or a list? e.g. `{"opennic":1,"namecoin":1,"adblocking":1}` or just `namecoin;opennic;adblocking`. i guess this is hard to figure out. the description columns are fine but the only problem with them is they cant be sorted by feature. maybe turning the entire file into another format like json? but that would require a lot of changes. maybe someone else will think of a good idea eventually

ill get working on the resolvers webpage

**Comment by berrythesoftwarecodeprogrammar** [comment]
new version is up [https://berr.yt/h/dnscrypt-resolvers/](https://berr.yt/h/dnscrypt-resolvers/)
it now downloads the .csv to the browser and then creates the table out of that. toggling columns is also a lot neater now.

i used a condensed font and made things as small as possible. comments on the size of things, colors, etc. are welcome. next up is sorting

**Comment by Opensourcecommunitydevelopment** [comment]
hello, i suggest 

two new collums! UDP and TCP. Because some server are reachable over udp but not with tcp. if you use the TCP-ONLY switch. dnscrypt times out... it should know if a server supports TCP on dns Port in resolver list. if not report it if user trys this combination. as it does when trying use unknown resolvername!

and a script, to check the online status if resolvers or maybe uptime too. to only include stable and running dnsservers into resolvers list.

**Comment by jedisct1** [comment]
The webpage is now available [here](https://dnscrypt.org/dnscrypt-resolvers.html) and is reference in the documentation.

This is really useful!

Thanks!

**Comment by licaon-kter** [comment]
That's nice, too bad Firefox won't load the page when hosted on **dnscrypt.org** while it will load it just fine from **berr.yt**.

Vivaldi browser load it otherwise.

**Comment by jedisct1** [comment]
Weird, I had the opposite experience due to an expired certificate on berry.yt.

What errors are you seeing with Firefox?

**Comment by licaon-kter** [comment]
I'm not seeing anything, because **no page on dnscrypt.org actually loads** in a clean Firefox profile.
The "inspector" does not show anything either.

**Comment by jedisct1** [comment]
Weird. On what operating system is that? A vanilla Firefox install seems to work fine on MacOS.

**Comment by licaon-kter** [comment]
45.6 on Linux

**Comment by jedisct1** [comment]
That's very old! Does it still happen with a current version?

**Comment by licaon-kter** [comment]
Ummm, ok, that's ESR on Debian Sid, so I'll see how a newer version works, although consider that the site worked in the past, say 6 months ago.

**Comment by licaon-kter** [comment]
Ok, so Firefox 50 can open the pages, I can't use it (graphics corruption all over), but I think your site should be usable with any recent browser, version 45 is only 9 months old.

**Comment by berrythesoftwarecodeprogrammar** [comment]
Oh geez I didn't think it was that good. Glad people find it useful. I haven't had any time at all to finish it or improve it and was hoping somebody else would take it up or start something similar. And yeah oops I let all of my SSL certs expire for a while because I was really busy offline.

I do plan to eventually do more with it but anyone is free to work on it. You can just save the webpage like @jedisct1 has done. The only other files are the font I used and the papaparse script. You can download all files here: [https://berr.yt/h/dnscrypt-resolvers/dnscrypt-resolvers.tgz](https://berr.yt/h/dnscrypt-resolvers/dnscrypt-resolvers.tgz)
