### ISSUE TITLE
[issue/reqest] Is possible to block dns in DNSCrypt?

### ISSUE THREAD

**Issue by Galnospoke** [jedisct1/dnscrypt-proxy#388]
Hi

Is it possible to block certain adresses like in Windows 'host' file, but wth with asterix?

Like *.1e100.net to block all NSA/Google/MS/Apple servers?

Greeteings,
Gal

**Comment by jedisct1** [comment]
Of course, this is what the `ldns-blocking` module does.

You can use it to block IP addresses, and names. Full names, suffixes (`*.1e100.net`) or even just substrings that can appear anywhere in the name (`*sex*`).

**Comment by Galnospoke** [comment]
Thx, but it is possible to use under Windows?

**Comment by jedisct1** [comment]
Sure! And if you are using Windows, the easiest way is to use [Simple DNSCrypt](https://simplednscrypt.org), that enables this module and lets you add the path to a file with IPs and names to block.

**Comment by Galnospoke** [comment]
I cannot use Simple DNSCrypt: Vista x86... 

I try it manually, but 
`c:\Program Files\DNSCrypt>dnscrypt-proxy -R cisco opendns --install --plugin=libdcplugin_example_ldns_blocking.dll,--domains=C:\block.txt `
do not install plugin. It install service, but not plugin.

**Comment by jedisct1** [comment]
That should work.
Is the `block.txt` file actually at the root of your partition?

Also, remove `opendns`, it's just `cisco`.

**Comment by Galnospoke** [comment]
No, no change.

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy]
"Type"=dword:00000010
"Start"=dword:00000002
"ErrorControl"=dword:00000001
"ImagePath"=hex(2):63,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,\
  20,00,46,00,69,00,6c,00,65,00,73,00,5c,00,44,00,4e,00,53,00,43,00,72,00,79,\
  00,70,00,74,00,5c,00,64,00,6e,00,73,00,63,00,72,00,79,00,70,00,74,00,2d,00,\
  70,00,72,00,6f,00,78,00,79,00,2e,00,65,00,78,00,65,00,00,00
"DisplayName"="dnscrypt-proxy"
"ObjectName"="LocalSystem"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameters]
"ResolversList"="dnscrypt-resolvers.csv"
"ResolverName"="cisco"
"LocalAddress"="127.0.0.1:53"
`

Its registry path.

**Comment by Galnospoke** [comment]
I do it manually:

`Plugins (REG_MULTI_SZ) libdcplugin_ldns_blocking.dll,--domains=c:\Program Files\DNSCrypt\libdcplugin_ldns_blocking.txt`

As regedit export:
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameters]
"Plugins"=hex(7):6c,00,69,00,62,00,64,00,63,00,70,00,6c,00,75,00,67,00,69,00,\
  6e,00,5f,00,6c,00,64,00,6e,00,73,00,5f,00,62,00,6c,00,6f,00,63,00,6b,00,69,\
  00,6e,00,67,00,2e,00,64,00,6c,00,6c,00,2c,00,2d,00,2d,00,64,00,6f,00,6d,00,\
  61,00,69,00,6e,00,73,00,3d,00,63,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,\
  00,61,00,6d,00,20,00,46,00,69,00,6c,00,65,00,73,00,5c,00,44,00,4e,00,53,00,\
  43,00,72,00,79,00,70,00,74,00,5c,00,6c,00,69,00,62,00,64,00,63,00,70,00,6c,\
  00,75,00,67,00,69,00,6e,00,5f,00,6c,00,64,00,6e,00,73,00,5f,00,62,00,6c,00,\
  6f,00,63,00,6b,00,69,00,6e,00,67,00,2e,00,74,00,78,00,74,00,00,00,00,00
`

But it was tricki.
