### ISSUE TITLE
DNSCrypt-Proxy w/ OpenVPN

### ISSUE THREAD

**Issue by williclarkam** [jedisct1/dnscrypt-proxy#389]
Hello,

So I was wondering, if it's possible to use DNSCrypt-Proxy with OpenVPN. Let me explain:
I have VPS that openvpn runs on it, take for example, server IP is: 10.10.10.10 and OpenVPN runs on port 1194.  Now I install dnscrypt-proxy (with servers from dnscrypt.eu) and resolv.conf changes to 
```
127.0.0.1
127.0.0.2
```
now my VPS uses these IP addresses to solve any website, BUT OpenVPN still uses 8.8.8.8 and 8.8.4.4
Now I delete these two line in openvpn server config
```
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.8.8"
```
and replace it with:

```
push "dhcp-option DNS 127.0.0.1"
push "dhcp-option DNS 127.0.0.2"

```

now after I start OpenVPN client, it connects successfully but NO domain name will be resolved however pinging 8.8.8.8 does work but pinging google.com doesn't! 
So I wanted to know, if there is anyway to force OpenVPN to send all queries to DNSCrypt-Proxy.
Best Regards, 

---------------------------------

I have overcame this issue using Unbound DNS Server, and forward my queries to 127.0.0.1 to port 40
but it isn't fast, sometimes it doesn't response, older releases are in Ubuntu Repository, and the setup is somehow time consuming.

**Comment by jedisct1** [comment]
Hi,

I've never used OpenVPN, but [this](http://serverfault.com/questions/656694/allow-openvpn-client-to-push-its-own-dns-servers-regardless-of-openvpn-server) looks close to what you are trying to achieve.

I would highly recommend against using dnscrypt if you are using a VPN. Run Unbound on your VPN server instead and let the client use it.

**Comment by williclarkam** [comment]
Thanks Sir for your reply.
Could you please tell me why you would recommend me not using DNSCrypt-proxy when using VPN?

**Comment by jedisct1** [comment]
Your VPN is already authenticating everything, including DNS queries, so DNSCrypt is redundant.

Using DNSCrypt in addition to the VPN means also ruins performance, because CDNs will send route your queries to a location that might be far away from the VPN server.
It also means that a copy of your traffic is sent to two locations instead of one, which is not great for privacy.
