### ISSUE TITLE
Add Yandex server

### ISSUE THREAD

**Issue by dartraiden** [jedisct1/dnscrypt-proxy#391]
Yandex [announce](https://habrahabr.ru/company/yandex/blog/280380/) DNSCrypt support in their browser. They also state that dnscrypt-proxy clients can connect to their server:

resolver-address=77.88.8.78:15353 provider-name=2.dnscrypt-cert.browser.yandex.net provider-key=D384:C071:C9F7:4662:AF2A:CCD5:7B5D:CC97:14D4:07B6:AD36:01E1:AEDC:06D5:6D49:6327

**Comment by jedisct1** [comment]
This is really cool!

Thanks for the heads up.

**Comment by jedisct1** [comment]
Added. Thanks!
