### ISSUE TITLE
How can I confirm it correctly runs on Android?

### ISSUE THREAD

**Issue by rugk** [jedisct1/dnscrypt-proxy#393]
How can I confirm that it runs on Android?
Currently I don't even know whether the process itself keeps running. I tried to have a look with `ps` in the shell, but there was no process called dnscrypt or similar...

So how can I check this?

**Comment by licaon-kter** [comment]
What setup do you run? Port 53 and iptables?

So sites to test:
* https://ipleak.net
* https://dnsleaktest.com
* https://grc.com/dns/dns.htm (scroll all the way down; it's a long test wait)
* https://www.dns-oarc.net/oarc/services/dnsentropy
* dnssec.vs.uni-due.de

**Comment by rugk** [comment]
> What setup do you run? Port 53 and iptables?

Port 53, but I try to use AFWall+ instead of IPTables as this does not seem to work...

But good to know that two dnscrypt-proxy processes should be running. When executing ps from the command line I cannot see any instance. But when I execute `/etc/init.d/99dnscrypt` from the command line it does not show any error, but even afterwards I cannot see any dnscrypt-proxy process.

**Comment by licaon-kter** [comment]
> Port 53, but I try to use AFWall+ instead of IPTables as this does not seem to work

AFWall+ uses iptables, not sure what you mean.

> two dnscrypt-proxy processes should be running

With the current start script, yes two. 
You run the script that is in `/system/etc/init.d/` right?

**Comment by rugk** [comment]
> You run the script that is in /system/etc/init.d/ right?

Yes.

> AFWall+ uses iptables, not sure what you mean.

Well.. I do not use the default iptables rules in `/system/etc/init.d/99dnscrypt`, but created a rule in AfWall+.

**Comment by licaon-kter** [comment]
So, what do those sites have to say?

**Comment by rugk** [comment]
The tests fail...
I think I at first need to get the processes running. I should be able to see them with `$ ps`, shouldn't I?

**Comment by licaon-kter** [comment]
Yes.

Are you sure you have init.d support?

Run, from a terminal, as normal user on a port like 5301. Confirm that you can see the process with `ps`.
Then set up `iptables` or NetGuard, see above.

**Comment by rugk** [comment]
Without root privileges it can't create a socket (even if such a port is used):
![dnscryprissue](https://cloud.githubusercontent.com/assets/11966684/14464001/61cf143c-00cd-11e6-8960-2a755e7c64f7.png)

**Comment by licaon-kter** [comment]
Device?  Android version?

**Comment by rugk** [comment]
Device: Galaxy S4 (GT-I9505)
OS: CM-13.0-20160325-NIGHTLY-jfltexx (Android 6.0.1)

**Comment by licaon-kter** [comment]
Works here on 5.1.1 (installed via recovery so it's in */system/xbin/* but run through [Termux](https://github.com/termux/termux-app) as plain user ), so it might be something else at fault, mostly pointing to a ROM issue, either CM or maybe stuff changed in Android 6.0.x.

I'll see if I get a CM13 device setup to test though.

**Comment by itsKV** [comment]
Would you please give me .apk file link of this precompiled app? Or, where can I get it?
Thanks in advance.

**Comment by licaon-kter** [comment]
do read this: https://github.com/smarek/android-unbound-dns/issues/18
