### ISSUE TITLE
Questions about updating DNSCrypt for OpenDNS

### ISSUE THREAD

**Issue by Hip-Pop** [jedisct1/dnscrypt-proxy#395]
Thank you for DNSCrypt.

I have been using DNSCrypt 1.3.3 for the last few years, first on Windows XP and now on a Windows 7 (64-bit) desktop PC, with my external router's DNS addresses set to those of the closest OpenDNS resolvers, and this combination appears to be working correctly (no plain-text appears in the payloads of transmitted and received DNS packets, and, as far as I can tell, no errors have occurred). I have been unable to locate information on how to upgrade DNSCrypt to the latest version (1.6.1) for my situation. I've downloaded the 1.6.1 ZIP package. It's very different from the one for 1.3.3, as are the instructions for installing it. I have not been able to find any information on how to install it for my router's configuration.

I installed 1.3.3 by running "dnscrypt-proxy.exe --install" and nothing more (no "-R" on the command line, no Parameters key in the registry, or anything else). The dnscrypt-proxy service is running. My Windows DNS server is at 127.0.0.1, and is using HTTPS over UDP on port 443 (these must have been 1.3.3's or Windows's default values). I don't use any plug-ins. I don't want to block any domains or IP addresses.

My questions are:

1. Should I update from 1.3.3 to 1.6.1?

2. If so, why? (E.g., should the DoS vulnerability fixed in 1.4.0 be of concern to me?)

3. It appears that the installation of 1.6.1 requires a resolver to be chosen from those listed in dnscrypt-resolvers.csv. Can I install 1.6.1 the same way I installed 1.3.3 (with only the "--install" argument on the command line)? (Of course I'll first uninstall 1.3.3.)

Thank you very much for your help.

**Comment by licaon-kter** [comment]
On Windows do take a look at https://github.com/bitbeans/SimpleDnsCrypt too.

**Comment by Hip-Pop** [comment]
Thank you licaon-kter for your fast response.

I'm sorry, but I don't see answers to my questions on the SimpleDNSCrypt page. SimpleDNSCrypt appears to be a Windows GUI for dnscrypt-proxy and requires installation via an MSI and installation of .NET 4.5 and a Visual C++ run-time library, all just to avoid using dnscrypt-proxy's CLI.

Please tell me where my questions are answered.

Thanks!

**Comment by jedisct1** [comment]
Simple DNSCrypt is great.

But if you want to stick to the CLI and use Cisco: all you need is to add `-R cisco` to the command line, when you reinstall the service.

If you are a customer, use the `example-ldns-opendns-deviceid` plugin to attach your password to outgoing queries. Just add `--plugin example-ldns-opendns-deviceid,your_password` to the command line when installing the service.

1.3.3 is pretty old, and I'd recommend staying up to date. Until version 1.6.0, there was a vulnerability that allows a malicious resolver to potentially run arbitrary code on your system.
The protocol is also going to change slightly, to use more standard crypto algorithms (ChaCha20-Poly1305). So if you are running an old version of the client, it will completely stop working.

**Comment by Hip-Pop** [comment]
Thank you Jedisct1.

So, after uninstalling 1.3.3, are you saying I should extract 1.6.1's files from its ZIP archive and run "dnscrypt-proxy.exe --install -R cisco" and this will leave Windows's DNS resolver address at 127.0.0.1 and using HTTPS over UDP on port 443?

What version will start using the better crypto algorithms?

Many thanks.

**Comment by Hip-Pop** [comment]
What's the best way for me to get answers to the two questions I asked in my April 9 message (immediately above)?

Thank you.
