### ISSUE TITLE
Not able to change the Local Address

### ISSUE THREAD

**Issue by suknight** [jedisct1/dnscrypt-proxy#396]
dnscrypt-proxy works only with the default local address setting(default value 127.0.0.1:53) i.e when the "DNSCRYPT_LOCAL_ADDRESS=" is left blank in the file /etc/sysconfig/dnscrypt. If i try to assign a value like 127.0.0.1:40 or 127.0.0.2:40 dnscrypt-proxy fails to work/resolve.
Distro: openSUSE Leap 42.1
PS: I think "dnscrypt-proxy.socket" is missing, but dnscrypt-proxy.service is available.

**Comment by licaon-kter** [comment]
Use `--local-address=...` instead?

I can find `dnscrypt-proxy.socket` just fine:
```
[Unit]
Description=dnscrypt-proxy listening socket

[Socket]
ListenStream=127.0.0.1:40
ListenDatagram=127.0.0.1:40

[Install]
WantedBy=sockets.target
```

**Comment by suknight** [comment]
@licaon-kter   /etc/sysconfig/dnscrypt is the only file i know where i make change in configs like choosing different resolvers from csv file and start the dnscrypt-proxy.service.

Can you please explain where to use `--local-address=...` ?
And also about
 ```
[Unit]
Description=dnscrypt-proxy listening socket

[Socket]
ListenStream=127.0.0.1:40
ListenDatagram=127.0.0.1:40

[Install]
WantedBy=sockets.target
 ```
And what to do with the above lines ?

**Comment by licaon-kter** [comment]
Sorry to raise a RTFM but these are covered on the first page: https://github.com/jedisct1/dnscrypt-proxy use text ( F3 / CTRL-F ? ) search on that page.

**Comment by suknight** [comment]
Yes i did read it before but i am confused because it says "The easiest way to start the daemon is:" (where --local-address= is covered) but i run mine as service.
And for the second part about socket it says
 "The source distribution includes the `dnscrypt-proxy.socket` and `dnscrypt-proxy.service` files that can be used as a starting point. "
As i said in the beginning i don't have `dnscrypt-proxy.socket` .

**Comment by licaon-kter** [comment]
Where did you get the package from? Better ask there I guess, maybe they missed that file, since you can see it being available in the repo.

Saying that, why don't you put that missing file in the proper place yourself?

**Comment by suknight** [comment]
Got it from OBS opensuse repo, ok now that i know i will ask there too. Thanks
@licaon-kter  can you tell me the proper place to put that file ? 
i see two places with `dnscrypt-proxy.service'
/etc/systemd/system/multi-user.target.wants/dnscrypt-proxy.service
/usr/lib/systemd/system/dnscrypt-proxy.service

**Comment by licaon-kter** [comment]
IIRC, in systemd you have in */etc/...* links to files in */usr/...*, you can check this for the .service file, just make/put the .socket in the similar position.

**Comment by suknight** [comment]
ok i will try that.

**Comment by jedisct1** [comment]
Can you clarify what you mean with "work/resolve"?
Does the process start when you change the port? If it does, how are you testing that the proxy forwards (or not) the queries?

**Comment by suknight** [comment]
@jedisct1 by "work/resolve" i meant that after i change the ports/local address and save and restart the web browsers fail to resolve the web addresses which worked before the change of ports/local address. I didn't check if the process starts or not after the change of port. If the websites have loaded in the website i would have checked it by going to dnsleaktest.com

**Comment by jedisct1** [comment]
How did you tell the system to use this non-standard port? Or are you using a local DNS cache? Which one?

**Comment by suknight** [comment]
@jedisct1 by also changing it in the /etc/resolv.conf if thats what you mean ?

**Comment by licaon-kter** [comment]
_/etc/resolv.conf_ does not have a port option, you'll need someone listening on port 53 in the end (a caching application like Unbound) or ***iptables*** redirecting port 53 to some other port.

**Comment by suknight** [comment]
I copied the `dnscrypt-proxy.socket` file to both these locations  /etc/systemd/system/multi-user.target.wants/ and /usr/lib/systemd/system/ but it keeps failing to start/load when i try.  I installed `unbound` and tried but it is also not starting ( i guess because of the local address and port already being used by dnscrypt-proxy).

**Comment by licaon-kter** [comment]
What does `systemctl status...` say?
`journald` ?

**Comment by suknight** [comment]
systemctl status dnscrypt-proxy.socket 
dnscrypt-proxy.socket - dnscrypt-proxy listening socket 
  Loaded: loaded (/usr/lib/systemd/system/dnscrypt-proxy.socket; disabled) 
  Active: inactive (dead) 
  Listen: 127.0.0.1:53 (Stream) 
          127.0.0.1:53 (Datagram)

**Comment by suknight** [comment]
@jedisct1 yes it seems like distro specific issue and i have reported it. But still there seems to be some confusion for the packager. 
Any advice for this - https://bugzilla.suse.com/show_bug.cgi?id=977946
