### ISSUE TITLE
question

### ISSUE THREAD

**Issue by HDCrXrmgKWUqupB** [jedisct1/dnscrypt-proxy#397]

**Comment by jedisct1** [comment]
I'm not sure that such as setup provides anything over simply running BIND on Server B and using TSIG.

This is okay from a security standpoint, but every single query will requires a round-trip between Server B and Server A. Even invalid queries and queries for others zones will be forwarded.
Whereas running BIND on Server B will only transfer between A and B after a change was made.

**Comment by HDCrXrmgKWUqupB** [comment]
Well I thought about this solution because I don't want server B to modify anything on server A, is just a gateway. So if server B gets compromised it wouldn't do much damage besides some offline time. And since I can't setup Bind to be just a forwarder without allowing recursion I think this is the only way. This wouldn't be possible without your tool so I really appreciate your work on DNSCrypt-Proxy. Thanks.

**Comment by jedisct1** [comment]
If you declare the zones you want to serve as slaves, BIND will serve them without modifying anything on server A, and without requiring recursion.
