### ISSUE TITLE
My dnscrypt can't resolve bit domains 

### ISSUE THREAD

**Issue by merlinnusr** [jedisct1/dnscrypt-proxy#398]
I use the dns of cryptostorm and bit domains doesn't wok after that i use cloudns-ca and this don't work 
I use windowws 8 I have this problem with ubuntu and linux mint .
I don't know what happen

**Comment by jedisct1** [comment]
Can you provide an example of a `.bit` domain that you tried to resolve?
Can you try to resolve it using the `hostip` command, not a web browser?
When one of these resolvers is being used, can you try to resolve `resolver.dnscrypt.org` and post the output as well?

Thanks.

**Comment by merlinnusr** [comment]
http://meowbit.com/list-of-working-dot-bit-websites/ 
I tried alll this site .
I don't know how to use hostip if you can help me in this .
And i follow this tutorial  https://dominustemporis.com/2014/05/dnscrypt-on-windows-update/

**Comment by jedisct1** [comment]
Most of the `.bit` domains get quickly abandoned, and the list on that web page looks really old.

Once again, what is the output of `hostip resolver.dnscrypt.org`?

**Comment by merlinnusr** [comment]
Several .bit domains are up in the list 

Hos tip 74.125.45.132

**Comment by jedisct1** [comment]
`74.125.45.132` is not the IP address of a known DNSCrypt resolver. This is a Google IP address.
So, it looks like you are not using DNSCrypt at all at the moment.

Maybe uninstall everything and use https://simplednscrypt.org/ instead?

**Comment by merlinnusr** [comment]
I use simpledns*  before and this still happens  . I installed un linux and is the same thing

**Comment by merlinnusr** [comment]
I do the "hostip" again and this is the output it's diferent 173.194.99.165

**Comment by jedisct1** [comment]
Ok, good.

Can you now try `hostip -r 127.0.0.1 resolver.dnscrypt.org` ?

**Comment by merlinnusr** [comment]
185.60.147.77

**Comment by jedisct1** [comment]
Good, your queries are going to a Cryptostorm server in Switzerland.

Unfortunately, it looks like this server is unable to resolve `.bit` domains.
ClouDNS was one of the first to adopt namecoins, but it looks like they also threw in the towel, as I wasn't able to resolve `.bit` domains through them either.

Try an OpenNIC server. For example `OpenNIC Resolver Switzerland` (`d0wn-ch-ns1`). That one seems to still resolve `.bit` domains. I just tried `dotbitkittypix.bit` and successfully saw the most interesting site of the `.bit` planet.

**Comment by jedisct1** [comment]
I went through the whole list to check which ones were still supporting namecoin domains. Quite a lot don't any more :(

The list has been updated.
