### ISSUE TITLE
dnscrypt-proxy client sends first packet over udp even if --tcp-only is used

### ISSUE THREAD

**Issue by JulianeFischer** [jedisct1/dnscrypt-proxy#399]
Hi,

I am trying to tunnel DNS queries over Tor, which only supports TCP traffic, but dnscrypt fortunately has the --tcp-only option. Since dnscrypt-proxy does not support SOCKS natively, I have to use torsocks. When starting dnscrypt-proxy the first packet is still sent over UDP even if the --tcp-only option is used. This prevents dnscrypt-proxy from being tunnelled over Tor:

# torsocks /usr/sbin/dnscrypt-proxy --resolver-name=dnscrypt.eu-nl --tcp-only --local-address=127.0.2.1:53
[Apr 22 13:12:54] WARNING torsocks[12326]: [syscall] Unsupported syscall number 355. Denying the call (in tsocks_syscall() at syscall.c:465)
[INFO] + DNS Security Extensions are supported
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.1
[INFO] Generating a new session key pair
[Apr 22 13:12:54] WARNING torsocks[12326]: [syscall] Unsupported syscall number 355. Denying the call (in tsocks_syscall() at syscall.c:465)
[INFO] Done
[ERROR] Unable to create a socket (UDP)

As far as I have seen from other issues, dnscrypt-proxy will fallback to TCP if UDP failed. In this case, however, it does not fail gracefully. I guess, the issue can be fixed by sending the first request over TCP when the --tcp-only option is used. 

Issues #379, #374, #174, and #73 might be related.

**Comment by jedisct1** [comment]
There are no plans to support Tor, sorry.

**Comment by JulianeFischer** [comment]
Very unfortunate to hear. 

Is there any chance to make --tcp-only do what indicates to be doing? (currently, it does TCP most of the time). If you could indicate where this needs to be changed, I am happy to patch (and maintain) it myself..

**Comment by jedisct1** [comment]
You can try the `gfw` branch.

But resolvers will not send the certificates over TCP. Support for this was recently added to `dnscrypt-wrapper` but there is no released with this code yet, so nobody is using it.

`--tcp-only` forces DNSCrypt traffic to use TCP. The certificates are not send using DNSCrypt. These are regular DNS queries.

Or if you are running your own resolver, DNS-over-TLS is a better option than DNSCrypt for TCP.

**Comment by JulianeFischer** [comment]
Thanks for your suggestions!

The gfw branch works perfectly and I finally got DNSCrypt running (on Debian Jessie and Debian Wheezy) over Tor. I will add a brief summary to the issue later for the archive.

**Comment by JulianeFischer** [comment]
As written previously, the gfw branch of DNScrypt can be tunneled through Tor. It requires the --tcp-only option, and works only for very few resolvers (I can confirm 'ipredator' is working but many others I tried did not). 

Unfortunately, DNScrypt still binds to some UDP socket. For this reason, using helper tools like torsocks or torify do not work. DNScrypt can still be tunneled through Tor using iptables. First, Tor needs to be configured to listen on some port for "transproxying" (add "TransPort 127.0.0.1:9080" to your torrc). Then, configure iptables to redirect DNScrypt's traffic to Tor:
- iptables -t nat -A OUTPUT -m owner --uid-owner _dnscrypt-proxy -p tcp -j REDIRECT --to-ports 9080
- iptables -A OUTPUT -m owner --uid-owner _dnscrypt-proxy -p udp -j REJECT

Check functionality with tcpdump. (:
