### ISSUE TITLE
Multiple resolver for Dnscrypt

### ISSUE THREAD

**Issue by sam1275** [jedisct1/dnscrypt-proxy#400]
Hello.
I've noticed Dnscrypt client can only choose one resolver(DNS server) to use, why cannot it support multiple servers, at least for fail-over purpose? Will it add this support in the future?
Thanks.

**Comment by jedisct1** [comment]
Hi Sam,

The best way to achieve this is via your local caching resolver: https://www.dnscrypt.org/#dns-cache

Running multiple instances is not supported on Windows yet, but this will soon be the case.

**Comment by licaon-kter** [comment]
Use a cache in front of it, like Unbound, that forwards to multiple dnscrypts-proxy instances running on different ports ( eg. https://github.com/jedisct1/dnscrypt-proxy/issues/393#issuecomment-204802390 )
