### ISSUE TITLE
chroot and /dev/urandom acess

### ISSUE THREAD

**Issue by keystroke24** [jedisct1/dnscrypt-proxy#401]
I can't help but wonder how dnscrypt-proxy is generating random numbers while chrooted (I'm running it with --user=_dnscrypt).
Should I be mounting /dev/urandom into the chrooted directory?
Like such.. "mount --bind -n /dev/urandom /-chroot-dir-/dev/urandom"

Thanks

**Comment by jedisct1** [comment]
On modern Linux kernels, it doesn't use `/dev/urandom` at all, but the `sysrandom` system call.
On other platforms, it opens `/dev/urandom` before the `chroot()` call, so the file descriptor remains available after `chroot()`.
