### ISSUE TITLE
How to completely remove this program from windows 10

### ISSUE THREAD

**Issue by ciao97** [jedisct1/dnscrypt-proxy#402]
this program completely broke everything and i can't connect to anything please help me remove since i su*k at using computer

**Comment by jedisct1** [comment]
How did you install it?

**Comment by ciao97** [comment]
i just opened "dnscrypt-winservicemgr.exe",selected my network device and "opendns" as the provider and then clicked on enable,very often i just get dns problems anc can't connect to anything and disabling just directly kill my connection

**Comment by ciao97** [comment]
ops my bad i was referring to another program sorry you can cancel this tread
