### ISSUE TITLE
/etc/resolver and DNSCrypt bypasses

### ISSUE THREAD

**Issue by daveoran** [jedisct1/dnscrypt-proxy#403]
Every time DNScrypt on OSX changes its config, it scribbles all over /etc/resolver with a bunch of domain-specific resolver config files, most of which are for weird domains. Huh?

Why do I care? Well, it's because this is how DNScrypt configures bypasses, but it seems to be doing it wrong. It inserts the DNS resolver address of my home router into etc/resolver/* files when that's incorrect for the bypasses I need.

Now, if it just left manually-configured bypasses in /etc/resolver alone I'd be fine with that, but it overwrites anything in that directory every time the config changes. So again you ask, why do I care?

Well, my company uses split horizon DNS (don't vomit) so *some* names ending in the company domain are't resolvable unless you're inside the perimeter (directly or via VPN, which of course also tries to screw around with your DNS settings). What I'd like to have is an /etc/resolver/example.com file which forces DNSCrypt to bypass tits normal resover choice in favor of the corporate internal DNS servers.

So, I create this file, but every time DNSCrypt turns on or off or changes its config this file gets blown away.

Therefore:

(a) am i doing something wrong/stupid and there's a better way to accomplish bypass for domains with split-horizon DNS?

(b) if not, can I somehow prevent DNSCrypt from scribbling all over the files I put in /etc/resolver?

(c) if not, can I somehow cajole DNSCrypt to write correct bypass files when I put bypass domains into the config in the DNSCrypt pref pane on OSX.

**Comment by jedisct1** [comment]
Hi Dave,

dnscrypt-proxy doesn't change anything to the `/etc/resolver` directory, which doesn't even exist on most operating systems.

Since you are talking about OSX and a preference pane, it looks like you opened a ticket in the wrong project. The one you are using is probably https://github.com/alterstep/dnscrypt-osxclient

**Comment by daveoran** [comment]
Thanks - sorry for the noise - will post there.
