### ISSUE TITLE
[Android startup script] Wrong iptables command to enable redirection

### ISSUE THREAD

**Issue by Justsoos** [jedisct1/dnscrypt-proxy#404]
>  if [ "x${1}" = "xenable" -o "x${1}" = "xENABLE" ]; then
>         echo "Enbling dnscrypt-proxy..."
> iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1
> iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1

it must be -A by enable, not -D, OK?

**Comment by Justsoos** [comment]
and find another mistake, 

>     ps ax | grep 'dnscrypt-proxy' | while read pid _; do kill "$pid" ; done

why it show all same code both in enable and disable functions?? so copy and paste code making?

**Comment by jedisct1** [comment]
Hi,

Looks like a pasto, indeed. `-D` was changed to `-A` when enabling the proxy.

This whole `ps | grep` thing is quite ugly (no `pkill` command on Android?), and I'd rather save the pid to a file instead. 
But stopping the proxy in both cases makes sense. Even when starting it, you may want to stop a previous instance, possibly using a different configuration.

Thanks!
