### ISSUE TITLE
[ Enhancement ] Remember original list of DNS resolvers

### ISSUE THREAD

**Issue by i90rr** [jedisct1/dnscrypt-proxy#405]
Hi,

It would be nice that the client (Mac here) could remember the original set of DNS resolvers so in case there's a need to temporarily disable DNSCrypt they are restored; right now I'm managing it via the terminal but I think this would be a nice enhancement to the already comfortable enough client.

Thanks.

**Comment by jedisct1** [comment]
dnscrypt-proxy doesn't change the DNS configuration.

Looks like you are referring to a user interface which is a different project.
