### ISSUE TITLE
Windows starts it's own DNSClient automatically again

### ISSUE THREAD

**Issue by CHEF-KOCH** [jedisct1/dnscrypt-proxy#406]
I'm on Windows 10 LTSB N x64 and I see sometimes after couple of reboots that the windows own dnsclient automatically starts again, even after I set this to 'disabled' via services.msc.

How can I prevent this, otherwise DNSCrypt may can by bypassed/ignored. I only want to use this (+ unbound). I not need any MS services for DNS.

Can we may implement some additional checks?

**Comment by licaon-kter** [comment]
What exe-file is that exactly? Or is it under the `svchost` umbrella?
(for someone so privacy conscious you're using W10 of all things? :-o)

**Comment by CHEF-KOCH** [comment]
It's <code>svchost.exe -k NetworkService</code>. If I look under services.msc - dns-client I see depending on dhcp / netio and RPC. RPC must be running and DHCP, I'm unsure but I guess it's easier if it's running to optain the IP.

**Comment by GaneJ** [comment]
> after couple of reboots that the windows own dnsclient automatically starts again

> Its possible because something from W10 task scheduler or W10 service enabling dnsclient again. 
Impossible to make DNSCrypt-Proxy or Unbound interfere with an OS policy.

**Comment by jedisct1** [comment]
There's probably nothing that can be done by the proxy itself. It's just accepting and relaying queries; it doesn't change anything to the system configuration or to other services.
