### ISSUE TITLE
segfaulting: git versions after commit 324a75ff2374a4ce1933fbad4a8b8a90b1bf0e41

### ISSUE THREAD

**Issue by glitsj16** [jedisct1/dnscrypt-proxy#412]
Hi, as a regular user of the latest git code I recently experienced some segfaulting on dnscrypt-proxy. After some tests I believe there's something wrong with the most recent commits. A working binary results only from checking-out git commit 324a75ff2374a4ce1933fbad4a8b8a90b1bf0e41. Anything more recent throws a segfault. Apologies for not being able to track down the exact commit causing this.

Detailed info below, hope this helps. Regards, glitsj16.

$ lsb_release -d
Description:	Arch Linux

= = = SEGFAULTING :: git latest = = =
git checkout 68db395db4d351dba17344d26ece28f1c23b0c8d

$ pacman -Qi dnscrypt-proxy-git
Name            : dnscrypt-proxy-git
Version         : 1.6.1.r117.g68db395-1

$ pacman -Qi glibc
Name            : glibc
Version         : 2.23-4

$ sudo dnscrypt-proxy --resolver-name=dnscrypt.eu-nl --user=nobody --ephemeral-keys -a 127.0.4.0 --plugin=libdcplugin_example_ldns_aaaa_blocking.so
[INFO] + DNS Security Extensions are supported
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.1

Signal [11] received.

======== Stack trace ========
dnscrypt-proxy(+0x80e6) [0x557f9b4900e6]
/usr/lib/libc.so.6(+0x33310) [0x7f063377d310]
dnscrypt-proxy(+0x5fb7) [0x557f9b48dfb7]
dnscrypt-proxy(+0xb165) [0x557f9b493165]
dnscrypt-proxy(+0x411a) [0x557f9b48c11a]
/usr/lib/libc.so.6(__libc_start_main+0xf1) [0x7f063376a741]
dnscrypt-proxy(+0x3ba9) [0x557f9b48bba9]
Segmentation fault

= = = WORKING :: git commit 324a75ff2374a4ce1933fbad4a8b8a90b1bf0e41 = = =
git checkout 324a75ff2374a4ce1933fbad4a8b8a90b1bf0e41

$ pacman -Qi dnscrypt-proxy-git
Name            : dnscrypt-proxy-git
Version         : 1.6.1.r109.g324a75f-1

$ pacman -Qi glibc
Name            : glibc
Version         : 2.23-4

$ sudo dnscrypt-proxy --resolver-name=dnscrypt.eu-nl --user=nobody --ephemeral-keys -a 127.0.4.0 --plugin=libdcplugin_example_ldns_aaaa_blocking.so
[INFO] + DNS Security Extensions are supported
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.1
[INFO] Loading plugin [/usr/lib/dnscrypt-proxy/libdcplugin_example_ldns_aaaa_blocking.so]
[INFO] Loaded plugin: [Directly return an empty response to AAAA queries]
[INFO] Ephemeral keys enabled - generating a new seed
[INFO] Done
[INFO] Server certificate #808464433 received
[INFO] This certificate is valid
[INFO] Chosen certificate #808464433 is valid from [2015-09-11] to [2016-09-10]
[INFO] Server key fingerprint is E7AC:5C21:A4E6:6A90:B254:DD73:5229:3BA1:5BE9:8EB3:4E8F:E538:52DE:A2FB:DDB6:1357
[NOTICE] Proxying from 127.0.4.0:53 to 176.56.237.171:443

**Comment by jedisct1** [comment]
This was due to https://github.com/jedisct1/dnscrypt-proxy/pull/409, that has been reverted. Everything should be back to normal :)

Thanks!
