### ISSUE TITLE
[Question] RandomDNS - DNSCrypt with improvements?

### ISSUE THREAD

**Issue by CHEF-KOCH** [jedisct1/dnscrypt-proxy#414]
Hey, I just found an interesting project and I'm asking myself why they not contacted you or submit an pull-request to improve the original dnscrypt tool, I'm talking about [RandomDNS](https://github.com/pwnsdx/RandomDNS). I not tested it (yet) but why not stay in contact to work together? 

I'm also a bit worried that maybe non experts picking the source up and claiming it's more secure which is maybe wrong since it's difficult to proof. 

I would be thankfully if someone could explain this a little bit. I'm skeptical if I read something like 'cool new features'. 

The only thing I miss is something like an basic Cache to e.g. replace unbound and native DNSSEC support together maybe with an option to run maybe multiple instances or spawn separate processes (on e.g. heavy loads to get better performance).

**Comment by licaon-kter** [comment]
Add JavaScript to replace a cron job at most? :-1:

Umm, these take a few seconds:
* update resolvers list (minisign to check)
* pick 2-3-4 at random (or [not so random](https://github.com/berrythesoftwarecodeprogrammar/dns-crap/blob/master/dnscrapt#L22))
* kill all instances of the daemon
* restart them all
* restart the unbound service

> The only thing I miss is something like an basic Cache to e.g. replace unbound and native DNSSEC support 

This now works in the Unix-y way, one tool for one job, not sure if bundling all features into one application is the way to go forward, NIH mostly. See #366 too.

**Comment by CHEF-KOCH** [comment]
So overall we can close this and say RandomDNS project is bullshit? Because e.g. they using 'strange' improvements? Well, I would agree this javascript stuff is (for me) a no go.

**Comment by licaon-kter** [comment]
Well, that's a strong word. JS feels overkill.

**Comment by jedisct1** [comment]
Javascript would indeed be a problem on routers.

But no matter what the language is, I'm not convinced that sending a copy of your queries to multiple parties instead of just one increases security and privacy.

**Comment by shodan007** [comment]
What about implementing it so after every x number of requests it changes resolvers.

**Comment by berrythesoftwarecodeprogrammar** [comment]
still wouldn't really increase security or privacy

**Comment by CrisBRM** [comment]
@berrythesoftwarecodeprogrammar Might slightly increase privacy against rogue resolvers, as no one resolver will have access to all the queries.

**Comment by jedisct1** [comment]
Using more resolvers increases the likeliness of hitting a rogue resolver.

And the only defenses against rogue resolvers are local DNSSEC validation, and running your own resolvers.

**Comment by CHEF-KOCH** [comment]
If the original author of dnscrypt said it's not really an improvement I think I can close this ticket. Otherwise we can re-open it if they want to stay in contact with us. But as mentioned there are maybe some stuff which isn't really an _improvement_ or not really helpfully (especially on multi-platform support). 

Sorry for the time I wasted here, but I was just asking because I have the fear that such projects may lower the security and not increasing something because of misinterpretations or wrongly implemented stuff. 

It's not against anyone or the project but I could't get the point why someone not contact the original developer first or open an ticket for such thing, so that we could work together.
