### ISSUE TITLE
d0wn sg server

### ISSUE THREAD

**Issue by Xcelcio** [jedisct1/dnscrypt-proxy#415]
Why is it removed from the dnscrypt-resolvers.csv?

It's stable and I've been using it forever.
Not to mention it's the only server in SEA.

Please add it back, thank you.

**Comment by jedisct1** [comment]
Hi,

Servers get removed after they cannot be used for 2 days or more. Maybe the public key changed, and nobody sent a pull request to update it.

Looks like there are a few new d0wn servers that are not included either.

It's difficult to keep track of all the changes if server operators don't publish them anywhere but on their own website :(

I'm gonna compare what's on d0wn website and in the list. Thanks for the heads up.

**Comment by jedisct1** [comment]
Actually, the .sg one doesn't seem to be working right now:

```bash
$ dnscrypt-proxy -a 127.0.0.1:53 -r 128.199.248.105:443 --provider-name=2.dnscrypt-cert.sg.d0wn.biz --provider-key=D82B:2B76:1DA0:8470:B55B:820C:FAAB:9F32:D632:E9E0:5616:2CE7:7D21:E970:98FF:4A34 --test 10

[NOTICE] Starting dnscrypt-proxy 1.6.1
[INFO] Generating a new session key pair
[INFO] Done
[ERROR] Unable to retrieve server certificates
[INFO] Refetching server certificates
[ERROR] Unable to retrieve server certificates
[INFO] Refetching server certificates
[ERROR] Unable to retrieve server certificates
```

**Comment by jedisct1** [comment]
Looks like the actual issue is that this resolver is being listed as supporting queries to port 443.

But in fact, it doesn't.

Switching to port 54 works. I'm going to re-add it, but on this new port.

**Comment by jedisct1** [comment]
Done.

**Comment by Xcelcio** [comment]
Thanks man, yeah sorry for forgetting to mention that i use default port 53.

Anyway thanks again, re-adding it every time I update is not very nice.
