### ISSUE TITLE
"Standby" when connecting to certain servers

### ISSUE THREAD

**Issue by Matvei27** [jedisct1/dnscrypt-proxy#417]
I am unable to connect to certain servers, while others are working just fine. All of the servers were working for me until the other day. I am using the Mac version and I have ipv6 disabled.
Connecting to servers which previously worked fine now results in dnscrypt showing "Standby"
I do not think it is an issue with the server has it is happening with multiple servers hosted by multiple providers.
<img width="780" alt="screen shot 2016-05-25 at 10 27 36" src="https://cloud.githubusercontent.com/assets/12841042/15549849/73497c54-2263-11e6-8200-2b27ba0c3be0.png">

**Comment by licaon-kter** [comment]
I guess you should open the About screen and report that on that to the app developers.
