### ISSUE TITLE
missing-call-to-setgroups-before-setuid

### ISSUE THREAD

**Issue by comzeradd** [jedisct1/dnscrypt-proxy#421]
Hi, I'm trying to package this for Fedora.

This is an error I get running rpmlint:
```
missing-call-to-setgroups-before-setuid:
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```

https://www.securecoding.cert.org/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges

**Comment by jedisct1** [comment]
acdbeedebf016e35ba6c36ef98c3a233df78a536 should address this. Thanks!
