### ISSUE TITLE
app.c:206:9: warning: implicit declaration of function ‘initgroups’ 

### ISSUE THREAD

**Issue by ssten** [jedisct1/dnscrypt-proxy#424]
Trying to build today's git snapshot I've got the following warning from my package management system:

> \* QA Notice: Package triggers severe warnings which indicate that it
> \*            may exhibit random runtime failures.
> \* app.c:206:9: warning: implicit declaration of function ‘initgroups’ [-Wimplicit-function-declaration]

**Comment by jedisct1** [comment]
Fixed in https://github.com/jedisct1/dnscrypt-proxy/commit/3673840ada9bdb1e9b9446aeea47d7f4dd5f0d49

Thanks!
