### ISSUE TITLE
Missing connections for Little Snitch

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [jedisct1/dnscrypt-proxy#425]
The About tab in the preference pane lists several addresses that are supposed to be allowed in Little Snitch, but there were two requests made that aren't listed.

curl tried to establish a connection to download.dnscrypt.org on TCP port 443

DNSCrypt Menubar via curl tried to establish a connection to download.dnscrypt.org on TCP port 80

**Comment by licaon-kter** [comment]
Wrong place to report errors maybe, go here: https://www.obdev.at/support/index.html?product=LS&topic=contact

**Comment by GitTheHellOutaHere** [comment]
No, THIS is the correct place to report errors in DNSCrypt.

There's nothing wrong with Little Snitch, it did its job correctly.

I was simply reporting that DNSCrypt is missing two entries in the About tab.
It says 

> Using Little Snitch? There are a few rules you need to establish, which Little Snitch should prompt for when trying to activate this application:
Allow any outgoing connection for system processes (dnscrypt-proxy)
Allow any incoming connection for system process (dnscrypt-proxy)
Allow any outgoing connection for system processes (dig)
Allow outgoing TCP connections to port 80 (http) of www.apple.com for system process (curl)
For automatic updates, allow outgoing TCP connections to port 80 (http) of updates.dnscrypt.org and to port 443 (https) of github.com for system process (curl)


But evidently some addresses were either omitted or have changed, and need to be added to the list.

**Comment by jedisct1** [comment]
This project is dnscrypt-proxy, a headless client implementation of the protocol.

There is no "about tab" nor "preference pane" in this project.

The project you are referring to is probably https://github.com/alterstep/dnscrypt-osxclient which already lists `download.dnscrypt.org` in the set of things to whitelist in Little Snitch. So, it will show up when a new release of this software is available.

**Comment by GitTheHellOutaHere** [comment]
Oh, sorry about that.

Right site, wrong project. I wanted the dnscrypt-osxclient page.
https://github.com/alterstep/dnscrypt-osxclient

Feel free to delete this thread so people don't end up here instead of the other page I'm posting on.
