### ISSUE TITLE
DNSCrypt website: Wrong TLSA record

### ISSUE THREAD

**Issue by rugk** [jedisct1/dnscrypt-proxy#427]
Your website https://dnscrypt.org/ is down.
Also I see DNSSEC validation issues with my Firefox addon.

**Comment by licaon-kter** [comment]
Works now (at least): http://isup.me/dnscrypt.org/

**Comment by rugk** [comment]
Yes, now it works again for me too.
However I still see a DANE issue. DNSSEC works, but the TLSA entry seems to be wrong.

**Comment by jedisct1** [comment]
TLSA records removed. They are painful to keep in sync with Letsencrypt certs.

**Comment by rugk** [comment]
Well... just use the same CSR when renewing the LE cert or follow [these instructions](https://community.letsencrypt.org/t/please-avoid-3-0-1-and-3-0-2-dane-tlsa-records-with-le-certificates/7022).
