### ISSUE TITLE
[Feature Request] Black-/Whitelist and IP based rules won't allow you to import external lists

### ISSUE THREAD

**Issue by CHEF-KOCH** [jedisct1/dnscrypt-proxy#428]
The current situation is that the white-/blacklist and the IP based rules can be manually edited/enabled/disabled within the configuration file of dnscrypt-proxy. However, the problem or the missing feature I see here is that we don't have any option to work with external pre-made lists.

Modern adblockers like AdGuard, uBlock or the Pi-Hole allowing you to import external lists to make it easier to work with rules from external people.

For example [my blocklist rules](https://github.com/CHEF-KOCH/dnscrypt-proxy-blacklist-filter/blob/master/blacklist.txt) can't be imported directly into the blacklist or the dnscrypt-proxy.toml. So my wish here would be that people could pickup the [blacklist.txt](https://github.com/CHEF-KOCH/dnscrypt-proxy-blacklist-filter/blob/master/blacklist.txt) and import it into their blocklist/whitelist/IP list or the configuration file in order to import those rules. Idealy a parser for this seems to be required to check for errors or syntax problems. So we need somwething for the import to check this. 

![grg](https://user-images.githubusercontent.com/727123/39652324-6b4ab13a-4fed-11e8-99f3-9ebbbaa573fb.png)

**Comment by drew-kun** [comment]
This sounds like a really great idea to keep different lists separate and generally have a sanitized dnscrypt-proxy config...

**Comment by jedisct1** [comment]
These lists are highly redundant, with a lot of overlap. This is why external scripts such as the python one which is part of this project are useful. They remove invalid rules, but also optimize them, by merging duplicates and overlaps.

Looking at the output, such as in the mybase list, you can see how many useless rules have been optimized out, and it is quite huge.

Parsing different formats, validating and optimizing the content is not straightforward, and is really better done by an external script.
