### ISSUE TITLE
ERR Name to resolved - I'm unable to use dnscrypt

### ISSUE THREAD

**Issue by Maxiride** [jedisct1/dnscrypt-proxy#429]
Hello, I'm running an Arch Linux installation and I read and followed the [Arch Wiki instructions](https://wiki.archlinux.org/index.php/DNSCrypt) plus a [blog](http://linoxide.com/tools/install-dnscrypt-unbound-archlinux/) to properly set dnscrypt _with_ unbound.

After doing the proper modifications to my system resolv.conf, ubound.conf etc without incurring in any execution error, when I try to load any website I get the name not resolved error and I'm having some troubles at troubleshooting this because I'm not that expert about the connection scripts.

I'd like any hint to where and what to look for, thanks in advance.

**Comment by licaon-kter** [comment]
Your chosen DNS server supports DNSSEC, right?

**Comment by Maxiride** [comment]
I didn't modified the default one which accordingly to arch wiki is dnscrypt.eu-nl, which based on [this](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv) table supports it. 
So TLDR yes :)

**Comment by licaon-kter** [comment]
Do try others too, maybe that one was not working when you tested or something.

**Comment by jedisct1** [comment]
Can you try to just run it without systemd:

```
$ dnscrypt-proxy -R dnscrypt.org-fr -a 127.0.0.1:5300
```

And the check if you can resolve names:

```
hostip -r 127.0.0.1:5300 example.com
```

?

**Comment by Maxiride** [comment]
I tried to do some more troubleshooting and posted whatever I found [here] (https://bbs.archlinux.org/viewtopic.php?pid=1637434#p1637434) (at this point however you don't need to go through all the post).

@jedisct1 running it yelds _Unable to retrieve server certificates_ 
```
[federico@arch-anywhere-federico]: ~>$ dnscrypt-proxy -R dnscrypt.org-fr -a 127.0.0.1:5300
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.1
[INFO] Generating a new session key pair
[INFO] Done
[ERROR] Unable to retrieve server certificates
[INFO] Refetching server certificates
[ERROR] Unable to retrieve server certificates
[INFO] Refetching server certificates
[ERROR] Unable to retrieve server certificates
^C
```

So far I tried also many (not all) other resolvers all of them giving the same result as above:
- 4armed
- dnscrypt.org-fr
- dnscrypt.eu-nl
- d0wn-de-ns2
- ipredator
- cs-fr
- dnscrypt.eu-dk
- cs-uswest
- cs-uswest2

I find it _really_ unlikely that all of them are blocked by my ISP.

- ovpnto-se instead gave me:

```
[federico@arch-anywhere-federico]: ~>$ dnscrypt-proxy -R ovpnto-se -a 127.0.0.1:5300
[INFO] - [ovpnto-se] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.1
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate #808464433 received
[INFO] This certificate has expired
[ERROR] No useable certificates found
[INFO] Refetching server certificates
```
so this is something you might want to fix in the list or contact the resolver to update their certificate, but WOAH one of them answered the call! So I told myself, let's give a shot to one more aaaand **d0wn-gr-ns1** WORKS!!

```
[federico@arch-anywhere-federico]: ~>$ hostip -r 127.0.0.1:5300 google.com
172.217.20.46
```

That came unexpected since I started thinking that none of them was going to work =)


At this point I will test _all_ the remaining resolvers in the list but after this experience I would like to **highly** suggest to improve the dnscrypt service with some kind of test all and maybe order the results by ping. :D

**Comment by jedisct1** [comment]
The list of working resolvers is constantly being verified. For example `ovpnto-se` whose certificate expired has been temporarily [removed from the list](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv).

Apparently, your computer or something between your computer and the resolvers, is blocking or intercepting DNS queries. Certificates are retrieved with regular DNS queries, using UDP on port 53.
So, make sure that you don't have something on your computer or router blocking these queries.

**Comment by Maxiride** [comment]
Well yes I'm on a restricted network which provides it's own dns server and it's own certificate authority for websites so the blocking happens there for sure. 
I was hoping to be able to use dnscrypt to "escape free" on the net in conjunction with a paid VPN maybe.

**Comment by jedisct1** [comment]
dnscrypt was not designed to escape corporate policies. Since some servers are accessible and some aren't, maybe they are even explicitly blocking public DNS servers.

The [resolvers-check.sh](https://github.com/jedisct1/dnscrypt-proxy/blob/master/resolvers-check.sh) script can be used to automatically check all the resolvers.

**Comment by Maxiride** [comment]
Thanks for the infos and the link to the script, it's really useful =)
Guess that the issue can be closed at this point.
