### ISSUE TITLE
Unexpected Program Exit If Connected Between DNSCrypt-Proxy and Unbound

### ISSUE THREAD

**Issue by GaneJ** [jedisct1/dnscrypt-proxy#430]
2 DNSCrypt-Proxy Service active with DNS Server capable to validate DNSSEC.
one in 127.0.0.1:21820 and the other in 127.0.0.1:21826.
Both using ENDS with 1232 byte and EphemeralKeys enabled.
Both DNSCrypt-Proxy configure with -j -m 4 parameter.
Both EXE had been configure in Windows Event Log (I'm manually add an entry on both exe in eventlog).
Both also using LDns_BLocking plugin.
They both act as Unbound DNS Server.
DNSCrypt-Proxy version 1.6.1.

Unbound had been configure with DNSSEC enable.
Unbound handling client DNS request (binding into port 53).
Unbound EDNS and UDP using 1232 byte.
Unbound version 1.5.9.

When I'm using Unbound version 1.5.8, I though it was Unbound fault.
Since Unbound version 1.5.8 had an issue on WSAEvent.
But after it had been fixed in Unbound 1.5.9, that issue with DNSCrypt-Proxy still occured (Unexpected Exit from DNSCrypt-Proxy).
No detail log had been record in Windows Event Log from DNSCrypt-Proxy.

Now, I'm not using Unbound anymore because of that issue, also because it takes a lot bandwith if I'm enabling DNSSEC on both application.

Now, I'm just using 4 (four) DNSCrypt-Proxy service to handle client DNS request with EDNS 1232 byte and EphemeralKeys enabled. No Unexpected Program Exit anymore from DNSCrypt-Proxy.

The question is, why DNSCrypt-Proxy throw an error and exit if Unbound active and why DNSCrypt-Proxy work without an error if no Unbound active?

For reference, I'm using Windows 7 x64.

I hope with this, DNSCrypt team kind enough to look what causing this issue with Unbound.
Thank you.

**Comment by licaon-kter** [comment]
Not using version 1.6.1 because?

**Comment by GaneJ** [comment]
I think the problem is how DNSCrypt-Proxy handling DNSSEC.

Since Non Windows Server can't do DNSSEC to DNSCrypt-Proxy, the error will not occure.
That why, with Unbound, DNSCrypt-Proxy got that error. It because Unbound capable doing DNSSEC.

That error with DNSCrypt-Proxy happen when DNSCrypt-Proxy busy enough handling dns request.
I though I already set Unbound to request no more than 32 and set DNSCrypt-Proxy to handling no more than 32 request, that error still happen.

Also, if non DNSSEC TLD request from Unbound into 3rd DNSCrypt-Proxy with DNS Server without DNSSEC, that 3rd DNSCrypt-Proxy works fine without any error.

I hope this help DNSCrypt team to solve this problem.
Thank you.

**Comment by jedisct1** [comment]
If only there was such a "dnscrypt team"...

So, on Windows, `dnscrypt-proxy` sometimes crashes. Are you actually running it as a service? You said two of them were running simultaneously, but as a service, only one can run that way.

Can you try to run it from the command-line (not as a service), without plugins and without any options besides `-R <resolver name>`?

**Comment by GaneJ** [comment]
_If only there was a "dnscrypt team"..._
Sorry, since this is on github, I though there is others involve.

_Are you actually running it as a service?_
Yes.

_You said two of them were running simultaneously, but as a service, only one can run that way?_
I'm pretty sure about that.
Make more than 2 copies of DNSCrypt-Proxy binaries, patch a little with service name. Sign with my own certificate. Of course before that I read your source code.
At first I want to make that service name change in DNSCrypt-Proxy source code, but since my knowledge about mingw+cmake not too good and I don't have any other compiler and also my c/c++ knowledge also bad, I give up made that change on source code level. Instead I'm doing a little string patch in DNSCrypt-Proxy binaries.

_Can you try to run it from the command-line (not as a service), without plugins and without any options besides -R <resolver name>?_
First, I DID test DNSCrypt-Proxy+Unbound with DNSCrypt-Proxy run Not As A Service with No Error from DNSCrypt-Proxy. But I did that only in short time (less than 2 hours I think).
Since I want to use DNSCrypt-Proxy+Unbound on daily task and I hate to see a lot of console window appear in my screen, I run both of application as a Service. After more than 6 hours, I think, DNSCrypt-Proxy exit unexpectedly with Windows Event Log Record that exit, but without detail explanation from DNSCrypt-Proxy why that happen. I'm pretty sure 100% my computer free from a virus or whatever program that make DNSCrypt-Proxy exit like that.
Hmm... I'm thinking, Is it possible that error happen because DNSCrypt-Proxy want to write something on Windows Event Log (because -j -m 4 param)? If that thing cause the problem, why it need long operation just to make that error occure?

**Comment by GaneJ** [comment]
Since there is no team, maybe I test it again next week, maybe, I don't know when...
No promise.

**Comment by jedisct1** [comment]
In order to help find the bug, can you please use unmodified binaries?

Having a stack trace or at least a function name would help a lot to know where to look at. 
And running it from the command-line may print a stack trace or display a dialog box mentioning the function name it was executing just before the crash. There's not much I can do without this information.

**Comment by GaneJ** [comment]
- _In order to help find the bug, can you please use unmodified binaries?_
- The weird thing is that error came from non modified binaries (127.0.0.1:21820).



- _Having a stack trace or at least a function name would help a lot to know where to look at.
And running it from the command-line may print a stack trace or display a dialog box mentioning the function name it was executing just before the crash. There's not much I can do without this information._
- I'm trying. Lets say that the way to take full advantage of DNSCrypt is by using Unbound. Right know my daily use of DNSCrypt did not use Unbound anymore, just DNSCrypt. In fact, this very moment I'm writing this, I'm using DNSCrypt. So, like I said earlier, I'll do it again when I got more free time. Right know I'm too busy. And other thing, I did not see in DNSCrypt source code the difference between log level 4 and log level 7. I mean, with log level 7, DNSCrypt should write any activity in the log file or in the screen, right? Or could you tell me which log level that make DNSCrypt write the whole activity on the screen or on the log file, so I could send you whatever DNSCrypt wrote on the screen or in the log file?

**Comment by jedisct1** [comment]
All I need is know where the application crashes. It prints it on the console or displays it in an alert message window when crashing. Or if you can attach a debugger to get the stack trace and register values, that would be even better.

**Comment by GaneJ** [comment]
And it need Unbound to do that. Without Unbound DNSCrypt work flawless.
