### ISSUE TITLE
Please help add Hong Kong solution to file dnscrypt-resolvers.csv

### ISSUE THREAD

**Issue by junife** [jedisct1/dnscrypt-proxy#432]
Hello, I am from china mainland. You know Hong Kong dnscypt dns is very good and useful for us. So please kindly help me add the solution. See https://dns.d0wn.biz/, the page give a free Hong Kong DNS-Server with name ns1.hk.dns.d0wn.biz.
Thank you!

**Comment by HighIO** [comment]
'fvz-rec-hk-ztw-01' or 'cisco' in CSV should be better for you, because 'ns1.hk.dns.d0wn.biz' is offline frequently.

**Comment by junife** [comment]
OK, I got it. Thanks.
