### ISSUE TITLE
Help setting up DNSCrypt with pdnsd

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [jedisct1/dnscrypt-proxy#434]
I've been using DNSCrypt for a while now, and although it's been a PITA making it work with Viscosity and the wifi portal I need to connect through, I decided I should also install pdnsd to cache DNS requests.

But this seems to be above my skill level, and I haven't been able to make it operable.
I installed Homebrew and then pdnsd, and have tried editing the pdnsd.conf file.

I've found virtually no help for setting up either one on Mac. I did try some steps found on different sites.
Got some error messages and it seems DNSCrypt needs to be diverted from port 53 to another port so that pdnsd can use that port.

**Comment by jedisct1** [comment]
Hi,

I've never used pdnsd, but looks like there is some information [here](https://wiki.archlinux.org/index.php/DNSCrypt#Example:_configuration_for_pdnsd).

Their sample configuration connect to the dnscrypt proxy on port 40, so you need to adjust the dnscrypt `.plist` file in order to add this to the `<ProgramArguments>` section:

```
          <string>--local-address=127.0.0.1:40</string>
```

**Comment by GitTheHellOutaHere** [comment]
I've read that page several times and that's where I copied the text to place in the pdnsd.conf file.
That page is loaded with commands, and I didn't know what all was necessary.

At the bottom of the page it says "Since DNSCrypt is a long-running network service, it is recommended to run it as its own, unprivileged user. 
# useradd -r -d /var/dnscrypt -m -k /var/empty -s /bin/nologin dnscrypt"

I don't know if that's something I should do or not, seems like DNSCrypt would have done this or instructed how to do this on install if it was a preferred method.

I've reinstalled pdnsd and it's currently running and DNSCrypt is connected.
I added that line to the DNSCrypt plist, changing to 40 to 54 which I'd previously set in pdnsd.
I don't normally edit plists, so I had to read a bit to get it right (I hope).
The file now reads:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.github.dnscrypt-osxclient.DNSCryptMenuBar</string>
  <key>KeepAlive</key>
  <false/>
  <key>RunAtLoad</key>
  <true/>
  <key>ProgramArguments</key>
  <string>--local-address=127.0.0.1:54</string>
  <array>
    <string>/Applications/DNSCrypt Menubar.app/Contents/MacOS/DNSCrypt Menubar</string>
  </array>
  <key>LimitLoadToSessionType</key>
  <string>Aqua</string>
</dict>
</plist>


When I run **nslookup google.com** to test it, I get this:

Server:	127.0.0.54
Address:	127.0.0.54#53

Non-authoritative answer:
Name:	google.com
Address: 74.125.206.139
Name:	google.com
Address: 74.125.206.100
Name:	google.com
Address: 74.125.206.102
Name:	google.com
Address: 74.125.206.113
Name:	google.com
Address: 74.125.206.138
Name:	google.com
Address: 74.125.206.101


When I run dig @127.0.0.1 www.google.com to test, I get this:

; <<>> DiG 9.8.3-P1 <<>> @127.0.0.1 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: **SERVFAIL**, id: 40833
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Jul  9 18:16:11 2016
;; MSG SIZE  rcvd: 32


Don't like that SERVFAIL message.


Due to my extensive hosts file (a known problem for pdnsd although it's only 872 kb), I created a basic hosts-pdnsd file and added that path to pdnsd's conf file.

That file now reads as follows:

**global {
    perm_cache = 1024;
    cache_dir = "/usr/local/var/cache/pdnsd";
    run_as = "pdnsd";
    server_ip = 127.0.0.1;
    status_ctl = on;
    query_method = udp_tcp;
    min_ttl = 15m;       # Retain cached entries at least 15 minutes.
    max_ttl = 1w;        # One week.
    timeout = 10;        # Global timeout option (10 seconds).
    neg_domain_pol = on;
    udpbufsize = 1024;   # Upper limit on the size of UDP messages.
}

server {
    label = "dnscrypt-proxy";
    ip = 127.0.0.1;
    port = 54;
    timeout = 4;
    proxy_only = on;
}

source {
    owner = localhost;
    file = "/etc/hosts-pdnsd";
}**


I don't know if I was supposed to remove everything else in the file or just replace parts of it, but I deleted everything then pasted in text found on that page you linked to and changed a couple things


The command _sudo lsof -i -P | grep -i "listen"_ lists these ports.
Looks like I still need to redirect DNSCrypt from port 53?
I thought I did that already when I pasted in that string you posted.

iGlasses    537            Bob    9u  IPv4 0xa9a8b712bdd36883      0t0    TCP localhost:51622 (LISTEN)
dnscrypt-  8227         daemon    8u  IPv4 0xa9a8b712c41a6f8b      0t0    TCP 127.0.0.**54:53** (LISTEN)
2BUA8C4S2 35118            Bob   16u  IPv4 0xa9a8b712c6311883      0t0    TCP localhost:6258 (LISTEN)
2BUA8C4S2 35118            Bob   18u  IPv6 0xa9a8b712bdcd54fb      0t0    TCP localhost:6258 (LISTEN)
2BUA8C4S2 35118            Bob   19u  IPv4 0xa9a8b712c72f9693      0t0    TCP localhost:6263 (LISTEN)
2BUA8C4S2 35118            Bob   20u  IPv6 0xa9a8b712bdcd5a5b      0t0    TCP localhost:6263 (LISTEN)
pdnsd     68517         nobody    3u  IPv4 0xa9a8b712c41b1883      0t0    TCP localhost:53 (LISTEN)
Mac-mini:~ Bob$ 


With DNSCrypt disabled my IP address appears in the midwest where my chosen DNS server is located. When I enable it, the address is the selected location, currently overseas.

**Comment by GitTheHellOutaHere** [comment]
pdnsd DOES NOT start on boot.
I've rebooted several times and it DOES NOT launch on boot.

**Comment by jedisct1** [comment]
If I understand correctly, you are using Homebrew, including to install something called pdnsd, but not for not for the dnscrypt client. Instead, you installed the all-in-one OSX-DNSCrypt Client application.

That app does a lot of things. It changes network settings, it tries to find appropriate parameters for the proxy, it monitors the connection, it monitors the proxy, is enables modules, it detects network configuration changes, it provides a user interface and it bridges everything.

Adding support for a DNS cache in this application is likely to be way more complicated than just changing a `.plist` file.

The instructions you read on the Arch Linux website can be only be adapted to `dnscrypt-proxy` being run on macOS like it is on Linux.

But what are you actually trying to do? If you just need to block domain names, you can paste them in the "Block queries for the following domain names" box in the OSX-DNSCrypt Client application.

**Comment by GitTheHellOutaHere** [comment]
I already had DNSCrypt installed and had been using it a few months.

After reading that a local cache would speed up browsing, I decided to install pdnsd.
Pdnsd maintains a local disk cache of the queries that your system performs and subsequent queries will be faster from the cache. DNSCrypt turns regular DNS traffic into encrypted DNS traffic that is secure from eavesdropping and man-in-the-middle attacks.

Installing pdnsd required installing Homebrew or MacPorts first.
What Does Homebrew Do?
_Homebrew installs the stuff you need that Apple didn’t_ (says the [Homebrew website](http://brew.sh)).

I really didn't like the thought of installing more "garbage" and  hope I can uninstall it if I ever get pdnsd working. If I'd known getting pdnsd to run would be so difficult I wouldn't have attempted it. It looks simple on [this page](https://gist.github.com/fujimogn/3401490).

I'm not sure this will ever work for me.
I'm supposed to set the DNS in System preferences to 127.0.0.1.
But I'm connected to a business's wifi through their portal and it keeps changing the address to 127.0.0.x.


Also, there are four different DNSCrypt plist files in LaunchDaemons and they're very similar. I'm not sure which one that string should be placed in but I put it in ControlChange. And I don't know Jack about keys, arrays and strings, so did I insert it in the proper place?
It didn't work right using a text editor so I installed a plist editor.

 **<key>WorkingDirectory</key>
  <string>/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts</string>
  <key>ProgramArguments</key>
  <string>--local-address=127.0.0.1:54</string>
  <array>
    <string>/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts/handle-control-change.sh</string>
  </array>**

/Library/LaunchDaemons/com.github.dnscrypt-osxclient.DNSCryptAfterboot.plist
/Library/LaunchDaemons/com.github.dnscrypt-osxclient.DNSCryptConsoleChange.plist
/Library/LaunchDaemons/com.github.dnscrypt-osxclient.DNSCryptControlChange.plist
/Library/LaunchDaemons/com.github.dnscrypt-osxclient.DNSCryptNetworkChange.plist

**Comment by GitTheHellOutaHere** [comment]
BUMP.

Can anybody assist?

Actually it may be hard to set up now because the owners of the wifi portal I connect through changed their ISP yesterday and now DNSCrypt won't connect at all.

But I'd still like to get the pdnsd cache working so when I change locations it will be usable.

**Comment by jedisct1** [comment]
Questions about pdnsd or Homebrew have a better chance to get answered if asked on their respective issue trackers/mailing lists.

**Comment by GitTheHellOutaHere** [comment]
My issue has nothing to do with Homebrew and there's no issues tracker on GitHub for pdnsd.
That's why I posted it here - these apps are supposed to work together, pdnsd just adds a cache for DNSCrypt to use.
