### ISSUE TITLE
Unable to bind local address to localhost (AF_INET && AF_INET6)

### ISSUE THREAD

**Issue by GavinJS** [jedisct1/dnscrypt-proxy#435]
Hi,
I'm trying to bind the local address to "localhost" which immediately throws an error:
`[INFO] - [cisco] does not support DNS Security Extensions
[WARNING] - [cisco] logs your activity - a different provider might be better a choice if privacy is a concern
[ERROR] Unsupported local address: localhost:53
[ERROR] Unable to start the proxy
`

I'm able to specify `0.0.0.0` and `::` individually (also `127.0.0.1` and `::1` individually) but ideally I'd rather just run one instance of proxy which binds to both AF_INET and AF_INET6 addresses on the specified port.  I'm guessing this would require the port argument be split off into its own switch.

Is this achievable or something which is already possible through a means I'm not aware of?

Also thinking it through, if modifications need to be made to the bind code, it might be helpful in the future to also support AF_UNIX sockets for IPC between local caching resolvers and the proxy instances without the need to secure/firewall.

Thanks.

**Comment by jedisct1** [comment]
Hi,

It only binds one socket, so a single process can either bind `127.0.0.1` or `::1` but not both.

Running two processes simultaneously is not a crime :) And most of the memory is going to be shared.

Supporting `AF_UNIX` sockets is a good idea, thanks for suggesting it!
