### ISSUE TITLE
Is this the expected error? I have an error

### ISSUE THREAD

**Issue by bryongloden** [jedisct1/dnscrypt-proxy#436]
I believe this is not an expected error; however, I don't know how to correct it yet.

[[../dnscrypt-proxy-master/src/libevent-modified/evport.c:454](https://github.com/jedisct1/dnscrypt-proxy/blob/master/src/libevent-modified/evport.c#L454)]: (error) Array 'evpd.ed_pending[8]' accessed at index 8, which is out of bounds.

Ergo on line 454 array 'evpd.ed_pending[8]' is accessed at index 8, which is out of bounds.

Found by https://github.com/bryongloden/cppcheck

**Comment by jedisct1** [comment]
cppcheck is dumb.

```c
associated = 1;
for (i = 0; i < EVENTS_PER_GETN; ++i) {
        if (evpd->ed_pending[i] == fd) {
            associated = 0;
            break;
        }
    }
```
So, if there are no pending events, `associated = 1`.

Then we have:

```c
if (associated) {
    ... obviously no access to `evpd->ed_pending` ...
} else {
    /* associated == 0, i < EVENTS_PER_GETN */
    evpd->ed_pending[i] = -1;
}

**Comment by jedisct1** [comment]
An assertion was added to remove confusion.
