### ISSUE TITLE
after changing local port, dns service does not run

### ISSUE THREAD

**Issue by polinzhuo** [jedisct1/dnscrypt-proxy#439]
I am installing dnscrypt on raspberry pi. 
dnscrypt was installed correctly.
DNS test can be done, using dig.
i wanted to change local port from 53 to 5353.
At first, i modifyed the config file :"/etc/default/dnscrypt-proxy ", until i noticed the comment:
"If using systemd, this is not used and must be specified in dnscrypt-proxy.socket."
so i changed the port from modifying the config :
"/etc/systemd/system/sockets.target.wants/dnscrypt-proxy.socket"
After i modified the config file, I restarted the device.
i noticed the service dnscrypt can run sucessfully, but test can not be done. dig tool displayed the information:
" connection timed out; no servers could be reached"

how can i modify the local port of dnscrypt service ?

**Comment by jedisct1** [comment]
Hi,

You can change the port, but apps will all try to connect to port 53 no matter what. Changing the port of the dnscrypt proxy can be useful to add another proxy in front of it, but you always need something listening to port 53; that's the standard port for DNS services.

**Comment by polinzhuo** [comment]
thank you jedisct1
I want to create dns server by using dnscrypt + dnsmasq.
Dnsmasq can not listen port 53. 
How can I do?

**Comment by jedisct1** [comment]
`dnsmasq` certainly can listen to port 53, or else it wouldn't be very useful :)

The setup you're looking for is probably:
- dnsmasq listening to port 53, forwarding to another port (let's opt for port 54)
- dnscrypt-proxy listening to port 54

What you can't have is dnsmasq and the dnscrypt proxy listen to the same port simultaneously. But if nothing else is listening to port 53, dnsmasq should be able to listen to that port, and this is the default.

**Comment by polinzhuo** [comment]
thank you jedisct1
I see what i should do.
the flow of the request is like this:
dns request---53port----dnsmasq----5353----dnscrypt
I have gotten the twitter content from china GFW.
but I have one puzzle:
why i can access the twitter, but not youtube?
I had use the utility dig for youtube.com, and the IP of youtube.com have been stored in the dns cache.
But i still cannot access youtube.com

Can you tell me the reason? and where the dns cache is been stored?

**Comment by jedisct1** [comment]
Maybe the GFW blocks the Youtube IP addresses, not just DNS queries for it. In that case, there's not much you can do besides using a VPN :(
