### ISSUE TITLE
Clarification of protocol

### ISSUE THREAD

**Issue by bluejekyll** [jedisct1/dnscrypt-proxy#440]
In https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt#L383
It explains that when selecting a new certificate you perform this action:

> chooses the certificate with the higher serial number.

Then it goes on to explain https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt#L390

> The client must check for new certificates every hour, and switch to a
> new certificate if the current certificate is not present or not valid
> any more.

Which seems to not be entirely consistent with https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt#L394
 
> The client shouldn't switch to a new certificate if the current one is
> still valid and still present in the set of returned certificates,
> even if the new set includes certificates with a higher serial number
> than the current one.

Can anyone clarify this choice? Is there an optimization going on in the server that makes the client switching to the current highest serial numbered certificate in appropriate after the specified hour duration is complete?

**Comment by jedisct1** [comment]
Thanks for pointing this out this inconsistency.

Serial numbers are for certificate revocation, and no matter when, the valid certificate with the highest serial number should be prefered.

The protocol description has been updated accordingly.

Thanks again!
