### ISSUE TITLE
Not an issue, only a question

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#447]
Hi,

I just don't know where to share a mystery concerning _DNSCrypt-Proxy_ and if you, anyone could provide an explanation I'd be truly relieved.

I have installed latest _DNSCrypt-Proxy 1.7.0_ and it runs fine, no problem. The possible issue concerns not the tool itself but the encrypted DNS provider.

There is one site (only one I'm aware of at this time), https://archive.is/ which resolves to _**Server not found**_ when the DNS resolver is among these (I haven't tested all of course):

_**4armed, dnscrypt.org-fr, dnscrypt.eu-dk, dnscrypt.eu-nl, ns0.dnscrypt.is, cs-fr, cs-fr2**_

but which is correctly resolved (only?) with: **_cisco_**

Thanks for any information on this issue which I really pain to understand.

**Comment by jedisct1** [comment]
Hi,

Just tried from the `dnscrypt.org-fr` box, and none of the name servers for `archive.is` are answering DNS queries:

```
$ dnstracer -4 -c -s . archive.is
Tracing to archive.is[a] via A.ROOT-SERVERS.NET, maximum of 3 retries
A.ROOT-SERVERS.NET [.] (198.41.0.4)
 |\___ sns-pb.isc.org [is] (192.5.4.1)
 |     |\___ d1.dns.li [archive.is] (178.62.195.5) * * *
 |     |\___ h2.archive.is [archive.is] (146.0.75.2) * * *
 |      \___ c1.webmaster.ms [archive.is] (78.108.190.21) * * *
```

**Comment by jedisct1** [comment]
Tried from another network with the same result. Tried from yet another network and these were reachable.

Looks like these authoritative servers are currently experiencing connectivity issues.

**Comment by zymase** [comment]
The fact is what I've described above is not new (I has tested several times with the same above scenario with DNSCrypt-Proxy 1.6.1), that is,
1- This is not an ephemeral issue;
2- Why does cisco (alone?) resolves the query and not others?

**Comment by jedisct1** [comment]
Didn't check Cisco, but Yandex can resolve it. My ISP can't. `$ drill archive.is @178.62.195.5` times out.
Over 10 random RIPE Atlas probes, at least 2 don't get a reponse from their servers: https://atlas.ripe.net/measurements/4492513/#!probes

So this doesn't appear to be a DNS issue that can be solved on the resolvers.

**Comment by zymase** [comment]
My ISP's DNS resolves it (Bouygues Telecom), so do all other (non-encrypted) DNS resolvers I use occasionally:

BOUYGUES TELECOM
194.158.122.10
194.158.122.15

DNS.WATCH
84.200.69.80
84.200.70.40

GOOGLE DNS
8.8.8.8
8.8.4.4

OLEANE
194.2.0.20
194.2.0.50

OPENDNS
208.67.222.222
208.67.220.220

But with DNSCrypt-Proxy, only cisco (and Yandex since you've tested it) and not 4armed, dnscrypt.org-fr, dnscrypt.eu-dk, dnscrypt.eu-nl, ns0.dnscrypt.is, cs-fr, cs-fr2

I remain puzzled. I'm not going to limit DNSCrypt-Proxy to be used with cisco or yandex for the sole purpose of being available to open archive.is ... or I'll avoid archive.is which is more likely. Yet, I don't understand, as the non-techie I am, why this issue with archive.is

Thanks for your concern.

**Comment by jedisct1** [comment]
Actually, it's not just DNS queries, and it's not a routing problem. `archive.is` is completely firewalling some ISPs/hosting companies. Not just for DNS; HTTP queries are blocked as well.

They are refusing to respond to hosts whose IP belongs to Online, NetGroup, OVH and probably more.

Maybe the intent was to protect against a DDoS attack involving servers on these networks. But that's a bit overblown and blocks legitimate users.

So, their servers are basically saying "fuck you Netgroup, fuck you OVH, fuck you Online". And the DNSCrypt servers you are mentioning are hosted by these ISPs.

**Comment by zymase** [comment]
OK, @jedisct1 , I get the idea and the explanation. It has nothing to do with DNScrypt, is not specific to DNS resolving (HTTP queries concerned as well), and is all included in archive.is' firewalling some ISPs/hosting companies.

I appreciate to understand and thanks for your investigation, moreover when it appears that the whole issue had nothing to do with this, with your Github pages dedicated to DNSCrypt-Proxy.

Thanks again for your time and work. Now I know better.
