### ISSUE TITLE
So, what does dnscrypt actually do?

### ISSUE THREAD

**Issue by sixpointzero** [jedisct1/dnscrypt-proxy#452]
There are a lot of contradictory statements about `dnscrypt-proxy` on the Internet and I'm not sure what to believe.

[This](https://www.reddit.com/r/privacy/comments/4xnmyn/which_dns_do_you_use/d6h4ngi) guy says that `dnscrypt` authenticates _and_ encrypts DNS queries and he points [here](https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt#L43). However, [this](https://security.stackexchange.com/a/107091) guy says that my ISP can see all of my DNS queries even if I use `dnscrypt`.

So, can my ISP still see all of my browsing history via my DNS queries even if I'm using `dnscrypt`? Does `dnscrypt` only protect against DNS spoofing attempts? Does it do anything else? In simple terms, what difference does using `dnscrypt` make?

**Comment by jedisct1** [comment]
It depends on where the client and the server are running.

The [deployment](https://dnscrypt.org/#deployment) section on the website describes the different cases.

While it provides some confidentiality for DNS queries, your ISP can still observe the IP addresses you are connecting to, and, for most websites using HTTPS/HTTP2, the website name.
You should rather use a VPN if this is something you are concerned about.
