### ISSUE TITLE
SeServiceLogonRight permission issue?

### ISSUE THREAD

**Issue by milozelael** [jedisct1/dnscrypt-proxy#456]
I am using Windows 10 Home 64-bit. (It is pretty much a default install since I do not have a lot of Windows knowledge to make any significant changes.)

- I extracted the folder to C:\Program Files\dnscrypt-proxy-win64.
- dnscrypt-proxy.exe --resolver-name=dnscrypt.eu-nl --resolvers-list=C:\Program Files\dnscrypt-proxy-win64\dnscrypt-resolvers.csv --test=0 
- dnscrypt-proxy.exe --resolver-name=dnscrypt.eu-nl --resolvers-list=C:\Program Files\dnscrypt-proxy-win64\dnscrypt-resolvers.csv --install
- I added 127.0.0.1 and 8.8.4.4 to the TCP/IPv4 and it shows up correctly using: ipconfig /all.

open elevated cmd.exe
services.msc -> dnscrypt-proxy (right-click Properties) -> Log On -> This account -> otheruser and password (pop-up notification granting the SeServiceLogonRight permission to otheruser)

For security, I would rather have dnscrypt-proxy run as a otheruser and I have tried to specify a different user in the above procedure but dnscrypt-proxy will fail to start because of lack of permissions even though the SeServiceLogonRight was also granted to that user.

Please provide documentation of why dnscrypt-proxy will not work when using another user at least in Windows 10 Home 64-bit.

**Comment by licaon-kter** [comment]
Does this work: https://github.com/bitbeans/SimpleDnsCrypt ?

**Comment by milozelael** [comment]
Why? The screenshots do not show any support for running it as a different user either...

**Comment by licaon-kter** [comment]
It will run as SYSTEM.

**Comment by milozelael** [comment]
I do not want a GUI program, just a service that automatically starts at startup or logon.

It is a shame because the Linux version of dnscrypt-proxy is able to run as a different user. Why does it run as user SYSTEM? Isn't that a potential security risk?

**Comment by licaon-kter** [comment]
It's a GUI for setting up (server, IPv6, update etc), you only need it for that, the service is the only thing that runs actually. Do try the app instead of just musing while looking at the pictures though.

**Comment by milozelael** [comment]
In case if anyone is interested, there is a fully working solution to this problem at [serverfault](https://serverfault.com/questions/800188/run-program-at-startup-detached-and-as-another-user).
