### ISSUE TITLE
ldns_blocking

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#457]
Using the following command-line.

dnscrypt-proxy -R dnscrypt.eu-dk --plugin=libdcplugin_example_ldns_blocking.dll,--domains=C:\Users\Test\Downloads\dnscrypt-proxy-win32\blacklisted-domains.txt --tcp-only --plugin libdcplugin_example_ldns_aaaa_blocking.la

In the "blacklisted-domains.txt" file, the first line is facebook with an asterisk before and after as a wildcard.

Is this correct ?

When entering "www.facebook.com" in the browser's address bar, the FQDN name is still resolved and the page loads. Why ?

**Comment by morfikov** [comment]
It's probably your browser cache. Try to empty it, i.e. shift+refresh, or use a different profile for testing.

**Comment by uihdff** [comment]
Thanks for the quick reply.

Emptying the cache didn't make a difference.

What do you mean by a different profile ?

**Comment by morfikov** [comment]
For firefox, run:

`$ firefox --new-instance --ProfileManager`

and create one. But if there's no difference for you now, I don't think that was the problem.

**Comment by zymase** [comment]
Same issue here as @uihdff , impossible to integrate DNSCrypt-proxy plug-ins in a command line. i've tried everything I could imagine, nothing does it. The only solution I found was to run DNSCrypt-proxy via the _Simple DNSCrypt_ front-end application which manages those plug-ins flawlessly. Bothers me to be obliged to have to call a .net framework required application heavy as a whale just to be able to manage a slick DNSCrypt-Proxy application...

**Comment by jedisct1** [comment]
Version 1.8.0 can be configured on Windows using a config file: https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown#advanced-configuration

This includes plug-ins, that are way easier to use.
