### ISSUE TITLE
Can't build statically linked for mips64.

### ISSUE THREAD

**Issue by hamid-elaosta** [jedisct1/dnscrypt-proxy#458]
I am attempting to build a statically linked dnscrypt-proxy natively for mips64, not cross-compiling.

I have made several attempts to configure for static even modifying the makefile but it insists on picking up a dynamically linked libsodium.

What changes/flags are required to build this with all statically linked dependencies natively on mips64?

**Comment by rampageX** [comment]
#dnscrypt-proxy
    LDFLAGS='-Wl,-static -static -static-libgcc -s -Wl,--gc-sections' ./configure --prefix=/opt
    make -j2

    #1.7.0
    LDFLAGS='-Wl,-static -static -static-libgcc -s' ./configure --prefix=/opt --with-included-ltdl
    make -j2

**Comment by jedisct1** [comment]
Thank you, Rampage!
