### ISSUE TITLE
no way to have a clean exit

### ISSUE THREAD

**Issue by jaromil** [jedisct1/dnscrypt-proxy#459]
hi there, thanks for this fine software! at dyne/dowse we are writing a rather complex plugin, also using ldns, and all goes very well. I have only one issue to raise: there is no way to send a command for a "clean exit" to dnscrypt-proxy, signals do not seem to be trapped, both in daemon and foreground mode, as the host does not execute the destructors for the plugin.

The issue is particularly visible when debugging with valgrind, since a clean exit would definitely show if there are any buffers left unfree'd.

Am I missing something here? Do anyone has thought about this, are there desirable approaches already? My first try would be to trap some signals in the host application.

**Comment by jaromil** [comment]
...or am I supposed to trap the TERM signal in my own plugin code, receiving it from src/proxy/pid_file.c:L57 ?

**Comment by jedisct1** [comment]
You are correct, signals aren't caught. Usually not an issue for the service itself, but plugins may indeed have different requirements.
I'll try to fix this shortly. Thanks for pointing this out!

**Comment by jaromil** [comment]
Hi there, if you don't have time for this, I'm glad to help. A pointer about the best practice for this intervention would be welcome, but not needed, in case you are open to accept a PR on the issue.

**Comment by jedisct1** [comment]
Sorry for the delayed response.

Pull requests are always welcome! But I'll look at it as soon as possible.

**Comment by jedisct1** [comment]
Done!

**Comment by jaromil** [comment]
many thanks! keep up the good work!

**Comment by jaromil** [comment]
can you point out a reference, in which commit this was done? I can't find it. 10x

**Comment by jaromil** [comment]
actually after close look I can confirm this fix was never made.
