### ISSUE TITLE
can't reinstall on windows 10 ? 

### ISSUE THREAD

**Issue by fyulon** [jedisct1/dnscrypt-proxy#460]
i alredy do the dnscrypt-proxy.exe --uninstall command and after i do the new install command it says 
![ss 2016-09-13 at 09 59 26](https://cloud.githubusercontent.com/assets/22175033/18478966/668f7d5a-79fd-11e6-9136-8fc56e69ad04.png)
pretty sure i alredy remove the old one , and i can't unistall again ... unable to uninstall . 
if it by any chance still installed , is there any other way to uninstall ?

**Comment by KrasnayaPloshchad** [comment]
I have tried to create a BAT file to uninstall and then I can install via dnscrypt-winclient

**Comment by jedisct1** [comment]
Is it in an elevated command prompt? Are you sure the service is still installed?

**Comment by KrasnayaPloshchad** [comment]
> I have tried to create a BAT file to uninstall and then I can install via dnscrypt-winclient (I usually install/uninstall the service via this client)

I have not use VPN yet, but I encountered this issue a few times when I install it. To resolve it, I write a BAT file along with main program:
```
@echo off
dnscrypt-proxy.exe --uninstall
```
Then I run this file when I found dnscrypt-proxy in unable to install the servise, and I get resolved.

**Comment by fyulon** [comment]
thanks  krasnaya it works. yeah i pretty sure i do it the way you told me to unistall the dnscrypt jedisct .

**Comment by KrasnayaPloshchad** [comment]
It seems to me that dnscrypt-proxy does not quit cleanly at that time.
