### ISSUE TITLE
Is there a way to use ipset lists along with ldns_blocking plugin?

### ISSUE THREAD

**Issue by morfikov** [jedisct1/dnscrypt-proxy#461]
`ldns_blocking` plugin has an option to specify a file where you have listed some banned IPs. I'm using mostly sets of `ipset` to block IP addresses and some tools can even resolve DNS names and add their IP to that list with a specified timeout, which is useful when you want to block yt or fb. So is there a way to connect `ipset` lists with `dnscrypt-proxy`?

**Comment by jedisct1** [comment]
If your `ipset` list is just a list of IP, you should be able to use it as-s with the `ldns_blocking` plugin.
If the list is already present, and you need to extract the IPs it contains, `ipset list` should do it.
