### ISSUE TITLE
Is it possible to make DNSCrypt for Android works with x86 processor?

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jedisct1/dnscrypt-proxy#465]
The current version of DNSCrypt for Android is only complied for ARM processor. But there is some x86 devices uses Android, and some people have made Android run on x86 devices ([Android-x86](https://en.wikipedia.org/wiki/Android-x86)), thus making DNSCrypt has limited usage.

**Comment by jedisct1** [comment]
The `dist-build/android-x86.sh` and `dist-build/android-x86-64.sh` build scripts (also present in libsodium) are available for that purpose.

Pre-built binaries are not available because running Android on x86 is still relatively rare.
