### ISSUE TITLE
No "etc/rc.local" in Ubuntu 16.10

### ISSUE THREAD

**Issue by kensfc-23** [jedisct1/dnscrypt-proxy#466]
Hello Frank

I'm a linux user (Ubuntu). I've been using dnscrypt-proxy for a long time. English is not my mother tongue.

I do so in Ubuntu 16.04:

sudo adduser --system --quiet --home /run/dnscrypt --shell /bin/false --group --disabled-password --disabled-login dnscrypt

... and then I write this in the "etc/rc.local" file:

mkdir /run/dnscrypt

sudo dnscrypt-proxy --daemonize --ephemeral-keys --resolver-name=dnscrypt.org-fr --local-address=127.0.0.2 --user=dnscrypt

Sadly there is no "etc/rc.local" in Ubuntu 16.10 ... What can I do?

Thanks for the help

**Comment by licaon-kter** [comment]
Make one yourself:
```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

/usr/local/sbin/dnscrypt-proxy --ephemeral-keys --resolver-name=... --local-address=... --resolvers-list=/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv --daemonize

exit 0
```

and `sudo chmod 755 /etc/rc.local`

PS: be sure to specify full path to dnscrypt-proxy ;)

**Comment by kensfc-23** [comment]
I'm a normal linux-user ... No hacker :-)

I don't know what you mean with "be sure to specify full path to dnscrypt-proxy" :-)

I would like to use my "etc/rc.local" file and a different user. Not the root-user

Ubuntu 16.10 will be released in october. I think I'll wait till there is a tutorial somewhere in internet.

Thank you for your help :-)

**Comment by licaon-kter** [comment]
You need to setup this as root, to be able to use port 53 (which is below 1024), there is no user-specific rc.local.

Full path means `/usr/local/sbin/dnscrypt-proxy` (or whatever is your path where you put it) versus `dnscrypt-proxy`, else on start it might not be found and hence not executed.
