### ISSUE TITLE
DNSCrypt Failures

### ISSUE THREAD

**Issue by Bl2c5FlA9** [jedisct1/dnscrypt-proxy#469]
I am experiencing several issues with DNSCrypt.  It is running on OSX 10.11.6 - fully updated.

1. Connection to the automatically selected DNS server is lost and never re-establishes unless I manually go choose a new DNS server. Often even that fails.  This happens frequently - at least once per day, sometimes many times per day.  Despite having DNSCrypt installed and running most of the time it is not in effect.

2. Many returns given from a Google Search are not accessible!  If I turn off DNSCrypt I can easily get to the applicable Website.  These are very common Websites that have been in operation for many years.

3. For Websites I can get to if I attempt to invoke a link from the Home page the operation fails.  This is especially prevalent if it is a Website that requires the user to Login.  The Login link does not function.  If you put the Browser in Debug mode you immediately see that the Login link cannot be resolved.  As soon as DNSCrypt is turned off then the Website works fine.

These issues add up to DNSCrypt being an impediment, not a benefit.  DNSCrypt used to be very reliable.  But over the last year it has become a severe impediment to getting anything done.

**Comment by jedisct1** [comment]
Hi,

Sorry to hear that you are having issues resolving some DNS names in a setup involving DNSCrypt.

DNSCrypt is a protocol, not a product. Are referring to the `dnscrypt-proxy` client? How did you install it and how are you starting it?

Are you using a VPN at the same time?
