### ISSUE TITLE
Reliance on dnsapi.dll in Windows 7 and 10

### ISSUE THREAD

**Issue by Itsnothectic** [jedisct1/dnscrypt-proxy#470]
I am trying to point the windows update hostnames to only one IP each so I can whitelist them on my firewall, otherwise they will be quite random occasionally breaking firewall whitelists.

I have tried removing and also editing out the hosts from dnsapi.dll.

Some example hosts for windows 10:
go.microsoft.com (telemetry, thankfully this can be blocked in DNSCrypt despite existing in dnsapi.dll)
sls.update.microsoft.com (for windows update)

Windows 7:
ds.download.windowsupdate.com (for windows update).

Some furthur reading here from a long time ago: https://slashdot.org/story/06/04/16/1351217/microsoft-bypasses-hosts-file
Do not overlook the small text at the top of the thread there which contains a link to www.securityfocus.com.

If I delete dnsapi.dll Firefox crashes.

If I hex edit-out the hostnames from dnsapi.dll(it is not signed surprisingly, at least not in Windows 7). The hostnames do not resolve at all.

I have DNS Client service disabled and using exclusivly DNS Crypt with no other adapters but loopback.

I would like DNSCrypt to either make irrelevant the feature Microsoft has had with forced hostname resolution or for DNSCrypt to have a plugin which acts as its own high priority hosts file which can bypass the windows crap.

**Comment by licaon-kter** [comment]
This may fail anyway since they certainly use multiple hosts/IPs/load balancing/etc.

**Comment by Opensourcecommunitydevelopment** [comment]
in win10 it is signed sha256 but expires in 18.11.2016!
you could pass the connection with hostnames to socks5 firewalled, and make whitelist rules by hostname instead of ip... proplem solved.

**Comment by jedisct1** [comment]
Note that `unbound` can serve the IP addresses you want for specific names. Most other DNS caches can probably do the same thing. That's way cleaner and more reliable than deleting DLLs.
