### ISSUE TITLE
add custom DNS server

### ISSUE THREAD

**Issue by Joe-Ming** [jedisct1/dnscrypt-proxy#473]
hello.
Thenks for this project.
How to add a custom DNS server, and start use it ?

**Comment by licaon-kter** [comment]
Just add an entry to `dnscrypt-resolvers.csv` and then reference it by name.

**Comment by Joe-Ming** [comment]
ok...  
what software to use on server side ?

**Comment by Opensourcecommunitydevelopment** [comment]
dnscrypt wrapper on any dns server software!

but you can also add it parameters for future csv list updating

**Comment by Joe-Ming** [comment]
i install BIND on windows, now to protect connections from my pc and DNS server?

**Comment by jedisct1** [comment]
Hi @Joe-Ming ,

Client-side, you can indeed modify the CSV file, or create a new one, or directly pass the required parameters using `--provider-name`, `--provider-key` and `--resolver-address`.

Server-side, the opensource implementations I am aware of are [dnscrypt-wrapper](https://github.com/cofyc/dnscrypt-wrapper) and [dnsdist](http://dnsdist.org/).
The easiest way to get started is probably to use the [dnscrypt docker image](https://github.com/jedisct1/dnscrypt-server-docker).

These unfortunately don't work on Windows as far as I know.

**Comment by Joe-Ming** [comment]
@jedisct1 thanks, very thanks..
for informations.

**Comment by Opensourcecommunitydevelopment** [comment]
dnscrypt-wrapper on server dnscrypt-proxy on client

**Comment by jedisct1** [comment]
Hi Joe-Ming,

The server is indeed only designed to run on Linux.

So if you want to use it on Windows, you need to run a Linux virtual machine.

**Comment by KrasnayaPloshchad** [comment]
> The server is indeed only designed to run on Linux.

Recently Microsoft provided Bash on Ubuntu on Windows (also known as Windows Subsystem for Linux) for Windows 10, does it works with server client?

**Comment by jedisct1** [comment]
Last time I checked, the Linux subsystem for Windows didn't support networking :(

**Comment by Joe-Ming** [comment]
да я тоже думаю, надо поднимать резольвер из под линукс....
