### ISSUE TITLE
Unable to retrieve server certificates

### ISSUE THREAD

**Issue by WeirdConnection** [jedisct1/dnscrypt-proxy#480]
I hope this is the right place to post this:

I've set up DNSCrypt, dnscrypt-loader and unbound on Ubuntu Studio 16.04.1. unbound seems to be working without dnscrypt, but I can't open any site when I try to use it with dnscrypt.

DNSCrypt-loader configurations:
`cChroot="dnscrypt"

cPrimaryIP="127.0.1.2"
cPrimaryPort="5351"

cSecondaryIP="127.0.1.2"
cSecondaryPort="5352"

cProxyBaseDir="/usr/local/sbin/"
cProxyBaseName="dnscrypt-proxy"
cProxyApp="$cProxyBaseDir$cProxyBaseName"

cCSVBaseDir="/usr/local/share/dnscrypt-proxy/"
cCSVBaseName="dnscrypt-resolvers.csv"
cCSVFile="$cCSVBaseDir$cCSVBaseName"

cSIGBaseDir="/usr/local/share/dnscrypt-proxy/"
cSIGBaseName="dnscrypt-resolvers.csv.minisig"
cSIGFile="$cSIGBaseDir$cSIGBaseName"

cDaemon="$cProxyApp --daemonize "
cLocalAddress1="--local-address=$cPrimaryIP:$cPrimaryPort "
cLocalAddress2="--local-address=$cSecondaryIP:$cSecondaryPort "
cResolverAddress="--resolver-address"
cProviderName="--provider-name"
cProviderKey="--provider-key"
cResolverList="--resolvers-list=$cCSVFile "
cUser="--user=$cChroot"
cOtherParams="--ephemeral-keys "

cCSVURL="https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv"

cSIGURL="https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv.minisig"

cDigTarget="internic.net"
cDigTries=2
cDigTime=5

cAnonymousOnly=true

cIPVersion="ipv4"

cEnableSignCheck=true

cGUI="whiptail"`

Relevant unbound configs:
`do-not-query-localhost: no

forward-zone:
  name: "."
  forward-addr: 127.0.1.2@5351`

If I set the forward-addr: 8.8.8.8, everything's working, but when I try to use dnscrypt I can't open any site. 

Here's a result of dig not using dnscrypt:
`user@Host:~$ dig google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29460
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.            IN  A

;; ANSWER SECTION:
google.com.     299 IN  A   216.58.214.206

;; Query time: 64 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Oct 03 23:38:36 CEST 2016
;; MSG SIZE  rcvd: 55`

And with dnscrypt:
`user@Host:~$ dig @127.0.1.2 -p 5351 google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.1.2 -p 5351 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached`

dnscrypt-loader status:
`DNSCrypt-proxy  Loaded instances  
  │  
  │  --- Configs ---  
  │  Running as     = dnscrypt  
  │  Anonymous only = true  
  │  Sign check     = true  
  │  IP Version     = ipv4  
  │  
  │  --- Primary DNS ---  
  │  Status         = Running [3691]  
  │  Execution time = 21:07 01:01:43 (Date days-hh:mm:ss)  
  │  Proxy IP       = 127.0.1.2:5351  
  │  Resolver IP    = 185.121.25.85  
  │  Resolver name  = 2.dnscrypt-cert.uk.d0wn.biz  
  │  Resolver test  = Dig Query Time  :  msec 

  │  --- Secondary DNS ---  
  │  Status         = Running [3862]  
  │  Execution time = 21:07 01:01:41 (Date days-hh:mm:ss)  
  │  Proxy IP       = 127.0.1.2:5352  
  │  Resolver IP    = 95.154.236.104  
  │  Resolver name  = 2.dnscrypt-cert.fvz-rec-gb-lon-03.dnsrec.meo.ws  
  │  Resolver test  = Dig Query Time  :  msec`

Also this seems to be related somehow: since I've started tinkering with the network, when I sudo, it prints `sudo: unable to resolve host Host` then prompts for my password. With certain settings it took really long to respond.

It seems like everything is fine, yet DNSCrypt not working. So I'd like your help, since I've kinda run out of ideas on how to proceed...
Thanks!

**Comment by jedisct1** [comment]
Hi,

I'm not familiar with that script, but apparently, it's starting a proxy that listens to `127.0.1.2:5351`.

Does it work if you send queries directly to that proxy? eg:

```bash
hostip -r 127.0.0.1:5351 example.com
```

Do you get an IP address back?

**Comment by WeirdConnection** [comment]
Hi!

Nope, it just times out..
Btw, is there some config file, I can manually check / edit? Maybe dnscrypt-loader doesn't do it's job correctly.

**Comment by jedisct1** [comment]
So it means that dnscrypt is not even running.

Maybe `dnscrypt-loader` didn't properly install it. What distribution are you using? Doesn't it have an official dnscrypt-proxy package?

**Comment by WeirdConnection** [comment]
Ubuntu Studio 16.04.1
dnscrypt-proxy 1.7.0
dnscrypt-loader 1.2

I installed them manually. Now, that you mentioned, I've found a dnscrypt-proxy 1.6.1-1 package. So I'll try that, and report back with my findings.

In the meantime here's the last 4 lines from syslog concerning dnscrypt-proxy:
```
Oct 10 11:16:41 Host dnscrypt-proxy[2774]: Refetching server certificates
Oct 10 11:16:51 Host dnscrypt-proxy[3249]: Refetching server certificates
Oct 10 11:16:56 Host dnscrypt-proxy[2774]: Unable to retrieve server certificates
Oct 10 11:17:06 Host dnscrypt-proxy[3249]: Unable to retrieve server certificates
```
It is logged every 5 minutes, with some few hour gaps. What's interesting is that the latest is 10days old, yet dnscrypt-loader reported that dnscrypt-proxy is running. Also the latest syslog records about dnscrypt-loader are form Oct 9th. Yet I have these lines in crontab, which should "Download from official source, performs signature check and updates the resolvers.csv file" and "Load DNSCrypt-proxy using a resolver randomly choosed by DNSCrypt-loader" respectively:
```
@reboot root exec /usr/local/sbin/dnscrypt-loader -u
@reboot root exec /usr/local/sbin/dnscrypt-loader -r
```
Obviously, I have booted since then.

**Comment by WeirdConnection** [comment]
Nvm the last part. (Seems like grep stopped parsing syslog after a few thousand lines.) Anyway, here are the lines from last boot:
```
Oct 20 18:56:27 Host CRON[1428]: (root) CMD (root exec /usr/local/sbin/dnscrypt-loader -r)
Oct 20 18:56:27 Host CRON[1427]: (root) CMD (root exec /usr/local/sbin/dnscrypt-loader -u)
Oct 20 18:56:58 Host dnscrypt-loader: Loading /usr/local/sbin/dnscrypt-proxy
Oct 20 18:56:58 Host dnscrypt-loader: Restoring previous dnscript-loader session
Oct 20 18:56:58 Host dnscrypt-loader: Loading primary /usr/local/sbin/dnscrypt-proxy success.
Oct 20 18:57:09 Host dnscrypt-loader:  DNSCrypt-proxy  Loaded instances
Oct 20 18:57:09 Host dnscrypt-loader:  --- Configs ---
Oct 20 18:57:09 Host dnscrypt-loader:  Running as     = dnscrypt
Oct 20 18:57:09 Host dnscrypt-loader:  Anonymous only = true
Oct 20 18:57:09 Host dnscrypt-loader:  Sign check     = true
Oct 20 18:57:09 Host dnscrypt-loader:  IP Version     = ipv4
Oct 20 18:57:09 Host dnscrypt-loader:  --- Primary DNS ---
Oct 20 18:57:09 Host dnscrypt-loader:  Status         = Running [2877]
Oct 20 18:57:09 Host dnscrypt-loader:  Execution time = 18:56 00:00 (Date days-hh:mm:ss)
Oct 20 18:57:09 Host dnscrypt-loader:  Proxy IP       = 127.0.1.2:5351
Oct 20 18:57:09 Host dnscrypt-loader:  Resolver IP    = 37.235.49.61
Oct 20 18:57:09 Host dnscrypt-loader:  Resolver name  = 2.dnscrypt-cert.is.d0wn.biz
Oct 20 18:57:09 Host dnscrypt-loader:  Resolver test  = Dig Query Time  :  msec
Oct 20 18:57:09 Host dnscrypt-loader:  --- Secondary DNS ---
Oct 20 18:57:09 Host dnscrypt-loader:  Status         = Stopped []
Oct 20 18:57:09 Host dnscrypt-loader:  Execution time =   (Date days-hh:mm:ss)
Oct 20 18:57:09 Host dnscrypt-loader:  Proxy IP       =
Oct 20 18:57:09 Host dnscrypt-loader:  Resolver IP    =
Oct 20 18:57:09 Host dnscrypt-loader:  Resolver name  =
Oct 20 18:57:09 Host dnscrypt-loader:  Resolver test  =
Oct 20 18:57:09 Host dnscrypt-loader: Loading secondary /usr/local/sbin/dnscrypt-proxy success.
Oct 20 18:57:30 Host dnscrypt-loader:  DNSCrypt-proxy  Loaded instances
Oct 20 18:57:30 Host dnscrypt-loader:  --- Configs ---
Oct 20 18:57:30 Host dnscrypt-loader:  Running as     = dnscrypt
Oct 20 18:57:30 Host dnscrypt-loader:  Anonymous only = true
Oct 20 18:57:30 Host dnscrypt-loader:  Sign check     = true
Oct 20 18:57:30 Host dnscrypt-loader:  IP Version     = ipv4
Oct 20 18:57:30 Host dnscrypt-loader:  --- Primary DNS ---
Oct 20 18:57:30 Host dnscrypt-loader:  Status         = Running [2877]
Oct 20 18:57:30 Host dnscrypt-loader:  Execution time = 18:56 00:11 (Date days-hh:mm:ss)
Oct 20 18:57:30 Host dnscrypt-loader:  Proxy IP       = 127.0.1.2:5351
Oct 20 18:57:30 Host dnscrypt-loader:  Resolver IP    = 37.235.49.61
Oct 20 18:57:30 Host dnscrypt-loader:  Resolver name  = 2.dnscrypt-cert.is.d0wn.biz
Oct 20 18:57:30 Host dnscrypt-loader:  Resolver test  = Dig Query Time  :  msec
Oct 20 18:57:30 Host dnscrypt-loader:  --- Secondary DNS ---
Oct 20 18:57:30 Host dnscrypt-loader:  Status         = Running [3150]
Oct 20 18:57:30 Host dnscrypt-loader:  Execution time = 18:57 00:10 (Date days-hh:mm:ss)
Oct 20 18:57:30 Host dnscrypt-loader:  Proxy IP       = 127.0.1.2:5352
Oct 20 18:57:30 Host dnscrypt-loader:  Resolver IP    = 176.56.237.171
Oct 20 18:57:30 Host dnscrypt-loader:  Resolver name  = 2.dnscrypt-cert.resolver1.dnscrypt.eu
Oct 20 18:57:30 Host dnscrypt-loader:  Resolver test  = Dig Query Time  :  msec
```
```
Oct 20 18:56:58 Host dnscrypt-loader: Loading /usr/local/sbin/dnscrypt-proxy
Oct 20 18:56:58 Host dnscrypt-proxy[2877]: Starting dnscrypt-proxy 1.7.0
Oct 20 18:56:58 Host dnscrypt-proxy[2877]: Ephemeral keys enabled - generating a new seed
Oct 20 18:56:58 Host dnscrypt-proxy[2877]: Done
Oct 20 18:56:58 Host dnscrypt-loader: Loading primary /usr/local/sbin/dnscrypt-proxy success.
Oct 20 18:57:09 Host dnscrypt-proxy[3150]: Starting dnscrypt-proxy 1.7.0
Oct 20 18:57:09 Host dnscrypt-proxy[3150]: Ephemeral keys enabled - generating a new seed
Oct 20 18:57:09 Host dnscrypt-proxy[3150]: Done
Oct 20 18:57:09 Host dnscrypt-loader: Loading secondary /usr/local/sbin/dnscrypt-proxy success.
Oct 20 18:57:13 Host dnscrypt-proxy[2877]: Unable to retrieve server certificates
Oct 20 18:57:14 Host dnscrypt-proxy[2877]: Refetching server certificates
Oct 20 18:57:24 Host dnscrypt-proxy[3150]: Unable to retrieve server certificates
Oct 20 18:57:25 Host dnscrypt-proxy[3150]: Refetching server certificates
Oct 20 18:57:29 Host dnscrypt-proxy[2877]: Unable to retrieve server certificates
Oct 20 18:57:32 Host dnscrypt-proxy[2877]: Refetching server certificates
```

**Comment by jef-00** [comment]
i have this problem too

**Comment by jedisct1** [comment]
`Unable to retrieve server certificates` means that the initial query to the server failed.

This initial query doesn't even use DNSCrypt at all; it's a standard DNS query.

Maybe the server information is out of date. Or the server doesn't work any more at the moment. Or you have a firewall blocking DNS queries (regular queries, to port 53, using UDP).
