### ISSUE TITLE
1.7.0 ceased to work on Android 4.0

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jedisct1/dnscrypt-proxy#484]
When I try to run DNSCrypt on Android 4.0, it always show `FIX ME!` notice firstly and then notice `Segmentation fault` continously. [BusyBox](https://apkpure.com/busybox/ru.meefik.busybox) has already installed.

![screenshot_2016-10-11-23-59-50](https://cloud.githubusercontent.com/assets/10364351/19303695/3f5c93fc-909c-11e6-9352-e6dcc9526a4f.png)

**Comment by jedisct1** [comment]
`dnscrypt-proxy` doesn't seem to be explicitly using that function anywhere in the code.

Did it work with previous versions of the proxy? Maybe this is due to increasing the SDK version.

In any case, I don't think we can reasonably keep supporting Android 4 which is really really old now.

**Comment by KrasnayaPloshchad** [comment]
OK I got v1.6.1 to run, then it give me `FIX ME!` notice again, the content look the same, but have additional information `iptables: No chain/target/match by that name.` Finally show me `Segmentation fault` once and quit.

**Comment by jedisct1** [comment]
Unfortunately I don't think we can support Android 4, especially since testing it on a real device becomes difficult.
Would it be possible for you to use something more recent, if only by using Cyanogen or another Mod?

**Comment by itsKV** [comment]
is there any .apk package available to install directly on android v5.0 and above which should listen on port 53 so that, by using my android phone as a dedicated wifi router, I should be able to use this phone as on the go DNS encryptor as well as mobile router? 
I think, just to listen on port does not need root access. Am I correct?

**Comment by licaon-kter** [comment]
Yes and no, yes you can listen to a port without root, no you can't listen on ports <1024.

You need to setup something like this: https://github.com/jedisct1/dnscrypt-proxy/issues/393#issuecomment-204802390

**Comment by morfikov** [comment]
@jedisct1, I just tested 1.7.0 on Android 5.1, and it looks like it works just fine, so I think the 4.0 is to old. I have one question though. Why isn't dnscrypt-proxy available in Google Play? Is there a way to add it there? If not, would you consider adding it at least to the [F-Droid repository](https://f-droid.org/)?

**Comment by KrasnayaPloshchad** [comment]
@morfikov I think add a frontend to F-Droid is enough.

**Comment by KrasnayaPloshchad** [comment]
@morfikov I found an app to tun dnscrypt-proxy
https://play.google.com/store/apps/details?id=com.okirat.dnsmanager
This app has an option to run DNSCrypt, but has very limited function to configure.

**Comment by morfikov** [comment]
I've seen that app, but since it requires the root access and is not OpenSource, I'm not going to install it. That's my rule.

**Comment by KrasnayaPloshchad** [comment]
@morfikov OK I agree with you, I think create a full featured frontend app release to F-Droid would be better.

**Comment by licaon-kter** [comment]
See my post above, follow the link and read: it's a bit more complicated without root, you want to control the connection flow ( local VPN like NetGuard), then re-route DNS requests to another app (say Unbound) that forward DNS requests to a running dncrypt-proxy instance.

**Comment by morfikov** [comment]
Actually it's not about root or not root. The dnscrypt-proxy app isn't available in Google Play or F-Droid repo, which is a little bit inconvenient to install it. I can set it up without a problem on my phone, but I have to manually download the zip file and do the other stuff. I'm just asking to add the app to the Google Play or F-Droid repo, that's all.

**Comment by KrasnayaPloshchad** [comment]
Currently I run dnscrypt-proxy via BusyBox + Kernel Adiotur + DNS Forwarder, but I think using a client apk performenced as [dnscrypt-winclient](https://github.com/Noxwizard/dnscrypt-winclient) is better.

**Comment by licaon-kter** [comment]
see
https://github.com/smarek/android-unbound-dns/issues/18
