### ISSUE TITLE
dnscrypt resets dns settings to modem defaults

### ISSUE THREAD

**Issue by consoflight** [jedisct1/dnscrypt-proxy#486]
Hello,

I have been using dnscrypt for years without an issue until now. I updated to the latest version and when I enable dnscrypt, it changes the current dns settings to the modems default settings and stays in 'not using DNSCrypt' status.

I'm on mac osx 10.11.6

What could be doing this, any ideas?

Cheers!

**Comment by jedisct1** [comment]
Hi,

Looks like this bug report is not for this project. There is nothing that changes DNS settings or that says "not using DNSCrypt" in dnscrypt-proxy.

Maybe you are using https://simplednscrypt.org/  or https://github.com/alterstep/dnscrypt-osxclient ?
