### ISSUE TITLE
DNScrypt not enabled

### ISSUE THREAD

**Issue by kevinwahyudi** [jedisct1/dnscrypt-proxy#487]
DNScrypt not enabled even after enabling it.
installed using GUI osx installer dmg file, on OSX 10.12

![screen shot 2016-10-26 at 1 16 46 pm](https://cloud.githubusercontent.com/assets/2149365/19715332/a2c69874-9b7e-11e6-83a7-873356ee3ab5.png)

**Comment by jedisct1** [comment]
Wrong project.

I think this screenshot is from https://github.com/alterstep/dnscrypt-osxclient
