### ISSUE TITLE
Yes, Ipredator supports DNSSEC

### ISSUE THREAD

**Issue by sergeevabc** [jedisct1/dnscrypt-proxy#489]
Official website of [Ipredator states](https://beta.ipredator.se/page/services#service_dns) its resolvers support DNSSEC.
Action required: [update resolvers list](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv), put “yes” into column “DNSSEC validation”.

**Comment by jedisct1** [comment]
Updated, thanks!
