### ISSUE TITLE
DNS Override on IOS rebuild integrating DNSCrypt without Jailbreak

### ISSUE THREAD

**Issue by holderad** [jedisct1/dnscrypt-proxy#490]
Recommend you contact developer of DNS Override on iOS. Cleverly uses internal VPN on demand to Override DNS on both WiFi and cellular carriers.

App is hampered by some (bastard) ISPs intercepting DNS traffic and overriding at their server. Effectively overriding "the Override."

DNSCrypt integration (along with DNSSEC) into the internal VPN of the App could eliminate this intrusion.

**Comment by tomaszkoperski** [comment]
Hi holderad, I'm one of the founders of DNS Override app. Just reached this place after the message I got from you (thanks btw!). We are looking into the possibility of including DNSCrypt in DNS Override app. I'll try to contact the developers for further information.

**Comment by holderad** [comment]
Awesome!
You can charge for the feature. Just wanted to get it on your development map!

You have an awesome app and are out in front! Just want you to stay that way!

Dr. Allen D. Holder
holderad@mac.com
(210) 391-0320

On Oct 28, 2016, at 11:54 AM, Tomasz Koperski <notifications@github.com> wrote:

Hi holderad, I'm one of the founders of DNS Override app. Just reached this place after the message I got from you (thanks btw!). We are looking into the possibility of including DNSCrypt in DNS Override app. I'll try to contact the developers for further information.

**Comment by jedisct1** [comment]
Awesome news.

Are you gonna use the `NEAppProxyProvider` extension for this?

Lemme know if there is anything I could do in order to help.
