### ISSUE TITLE
Does not work? Or doesn't help against ISP blocking blacklisted sited via DNS spoofing?

### ISSUE THREAD

**Issue by Drugoy** [jedisct1/dnscrypt-proxy#491]
I live in a shitty country where out government decided to censor internet by restricting access to some sites.
Many ISPs don't just drop the packets addressed to the site when requesting the site by its hostname or IP, instead they redirect you onto a page saying that the access to that site is restricted by law blah-blah.

I thought that dnscrypt is supposed to help in that case, since ISP doesn't drop the packets addressed to those sites, it just does that spoofing. dnscrypt was advertised as it does help in such case (not on your site, but in the articles on IT-related sites)

But the fact is that it doesn't.
I still can't visit those sites.

Win7SP1x64, I've tried to use dnscrypt-proxy as just a command line tool and with both GUI clients (dnscrypt winclient and Simple DnsCrypt).
I've tried using different resolvers.
I've tried flushing DNS cache (ipconfig /flushdns). I've tried restarting browsers afterwards.
Nothing helps.

**Comment by Drugoy** [comment]
Just read another closed issue which explains why dnscrypt is useless against ISP censure.

**Comment by jedisct1** [comment]
> dnscrypt was advertised as it does help in such case (not on your site, but in the articles on IT-related sites)

Looks like you answered your own question.

If your ISP is redirecting connections to a list of blacklisted IPs, there's nothing dnscrypt can do for you. A VPN might be better a choice.
