### ISSUE TITLE
Problem DNS 127.0.0.1 (Windows 10 x64)

### ISSUE THREAD

**Issue by AlexBO222** [jedisct1/dnscrypt-proxy#492]
Hello. I have a problem. Install and test DNSCrypt, everything works, the server passes the test. As soon as I change DNS to 127.0.0.1, all the addresses are not recognized (the system does not see 127.0.0.1 as the DNS server, and does not send requests through it).

Six months ago, it worked, but now is not.
Installed Windows 10 x64.
Tried all versions DNSCrypt and SimpleDNSCrypt - the problem is that DNS requests are coming in DNSCrypt service if I change the DNS for your network card to 127.0.0.1.
I tried to put a local address of the PC (192.168.0.5) in the service DNSCrypt and DNS network card - the same questions are not recognized as DNS.

Please help me.

**Comment by mausspb** [comment]
What is srv you use ? 
Try update resolve.csv and select other provider dns ( i have seems problem with d0wn-ru-ns1 ).

**Comment by AlexBO222** [comment]
**mausspb**
DNS proxy server working. Windows does not recognize the DNSCrypt as DNS - to 127.0.0.1 are not sent to queries as DNS server.

**Comment by degski** [comment]
Hi, just would like to signal I have the same issue (and same setup/tested with firewall off, just to avoid issues with that) as AlexBO222. What does work though is the original DNSCrypt from OpenDNS https://github.com/opendns/dnscrypt-win-client .

**Comment by KrasnayaPloshchad** [comment]
What happened if you try [this client](https://github.com/Noxwizard/dnscrypt-winclient)?

**Comment by AlexBO222** [comment]
> What happened if you try this client?

I tried all clients (and even private) - the result is the same. The client is not guilty - the operating system is blocking DNS queries for this program, when installed in the system. Exactly where and how locked - can not find.

**Comment by jedisct1** [comment]
I don't think the operating itself can be responsible for that behavior, unless you are running some very unique version of Windows.

Are you running some firewall, antivirus, or hypervisor?

**Comment by AlexBO222** [comment]
Windows 10 Pro x64 Russian (build 1607)
Kaspersky KIS 17.0.0.611
4 PCs with the same systems and antivirus software, but different on the iron - on all blocked DNSCrypt.

**Comment by KrasnayaPloshchad** [comment]
WTF, that is so Russian. Maybe we need to contact Kaspersky Lab. for why they block DNSCrypt.

**Comment by licaon-kter** [comment]
@AlexBO222 Add your voice here: https://forum.kaspersky.com/index.php?showtopic=355020 and here: https://forum.kaspersky.com/index.php?showtopic=355127

**Comment by AlexBO222** [comment]
> licaon-kter

Thank you. I will try, as suggested in the topic for the second link.

**Comment by AlexBO222** [comment]
>  KrasnayaPloshchad
The problem is deeper. When installing KIS system modifies. If you unload the KIS, DNSCrypt not work anyway.

**Comment by licaon-kter** [comment]
Unload means uninstall? If not, what happens if you uninstall it completely and reboot?

**Comment by AlexBO222** [comment]
Not uninstall. Only unload. If back to 2016 version KIS - DNSCrypt ok.

**Comment by degski** [comment]
The KIS discussion is a red-herring, I have no (as in none) AV installed and DNSCrypt doesn't work. As said, by the OP and by me in the above, as soon as one changes the proxy settings to 127.0.0.1, it stops working. A thought: "Does the port (53, which one CANNOT specify) prevent this?"

**Comment by AlexBO222** [comment]
> degski 

Maybe you are right. Can the OS itself does not run other applications at the 53rd port. I did roll back to the previous point (when the KIS was installed 2016 version), but the operating system has to this point no other current updates. Perhaps in the new updates to the windose 10 (x64) made such a ban.

**Comment by licaon-kter** [comment]
@degski You need an actual app to listen on port 53, else Windows won't use it as as a DNS server, that's not an issue.

Does SimpleDNScrypt fail too?

**Comment by degski** [comment]
@licaon-kter "Does SimpleDNScrypt fail too?" No, it works. Tested here: http://www.openresolver.com/?ip=212.47.228.136 , which gives me "Recursive resolver is not detected on 212.47.228.136", which seems to be the "correct" answer, if things are set up properly and work correctly.

How can one (if one can) specify port 53, surely there must be a way (so I won't need an app)?

**Comment by licaon-kter** [comment]
Specify 53 where? What for? 

Do read a bit more about how DNS works, this is the basic stuff: server needs to listen on port 53, clients only connect to port 53. (it does not matter if client and server are actually the same machine)

If SimpleDNSCrypt works then just use it.

Use these sites to verify that only the selected server is used: https://github.com/jedisct1/dnscrypt-proxy/issues/393

**Comment by jedisct1** [comment]
`openresolver.com` checks that a public resolver is running on a public IP address.

This is very unlikely to be what you want.

Use one of the sites listed by @licaon-kter or run that command:

```sh
hostip resolver.dnscrypt.org
```

It will return the IP address of the resolver you are actually using, and it should match the DNSCrypt rseolver you chose (you can use http://iptoasn.com/ to check its name if you need to).

**Comment by degski** [comment]
@jedisct1 and @licaon-kter Alright guys, stop shouting! No, you both were right, it didn't work (checked with https://dnsleaktest.com/), up till now. One (apparently) still has to manually set the dns-server to 127.0.0.1 in the IP4 settings of the network adaptor. After doing this, dnsleaktest.com returned the address/ip of the dns-server I picked. Thanks to all of you, resolving (pun intended) this issue!

**Comment by licaon-kter** [comment]
@degski That's a given, I mean setting up manually.

**Comment by AlexBO222** [comment]
In my case, no matter what sites I can not go after the installation of 127.0.0.1, and nothing I can not check - so there is no DNS server on your PC. DNSCrypt works, but the OS does not let him as a DNS server and says I do not have a PC desktop DNS server, and anywhere I can not enter.

**Comment by pepoluan** [comment]
@AlexBO222 you using Windows 10? Have you allowed Incoming traffic to TCP port 53 and UDP port 53 in "Windows Firewall with Advanced Security"?

I have to personally add rules to allow Incoming traffic to those two ports before dnscrypt-proxy works.

**Comment by AlexBO222** [comment]
All Windows Security - OFF. KIS 2017 manages all security windows 10. The KIS has no such settings in your firewall.

**Comment by jedisct1** [comment]
Maybe KIS hijacks DNS queries. This is probably something you should discuss on a Kaspersky support forum.
