### ISSUE TITLE
DNS in Russia d0wn-ru-ns1 not working

### ISSUE THREAD

**Issue by mausspb** [jedisct1/dnscrypt-proxy#493]
DNS srv -  **d0wn-ru-ns1**
System - openwrt
SRV - connected, key pair - ok, but ip not resolve (
`forwarded www.google.ru to 127.0.0.1`

**Comment by jedisct1** [comment]
Maybe a temporary issue with that resolver? It seems to be resolving `www.google.ru` just fine now.
