### ISSUE TITLE
How to change local listening port on Windows?

### ISSUE THREAD

**Issue by sam1275** [jedisct1/dnscrypt-proxy#495]
Hi.
I want to have multiple resolvers available for my computer, and there's no native way to do this on Windows, so I want to try running multiple DNScryot client and listening on different port, how to set the DNScrypt to listening on port different than 53?
Thank you.

**Comment by licaon-kter** [comment]
You need something listening on port 53, so that it answers DNS queries, that thing can be some sort of caching/forwarding program like Unbound (at least on Linux) that calls many different dnscrypt-proxy instances that actually resolve addresses. You can't do that only with dnscrypt-proxy directly.

**Comment by sam1275** [comment]
Thank you, so Windows user still stuck at one resolver only?

**Comment by licaon-kter** [comment]
Nope, read this: https://stackoverflow.com/questions/29067825/windows-8-1-dnscrypt-unbound-for-dns-cache

**Comment by sam1275** [comment]
Thank you, but your link (and the Russian link inside your link) doesn't even mention multiple resolvers, they just meanly discuss how to use Unbound on windows with the Dnscrypt, but still only one resolver only.

**Comment by licaon-kter** [comment]
Add multiple
```
forward-addr: 127.0.0.2@40
forward-addr: 127.0.0.2@41
forward-addr: 127.0.0.2@42
...
```

Where you have one instance of dnscrypt-proxy running for each port, Unbound will randomly query them.

**Comment by sam1275** [comment]
Thank you, I knew that, and that's what I asked in the first post, how can I change Dnscrypt port and run multiple instance on Windows?

**Comment by jedisct1** [comment]
Unfortunately, you can't. Not on Windows.

This will change in the future, but there is only one hardcoded set of registry keys that can be used for now.
