### ISSUE TITLE
d0wn servers no longer OpenNIC resolvers?

### ISSUE THREAD

**Issue by holdit** [jedisct1/dnscrypt-proxy#496]
From dns.d0wn.biz:

> 11-04-2016
>
> Goodbye OpenNIC. Hello world.
> 
> Due some massiv problems with OpenNIC with DNSSEC I decided
> to run all DNS servers without OpenNIC tld's! The servers
> should now run more stable and faster.

Maybe we should update the `dnscrypt-resolvers.csv` file?

**Comment by jedisct1** [comment]
This is sad, but OpenNIC and DNSSEC indeed never played well together :(

The list has been updated.

Thanks for the heads up!
