### ISSUE TITLE
Can't stop listening 53 port

### ISSUE THREAD

**Issue by azgh** [jedisct1/dnscrypt-proxy#498]
I run dnscrypt-proxy 1.7.0 on my macbook with macos 10.12.1, and work with unbound together, as the guideline "Using DNSCrypt in combination with a DNS cache" I edit the unbound.conf, then lsof -i tcp:53, it show me as below:

COMMAND    PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
dnscrypt-  101  nobody    9u  IPv4 0x7ea1630480685869      0t0  TCP localhost:domain (LISTEN)
unbound   1352 nobody    4u  IPv4 0x7ea16304853fd351      0t0  TCP *:domain (LISTEN)
unbound   1352 nobody    6u  IPv6 0x7ea163047e899639      0t0  TCP *:domain (LISTEN)

so both of them listening port 53, and i don't know which one of them is working for local dns? I am confused.
Do I need stop dnscrypt to listen 53 port? and how?
thanks.

**Comment by jedisct1** [comment]
Looks like `dnscrypt-proxy` listens to port 53 on `127.0.0.1` and `unbound` listens to port 53 on other interfaces.

It might work, but I wouldn't expect that to be very reliable if the network configuration changes.

You'd better keep port 53 only for `unbound`, and configure `dnscrypt-proxy` to listen to a different port.

**Comment by jedisct1** [comment]
The `--local-address=` can be used to change the port `dnscrypt-proxy` is listening to.

For example:
`dnscrypt-proxy --local-address=127.0.0.1:54`

**Comment by azgh** [comment]
As you mentioned example, I got the message as below:

/usr/local/Cellar/dnscrypt-proxy/1.7.0/sbin/dnscrypt-proxy --local-address=127.0.0.1:54
[ERROR] Resolver information required.
[ERROR] The easiest way to do so is to provide a resolver name.
[ERROR] Example: dnscrypt-proxy -R mydnsprovider
[ERROR] See the file [/usr/local/Cellar/dnscrypt-proxy/1.7.0/share/dnscrypt-proxy/dnscrypt-resolvers.csv] for a list of compatible public resolvers
[ERROR] The name is the first column in this table.
[ERROR] Alternatively, an IP address, a provider name and a provider key can be supplied.
[ERROR] Please consult https://dnscrypt.org and the dnscrypt-proxy(8) man page for details.

So many errors. 
I had let dnscrypt listen 40 and 41 on dnscrypt.org-fr and dnscrypt.eu-nl with " -R dnscrypt.org-fr --local-address=127.0.0.1:40 --daemonize", successful, but can't stop on 53.

**Comment by licaon-kter** [comment]
> [ERROR] The easiest way to do so is to provide a resolver name.

Why won't you provide one?

Look, below for :40 you provided one, you took @jedisct1 example at face value, while it was only to show you how to change the listening port, you need to provide the resolver, daemonize and anything else that you need. The error message is pretty clear, it tells you how to do it and how where you the the resolver name from. Combine those two.

**Comment by azgh** [comment]
@licaon-kter thanks, I want to stop dnscrypt to listen 53 port and let unbound to listen 53, and I can make dnscrypt to change the listening port to other ports, but dnscrypt still listening 53.
I‘m confused on what you said, how to "combine those two"? could you please let me know detail? I will try more.
I try "dnscrypt-proxy --local-address=127.0.0.1:54", show me errors.
I try "dnscrypt-proxy dnscrypt.org-fr --local-address=127.0.0.1:54", show me errors too.
I try "dnscrypt-proxy -R dnscrypt.org-fr --local-address=127.0.0.1:54", successful, but still listening 53.
what can I try? and what you will try?

**Comment by jedisct1** [comment]
`dnscrypt-proxy -R dnscrypt.org-fr --local-address=127.0.0.1:54` is the right command.

It won't listen to port 53. If you still have something on port 53, it has to be something else. Maybe unbound, or mdnsresponder.

**Comment by azgh** [comment]
Thanks @jedisct1 , on my mac, it is really still listen 53 port after `dnscrypt-proxy -R dnscrypt.org-fr --local-address=127.0.0.1:54`, `sudo lsof -i tcp:53`, show me below:
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
dnscrypt- 101 nobody 9u IPv4 0x7ea1630480685869 0t0 TCP localhost:domain (LISTEN)
unbound 1352 nobody 4u IPv4 0x7ea16304853fd351 0t0 TCP *:domain (LISTEN)
unbound 1352 nobody 6u IPv6 0x7ea163047e899639 0t0 TCP *:domain (LISTEN)
Mybe my mac have some problem, I will try to find it.
thnaks @jedisct1 .
