### ISSUE TITLE
future is DNS over TLS

### ISSUE THREAD

**Issue by drzraf** [jedisct1/dnscrypt-proxy#500]
Future is now:
https://portal.sinodun.com/wiki/display/TDNS
Please join their effort rather than creating yet-another-protocol so that DNS-over-TLS (TCP) can be upstreamed (client/servers) and mainstreamed quickly.

**Comment by jedisct1** [comment]
DNSCrypt was created before this, and makes different tradeoffs. 

Whatever improves security is good!
