### ISSUE TITLE
Send some queries to a specific DNS server

### ISSUE THREAD

**Issue by morfikov** [jedisct1/dnscrypt-proxy#502]
There are some situations when you want to encrypt all of your DNS queries, but a few queries have to go to a specific DNS server. For instance, there's Aero2 free version, but it requires that the DNS queries go to Aero2 DNS server. If I wanted to use dnscrypt-proxy with this Aero2, I wouldn't get the CAPTCHA screen when needed, so I wouldn't be able to use the internet connection. I could use dnscrypt-proxy after typing the CAPTCHA code, but after another hour I have to switch to the Aero2 DNS server, and so on. For now I use dnsmasq to set a domain and its queries go to the Aero2 DNS server, and the rest go through dnscrypt-proxy. That's fine solution for a desktop, but on a smartphone it isn't. So I have a question. Is there a way to tell dnscrypt-proxy to send  specific domain queries to a certain DNS servers?

**Comment by jedisct1** [comment]
Nope. But the local cache sitting in front of `dnscrypt-proxy` is likely to support that. Even `dnsmasq` probably supports that.
