### ISSUE TITLE
Dense fuzzer ready to volunteer some cycles

### ISSUE THREAD

**Issue by c0nfuci05** [jedisct1/dnscrypt-proxy#504]
Greetings, I'm a dense fuzzer in space and would love to volunteer some cycles. Is the DNSCrypt team looking for a confidential third party security audit of source and applicable technologies anytime soon? I'm dense in the math. 

Contact Obi.: email: [jits3@protonmail.com](mailto:jits3@protonmail.com) and via [Surespot](https://www.surespot.me/): d4r34p3r

**Comment by jedisct1** [comment]
Bug reports are always welcome, and if you can volunteer some cycles to fuzz the proxy, this is great!
Looking forward to your findings!
