### ISSUE TITLE
Logging for domain names blocking.

### ISSUE THREAD

**Issue by DebugReport** [jedisct1/dnscrypt-proxy#508]
How can i get logs like this.
> 2015-03-06 00:00:00 (1425596400) - blocked: test.example.com *.example.com

I use this command:
> dnscrypt-proxy --resolver-name=dnscrypt.eu-dk-ipv6 --ephemeral-keys --local-address='[::1]:53' --plugin=libdcplugin_example_logging.so,/var/log/dnscrypt.log --plugin=libdcplugin_example_ldns_blocking.so,--domains=/etc/domains.list --daemonize

But in logs i see only this:
> github.com      [A]

**Comment by DebugReport** [comment]
I'm not C developer...
But maybe use code from here? https://github.com/kdave/dnscrypt-plugins

**Comment by jedisct1** [comment]
Done in bfc8170520be581fb53c19865cfa7f4b5ab79f7c
