### ISSUE TITLE
Wrong Registry Key

### ISSUE THREAD

**Issue by bitbeans** [jedisct1/dnscrypt-proxy#513]
```
dnscrypt-proxy.exe -R dnscrypt.org-fr --install
12/19/16 06:58:32 [INFO] + DNS Security Extensions are supported
12/19/16 06:58:32 [INFO] + Provider supposedly doesn't keep logs
12/19/16 06:58:32 [INFO] The [dnscrypt-proxy] service has been installed and started
12/19/16 06:58:32 [INFO] The registry key used for this service is [SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameter]
12/19/16 06:58:32 [INFO] Now, change your resolver settings to 127.0.0.1:53
```

The correct registry key should be: SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameter**s**

Tested on 2 Windows 10 systems.

**Comment by KrasnayaPloshchad** [comment]
👍

**Comment by jedisct1** [comment]
Aww crap.

f30c3e97f311307cf266b3eda071fdfcbf1b9210 should fix it.

I'm gonna tag a new release shortly.

Thanks!

**Comment by jedisct1** [comment]
1.8.1 has been released in order to fix that issue.

I'm really sorry for this stupid bug.

Thanks again for spotting and reporting it!
