### ISSUE TITLE
1.8.0 does not work on Android 4.3

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jedisct1/dnscrypt-proxy#514]
I have tried to run DNSCrypt 1.8.0 on an Android 4.3 device, but it always notice `cannot locate symbol "signal" referenced by dnscrypt "dnscrypt-proxy"` to me. After I back to 1.7.0, it works.

**Comment by jedisct1** [comment]
Thanks for reporting this.

Can you try the updated binaries?

**Comment by jedisct1** [comment]
Might be fixed by 7ce08b9f22f68e9fecda109c36980b925854e055

**Comment by KrasnayaPloshchad** [comment]
Yeah, it works for me.
