### ISSUE TITLE
Is latest release 1.8.0 or 1.8.1?

### ISSUE THREAD

**Issue by ilovezfs** [jedisct1/dnscrypt-proxy#515]
I noticed a new tag (1.8.1) was posted but not designated the latest release. Which version should we be distributing downstream in Homebrew? 1.8.0 or 1.8.1?

**Comment by jedisct1** [comment]
Hi,

1.8.1 is the latest one, but the release notes hadn't be copied on Github. Done!

**Comment by ilovezfs** [comment]
@jedisct1 thanks. Merged: https://github.com/Homebrew/homebrew-core/pull/8029.
