### ISSUE TITLE
1.8.1-win32 on windows xp

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#518]
https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-win32-full-1.8.1.zip
![2016-12-20_195001](https://cloud.githubusercontent.com/assets/8692234/21349624/e39ec6e2-c6ed-11e6-9cfa-97dd5e38b399.png)

**Comment by bitbeans** [comment]
This also happened on a Windows 10 Pro 64 bit.
I added the DLL to SimpleDNSCrypt https://github.com/bitbeans/SimpleDnsCrypt/blob/master/SimpleDnsCrypt/dnscrypt-proxy/libgcc_s_sjlj-1.dll

**Comment by jedisct1** [comment]
Good catch :/

Indeed, it looks like an additional linked flag is required to avoid having to ship this extra DLL.

I updated the .zip file to include that DLL. Thanks!
