### ISSUE TITLE
dnscrypt.org-fr not working.

### ISSUE THREAD

**Issue by Nurple** [jedisct1/dnscrypt-proxy#523]
Heya,

Just updated to v1.8.1 from v1.7.0 on Windows 10 x64 & on a Win7 x64 VM, and dnscrypt.org-fr doesn't resolv anymore, cisco works fine though.

Console output;

>C:\Program Files\DNSCrypt-Proxy>DNSCrypt-Proxy.exe "C:\ProgramData\DNSCrypt\DNSCrypt.conf"
12/26/16 21:19:53 [INFO] + DNS Security Extensions are supported
12/26/16 21:19:53 [INFO] + Provider supposedly doesn't keep logs
12/26/16 21:19:53 [NOTICE] Starting dnscrypt-proxy 1.8.1
12/26/16 21:19:53 [INFO] Loading plugin [C:\Program Files\DNSCrypt-Proxy\libdcplugin_example_ldns_aaaa_blocking.dll]
12/26/16 21:19:53 [INFO] Loaded plugin: [Directly return an empty response to AAAA queries]
12/26/16 21:19:53 [INFO] Ephemeral keys enabled - generating a new seed
12/26/16 21:19:53 [INFO] Done
12/26/16 21:19:53 [INFO] Server certificate with serial #1482768334 received
12/26/16 21:19:53 [INFO] This certificate is valid
12/26/16 21:19:53 [INFO] Server certificate with serial #1482768334 received
12/26/16 21:19:53 [INFO] This certificate is valid
12/26/16 21:19:53 [INFO] Favoring certificate #1482768334 which is for a more recent version than #1482768334
12/26/16 21:19:53 [INFO] Using version 2.0 of the DNSCrypt protocol
12/26/16 21:19:53 [INFO] Server key fingerprint is 7792:2899:6414:A9FE:47B4:9F95:787F:3A36:1577:363B:484A:FA71:E09B:00DA:9342:D011
12/26/16 21:19:53 [NOTICE] Proxying from 127.0.0.3:53 to 212.47.228.136:443

**Comment by jedisct1** [comment]
The log you posted looks good, and that's the resolver I'm using right now.

Can you clarify what you did that doesn't resolve?

**Comment by Nurple** [comment]
I've tried dig resolver.dnscrypt.org and got "connection timed out; no servers could be reached", and browsing the web.

**Comment by Nurple** [comment]
Just for the fun of it I tried Simple DNSCrypt in a clean Win7 VM and had the same result.

**Comment by jedisct1** [comment]
Do you have anything that could block outgoing traffic to port 443?

The resolver looks fine on my end, and there are a lot of queries being currently handled by it.

**Comment by Nurple** [comment]
I shouldn't have, I don't run any anti-malware, and the only firewall I use is the Windows builtin one.

**Comment by ZJaume** [comment]
Since the update to version 1.8.1 I'm having the same problem. Neither Cisco or dnscrypt.eu/.org work, i don't have tested more but I think it's a problem of the client. And then I tried setting a normal dns resolver and HTTPS traffic works well.
Running Arch Linux.

**Comment by jedisct1** [comment]
@Nurple Can you try without ephemeral keys? And forcing TCP?

**Comment by Nurple** [comment]
Just turning off ephemeral keys fixes it.

------------------------------------------------

It works with ephemeral keys on in a Ubuntu 16.04 VM. I built v1.8.1 with libressl 2.5.0 and libsodium 1.0.11, though it gives this  output;

[WARNING] Unsupported certificate version: [0][2]

**Comment by jedisct1** [comment]
I was unable to duplicate this (using Windows 10, unmodified precompiled binaries).

Are you using the precompiled binaries? Would you mind sharing the exact configuration file you use?

**Comment by jedisct1** [comment]
Nevermind, I was able to duplicate this, using a 32-bit build.

Investigating...

Thanks!

**Comment by jedisct1** [comment]
Ok, problem found :)

The Windows binaries were correct. The bug was actually in Linux binaries compiled with older libsodium versions.

I temporarily disabled xchacha20 certificates from the server, until most Linux users update to version 1.9.0 of the client proxy (which will be tagged soon).

**Comment by Nurple** [comment]
Fyi, I was using the unmodified precompiled binaries for Windows.

I re-enabled ephemeral keys now that you've disabled the xchacha20 certificate, and all is working.
