### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by FixedTorres** [jedisct1/dnscrypt-proxy#525]
Hi, guys.

After installing Dnscrypt-Proxy 1.8.1 and running it, an error happens in Linux Mint 18.1. This error says: dnscrypt-proxy: symbol lookup error: dnscrypt-proxy: undefined symbol: crypto_box_curve25519xchacha20poly1305_open_easy.

Any idea? or, Any solution?
Why does this happen?

Thanks.
Regards.

**Comment by jedisct1** [comment]
Can you describe how you compiled/installed libsodium and dnscrypt-proxy?

Looks like the binary was compiled on a different system, with a different libsodium version.

**Comment by FixedTorres** [comment]
Hi.

libsodium was compiled in this way:

./configure --prefix=/usr
make
sudo make install

libsodium version: 1.0.11
I was trying with libsodium git version.

And, dnscrypt-proxy was compiled in this way:

./configure --prefix=/usr --with-systemd
make
sudo make install

dnscrypt-proxy version: 1.8.1
I was trying with dnscrypt-proxy git version.

I don't know if I do it wrong.
I need something more?

**Comment by jedisct1** [comment]
To quote the message that was printed when you compiled this:
```
*** This is unstable, untested, development code.
It might not compile. It might not work as expected.
It might be totally insecure.
Do not use this in production.
Use releases available at https://download.libsodium.org/libsodium/releases/ instead.
```

This is especially true during the holiday season, where I have no Linux machine, and I get limited sleep, but drink too much.

More seriously, that symbol was introduced in non-released code, but as we're not even close to a release, the library version number is the same as when this function was not present. 

My guess is that you compiled dnscrypt-proxy with one version of libsodium, but then it uses a different version when it runs. Check that you don't have multiple installations, such as one in `/usr` and another one in `/usr/local`.

**Comment by FixedTorres** [comment]
Hi friend.

Effectively, it had 2 versions of libsodium in my system. Error fatal, I hadn't noticed this, I had the libsodium version with the number 18 installed from the repositories of Ubuntu and the libsodium version 1.0.11 installed by me. Problem solved!!

Thank you very much for help me.

**Comment by jedisct1** [comment]
Glad that it's solved!

If you are using the git version of the proxy, feel free to test the [recent changes](https://github.com/jedisct1/dnscrypt-proxy/blob/master/NEWS) and to improve the [new documentation](https://github.com/jedisct1/dnscrypt-proxy/wiki) so that version 1.9.0 can be released soon!

Cheers.

**Comment by FixedTorres** [comment]
Hi Frank.

I would like to collaborate with the documentation but my English is not very good, I am from Latin America and I speak Spanish. I am currently using Manjaro Linux and the git version of dnscrypt.

Greeting!
