### ISSUE TITLE
.host not resolv with dnscrypt

### ISSUE THREAD

**Issue by safeith** [jedisct1/dnscrypt-proxy#526]
Hello Dear,

I think dnscrypt not resolv .host domains, How to fix it's in server and client sid ?

**Comment by jedisct1** [comment]
Hi!

What resolver are you using?

Do you have an example of a name that doesn't resolve?

**Comment by safeith** [comment]
I have own server ifreenet and tested soltysiak too but bith if them can not resolve

get.host
0web.host

**Comment by jedisct1** [comment]
Indeed. `.host` was in the list of nonexistent TLDs frequently on local networks.

The fact that it's now a real TLD is quite frightening. Anyway, removing this from the list of local zones should do the trick: https://github.com/jedisct1/dnscrypt-server-docker/commit/9051c13aaaf4141a2c4afcf69685a45ea71e50e3

The Docker image was updated with that change.

Thanks a lot for spotting this!
