### ISSUE TITLE
dnscrypt-proxy listens on 127.0.0.1 no matter what is in /etc/dnscrypt-proxy.conf

### ISSUE THREAD

**Issue by kenb0t** [jedisct1/dnscrypt-proxy#528]
Using dnscrypt-proxy v1.8.1 on Arch Linux, downloaded from pacman.
No matter what address I specify for LocalAddress in /etc/dnscrypt-proxy.conf, it will bind to 127.0.0.1. However, if I copy dnscrypt-proxy.socket to /etc/systemd/system/, edit the IP addresses there, issue `systemctl daemon-reload && systemctl restart dnscrypt-proxy` then the IP address will change.

**Comment by jedisct1** [comment]
`LocalAddress` is when the proxy itself binds the socket, i.e. when systemd doesn't do it.

I don't use systemd, so feel free to update the wiki with systemd specific instructions that could be useful to other users!
