### ISSUE TITLE
Dnscrypt goes into standby mode or 'not using dnscrypt' mode very easily

### ISSUE THREAD

**Issue by royalblood87** [jedisct1/dnscrypt-proxy#530]
hi, 

Pls ensure that this does not happen regardless of whatever programs that open up, dnscrypt has to BE OF utmost priority. 

Warmest regards, 

sean

**Comment by licaon-kter** [comment]
What version? What operating system? What server? What? What?

**Comment by jedisct1** [comment]
What application are you talking about?

**Comment by royalblood87** [comment]
dnscrypt for mac osx

on mac sierra 10.12.1

thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jedisct1** [comment]
The project you are having issue with is probably https://github.com/alterstep/dnscrypt-osxclient , not that one (dnscrypt-proxy).
