### ISSUE TITLE
Problem with blocking.

### ISSUE THREAD

**Issue by DebugReport** [jedisct1/dnscrypt-proxy#531]
> cat /etc/domains.list
*.luxup.ru

http://luxup.ru/ - ERR_NAME_NOT_RESOLVED (blocked)
But 
http://c.luxup.ru/t/lb181488_1.js - Not blocked. Why?
Version: r2186.339f75e

**Comment by jedisct1** [comment]
This might have been cached by your web browser. You can try flushing your system DNS cache or resolving the name directly in order to confirm this.

When it comes to blocking, I would highly suggest upgrading to the just released version 1.9.0. The blocking module was completely rewritten to be more reliable and way faster.

**Comment by DebugReport** [comment]
It's not a cache. I try empty profile of browser and dig ( see gist link )
https://gist.github.com/DebugReport/89d086d048d8cdd464c716f8f5014ba5
I have latest version - dnscrypt-proxy 1.9.0

**Comment by DebugReport** [comment]
And i think that is not system DNS cache, because entry like this

> luxup.ru
> c.luxup.ru

work fine. But not

> *.luxup.ru

**Comment by jedisct1** [comment]
Unfortunately, I was not able to duplicate this :( 
Would you mind sharing your full domain block file?

**Comment by jedisct1** [comment]
Or just the minimum file that triggers this on your system.

**Comment by DebugReport** [comment]
I don't know why, but now i can't reproduce this trouble...
But before i recreate domains.list and input only one line with *.luxup.ru and it's work.
Maybe some rules is bad...I check it now.

**Comment by DebugReport** [comment]
Yes. Something with rules...

[domains.txt](https://github.com/jedisct1/dnscrypt-proxy/files/676856/domains.txt)

Maybe some rules broke when i convert it from hosts file...

**Comment by jedisct1** [comment]
This happens because you have both `*.luxup.ru` and overlapping rules such as `is.luxup.ru`.

But this is indeed a bug; overlapping rules should be ignored.

Thanks for reporting this! I'll see how it can be fixed.

**Comment by DebugReport** [comment]
> laptop% dig +short apis.google.com
plus.l.google.com.
216.58.210.46

> laptop% dig +short google.com
Output empty

> laptop% cat /etc/domains.list 
*.doubleclickbygoogle.com
*.google.com

It's not correct too...

**Comment by jedisct1** [comment]
Yes, same issue.

The bug is in `fpst_starts_with_existing_key()`, which should do prefix matching, but actually cannot do it without a stack.

If we have a single branch with two nibbles: `abcdef` and `abcdefgh` and we look for what key is a prefix for `abcdefg`, the current algorithm will only explore the second nibble. 

Anybody want to help fix this?

**Comment by DebugReport** [comment]
I can't help to fix it, because learn Ruby. But i want to learn C too. Later. :-(
And thanks for an explanation.

**Comment by DebugReport** [comment]
Maybe use regexp library for more flexibility? Or it's will be slow?

**Comment by jedisct1** [comment]
Maybe something like Hyperscan would work, but will still be way slower and overkill for this.

**Comment by DebugReport** [comment]
What if use some code from here https://github.com/cesanta/slre ?
I think that is smaller than hyperscan. Maybe...
Or compare domain and mask by index.
string = 'example.com'
string[0] contains 'e', string[1] contains 'x', etc...

**Comment by jedisct1** [comment]
And compare every single character of every query against every single line of the black list every time?

Do not ever suggest anything like that during a coding interview :)

**Comment by jedisct1** [comment]
Can you try the current code in git?

This should fix it :)

**Comment by DebugReport** [comment]
> Do not ever suggest anything like that during a coding interview :)
Ok, thanks you. 
I'm compile and install new dnscrypt-proxy. I'm testing it now.

**Comment by DebugReport** [comment]
> *.luxup.ru
c.luxup.ru

It's work correct. Blocked luxup.ru and c.luxup.ru

> *.doubleclickbygoogle.com
*.google.com

It's too. Blocked doubleclickbygoogle.com, google.com, apis.google.com

I'm will report if i found any problems with blocking. Thanks you very much.

**Comment by jedisct1** [comment]
Just made some minor changes. Can you confirm that everything looks fine with the latest code?

If that is the case, I'll release 1.9.1 shortly :)

Thanks again for spotting and reporting this!

**Comment by DebugReport** [comment]
Mask *google* work fine. But this *.google* & *.google.* not.
It's bug or feature?

**Comment by jedisct1** [comment]
Can you provide some examples of queries that should match `*.google*` but don't? Same for `*.google.*`?

**Comment by jedisct1** [comment]
Looks like it works as expected.

`*.google*` matches names with the `.google` substring such as `www.googleanalytics.com`.
`*.google.*` matches names with the `.google.` substring such as `www.google.example.com`.

The `.` is not ignored, as this is probably not what you want when matching substrings.
It is ignored when doing suffix matching such as `*.example.com` that matches both `www.example.com` and `example.com` since this is the most natural behavior.

**Comment by DebugReport** [comment]
Hmm... If mask has two `*` (`*.google.*`), `*.` is not a suffix?

**Comment by jedisct1** [comment]
`*xxx*` is not a suffix, it's a substing. It means "match that exactly substring, anywhere in the query name".
`*xxx` is a suffix. It matches `xxx` and anything followed by `.xxx`
`xxx*` is a prefix. It matches anything starting with `xxx`

Substrings are great to filter things such as `sex` no matter where this 3 character sequence is.
But with extra dots, it can be used to filter specific components of a name such as filtering `.ads.` to block `test.ads.example.com` but not `madserver.com`.

**Comment by DebugReport** [comment]
Ok, thanks :-)

**Comment by DebugReport** [comment]
I have problem again :-(
apis.google.com & cse.google.com not blocked...I don't know why...
[domains.txt](https://github.com/jedisct1/dnscrypt-proxy/files/692072/domains.txt)

**Comment by jedisct1** [comment]
Damn, I am having a hard time getting this right :)

Can you try the latest code in git? 76cd1fdf787d6f61af96312a47190c5ad17ced2b hopefully fixes it.

**Comment by DebugReport** [comment]
Yes, now it's work. Thanks you :-)

**Comment by DebugReport** [comment]
Mask
```
laptop% cat /etc/domains.list 
*.redtram.com
ru.redtram.com
```
Result
```
laptop% dig +short img150-ru.redtram.com
img150.ru.redtram.com.
front03-carp.redtram.com.
62.244.25.71
```
Without `ru.redtram.com` blocking work fine.

**Comment by jedisct1** [comment]
Thanks!

That one is pretty sneaky, but e3d43d108226b3997f804c443448c6644480a9e6 should fix it.

**Comment by DebugReport** [comment]
Confirm, it's work :-)

**Comment by jedisct1** [comment]
Thanks for spotting that one. This is pretty annoying as handling this can make lookups twice as slow :(

**Comment by MrSorcus** [comment]
It's me, again...
Mask `*.redtram.com`
```
laptop% dig +short n4p-ru.redtram.com
n4p.ru.redtram.com.
front02-carp.redtram.com.
62.244.25.75
laptop% dig +short nc-ru.redtram.com 
nc.ru.redtram.com.
front04-carp.redtram.com.
62.244.25.72
```
[domains.txt](https://github.com/jedisct1/dnscrypt-proxy/files/790642/domains.txt)

I think problems with `-`. Because rule `advert-department-pages-info.twomini.com` doesn't work too.
```
laptop% dig + short advert-department-pages-info.twomini.com
;; Invalid option 

; <<>> DiG 9.11.0-P3 <<>> + short advert-department-pages-info.twomini.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 12991
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;short.                         IN      A

;; AUTHORITY SECTION:
.                       10800   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2017022100 1800 900 604800 86400

;; Query time: 78 msec
;; SERVER: ::1#53(::1)
;; WHEN: Tue Feb 21 15:52:07 UTC 2017
;; MSG SIZE  rcvd: 109

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 27169
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 33db9abb33e67111 (echoed)
;; QUESTION SECTION:
;advert-department-pages-info.twomini.com. IN A

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Tue Feb 21 15:52:07 UTC 2017
;; MSG SIZE  rcvd: 81
```
Version.
```
laptop% dnscrypt-proxy --version                         
dnscrypt-proxy 1.9.3

Compilation date: Jan 19 2017
Support for plugins: present
Plugins root directory: [/usr/lib/dnscrypt-proxy/]
Support for ldns-based plugins: present
Support for systemd socket activation: present
Support for the XChaCha20-Poly1305 cipher: present
```

**Comment by jedisct1** [comment]
dnscrypt-proxy 1.9.3 is old! The current stable one is 1.9.4 :)

**Comment by MrSorcus** [comment]
@jedisct1 , Ooops...
Result with 1.9.4
```
laptop% dig +short n4p-ru.redtram.com
laptop% dig +short nc-ru.redtram.com
laptop% dig + short advert-department-pages-info.twomini.com
;; Invalid option 

; <<>> DiG 9.11.0-P3 <<>> + short advert-department-pages-info.twomini.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 59825
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;short.                         IN      A

;; AUTHORITY SECTION:
.                       4659    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2017022100 1800 900 604800 86400

;; Query time: 72 msec
;; SERVER: ::1#53(::1)
;; WHEN: Tue Feb 21 17:34:27 UTC 2017
;; MSG SIZE  rcvd: 109

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 62025
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: a5ab3f784ba79724 (echoed)
;; QUESTION SECTION:
;advert-department-pages-info.twomini.com. IN A

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Tue Feb 21 17:34:27 UTC 2017
;; MSG SIZE  rcvd: 81
```

**Comment by MrSorcus** [comment]
@jedisct1 , Ooops...All works. :-)

**Comment by jedisct1** [comment]
:)
