### ISSUE TITLE
Unable to compile dnscrypt 1.9.0 on linux

### ISSUE THREAD

**Issue by zivender** [jedisct1/dnscrypt-proxy#532]
#./configure 
...
checking for readdir... yes
checking for strlcat... no
checking for strlcpy... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `contrib/Makefile.in'

**Comment by licaon-kter** [comment]
Works here from `git clone` and `./autogen.sh`

Is this from ZIP or git?

**Comment by jedisct1** [comment]
Crap, I forgot to add `contrib` to `SUBDIRS`.

Rolling a new tarball ASAP.

**Comment by jedisct1** [comment]
Fixed. Thanks a lot for reporting this, and sorry for the inconvenience :(
