### ISSUE TITLE
Unreliable on OS X

### ISSUE THREAD

**Issue by Haravikk** [jedisct1/dnscrypt-proxy#538]
I've been trying for a little while now to use DNS Crypt via the OS X GUI distribution (as a menubar widget and preference pane), however I've found it be far too unreliable.

At least once a day it just locks up and stops responding entirely, forcing me to disable and re-enable DNS Crypt. It doesn't seem to matter which resolver I'm using.

Today this went a step further and I just couldn't get it to work at all, forcing me to go into my network interfaces and manually remove the 127.0.0.1 entry from the DNS servers list, i.e; the preference pane was no longer doing this automatically.

The process seems to keep running, it just won't respond to queries anymore. Like I say, usually disabling and re-enabling it works but that didn't work at all today which has forced me to go back to using my ISP's DNS service for now until I can find some way to determine what's wrong.

I'm running macOS El Capitan (all updates installed) in case that matters.

**Comment by jedisct1** [comment]
Sorry to hear that, but this project is not the OSX GUI.

**Comment by Haravikk** [comment]
Sorry, but I'm not 100% sure that the problem is with the macOS GUI itself, which is partly what I'd like to narrow down; there isn't really much to the GUI (select a resolver, then enable/disable the service), so it's likely that it's the service itself that is failing, which surely comes under this project?

**Comment by publicarray** [comment]
-> https://github.com/alterstep/dnscrypt-osxclient/issues/126
