### ISSUE TITLE
Homebrew: plugins fail with "can't be loaded: [Permission denied]"

### ISSUE THREAD

**Issue by m4dj4ck** [jedisct1/dnscrypt-proxy#539]
Sorry if this has been discussed previously. I upgraded to 1.9.0 from previous version via Homebrew. Not sure if I overlooked something trivial, but I am getting this at the moment while trying to run dnscrypt-proxy like this :
```
user:/usr/local/sbin]$ ./dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
Sun Jan  1 21:55:49 2017 [INFO] + DNS Security Extensions are supported
Sun Jan  1 21:55:49 2017 [INFO] + Provider supposedly doesn't keep logs
Sun Jan  1 21:55:49 2017 [INFO] Loading plugin [/usr/local/Cellar/dnscrypt-proxy/1.9.0/lib/dnscrypt-proxy/libdcplugin_example_cache.so]
Sun Jan  1 21:55:49 2017 [ERROR] Plugin [/usr/local/Cellar/dnscrypt-proxy/1.9.0/lib/dnscrypt-proxy/libdcplugin_example_cache.so] can't be loaded: [Permission denied]
Sun Jan  1 21:55:49 2017 [ERROR] Unable to load plugins
```
Meanwhile, starting the process via "sudo brew services restart dnscrypt-proxy" works just fine. But I need the QueryLog enabled, which I don't find this options available as parameter to the dnscrypt-proxy command.

**Comment by jedisct1** [comment]
`sudo` before `./dnscrypt-proxy` should solve this. Plugin files should either be owned by root, or by the user starting the service.

Everything from the config file is also available as a command-line option.

That plugin can be enabled with:

`--plugin=libdcplugin_example_logging.so,/tmp/query.log`

**Comment by m4dj4ck** [comment]
Thanks for your reply. I did tried with sudo, works this :
```
[user:~]$ sudo /usr/local/sbin/dnscrypt-proxy --ephemeral-keys --resolvers-list=/usr/local/opt/dnscrypt-proxy/share/dnscrypt-proxy/dnscrypt-resolvers.csv --resolver-name=dnscrypt.eu-dk
Wed Jan  4 03:37:06 2017 [INFO] + DNS Security Extensions are supported
Wed Jan  4 03:37:06 2017 [INFO] + Provider supposedly doesn't keep logs
Wed Jan  4 03:37:06 2017 [NOTICE] Starting dnscrypt-proxy 1.9.0
Wed Jan  4 03:37:06 2017 [INFO] Ephemeral keys enabled - generating a new seed
Wed Jan  4 03:37:06 2017 [INFO] Done
Wed Jan  4 03:37:06 2017 [INFO] Server certificate with serial '0001' received
Wed Jan  4 03:37:06 2017 [INFO] This certificate is valid
Wed Jan  4 03:37:06 2017 [INFO] Chosen certificate #808464433 is valid from [2016-09-10] to [2017-09-10]
Wed Jan  4 03:37:06 2017 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
Wed Jan  4 03:37:06 2017 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3C24:BFF3:2BF7:B406:108B:44DA:51FE:3711
Wed Jan  4 03:37:06 2017 [NOTICE] Proxying from 127.0.0.1:53 to 77.66.84.233:443
```

But, failed when enabled the logging plugin :
```
[user:~]$ sudo /usr/local/sbin/dnscrypt-proxy --ephemeral-keys --resolvers-list=/usr/local/opt/dnscrypt-proxy/share/dnscrypt-proxy/dnscrypt-resolvers.csv --resolver-name=dnscrypt.eu-dk --plugin=libdcplugin_example_logging.so,/tmp/query.log
Wed Jan  4 03:38:39 2017 [INFO] + DNS Security Extensions are supported
Wed Jan  4 03:38:39 2017 [INFO] + Provider supposedly doesn't keep logs
Wed Jan  4 03:38:39 2017 [NOTICE] Starting dnscrypt-proxy 1.9.0
Wed Jan  4 03:38:39 2017 [INFO] Loading plugin [/usr/local/Cellar/dnscrypt-proxy/1.9.0/lib/dnscrypt-proxy/libdcplugin_example_logging.so]
Wed Jan  4 03:38:39 2017 [ERROR] Plugin [/usr/local/Cellar/dnscrypt-proxy/1.9.0/lib/dnscrypt-proxy/libdcplugin_example_logging.so] can't be loaded: [Operation not permitted]
Wed Jan  4 03:38:39 2017 [ERROR] Unable to load plugins
```

I can confirm that all files in /usr/local/Cellar/dnscrypt-proxy/1.9.0/lib/dnscrypt-proxy/ belongs to user starting the service.

**Comment by jedisct1** [comment]
Still, try:
```sh
    sudo chown -R 0:0 /usr/local/Cellar/dnscrypt-proxy/1.9.0/lib/dnscrypt-proxy
```

**Comment by DomT4** [comment]
Homebrew [sets the user](https://github.com/Homebrew/homebrew-core/blob/193111ae961a45e6445a359f7ebbcf8ad9e78a06/Formula/dnscrypt-proxy.rb#L123) to `nobody` when using `brew services` FWIW.

**Comment by dexrualo** [comment]
Hi. I had the same problem. I know this issue was closed and months old but Google search result pointed me here. It might help others having the same problem. What I did to fix it was I installed it this way:
`brew install dnscrypt-proxy --with-plugins`

**Comment by jedisct1** [comment]
Is your Homebrew installation up to date?

I think `--with-plugins` is deprecated because it's been the default for quite some time.

**Comment by DomT4** [comment]
In the Homebrew formula it's not enabled by default. There was some discussion about it per my nudge but it didn't go anywhere.

**Comment by jedisct1** [comment]
Mmmm, ok. So it means that the default config file is not usable since caching is enabled by default.

**Comment by DomT4** [comment]
I can submit a PR at Homebrew to make it the default. I can't see a good argument against it being the default to be honest, unless there are significant security concerns about `--enable-relaxed-plugins-permissions` being set.
