### ISSUE TITLE
No issue, just another non-savvy question

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#541]
Hi,

Sorry guys for posting a simple question with certainly an obvious answer for savvy users, but I'd appreciate a simple definition of the only option I don't understand included in dnscrypt-proxy.conf

> - Run the proxy as a background process
> - Unless you are using systemd, you probably want to change this to "yes"
> - after having verified that the rest of the configuration works as expected.
> Daemonize no

So, daemonize is off by default. But what is daemonize to start with?
Point is, I'm running Windows 7, I don't even know what systemd is (is that a Linux setting?)
Logically, since I'm not running systemd (as I understand it) I'd "probably want to change this [Daemonize] to "yes" ...

I've left Daemonize to "no" and all is running smooth, yet I dislike ignoring things!

Thanks (again) for helping a newbie!

**Comment by jedisct1** [comment]
Hi!

No worries. Setting this to `yes` makes the server run as a background process on Unix.

It's ignored on Windows, so you can set it to anything you want :)

systemd is a long-lasting subject of trolling in the Linux world. You can safely ignore this as well :)

**Comment by zymase** [comment]
Thanks, @jedisct1 -- Now I get it (so to say!).
All is running smooth here with dnscrypt-proxy-win64-full-1.9.1 (just updated to 1.9.1, no major change for non-techies) and the dnscrypt-proxy.conf initiated with ver. 1.9.0 is a true user's friend.

All the best for 2017 (now that I "understand" daemonize and sysyemd!) :)
