### ISSUE TITLE
fpst.c redefinition of typedef in plugin compilation

### ISSUE THREAD

**Issue by fabiolcf** [jedisct1/dnscrypt-proxy#546]
Compiling on Debian 6 (I know...), when it becomes time to compile the plugins, at example-ldns-blocking, I get:
fpst.c:15: error: redefinition of typedef ‘FPST’
fpst.h:8: note: previous declaration of ‘FPST’ was here

If I configure with --disable-plugins , everything works (as it should). 

If I move the full definition of the struct in the .h file, everything compiles. I do not use the plugin so I don't really have any way to check if it also works as intended, but it should.

**Comment by jedisct1** [comment]
a4a4493db417fa1ba6a0f5453995b346c39eabe8 should fix it.

Thanks for your report!

**Comment by fabiolcf** [comment]
Yeah, that's functionally equivalent to what I did. Thanks for the fast reply and the confirmation!
