### ISSUE TITLE
stdout or stderr?

### ISSUE THREAD

**Issue by GaneJ** [jedisct1/dnscrypt-proxy#549]
@jedist1,
in `logger.c` -> `logger()` , I see you use stdout if context is null ( `log_fp` variable ).
Isn't better to use stderr rather stdout for notification?

**Comment by jedisct1** [comment]
Hi Gane,

Maybe it should depend on the log level. Anything with log level `>= LOG_NOTICE` can probably go to `stdout` whereas more serious issues should go to `stderr`.

What do you think?

**Comment by jedisct1** [comment]
Did something like that in 4ecd00ba2332c31dd61377ce744a3256df414a86

**Comment by GaneJ** [comment]
[`4ecd00b`](https://github.com/jedisct1/dnscrypt-proxy/commit/4ecd00ba2332c31dd61377ce744a3256df414a86) :+1:

I'm thinking about windows service.
Since some log info/error won't print in console if something failed before `context` got initialize (`null context`) maybe we can find away to write it somewhere else, beside `standard handler`.
Maybe temporary file?
or
maybe dnscrypt-proxy open new console window and write a message in there?

This "won't print log" happen because when dnscrypt-proxy service set into `autostart` or start by other program, the console windows doesn't exist ( Print anything into `standard handler` won't work ).

This "won't print log" is very important since some user can report back here if something failed with dnscrypt-proxy before `context` got initialize.
