### ISSUE TITLE
About the mimimum time to keep a record in cache

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#550]
Hi,

I read that dnscrypt-proxy 1.9.1 includes a mimimum time to keep a record in cache:

> The mimimum time to keep a record in cache can be specified in the cache plugin, with the
>  --with-ttl option (config file: with-ttl:...).

Should it be applied in dnscrypt-proxy.conf as:

> LocalCache on  --with-ttl:

Is ttl expressed in seconds or minutes?
What is the default ttl?

Thanks. It's not obvious for plain Windows users!

**Comment by jedisct1** [comment]
Hi!

This is in seconds, and the default is 1 minute.

**Comment by zymase** [comment]
I've downloaded SimpleDNSCrypt_0.4.0.zip, extracted its dnscrypt-proxy.exe
In the files binary soup, found 

> LocalCache? <bool> min-ttl:(<digits>)

I applied:

> LocalCache on min-ttl:3600

and it seems to work, that is : dnscrypt-proxy starts and checking dns requests seems to show that a new dns request was not performed when a given site was re-opened after the default DNS LocalCache 60seconds.

I don't know, just digging ...

**Comment by jedisct1** [comment]
`LocalCache on min-ttl:3600` is indeed the correct syntax.

**Comment by zymase** [comment]
OK, no problem. Works nice.
Concerning this ttl : minimum=60 seconds (default), maximum=86400.

Of course,  the best ttl for dns caching is a major question. I've set it to 3600sec (1hour), so I'd like to ask you what value you consider the best with DNSCrypt-proxy. 

Also, is the cache emptied when DNSCrypt-proxy is stopped? If so, which I hope, it would allow to circumvent the disadvantages of a long ttl.

Thanks, @jedisct1

**Comment by jedisct1** [comment]
Hi Zymase,

Keep in mind that this is the _minimum_ TTL. If the orginal TTL specified in records sent by the original authoritative server is higher, the higher value will be used.

The default value is usually fine.
