### ISSUE TITLE
Unable to load plugins

### ISSUE THREAD

**Issue by DebugReport** [jedisct1/dnscrypt-proxy#553]
Version 1.9.1
Revision 2251
Commit 0bb4b3c
Command:
>sudo dnscrypt-proxy --resolver-name=dnscrypt.eu-dk-ipv6 --ephemeral-keys --local-address='[::1]:53' --plugin=libdcplugin_example_logging.so,/var/log/dnscrypt.log --plugin=libdcplugin_example_ldns_blocking.so,--domains=/etc/domains.list,--ips=/etc/ips.list,--logfile=/var/log/dnscrypt.blocked.log

Logs:
>Sun Jan  8 08:40:10 2017 [INFO] Loading plugin [/usr/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so]
Sun Jan  8 08:40:10 2017 [ERROR] Unable to load [/usr/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so]: [file not found]
Sun Jan  8 08:40:10 2017 [INFO] Loading plugin [/usr/lib/dnscrypt-proxy/libdcplugin_example_logging.so]
Sun Jan  8 08:40:10 2017 [INFO] Loaded plugin: [Log client queries]
Sun Jan  8 08:40:10 2017 [ERROR] Unable to load plugins

List of libs:
>laptop% ls /usr/lib/dnscrypt-proxy/                                    
libdcplugin_example_cache.so               libdcplugin_example_ldns_blocking.so    libdcplugin_example_ldns_opendns_deviceid.so       libdcplugin_example_logging.so
libdcplugin_example_ldns_aaaa_blocking.so  libdcplugin_example_ldns_forwarding.so  libdcplugin_example_ldns_opendns_set_client_ip.so  libdcplugin_example.so

Work fine with:
Version 1.9.1
Revision 2219
Commit 37ed781

**Comment by jedisct1** [comment]
It says "file not found". My guess is that the `ldns` library was missing when it was compiled.

**Comment by DebugReport** [comment]
Package ldns installed in chroot...
> vs0% sudo arch-nspawn /tmp/chroot/root pacman -Qi ldns
Name            : ldns
Version         : 1.7.0-1
Description     : Fast DNS library supporting recent RFCs
Architecture    : x86_64
URL             : https://www.nlnetlabs.nl/projects/ldns/
Licenses        : custom:BSD
Groups          : None
Provides        : None
Depends On      : openssl  dnssec-anchors
Optional Deps   : libpcap: ldns-dpa tool
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1839.00 KiB
Packager        : Gaetan Bisson <bisson@archlinux.org>
Build Date      : Sun Jan 1 07:52:00 2017
Install Date    : Tue Jan 10 08:31:32 2017
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature


Maybe logs can help...
https://gist.github.com/DebugReport/4b6082edbde87a7a7a09f9ce3c643bcf

**Comment by DebugReport** [comment]
I can't reproduce it with commit fd04afb
Closed...

**Comment by FixedTorres** [comment]
Hi @DebugReport 

I see you're using Archlinux or some derivative, right?

The problem occurs because the package is not installing the files with extension .la, this causes that you can not use the plugins.

There is a package AUR git version which is configured to install plugins and script to generate blacklists. There is also a PKGBUILD of stable version in github.

AUR: https://aur.archlinux.org/packages/dnscrypt-proxy-git/
For more information, see: https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-on-Archlinux

**Comment by DebugReport** [comment]
Hi @FixedTorres 
You right, i'm using ArchLinux.

Thanks you for link to PKGBUILD, but i'm not sure, that's trouble with extensions...

**Comment by FixedTorres** [comment]
Hi @DebugReport 

Try it, I had the same problem. That is why I suggest you the new PKGBUILD, I am currently using the plugins and the script to generate domains blacklist, all tests are done and resolved. 

Regards guys! 😃

**Comment by DebugReport** [comment]
@FixedTorres 
Ok, thanks you again. :-)
