### ISSUE TITLE
feature request: recursive configuration files

### ISSUE THREAD

**Issue by fabiocannizzo** [jedisct1/dnscrypt-proxy#554]
I have suggestions for two possible features.

1) When launching multiple instances of dnscrypt, most of the configurations options are the same except for a few , like for the resolver name and the port. Instead of duplicating the configuration file for each instance, it would be nice to have an "include" configuration statement, like in the example below:
`# dnscryp_instance_1.conf` 
` LocalAddress 127.0.0.1:53531` 
` ResolverName cs-fr` 
` include /etc/dnscrypt-common.conf` 

2) It would be nice to have the ability to specify which interface to use to route outgoing encrypted resolution requests

Thanks for consideration.

**Comment by jedisct1** [comment]
Thanks for the suggestions!

**Comment by jedisct1** [comment]
Recursive configuration files have been implemented!

Thanks!
