### ISSUE TITLE
How to flush dnscrypt-proxy's (dns) LocalCache

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#556]
Hi,

We know how to flush Windows dns cache, a browser's dns cache, but how is this done, if possible, with dnscrypt-proxy?

Point is, if the default value of 60 seconds (LocalCache on min-ttl) is kept and a dns has failed because that in the cache is no longer valid, all the user has to do is wait 60 seconds (provided i.e. the browser is used and the browser's dns ttl -- 60 seconds on Firefox -- hasn't been increased).

But if this LocalCache on min-ttl has been set to an hour or more it may be necessary to flush that LocalCache in order to not to have to wait whatever the new delay (3600, 10800, 86400 max). See what I mean?

This is why I wish to know if it is possible to flush dnscrypt-proxy's LocalCache. Maybe is it automatically flushed upon dnscrypt-proxy uninstall, say for instance when uninstalled to change resolver then re-installed?

Thanks. I haven't found an ounce of information regarding this LocalCache besides some very techie documentation provided to UNIX users ...

**Comment by jedisct1** [comment]
Hi,

Responses that indicate a failure are not cached, so you don't have to flush the cache if you get these.

The cache is only stored in memory, so restarting the service flushes it.

**Comment by pysiak** [comment]
Perhaps sending a signal what be more convenient than a restart in some cases where you need to flush a recently changed record.
What do you think about accepting SIGHUP to clear the cache like it is in dnsmasq?
I guess I could write it.

**Comment by jedisct1** [comment]
Sending `SIGHUP` already works, but not on Windows where there is no such signal.
