### ISSUE TITLE
can i make a traceable generated-domains-blacklist?

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#557]
can i generate it with order in the configuration file, and sort the domains, make it easy to track changes

**Comment by jedisct1** [comment]
Are you referring to the `generate-domains-blacklist.py` script?

The domains are already sorted, but within every section, not globally.

You can sort them globally by running something similar to:

```sh
./generate-domains-blacklist.py | egrep -v '^#' | rev | sort | rev > blacklist.txt
```

**Comment by CNMan** [comment]
thanks.
