### ISSUE TITLE
Unable to attach to systemd socket when dropping privileges

### ISSUE THREAD

**Issue by Nnubes256** [jedisct1/dnscrypt-proxy#558]
* When starting the dnscrypt-proxy without systemd, everything will work as expected. 
* When starting the dnscrypt-proxy with systemd and **not** dropping privileges, everything will work as expected.
* When starting the dnscrypt-proxy with systemd and dropping privileges, it will crash with `[ERROR] Unable to bind (UDP) [Address already in use]`. Strangely, the exit code is 0. 

This can be worked around by removing the `dnscrypt-proxy.socket` unit, editing the `dnscrypt-proxy.service` unit to not use it, and then configuring the listening socket the classic way, although I would like to know if this is an actual bug(aside from the exit status 0) or just Raspbian doing weird stuff again.

**Comment by jedisct1** [comment]
Did you compile the server with support for systemd? (`./configure --with-systemd`) ?

**Comment by Nnubes256** [comment]
Yes, in fact on the second case it will properly bind to the systemd socket.

**Comment by jedisct1** [comment]
I tried really hard but couldn't reproduce this :(

Sorry, I won't be able to help :/
