### ISSUE TITLE
Error using manual settings in conf file (works when added to csv resolvers file)

### ISSUE THREAD

**Issue by glitsj16** [jedisct1/dnscrypt-proxy#559]
Hi, while experimenting with the recently introduced conf file format I've stumbled on the following issue. When using a custom resolver that is not in the csv list I get the below error. When adding the exact same credentials to the csv file (and adapting the conf file accordingly), everything works as expected. Did I use an incompatible format or might this be a bug?

$ lsb_release -d
Description:	Arch Linux

$ dnscrypt-proxy -V
dnscrypt-proxy 1.9.1

$ pacman -Qi dnscrypt-proxy-git | grep Version
Version         : 1.9.1.r32.g67d6046-1

Using example values here, double-checked that the real ones have no errors (format kept intact).

$ grep dnscrypt.resolver.test /usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv
dnscrypt.resolver.test,DNSCrypt server,,Germany,,,1,yes,yes,no,xx.xxx.xxx.xx:5353,2.dnscrypt-cert.dnscrypt.resolver.test,E801:B84E:A606:BFB0:BAC0:CE43:445B:B15E:BA64:B02F:A3C4:AA31:AE10:636A:0790:324D,

/etc/dnscrypt/dnscrypt-proxy-test.conf @
https://gist.github.com/e410b6844c2745e691834bfb43263deb

$ sudo dnscrypt-proxy /etc/dnscrypt/dnscrypt-proxy-test.conf
Fri Jan 13 20:00:35 2017 [ERROR] Unsupported server protocol version

**Comment by jedisct1** [comment]
The `ProviderName` property doesn't look correct.

`ProviderName` is the provider name, that usually looks like `2.dnscrypt.example.com`. In your case, I guess it is `2.dnscrypt-cert.dnscrypt.resolver.test`.

This is different from the resolver name (first column in the CSV file, unused when details are provided instead of the CSV file).

**Comment by glitsj16** [comment]
Thanks for clearing things up. Working fine now.

**Comment by jedisct1** [comment]
Awesome!
