### ISSUE TITLE
Local address at 127.0.0.1 with a HOSTS blocking file using 127.0.0.1

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#563]
Sorry if the question is naive.

I'm running dnscrypt-proxy with the default 127.0.0.1 local address (and 127.0.0.2 for second instance).

I happen to use a HOSTS file dedicated to blocking which may be set to block addresses with 127.0.0.1 or 0.0.0.0

Should dnscrypt-proxy using 127.0.0.1 be considered as an argument to avoid 127.0.0.1 on the HOSTS file? If so, dnscrypt-proxy set to use 127.0.0.2 and 127.0.0.3 or set HOSTS to use 0.0.0.0 ?

Thanks.

**Comment by jedisct1** [comment]
Redirecting domains you want to avoid to `127.0.0.1` or `0.0.0.0` is a terrible idea, as connections will still happen, and will be directed to your local machine. The `hosts` file also involves a linear scan for every query, which is slow if you have a long list.

You can use dnscrypt-proxy to block domains. It's much easier, faster and powerful than a `hosts` file, as it can match suffixes, prefixes and patterns. It can also log the queries that have been blocked, along with the rule that cause the block.

If you are using dnscrypt-proxy, there are no reasons to use a `hosts` file.

**Comment by zymase** [comment]
Thanks, @jedisct1 

I've always used a HOSTS file here with Windows, manged by an application called HostsManager which allows to concatenate several HOSTS sources, always with Windows DNS Client service (dnscache) set to disabled and the blocking has always been free of any problems, speed included.

I understand your argument. The fact is,
- I use several hosts sources all managed by HostsMan
- Using dnscrypt-proxy to block domains is easy with a local file, in my case, set in the conf file:

> BlackList domains:"d:\My Data\DNSCrypt\dnscrypt-dom.txt" logfile:"d:\My Data\DNSCrypt\dnscrypt-blocked.log"

But mixing external sources with my own local blocked domains file is more problematic for me. It's easy with Simple DNSCrypt, less with dnscrypt-proxy. I've read the documentation here but as I understand it I'd have to use .py scrpting to handle those external sources... that's what I'm facing at this time.

I'm discovering a new world, I appreciate,  always, your help, and so promptly proposed. But I cannot ask here for personal school-type assistance! So I try to manage and ask for advice/help only when I believe the answer is out of my present possibilities.

Of course using dnscrypt-proxy's built-in features to handle all domains and IPs is the most clever thing to do.

**Comment by TroudhuK** [comment]
@zymase So what is the problem to use Simple DNSCrypt if it makes all easier? Do you lose something?

@jedisct1 I'm using W10Privacy which contains lists of blocked IPs and domains. It uses the hosts file to block domains, and the firewall to block IPs.
- Is it faster to use DNSCrypt to block both? You confirm for the hosts file but for the firewall? Even if we take a classic list without pattern?
- If yes, after entering it in DNSCrypt, should we remove the entries from hosts/firewall to be faster, or can we keep it without performance lost?

**Comment by zymase** [comment]
@TroudhuK I'd rather run whatever app free of .net Framework, because it is dependency and because it is heavy.

Also, Simple DNSCrypt seems unable to log the blocked domain/ips, as with 

> BlackList domains:"d:\My Data\DNSCrypt\dnscrypt-dom.txt" logfile:"d:\My Data\DNSCrypt\dnscrypt-blocked.log"

I saw no way of getting this dnscrypt-blocked.log

Third, I cannot get Simple DNSCrypt to add my local domain blocking file to external ones (which it handles nicely) : local filters have to be added 1 by one. My domain blocking file is important, 300+ entries so i've tried to have SDNSCrypt add it via a "local url" such as file:///D:/My%20Data/DNSCrypt/dnscrypt-dom.txt : it's accepted but the content is not added!

@jedisct1 is right, everything can and should be operated via dnscrypt-proxy's blocking features. But ley this feature be considered to its full potential : I will not add an external source built up as a hosts file when,dnscrypt can handle with one rule, i.e. 302br.* ... hundreds of the family in an external source. What i'm doing right now is to consider the heavyweights of my HOSTS file (such as 302br.*) which can be considered not as exceptions to a valid domain but the very expressions of unhealthy domains. Once done I add their short form to my local domain blocking file and ... add them to my HostsMan applications 'exceptions' (HostsMan then removes them from my Hosts file. I did so and, just with 302br.* my HOSTS file went from 80,000 to 65,000 or so entries!

My rhetoric is not elegant and even less technical but I hope you get the idea. Moreover I'm French so English is expressed with many approximations.

Thanks.

**Comment by TroudhuK** [comment]
Je suis français aussi, je crois qu'on l'est tous en fait, qu'est-ce qu'on s'embête avec une langue étrangère ? Enfin bon.

> Third, I cannot get Simple DNSCrypt to add my local domain blocking file to external ones (which it handles nicely) : local filters have to be added 1 by one.

You can edit domains-blacklist.yaml in `Simple DNSCrypt\data` folder. Simple DNSCrypt is just a configurator GUI for DNSCrypt-proxy, which evolves well to support all the possibilities, but you can edit the configuration yourself, waiting for the support of more features from the GUI.

> I saw no way of getting this dnscrypt-blocked.log

Simple DNSCrypt configure at `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy\Parameters`, then you can edit Plugins, and at the line libdcplugin_ldns_blocking.dll add :
`,--logfile=d:\My Data\DNSCrypt\dnscrypt-blocked.log`

**Comment by zymase** [comment]
Merci, @TroudhuK (original comme pseudo!)
OK. For editing the .yaml file directly, I ignored that. Cumbersome nevertheless.
As for editing the Reg entry, you do realize I'd have to do it every time I uninstall a dns server or whenever the connection to that server is closed (this happens sometimes when editing the settings): cumbersome as well.
Cumbersome but feasible. I still prefer rolling over dnscrypt-proxy (not to mention Beethoven!).
Thanks again, compatriote :)
