### ISSUE TITLE
LocalCache status and interface without config file

### ISSUE THREAD

**Issue by ssten** [jedisct1/dnscrypt-proxy#566]
In announced with 1.9.0 release config file I see Cache description:

> \#\# Cache DNS responses to avoid outgoing traffic when the same queries
> \#\# are repeated multiple times in a row.
> 
> LocalCache on

But this feature is not mentioned in manual page (_man 8 dnscrypt-proxy_).
What is the status of LocalCache, when I use dnscrypt-proxy without config?
Some kind of option to force it on or off is also needed.
And, possibly, some more detailed description in manual page.

**Comment by jedisct1** [comment]
This is a plugin.

Plugins have never been documented in the proxy man page. Users can choose to compile them or not, to selectively load them or not, and some platforms don't support them, and their availability depends on external libraries.

If that plugin is not loaded, no matter how the proxy is configured, there is no cache.

Plugins are documented in the Wiki, except the vendors-specific ones.

**Comment by physkets** [comment]
Okay, but if the plugin has been loaded, is there an option I can use to enable its use? This is for a situation where I have to use dnscrypt-proxy "without a config file".

**Comment by jedisct1** [comment]
List of plugins and how to activate them from the command line: https://github.com/jedisct1/dnscrypt-proxy/issues/747#issuecomment-331500963

**Comment by jedisct1** [comment]
Duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/747
