### ISSUE TITLE
Installation config files in the root of system config directory instead of package's name subdirectory

### ISSUE THREAD

**Issue by ssten** [jedisct1/dnscrypt-proxy#567]
1.9.0 release by default installs **two** config files: sample and main into root of system's config directory.
For reliable DNS resolving it's recommended to use at least two DNS servers, so user probably will clone sample config to some another(s).

For readability of system's config directory, AFAIR, when package installs more than one config files, they are installed not into top, but into package's subdirectory.
For dnscrypt-proxy and common GNU/Linux the expected path is /etc/dnscrypt-proxy/

**Comment by jedisct1** [comment]
Hi,

There is only one configuration file. The `.example` one is just a template to avoid overwriting an existing configuration file.

The location can always be changed with `--sysconfdir=...` if you prefer a different one.
