### ISSUE TITLE
Problem with latest dnscrypt-proxy 1.9.2

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#568]
Downloaded dnscrypt-proxy-win64-full-1.9.2.zip, removed previous dnscrypt-proxy 1.9.1 and unzipped new version. Same settings, did not use the new 'Include' for common configuration.

I launched dnscrypt-proxy as before, cmd confirmed install, but no service in fact. Uninstalled service, replaced 1.9.2 by previous 1.9.1 and all is fine.

Windows 7 64-bit here.

**Comment by jedisct1** [comment]
Hi,

Can you clarify what you mean with "no service in fact"? The `dnscrypt-proxy` is not listed as `running` in the list of installed services? Not listed at all?

Can you post the configuration file and the exact commands you typed in order to install the service using this configuration file?

**Comment by zymase** [comment]
This is as we say in French "une histoire de fous", a crazy scenario. I hope I'm not nuts myself.
I proceeded again after reading your comment above exactly as I had done as described in my post, and now it runs. I don't understand. There was no dnscrypt-proxy installed, all closed, extracted all new 1.9.2 files, kept all my settings the same (conf file) ... I had no dnscrypt-proxy visible on NirSoft's CurrPorts application but I didn't check then if dnscryot-proxy appeared or not in Windows Services. I had tried with same resolvers, once with cisco on 127.0.0.1:53, the with two resolvers, cs-fr  on 127.0.0.1:53 and cs-fr 2 on 127.0.0.2:53 ... exactly same configs with 1.9.1 and 1.9.2, first fails then succeeds ... I just don't get it.

Anyway, sorry for the bother but I can't feel more sorry than that because I proceeded in the rules, really. Gosh...

**Comment by jedisct1** [comment]
Cosmic rays, probably :)

Glad to hear that everything now works as expected!

**Comment by zymase** [comment]
Perhaps slightly more complex.

Things went this way when I first installed 1.9.2:
1- I used the new keyword Include and consequently built my new conf file as:

> ResolverName cisco
> LocalAddress 127.0.0.1:53
> Include "d:\My Data\DNSCrypt\all-config.conf"

Then I tested, failed. I restored the original conf file and failed again which is why I concluded that the Include keyword was not the culprit.

Now I've tested again with the Include keyword, that is that everything except ResolverName and Local Address has been copied to  "d:\My Data\DNSCrypt\all-config.conf"

Fails. I checked with CurrPorts and dnscrypt-proxy as before is absent. This time I checked as well Windows Services and dnscrypt-proxy appears as automatic but nor as running...

Looks like I have a new friend : Include ...

**Comment by jedisct1** [comment]
If I understand properly, you tried the `Include` keyword, but the parser displayed that the file to be included was not found?

    Include "d:\My Data\DNSCrypt\all-config.conf"

Remove the quotes.

**Comment by zymase** [comment]
Remove the quotes?
But I had been told on another thread here that when a link had spaces it should be written with quotes!

I had mentioned that

> BlackList ips: d:\My Data\DNSCrypt\blacklist-ips.txt
and I was answered that because of the space I should write

> BlackList ips:"d:\My Data\DNSCrypt\blacklist-ips.txt"

How can anyone guess the syntax depends on the keyword?

So it would be
Include d:\My Data\DNSCrypt\all-config.conf

Not to mention that some keywords require the semi:colon ( : ) and some others not.

Well, looks like code is similar to languages with rules in contradiction with coherence and logic ...

I'll try without the quotes... thanks.

**Comment by jedisct1** [comment]
The easiest way is probably to just modify the example configuration file.

Quotes are not required when the whole line contain nothing but a single value.
Quotes are required when a line contains multiple values, so that the distinction between a space in a value and a space between different values can be made.

**Comment by zymase** [comment]
So it is. Well, hard to guess.
**We'll have without quotes**

> Include d:\My Data\DNSCrypt\blacklist-ips.txt

**and**

> BlackList domains:d:\My Data\DNSCrypt\blacklist-domains.txt

**but not** 

> BlackList domains:d:\My Data\DNSCrypt\blacklist-domains.txt logfile:d:\My Data\DNSCrypt\blacklists-log.log

**because the line contains multiple values.** If I had been told that last time we would have spared and your time and mine.

I'm off for sweat dreams, wishing you the same.
