### ISSUE TITLE
Problem with the new Include keyword in dnscrypt-proxy 1.9.2

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#569]
Why are issues so quickly closed? I understand having 256 issues on the list once they've been resolved is a bother except that resolved issues may appear to not be as resolved as they seem: https://github.com/jedisct1/dnscrypt-proxy/issues/568

In a similar way as with https://github.com/jedisct1/dnscrypt-proxy/issues/550 when the LocalCache ttl is of the form _LocalCache on min-ttl:_ and not _LocalCache on with-ttl:_, still not corrected on https://github.com/jedisct1/dnscrypt-proxy/releases by the way ...

I added a new pertinent comment but the issue remains closed. Thanks for having a look. As you like it, of course.

**Comment by jedisct1** [comment]
Can you clarify your question/issue/improvement request?

**Comment by jedisct1** [comment]
I am confused. Is your question about the cache plugin and its `min-ttl` option? Or the `Include` keyword in the config file?

**Comment by zymase** [comment]
You are confused? Less than I am. I've never handled problems here but with you, @jedisct1 yet I've pointed out the context for clarity. i'm sorry but I don't speak Chinese.

**Comment by jedisct1** [comment]
I guess you are pointing out that the release notes had a pasto: `--with-ttl` instead of `--min-ttl`.

This has been fixed, thanks!
