### ISSUE TITLE
unable to initialize plugin ldns

### ISSUE THREAD

**Issue by gotenyama** [jedisct1/dnscrypt-proxy#570]
Hi @jedisct1 ,

I'm having some problems when trying to initialize the ldns plugins for utilizing the blocklist. The error message I got was below.

dnscrypt version - 1.9.2
libsodium - 1.0.9

I'm not sure if related to #149 or not but the plugin system does not seem to like the version of ldns that I'm using.

```
ii  libldns-dev                    1.6.17-5+b1                       amd64        ldns library for DNS programming
```

```
OS: Debian 8.7 jessie
Kernel: x86_64 Linux 3.16.0-4-amd64
```

```
Tue Jan 17 22:17:29 2017 [INFO] - [cisco] does not support DNS Security Extensions
Tue Jan 17 22:17:29 2017 [WARNING] - [cisco] logs your activity - a different provider might be better a choice if privacy is a concern
Tue Jan 17 22:17:29 2017 [INFO] Loading plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so]
Tue Jan 17 22:17:29 2017 [ERROR] Unable to initialize plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so]
Tue Jan 17 22:17:29 2017 [INFO] Loading plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so]
Tue Jan 17 22:17:29 2017 [ERROR] Unable to initialize plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_ldns_blocking.so]
Tue Jan 17 22:17:29 2017 [INFO] Loading plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_logging.so]
Tue Jan 17 22:17:29 2017 [INFO] Loaded plugin: [Log client queries]
Tue Jan 17 22:17:29 2017 [INFO] Loading plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_cache.so]
Tue Jan 17 22:17:29 2017 [INFO] Loaded plugin: [A basic DNS cache]
Tue Jan 17 22:17:29 2017 [ERROR] Unable to load plugins
```

Please let me know if you need any more information.

**Comment by gotenyama** [comment]
Ran the dnscrypt-proxy with level7 debug level logging turned on with nothing except for the logs that I've provided.

**Comment by jedisct1** [comment]
What does your block list look like? And the `Block` list in the config file?
This is very likely to be a syntax error in the way the plugin is called.

Also, with that resolver, there are additional plugins you should use. These can be directly enabled from the configuration file:
* https://github.com/jedisct1/dnscrypt-proxy/blob/master/src/plugins/vendor-specific/example-ldns-opendns-deviceid/CONFIGURATION.txt
* https://github.com/jedisct1/dnscrypt-proxy/blob/master/src/plugins/vendor-specific/example-ldns-opendns-set-client-ip/CONFIGURATION.txt

**Comment by gotenyama** [comment]
Reopening @jedisct1 did you want me to include a gist of the blocklist ? I've made them using the contrib test python from the gihub repo.

**Comment by jedisct1** [comment]
Maybe the path to the file is not good, then?

Granted, plugins should be able to print more descriptive errors, but an API to do so doesn't exist yet :/

**Comment by gotenyama** [comment]
@jedisct1 Here's what I'd ended up doing to get this working. I've had to reduce the blocklist used to generate the dnscrypt-blacklist-domains.txt to less than 1.2 M file. It is now working perfectly.

**Comment by gotenyama** [comment]
Hi,

Re-opening this since re-generating the file `dnscrypt-blacklist-domains.txt` dnscrypt-proxy has stopped blocking any domains. Also interesting enough I can no longer block any domains even using my old files.

###### Current dnscrypt version:
dnscrypt-proxy 1.9.5
Compilation date: Nov 12 2017
Support for plugins: present
Plugins root directory: [/usr/local/lib/dnscrypt-proxy/]
Support for ldns-based plugins: present
Support for the XChaCha20-Poly1305 cipher: present

###### Current libsodium version
libsodium 1.0.15

###### Current files used for domains blacklsit

[dnscrypt-blacklist-domains.txt](https://gist.githubusercontent.com/anonymous/d8796591287fe859a5d814cb1d3dfb7c/raw/2ae5bf7f56146d9a2314fe3eb27addaa0c8e0c5d/dnscrypt-blacklist-domains.txt)

[domains-blacklist.conf](https://gist.githubusercontent.com/anonymous/1cfe9e50d442c4a3a748f6566e964047/raw/22f6505889ae90aad717592b06a593129ddec534/domains-blacklist.conf)
