### ISSUE TITLE
dnscrypt v1.9.3 doesn't work with dnscrypt-loader

### ISSUE THREAD

**Issue by jpgpi250** [jedisct1/dnscrypt-proxy#571]
I've installed / upgraded dnscrypt, using dnscrypt-loader, using these [instructions](https://discourse.pi-hole.net/t/setting-up-and-using-dnscrypt-loader/606). dnscrypt and dnscrypt-loader do not start anymore.
The syslog messages are:
Jan 19 10:06:06 raspberrypi dnscrypt-loader: The path to resolvers.csv on dnscrypt-loader script
Jan 19 10:06:06 raspberrypi dnscrypt-loader: differs from dnscrypt-proxy setup
Jan 19 10:06:06 raspberrypi dnscrypt-loader: Please change dnscrypt-loader 'cCSVBaseDir' and 'cSIGBaseDir' parameters to
Jan 19 10:06:06 raspberrypi dnscrypt-loader: cCSVBaseDir='/'
Jan 19 10:06:06 raspberrypi dnscrypt-loader: cSIGBaseDir='/'
Jan 19 10:06:06 raspberrypi dnscrypt-loader: Edit script at /usr/local/sbin/dnscrypt-loader
Changing the parameters, as indicated by this message doesn't solve the problem...
the resolver.csv files are in /usr/local/share/dnscrypt-proxy, this path matches the configuration in the (unchanged) dnscrypt-loader configuration file (/usr/local/sbin/dnscrypt-loader)

**Comment by jedisct1** [comment]
Hi!

I am not familiar with dnscrypt-loader. This is a distinct project, with a different maintainer and its own repository.

So you'd better ask here https://github.com/GortCodex/DNSCrypt-Loader
