### ISSUE TITLE
multiserver/fallback option

### ISSUE THREAD

**Issue by psyborg55** [jedisct1/dnscrypt-proxy#572]
hi

one of the dns resolvers used often has problems resulting in connectivity loss, requiring to switch to another one.

would be useful if there is an option to list multiple resolvers that checks if current resolver does not return expected result, switches to the next one and restarts service.

or at least an option for a secondary resolver. thanks

**Comment by licaon-kter** [comment]
You use a cacher like Unbound and you run multiple dnscrypt-proxy processes on different ports.

**Comment by jedisct1** [comment]
Properly DNS load balancing / failover is completely different from what dnscrypt-proxy does.

As pointed out by licaon-kter, you should use something like Unbound or even [edgedns](https://github.com/jedisct1/edgedns) for this kind of thing.

**Comment by jedisct1** [comment]
You can also run multiple instances of the proxy on different IP addresses, and use these different IPs in your operating system configuration.
