### ISSUE TITLE
Certificate's serial: what is the expected order of bytes?

### ISSUE THREAD

**Issue by ynikanchyk** [jedisct1/dnscrypt-proxy#573]
In [cert.c](https://github.com/jedisct1/dnscrypt-proxy/blob/master/src/proxy/cert.c#L68), htonl() conversion is applied to serial, ts_begin, ts_start values obtained. At [some server-side implementation](https://github.com/PowerDNS/pdns/blob/rel/rec-4.0.x/pdns/dnscrypt.cc#L101) serial is not converted before signing but tsStart & tsEnd are. 
Question is if [DNSCRYPT-V2-PROTOCOL](https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt) implies that all data are transferred in network-specific order, or it depends on actual data?

**Comment by ynikanchyk** [comment]
Sorry, in a minute after submitting have found the statement: <serial> ::= a 4 byte serial number in big-endian format.

**Comment by jedisct1** [comment]
Hi Yuri,

Yes, this is correct, the serial is in big endian format.
