### ISSUE TITLE
Installation path for dnscrypt-proxy.conf.example

### ISSUE THREAD

**Issue by lahwaacz** [jedisct1/dnscrypt-proxy#575]
First, https://github.com/jedisct1/dnscrypt-proxy/commit/0d8d3f84d4c2a0a34287f84f3497ed144458c5fa does the opposite of what is stated in the commit message: it installs `dnscrypt-proxy.conf.example` when `dnscrypt-proxy.conf` does not exist, and `dnscrypt-proxy.conf` when it exists. This may have caused #574, but please consider also the following.

I assume that the entire point of installing the `.example` file is to avoid overwriting the potentially modified `.conf` file without complicated automatic merging. IMHO this is equally effective to only installing the `.example` under all circumstances and leaving it up to the user to copy it to the right location. (In fact, I think the latter is slightly better, because by copying the user acknowledges that he is responsible for merging the config updates.) Avoiding the conditional in the install script is also much better for packaging.
Another problem is where the "example config" should be installed. Some distributions prefer `/usr/share/doc/<pkgname>/` over `/etc/` (see [here](https://lists.archlinux.org/pipermail/arch-general/2014-May/036386.html) for the reasoning), so there should be a configure option for the path. Or the config could simply not be installed at all - packagers can add a custom command to copy the file to the right path and people installing from source can copy the file from source as well.

**Comment by jedisct1** [comment]
PR ?

**Comment by lahwaacz** [comment]
What is your opinion on the proposed variants and which one would you prefer?

**Comment by jedisct1** [comment]
I'd better avoid being too inventive here.

On all the example I saw using autoconf, the samples and config files were installed in `${DESTDIR}${sysconfdir}`. Do you have example of popular software where this is handled differently?

**Comment by lahwaacz** [comment]
For example wpa_supplicant and lighttpd don't install the configs nor samples at all, which allows the Arch's PKGBUILDs to do [this (line 43)](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/wpa_supplicant#n43) and [this (line 67)](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/lighttpd#n67). I have zero experience with autoconf, but I guess that in this case the `--sysconfdir` option is used only to configure where the config is looked up.

Generally, if the software can be started without any config (i.e. sane defaults are in the software itself), there is no need to install config with defaults. If not, it is perfectly fine to place a config with _generic_ defaults into the `sysconfdir`. But if the config contains uncommented examples that may not work for everybody (i.e. it clasifies as an "example documentation config" as I've written [here](https://lists.archlinux.org/pipermail/arch-general/2014-May/036386.html)), then IMHO it has no place in the `sysconfdir`.

Similarly, checking if the target config already exists from the install script is IMHO rather pointless - this had better be left up to the package manager. People not using it should be aware that their modifications might be overwritten on updates.

**Comment by jedisct1** [comment]
According to the tickets here, most people compile the software themselves instead of using packages, if only because most Linux distros (not Arch!) ship completely outdated packages.

Having to copy a file only present in the source code distribution to the system is a bit weird. And that's one additional step. But well, let's do that.

**Comment by jedisct1** [comment]
What was great about using `sysconfdir` is that the directory is also automatically created and removed by the autoconf scripts. The Android packages got the `/system/etc/dnscrypt-proxy/` directory created and populated, with the example file ready to be edited.
Without this, I don't even know how to explain the procedure.

**Comment by jedisct1** [comment]
Even on other platforms, we will now have a distdir that doesn't include any example. So people will look at an example config file online, and find one that doesn't match the version they have.
Oh fuck, I hate that change, I really do.

**Comment by jedisct1** [comment]
So, on Windows/iOS/Android, the sample is in the package, because there is no source code. But people on Unix won't have the sample in the package, it's in the source code.

**Comment by jedisct1** [comment]
And even the sample systemd file does not make any sense if `/etc/dnscrypt-proxy.conf` is not installed any more.

**Comment by jedisct1** [comment]
What should I say in the `dnscrypt-proxy.service` file since some distros/scripts directly copy the one from the source code ?

```
# Copy the dnscrypt-proxy.conf.example file present in the root directory of the source code distribution to /etc/dnscrypt-proxy.conf,
# and edit it according to your needs. Unless you didn't get this service file from the source distribution
# and something else installed it. In that case, look for a file called `dnscrypt-proxy.conf` somewhere.
# Or maybe `dnscrypt-proxy.conf.example`, so in that case you need to copy it as `dnscrypt-proxy.conf` first.
```

**Comment by jedisct1** [comment]
That `dnscrypt-proxy.service` file is not even supposed to work anyway, because of the hardcoded paths.

**Comment by lahwaacz** [comment]
> What was great about using sysconfdir is that the directory is also automatically created and removed by the autoconf scripts.

You can use [install -D](http://man7.org/linux/man-pages/man1/install.1.html) instead of the `mkdir + cp` combo. Removing files is not the job of the install scripts, that's the job of package managers.

> Without this, I don't even know how to explain the procedure.

For sure every other 3rd party man page on my system contains wrong paths to some config files or documentation, because the software was developed for other platform or distribution and the authors hardcoded the paths used on their system. As embarrassing as that is, I don't think there is a real solution.

> So, on Windows/iOS/Android, the sample is in the package, because there is no source code. But people on Unix won't have the sample in the package, it's in the source code.

AFAIK there are [official binary packages](https://download.dnscrypt.org/dnscrypt-proxy/) only for Windows/iOS/Android, so what's the point?

> And even the sample systemd file does not make any sense if /etc/dnscrypt-proxy.conf is not installed any more.

It hasn't made sense even with the sample config, because [please-change-the-resolver-name-in-the-config-file](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy.conf#L14) is not a valid resolver name. systemd assumes that every installed service is functional even before users edit some configs, which is simply not the case of dnscrypt-proxy.

> What should I say in the dnscrypt-proxy.service file since some distros/scripts directly copy the one from the source code ?

Don't explain it in the systemd service, but in the man page. Let the service contain just

    ExecStart=/usr/sbin/dnscrypt-proxy <options or config path>

Also note that the path to `dnscrypt-proxy` depends on the `--sbindir` autoconf option (e.g. in Arch it works only because `/usr/sbin/` is a symlink to `/usr/bin/`, which is where `dnscrypt-proxy` is installed). If you inisist on providing a fully functional systemd unit, you might convert this to an autoconf template.

**Comment by jedisct1** [comment]
I would just love to get rid of that systemshit config file, but some people apparently want it.

**Comment by jedisct1** [comment]
They apparently even expect it to work unmodified. And I think that was the case for Arch Linux.

**Comment by jedisct1** [comment]
You can't expect the `install` command to be present or to support `-D`. That what the autoconf script test for and provide alternative implementations for.

**Comment by jedisct1** [comment]
So probably the systemd files should be renamed `.example` as well.

**Comment by jedisct1** [comment]
And the `plist` file as well.

**Comment by jedisct1** [comment]
In `$docdir`?

I don't know. Looks like openbsd ports have to modify all the things using `docdir`.

**Comment by jedisct1** [comment]
Non-Linux users don't give a fuck about the `plist` and `systemd` files, so these shouldn't be installed.

**Comment by jedisct1** [comment]
Essentially the only thing that can be installed is the example config file. Does it make sense to have that thing alone in `$docdir`?

**Comment by jedisct1** [comment]
And maybe the vendor-specific README files.

**Comment by jedisct1** [comment]
Sorry, it's too complicated. I don't know how to do that, and I don't have more time to spend on it.

**Comment by jedisct1** [comment]
Feel free to remove the package from Arch Linux if this is a problem.

Sorry. I give up.

**Comment by jedisct1** [comment]
The resolver name can now be set to `random` in order to pick a random name at startup.

So the default configuration file can now be used as-is in most cases.
