### ISSUE TITLE
Android init script failing with fast key rotating servers

### ISSUE THREAD

**Issue by elgab** [jedisct1/dnscrypt-proxy#579]
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dist-build/android-files/system/etc/init.d/99dnscrypt#L9

3600 will return 2 warnings
"The certificate is not valid for the given safety margin"
"Safety margin wider than the certificate validity period"

1440 will return 1 warning
"The certificate is not valid for the given safety margin"

using 720 returns 0 warnings, proxy should work.
--test=120 should fix for good https://github.com/jedisct1/dnscrypt-proxy/issues/479

**Comment by jedisct1** [comment]
`720` is the margin used by the docker image before switching to a new key, so yes, this is the maximum value that should be used.
Or to avoid a race condition, use a slightly lower value such as `700`.
