### ISSUE TITLE
Homebrew instructions are terrible and I don't know what to do

### ISSUE THREAD

**Issue by taoeffect** [jedisct1/dnscrypt-proxy#582]
There is a file on OS X that acts as the systemd equivalent and selects the server: `/Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist`

However, edits to that file get overwritten and lost.

`brew info dnscrypt-proxy` doesn't even mention that file (directly) except to say that to start dnscrypt-proxy on login you need to run `sudo brew services start dnscrypt-proxy`.

It does, however, mention a non-existent file `/usr/local/etc/dnscrypt-proxy.conf`, with no instructions on how to edit it or whatever.

Given that the launchd plist will probably override anything in the .conf file, I'm guessing even if I did know what to put in there it probably would have no effect.

So, how do I force dnscrypt-proxy to respect the `--resolver-name=dnscrypt.eu-dk` setting in the launchd plist and stop overriding it?

**Comment by chew-z** [comment]
launchd and conf file are sort of alternatives. Conf is a new way of doing thing since version 1.8 and 1.9. Simply speaking the old way of doing things was to specify every single startup option and argumnets in plist file. Now you can do that in .conf file and in plist just give one argument  location of your .conf file. 
And yes, brew info is kind of bad at the moment. And .plist file is overwritten with every relase so you have to take care of that yourself.

```
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy</string>
      <string>--local-address=127.0.0.1:53</string>
      <string>--logfile=/var/log/dnscrypt-proxy.log</string>
      <string>--max-active-requests=256</string>
      <string>--resolvers-list=/usr/local/opt/dnscrypt-proxy/share/dnscrypt-proxy/dnscrypt-resolvers.csv</string>
      <string>--resolver-name=ns0.dnscrypt.is</string>
      <string>--plugin=libdcplugin_example_ldns_aaaa_blocking.so</string>
      <string>--plugin=libdcplugin_example_logging.so,/var/log/dnscrypt-queries.log</string>
      <string>--plugin=libdcplugin_example_ldns_blocking.so,--domains=/usr/local/etc/dnscrypt-proxy/blacklist-domains,--ips=/usr/local/etc/dnscrypt-proxy/blacklist-ips,--logfile=/var/log/dnscrypt-blocks.log</string>
      <string>--plugin=libdcplugin_geoip_block.so,--blacklist=/usr/local/etc/dnscrypt-proxy/blacklist-countries,--geoipdb=/usr/local/var/GeoIP/GeoIP.dat</string>
      <string>--plugin=libdcplugin_example_cache.so</string>
      <string>--user=nobody</string>
    </array>
```

And now 
```

    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy</string>
      <string>/usr/local/etc/dnscrypt-proxy.conf</string>
    </array>
```

**Comment by jedisct1** [comment]
The `.plist` file being overwritten shouldn't be an issue any more now that we have a config file :)

**Comment by taoeffect** [comment]
Ah, I see, I forgot to run `brew upgrade dnscrypt-proxy`, that's why the conf file wasn't there. Thanks so much for your help!
