### ISSUE TITLE
Failed to start DNSCrypt client proxy when system boot.

### ISSUE THREAD

**Issue by tannx** [jedisct1/dnscrypt-proxy#583]
`OS: debian testing 4.5.5.1`
`dnscrypt-proxy 1.7.0`

Starting DNSCrypt client proxy...
dnscrypt-proxy[606]: /usr/sbin/dnscrypt-proxy: symbol lookup error: /usr/sbin/dnscrypt-proxy: undefined symbol: crypto_core_hchacha20
systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=127/n/a
systemd[1]: Failed to start DNSCrypt client proxy.
systemd[1]: dnscrypt-proxy.service: Unit entered failed state.
systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
systemd[1]: Started Modem Manager.
systemd[1]: dnscrypt-proxy.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped DNSCrypt client proxy.

**Comment by licaon-kter** [comment]
Installed from packages or?

**Comment by tannx** [comment]
yup, from packages.

**Comment by jedisct1** [comment]
The `dnscrypt-proxy` binary was compiled using a `libsodium` version that is way newer than the one installed on the system.

Where does that package come from?

**Comment by tannx** [comment]
just update the libsodium, it's work. thank you!
