### ISSUE TITLE
Option to send queries using UDP or TCP first

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jedisct1/dnscrypt-proxy#584]
With this option an user can define which of them used firstly, then other procotol used as fallback. This option shouldn’t enabled by default until user specified.

**Comment by jedisct1** [comment]
Hi Krasnaya,

The protocol is actually defined by the client. If the client uses UDP, the dnscrypt query will use UDP (and then TCP if truncation is required). If the client uses TCP, it will use TCP. The proxy itself does not change the transport type.

What is your use case for this?
