### ISSUE TITLE
question about v1.9.4 implementation

### ISSUE THREAD

**Issue by jpgpi250** [jedisct1/dnscrypt-proxy#585]
This is NOT an issue, at least I hope it isn't, this is a question to understand what is going on.

Running dnscrypt-proxy on a raspberry pi 3 model B, using the latest build of raspbian jessie lite.
The primary program is [pi-hole](https://pi-hole.net/), witch is basically dnsmasq. I've upgraded dnsmasq from v2.72 to v2.76, as there seem to be [issues](http://serverfault.com/questions/720293/dnsmasq-returns-false-bogus-result-for-dnssec-validation) with earlier versions. I used these [instructions](http://raspberrypi.stackexchange.com/questions/59435/how-to-use-stretch-testing-packages) to upgrade dnsmasq, after the upgrade was completed, i removed the additional repositories, so the system is only running 1 stretch package. The system is fully upgraded.

I installed dnscrypt-proxy, using these [instructions](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt), but modified the number of resolvers, the ip addresses and the ports. To avoid listing all these files, you can download a [rar file](http://users.telenet.be/MySQLplaylist/dnscrypt-proxy-v1.9.4.rar), containing the resulting files. As indicated in the wiki instructions. the service and socket files go into /lib/systemd/system, the conf file, containing the server settings goes into /etc/dnsmasq.d

I managed to get things running (some hiccups - inactive(dead)) but ended up with a working system.
So I assumed I would be using the 4 resolvers, specified in the four socket files, but when doing a [dns leak](https://dnsleaktest.com/) test, I noticed I was using different servers all the time, not even specified in the socket files.
After some digging, I found this [change document](https://fossies.org/diffs/dnscrypt-proxy/1.9.3_vs_1.9.4/dnscrypt-proxy.conf-diff.html), explaining the random behaviour.

Finally, the question: How do I configure the system to use the four resolvers, specified in the socket files, and eliminate the random behaviour. I assumed it already was, because off the log entries, but the dns leak test proved me wrong :
Feb  1 06:18:21 dnsmasq[9141]: forwarded archive.raspberrypi.org to 127.10.10.4
Feb  1 06:18:21 dnsmasq[9141]: forwarded archive.raspberrypi.org to 127.10.10.3
Feb  1 06:18:21 dnsmasq[9141]: forwarded archive.raspberrypi.org to 127.10.10.2
Feb  1 06:18:21 dnsmasq[9141]: forwarded archive.raspberrypi.org to 127.10.10.1

Thank you for your time and response

**Comment by jedisct1** [comment]
```
ExecStart=/usr/local/sbin/dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
        --resolver-name=%i \
        --user=dnscrypt
```

This is loading a configuration file from `/usr/local/etc/dnscrypt-proxy.conf`.
Remove that if you just want to specify options from the command-line.

**Comment by jpgpi250** [comment]
I tried removing all of it, rebooted, the instances are no longer loaded:
pi@raspberrypi:~ $ ps ax | grep dnscrypt
  827 pts/0    S+     0:00 grep --color=auto dnscrypt
DNS is broken, pages no longer load
I tried removing just "/usr/local/etc/dnscrypt-proxy.conf", keep the rest, rebooted, the instances load:
pi@raspberrypi:~ $ ps ax | grep dnscrypt
  589 ?        SLs    0:00 /usr/local/sbin/dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
  590 ?        SLs    0:00 /usr/local/sbin/dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
  593 ?        SLs    0:00 /usr/local/sbin/dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
  594 ?        SLs    0:00 /usr/local/sbin/dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
  866 pts/0    S+     0:00 grep --color=auto dnscrypt

The pages load now, however, the result however is the same, the random setting seems to be activated, probably a default.
The question remains: How do I configure the system to use the four resolvers, specified in the socket files, and eliminate the random behavior, **automatically**, no after care or command line intervention?

**Comment by jpgpi250** [comment]
I think I found it, please confirm. It should read (backslash at he end)

`ExecStart=/usr/local/sbin/dnscrypt-proxy \`
`	--resolver-name=%i \`
`	--user=dnscrypt`

**Comment by jedisct1** [comment]
Yes, that should do it.

Sorry, I don't know anything about pi-hole and I don't even have the hardware to install it.
