### ISSUE TITLE
Just a question regarding a second resolver

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#586]
dnscrypt-proxy 1.9.4 running fine, be it with one as with two resolvers. The new Doc folder's content much appreciated.

Simple curiosity, when two resolvers when does the second become active? Is it only if the first appears to be broken, is it when the first is too long to respond, or do both work concurrently letting the fastest resolve?

**Comment by jedisct1** [comment]
`dnscrypt-proxy` handles a single resolver. Are you referring to Simple DNSCrypt? I think it uses the secondary one after the first one times out.

**Comment by zymase** [comment]
What?! dnscrypt-proxy handles a single resolver?

I'm talking about dnscrypt-proxy 1.9.4, not about Simple DNSCrypt. I know Simple DNSCrypt enabled a secondary resolver starting its version 0.3.7 but as I had understood it bitbeans was waiting for an update of dnscrypt-proxy as a requisite.

From there on, and considering what was made available for dnscrypt-proxy, the conf file, I believed that latest dnscrypt-proxy handled two resolvers (or more) basically speaking.

Most of the time I use only 1 resolver, but I happe to use 2 (reading you would mean the second never interfers?) by proceeding as follow:

1- A batch file to start two conf files:
```
B2-cs-cf.bat
@echo off
cmd.exe /c "dnscrypt-proxy.exe --install-with-config-file=B1-cs-cfi.conf"
cmd.exe /c "dnscrypt-proxy.exe --install-with-config-file=B2-cs-cfii.conf --service-name=dnscrypt-proxy-2"
cmd.exe /k "c:\Program Files (x86)\DnsJumper\DnsJumper.exe" 127.0.0.1,127.0.0.2
```

2.1- B1-cs-fr.conf
```
######  CONFIGURATION FILE FOR DNSCRYPT-PROXY  ######
ResolverName cs-fr
LocalAddress 127.0.0.1:53
Include d:\My Data\DNSCrypt\all-config.conf
```

2.2- B2-cs-fr2.conf
```
######  CONFIGURATION FILE FOR DNSCRYPT-PROXY-2  ######
ResolverName cs-fr2
LocalAddress 127.0.0.2:53
Include d:\My Data\DNSCrypt\all-config.conf
```
And I have dnscrypt-proxy and dnscrypt-proxy-2 running ... if I read you correctly two are running but only the first is active, if it fails the secondary resolver is meaningless?

I really like dnscrypt-proxy but I've never encountered so many surprises with an application :)

**Comment by jedisct1** [comment]
So you configured `127.0.0.1` and `127.0.0.2` as DNS resolvers in the Windows TCP/IP network preference pane. How Windows uses the set of provided resolvers IP addresses is independent from `dnscrypt-proxy`, but Google instantaneously found this answer, that seems to summarize pretty well how it works: https://serverfault.com/questions/84291/how-does-windows-decides-which-dns-server-to-use-when-resolving-names

**Comment by zymase** [comment]
Thanks for the link leading to an interesting explanation.
That's for my initial question,  that of this thread.

When you write above 'dnscrypt-proxy handles a single resolver.", how does this assertion play in the game? I'm sure it's clear in your mind but having a developer tell you a feature doesn't exist then send you to an article describing how it works is confusing. 

At this point, and given my description aboven do I have one ot two operational dnscrypt-proxies? This becomes my second question. Mama mia ...

I love your work, @jedisct1 but there's a communication problem :)

**Comment by jedisct1** [comment]
You can have as many instances of dnscrypt-proxy as you like, provided than they listen to different addresses. This is what you did. Each instance handles a single resolver. So, you have 2 IP addresses that can be used to resolve names, and they forward queries to 2 different resolvers.

This is similar to using Google DNS where one usually uses both `8.8.8.8` and `8.8.4.4` as resolver addresses.

How the load is balanced across these IP addresses depends on the operating system or intermediary cache. This is what sends the queries to these IP addresses.

**Comment by zymase** [comment]
OK. In fact dnscrypt-proxy pauses its task where the Windows TCP/IP network starts it, and that the DNS resolvers be those handled by dnscrypt-proxy or be they any other resolver (Google DNS as you mention it, OpenDNS, etc etc, the process is the same. Fine.

And thanks :)
