### ISSUE TITLE
DNSSEC enabled?

### ISSUE THREAD

**Issue by jpgpi250** [jedisct1/dnscrypt-proxy#587]
I've configured my system to use dnscrypt-proxy, using this [guide](https://github.com/pi-hole/pi-hole/wiki/DNSCrypt). The resulting files can be downloaded [here](http://users.telenet.be/MySQLplaylist/dnscrypt-proxy-v1.9.4.rar). As instructed, I ran **sudo systemctl status -l dnscrypt-proxy@\*** to get the system status, this is the result (notice there is only one resolver that says **DNS Security Extensions are supported**)
I'm getting al kind of weird results (lots of INSECURE, some ABANDONED and very few SECURE results) in the logs of dnsmasq, and wondered if the resolvers I'm using are even DNSSEC enabled (apart from the one that says it), even though the list ([dnscrypt-resolvers.csv](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv)) says they are.

A second question I have (I'm not a linux goeroe) is how to remove the symbolic link for resolvers I don't want to use anymore.
Registering is, as per instructions:
sudo cp ./dnscrypt-proxy@* /lib/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable dnscrypt-proxy@.service

below, the output from **sudo systemctl status -l dnscrypt-proxy@\***
 sudo systemctl status -l dnscrypt-proxy@\*
● dnscrypt-proxy@dnscrypt.eu-dk.service - DNSCrypt client proxy
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy@.service; enabled)
   Active: active (running) since Sun 2017-02-05 10:15:39 CET; 35s ago
     Docs: man:dnscrypt-proxy(8)
 Main PID: 592 (dnscrypt-proxy)
   CGroup: /system.slice/system-dnscrypt\x2dproxy.slice/dnscrypt-proxy@dnscrypt.eu-dk.service
           └─592 /usr/local/sbin/dnscrypt-proxy --resolver-name=dnscrypt.eu-dk --user=dnscrypt

Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] + Provider supposedly doesn't keep logs
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] Generating a new session key pair
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] Done
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] Server certificate with serial '0001' received
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] This certificate is valid
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] Chosen certificate #808464433 is valid from [2016-09-10] to [2017-09-10]
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3C24:BFF3:2BF7:B406:108B:44DA:51FE:3711
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[592]: Sun Feb  5 10:15:40 2017 [NOTICE] Proxying from 127.10.10.4:5554 to 77.66.84.233:443

● dnscrypt-proxy@ns0.dnscrypt.is.service - DNSCrypt client proxy
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy@.service; enabled)
   Active: active (running) since Sun 2017-02-05 10:15:39 CET; 35s ago
     Docs: man:dnscrypt-proxy(8)
 Main PID: 593 (dnscrypt-proxy)
   CGroup: /system.slice/system-dnscrypt\x2dproxy.slice/dnscrypt-proxy@ns0.dnscrypt.is.service
           └─593 /usr/local/sbin/dnscrypt-proxy --resolver-name=ns0.dnscrypt.is --user=dnscrypt

Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] + Provider supposedly doesn't keep logs
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] Generating a new session key pair
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] Done
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] Server certificate with serial #1482946221 received
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] This certificate is valid
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] Chosen certificate #1482946221 is valid from [2016-12-28] to [2017-12-28]
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [INFO] Server key fingerprint is 061C:F483:39D2:A4DA:610F:E934:F3AE:50BE:E19E:6F6F:04EA:123D:7548:28BA:733E:7555
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[593]: Sun Feb  5 10:15:40 2017 [NOTICE] Proxying from 127.10.10.2:5552 to 93.95.228.87:443

● dnscrypt-proxy@dnscrypt.eu-nl.service - DNSCrypt client proxy
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy@.service; enabled)
   Active: active (running) since Sun 2017-02-05 10:15:39 CET; 35s ago
     Docs: man:dnscrypt-proxy(8)
 Main PID: 596 (dnscrypt-proxy)
   CGroup: /system.slice/system-dnscrypt\x2dproxy.slice/dnscrypt-proxy@dnscrypt.eu-nl.service
           └─596 /usr/local/sbin/dnscrypt-proxy --resolver-name=dnscrypt.eu-nl --user=dnscrypt

Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] + Provider supposedly doesn't keep logs
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] Generating a new session key pair
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] Done
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] Server certificate with serial '0001' received
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] This certificate is valid
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] Chosen certificate #808464433 is valid from [2016-09-08] to [2017-09-08]
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [INFO] Server key fingerprint is 72DF:BE14:531F:F2AD:FD0F:BC8B:F711:B93D:799F:E4D0:34EC:D26B:8BF9:FFA9:32E7:2B79
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[596]: Sun Feb  5 10:15:40 2017 [NOTICE] Proxying from 127.10.10.3:5553 to 176.56.237.171:443

● dnscrypt-proxy@dnscrypt.org-fr.service - DNSCrypt client proxy
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy@.service; enabled)
   Active: active (running) since Sun 2017-02-05 10:15:39 CET; 35s ago
     Docs: man:dnscrypt-proxy(8)
 Main PID: 597 (dnscrypt-proxy)
   CGroup: /system.slice/system-dnscrypt\x2dproxy.slice/dnscrypt-proxy@dnscrypt.org-fr.service
           └─597 /usr/local/sbin/dnscrypt-proxy --resolver-name=dnscrypt.org-fr --user=dnscrypt

Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] + **DNS Security Extensions are supported**
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] + Provider supposedly doesn't keep logs
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] Generating a new session key pair
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] Done
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] Server certificate with serial #1486267627 received
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] This certificate is valid
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] Chosen certificate #1486267627 is valid from [2017-02-05] to [2017-02-06]
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [INFO] Server key fingerprint is B46C:103D:E331:CCD6:4A36:9C2C:F945:3E58:C925:39A5:FD14:2F50:72A9:F88A:E431:3736
Feb 05 10:15:40 raspberrypi dnscrypt-proxy[597]: Sun Feb  5 10:15:40 2017 [NOTICE] Proxying from 127.10.10.1:5551 to 212.47.228.136:443

Eagerly awaiting your response
Thank you for your time and effort

**Comment by jpgpi250** [comment]
Additional information regarding this question
As instructed by the developer of dnsmasq, I'm running the following command (in a loop), using this script (4 different script, each running in a putty session, only listing the code for the first resolver):
#!/bin/bash
while true
do
	dig @127.10.10.1 -p 5551 +dnssec www.raspberrypi.org
	date
	sleep 30
done

the results from these commands are:
**dig @127.10.10.4 -p 5554 +dnssec www.raspberrypi.org**
; <<>> DiG 9.9.5-9+deb8u9-Raspbian <<>> @127.10.10.4 -p 5554 +dnssec www.raspberrypi.org
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
**dig @127.10.10.3 -p 5553 +dnssec www.raspberrypi.org**
; <<>> DiG 9.9.5-9+deb8u9-Raspbian <<>> @127.10.10.3 -p 5553 +dnssec www.raspberrypi.org
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
**dig @127.10.10.2 -p 5552 +dnssec www.raspberrypi.org**
;; Truncated, retrying in TCP mode.
;; communications error to 127.10.10.2#5552: end of file
**dig @127.10.10.1 -p 5551 +dnssec www.raspberrypi.org**
; <<>> DiG 9.9.5-9+deb8u9-Raspbian <<>> @127.10.10.1 -p 5551 +dnssec www.raspberrypi.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46235
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 001b , udp: 1252
;; QUESTION SECTION:
;www.raspberrypi.org.           IN      A

;; ANSWER SECTION:
www.raspberrypi.org.    27      IN      CNAME   lb.raspberrypi.org.
www.raspberrypi.org.    27      IN      RRSIG   CNAME 10 3 300 20170306194909 20170204193456 59405 raspberrypi.org. J7RAY2LtCH+7tdCiY29e5XSMT8Q/M9OHBClcXFwwolRSiRL3kJ92lzwn q5w1oLDjwDQMpDzGI0Xqtz2utLkJyJ7EhteEz9v0zdjpgNqz6/bNUv7c hVJPlXm2VOGfGErVhwBc4ueC0jDxQcT8qGCfb56ZwrIN6g+mXzje/FQM 9s6R9+RvSZBoRu/lB4u/Pyw6xIQuKTI40pnWSm67UC69NtKWPuslynmp 9//5fGaUhF6C5jUGTTPND7G7gtJtrBswa8xWz27UU35u2m+OISHior+C 04Vy4BKNzhzmoqKMj9b/erP7b2c1dSJBRM+3HopQV7TCcA/iIfTmMccu NnPTwA==
lb.raspberrypi.org.     27      IN      A       93.93.130.104
lb.raspberrypi.org.     27      IN      A       93.93.128.133
lb.raspberrypi.org.     27      IN      A       93.93.130.214
lb.raspberrypi.org.     27      IN      A       46.235.227.11
lb.raspberrypi.org.     27      IN      A       93.93.128.230
lb.raspberrypi.org.     27      IN      A       93.93.130.39
lb.raspberrypi.org.     27      IN      RRSIG   A 10 3 300 20170306195401 20170204193456 59405 raspberrypi.org. 65iVHeB0bZQBBt803j2zp9J/cE/Af38hTddv576dc/ol08y7vBhVWdKl jplFpnx3WAMMJZsl0Cn7+cLLx6NkVaFz2lS5pbE1IIx23mZzayIqx9dQ vJCbqgLlHo9OyrvaFJyLP/ory/+A0hSxvab1d7ur1Mms//tgrGagozy1 UPxx4d2/PBK5JIWBx+lDe9RI+dYjjq9luL5cYT/MJKHSkuPBzL2uLP+Y uJgIpFAPgt0O8DiLojYv5COD6MuRFcHYuSGiC3VwRpA6f8Ob9qTvBX3h ghisIKPFRuKO14wN7BPdT/gLscwKgArJ4pcPhDwFI6up4HnJrRcjQM88 Pg6k/A==

;; Query time: 34 msec
;; SERVER: 127.10.10.1#5551(127.10.10.1)
;; WHEN: Sun Feb 05 12:06:10 CET 2017
;; MSG SIZE  rcvd: 767

**Note that the results from 127.10.10.2#5552 are only like this for a while, after a reboot**
;; Truncated, retrying in TCP mode.
;; communications error to 127.10.10.2#5552: end of file
**After some time, this changes into:**
; <<>> DiG 9.9.5-9+deb8u9-Raspbian <<>> @127.10.10.2 -p 5552 +dnssec www.raspberrypi.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37547
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 9, AUTHORITY: 3, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;www.raspberrypi.org.           IN      A

;; ANSWER SECTION:
www.raspberrypi.org.    209     IN      CNAME   lb.raspberrypi.org.
www.raspberrypi.org.    209     IN      RRSIG   CNAME 10 3 300 20170306194909 20170204193456 59405 raspberrypi.org. J7RAY2LtCH+7tdCiY29e5XSMT8Q/M9OHBClcXFwwolRSiRL3kJ92lzwn q5w1oLDjwDQMpDzGI0Xqtz2utLkJyJ7EhteEz9v0zdjpgNqz6/bNUv7c hVJPlXm2VOGfGErVhwBc4ueC0jDxQcT8qGCfb56ZwrIN6g+mXzje/FQM 9s6R9+RvSZBoRu/lB4u/Pyw6xIQuKTI40pnWSm67UC69NtKWPuslynmp 9//5fGaUhF6C5jUGTTPND7G7gtJtrBswa8xWz27UU35u2m+OISHior+C 04Vy4BKNzhzmoqKMj9b/erP7b2c1dSJBRM+3HopQV7TCcA/iIfTmMccu NnPTwA==
lb.raspberrypi.org.     210     IN      A       46.235.227.11
lb.raspberrypi.org.     210     IN      A       93.93.130.104
lb.raspberrypi.org.     210     IN      A       93.93.130.214
lb.raspberrypi.org.     210     IN      A       93.93.128.133
lb.raspberrypi.org.     210     IN      A       93.93.128.230
lb.raspberrypi.org.     210     IN      A       93.93.130.39
lb.raspberrypi.org.     210     IN      RRSIG   A 10 3 300 20170306195401 20170204193456 59405 raspberrypi.org. 65iVHeB0bZQBBt803j2zp9J/cE/Af38hTddv576dc/ol08y7vBhVWdKl jplFpnx3WAMMJZsl0Cn7+cLLx6NkVaFz2lS5pbE1IIx23mZzayIqx9dQ vJCbqgLlHo9OyrvaFJyLP/ory/+A0hSxvab1d7ur1Mms//tgrGagozy1 UPxx4d2/PBK5JIWBx+lDe9RI+dYjjq9luL5cYT/MJKHSkuPBzL2uLP+Y uJgIpFAPgt0O8DiLojYv5COD6MuRFcHYuSGiC3VwRpA6f8Ob9qTvBX3h ghisIKPFRuKO14wN7BPdT/gLscwKgArJ4pcPhDwFI6up4HnJrRcjQM88 Pg6k/A==

;; AUTHORITY SECTION:
raspberrypi.org.        22429   IN      NS      ns1.mythic-beasts.com.
raspberrypi.org.        22429   IN      NS      ns2.mythic-beasts.com.
raspberrypi.org.        22429   IN      RRSIG   NS 10 2 86400 20170306201032 20170204193456 59405 raspberrypi.org. Mz2EKx5jFra3Lpy6RhG5F8UyfgqIrOT5DYJrIcgdvokb1ZGs2guckjGG 4gVNdyVOtCrDPmhSR0m1caFqSuuoN9NyaNNRc7FY6RkefVvGYBM1zSjw QUuKWNpAxQ24644z+wMvi3WEDjZssxDdG7HjdCgKH3JS1CJo4EblfXol V9lI0bBNA8yBJ12Zg8DtKV3Popj6VBs8m9t7lE/jmbreFQSqaLRwJfdY cFEUyzxJqZizHq/hVDX71uQqXJINRJFncQr2idvXfihzdgWbiz3QfkkC xDhRiUwaNiy/Blr4wsWi3kxODOzpzH4jJH9aBEpfVDqJ97tgFP3LF89S t07k5Q==

;; Query time: 68 msec
;; SERVER: 127.10.10.2#5552(127.10.10.2)
;; WHEN: Sun Feb 05 12:09:15 CET 2017
;; MSG SIZE  rcvd: 1123

Sun  5 Feb 12:09:15 CET 2017

I noticed in dnscrypt-resolvers.csv the server dnscrypt.org-fr (matches 127.10.10.1 -p 5551) is the only server listed as a **version 2** server

**Comment by jedisct1** [comment]
Truncated responses are not an error. They tell the client to send the query again using TCP.

In order to avoid amplification, the DNSCrypt protocol requires questions sent using UDP to be at least as large as responses. If this is not the case, a truncated response is sent so that the client retries using TCP.

When it starts, the proxy slowly adjusts the padding of the questions so that less and less queries using TCP are required.

**Comment by jedisct1** [comment]
You know this environment way better than I do, but in order to remove a service, this may work:
```sh
sudo systemctl disable dnscrypt-proxy@<service name>
sudo rm /lib/systemd/system/dnscrypt-proxy@<service name>
sudo systemctl daemon-reload
```

**Comment by jpgpi250** [comment]
Thank you for your replies.
Any thoughts on the time-outs (;; connection timed out; no servers could be reached) and on whether or NOT the servers are truely DNSSEC enabled?

**Comment by jpgpi250** [comment]
I'm so sorry to keep harassing you but I just found this [topic](https://discourse.pi-hole.net/t/running-dnscrypt-and-dnssec-using-debian-testing-repositories/1622).
I've been using one (1) service file and four (4) socket files (see the [rar file](http://users.telenet.be/MySQLplaylist/dnscrypt-proxy-v1.9.4.rar)).
The method, used in the topic, i found, uses 2 service files and no socket file(s). This is how it looks:
[Unit]
Description=Secure connection between your computer and DNS resolver
After=network.target network-online.target
[Service]
Type=forking
Restart=always
RestartSec=5
PIDFile=/var/run/dnscrypt-proxy.pid
ExecStart=/usr/local/sbin/dnscrypt-proxy --daemonize \
-a 127.0.0.2:40 \
-R dnscrypt.eu-nl \
-E \
--edns-payload-size=4096 \
-p /var/run/dnscrypt-proxy.pid
[Install]
WantedBy=multi-user.target

Could you please explain the advantage of using the different methods and possibly provide an explanation for the various settings? I already noticed the proxy will be running as root.
Does the method I found in the topic allow for multiple (more than 2) resolvers?1

Thank you so much...

**Comment by zymase** [comment]
> [...] whether or NOT the servers are truely DNSSEC enabled?
I may be totally off-topic but I know the following possibility to check if a DNS server supports factually DNSSEC:

From https://dns.d0wn.biz/, at the bottom of the page, _Additional Information_:

> All servers are supporting DNSSEC. You could test it by opening sigfail.verteiltesysteme.net. You should get an error. If you test sigok.verteilesysteme.net you should see a blank page.

I've checked servers stated in dnscrypt-resolvers.csv as supporting or not DNSSEC and the results for those I've tested corroborated the statements.

**Comment by jpgpi250** [comment]
@zymase 
Thank you for this
In the mean time, I've reduced my configuration from four resolvers down to just one.
Using your links is great in such a configuration (using just one resolver)
this are the results:
Fail test (page should fail to load): dnsmasq validation: BOGUS, page failed to load
OK test (a blank page should load): dnsmasq validation: ABONDONED, a blank page did load, the validation should be SECURE!
One question though: Is it possible to use these test when you have multiple resolvers (I originally had four). It seems to me you can never tell witch resolver answered (unless of course you start analyzing logs)

**Comment by zymase** [comment]
As I understand it these test page are pertinent to the dns server which resolved them, and therefor you'd have to test one server after another.

I was concerned as well with how several resolvers interact when I noticed that a DNS leak test would never give results but for the resolver used, called (it doesn't test one resolver after another but only the "active" one), which is why I initiated #586, and in the context of Windows. It appears that it's the OS which decides when, how one resolver will be used rather than the other, with the first listed as default and most of the time persistent. At least on Windows.

That's all I know, the strict basics...

**Comment by jpgpi250** [comment]
the developer of dnsmaq (there is an email address on [this page](http://www.thekelleys.org.uk/dnsmasq/doc.html)) just left me a message with his analysis. I've asked him to contact you.
This was his messages (regarding this problem):
So, looking at the data you've gathered so far, what I think is happening is this.

1) Client sends request over UDP
2) Dnsmasq forwards request over UDP to dnscrypt
3) Dnscrypt returns synthetic "truncated" answer, for it's own reason which are irrelevant.
4) Dnsmasq returns truncated answer to client in order to prompt it to-
5) Client retries query over TCP to dnsmasq
6) Dnsmasq sends query over TCP to dnscrypt.
7) dnscrypt replies over TCP
8) dnsmasq needs to make further queries to validate DNSSEC signatures, which it does over TCP to dnscrypt.
9) dnscrypt closes the TCP connection without replying to a query.
10) Dnsmasq reacts to the closed TCP connection by ABANDONing the validation and returns an error.
11) Whole lookup fails.
There's no doubt that dnsmasq could respond better to the closed TCP connection, but the crucial thing here seems to be that dnscrypt is closing TCP connections without accepting queries, or without returning a reply. You can see this happening every time your "dig"
test shows the error

;; Truncated, retrying in TCP mode.
;; communications error to 127.10.10.2#5552: end of file

The TCP retry is seeing the TCP connection closed (which is what generates the end-of-file condition.

**It would be very interesting to know the situation(s) under which dnscrypt is expected to do this.**

**Comment by zymase** [comment]
I'm a kindergarten kid discussing with graduates. I hardly understand the basics of Windows, I'm totally illiterate when it comes to coding, networks, computing as a whole and UNIX which is as far as I understand it the infrastructure in which dnscrypt-proxy has been developed is for me another universe, the Twilight Zone, one  step beyond.

I'm exercising modesty because for once it applies ;) I came and come here (as any other place filled with brains) when I cannot understand and wish at the same time use an application, code etc... what I mean @jpgpi250  is that I have but common sense to very partially fill the gap of my ignorance, such as above with the links to test DNSSEC effectiveness.

Frankly : I understand just a very tiny bit (not even a byte!) of the problem you expose, not because it would be poorly exposed but because this is not my domain. Should the developer of dnsmaq contact me he'd loose his time.

OK. As I poorly understand your problematic, 1- You're on a Linux OS and 2- you are encountering problems when a dns resolver is called through UDP and when, UDP failing, TCP should take the relay and doesn't? Perhaps I've misunderstood but as I said, I'm a neophyte bravely trying to keep my chin up in face of Windows ...

You do know that dnscrypt-proxy.conf includes the following parameter:
`# TCPOnly no`

explained as,

> Do not send queries using UDP. Only use TCP.
> Even if some resolvers mitigate this, DNS over TCP is almost always slower
> than UDP and doesn't offer additional security.
> Only enable this option if UDP doesn't work on your network.

So default is UDP. Maybe is your problem related to this? have you tried setting _TCPOly_ to _yes_?

@jedisct1 seems to me your explanations would be helpful when mine are hardly scholar and totally partial when not off-topic.

All I can do is try to do my best (the blend of formal logic and good sense characteristic of those who know little or not)

**Comment by jedisct1** [comment]
This is probably happening because your systemd sockets are not properly set up.

Your whole setup is way more complicated than what I ever did (which is essentially running a single instance with the default configuration file).

Remove all these files and services and don't blindly copy/paste things from random tutorials. I'm not convinced that delegating the sockets to systemd is useful. It just makes things complicated, and unless you are a systemd expert, the outcome is likely to be that nothing will work.

You can still use systemd, but just to start the server. This is all you need:

```
[Unit]
Description=DNSCrypt client proxy
After=network.target
Before=nss-lookup.target

[Service]
Type=simple
ExecStart=/usr/sbin/dnscrypt-proxy -R random -a 127.0.0.1:40
```

Save that in `/lib/systemd/system/dnscrypt-proxy.service` and that's all you need.
`random` picks a random resolver that supports DNSSEC, but you can of course use a specific one.

Duplicate as you did before if you need more instances. Don't bother with `.socket` files, just delete them.

You can also use a configuration file instead of the old-style command-line switches:
```
ExecStart=/usr/sbin/dnscrypt-proxy /etc/dnscrypt-proxy.conf
```

I don't know where the default configuration file is on your system, but probably in `/etc`. You can configure everything in it. It should look like this: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy.conf

Change whatever you need here. Probably not much except `LocalAddress` and `ResolverName`.

**Comment by jpgpi250** [comment]
I followed your instructions as much as possible. I modified the IP address and added the logging. I didn't want to use random, this to make sure I always get the result from one source only. I also needed to add the install section for the service to start. So this is the config:
file: /lib/systemd/system/dnscrypt-proxy.service
[Unit]
Description=DNSCrypt client proxy
After=network.target
Before=nss-lookup.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
ExecStart=/usr/local/sbin/dnscrypt-proxy \
	--resolver-name=dnscrypt.org-fr \
	--local-address=127.0.0.2:40 \
	--logfile=/var/log/dnscrypt-proxy.log \
	--loglevel=7

Please confirm this is correct.

**Unfortunally**, when trying to get to www.raspberrypi.org, I still get:
Feb  6 20:44:17 dnsmasq[1093]: validation www.raspberrypi.org is **ABANDONED**
It's not the only domain being validated like that:
Feb  6 20:43:59 dnsmasq[1090]: validation tiles-cloudfront.cdn.mozilla.net is **ABANDONED**

the log at /var/log/dnscrypt-proxy.log shows the following entries, nothing seems to be wrong:
Mon Feb  6 20:31:41 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Mon Feb  6 20:31:41 2017 [INFO] Generating a new session key pair
Mon Feb  6 20:31:41 2017 [INFO] Done
Mon Feb  6 20:31:41 2017 [INFO] Server certificate with serial #1486397230 received
Mon Feb  6 20:31:41 2017 [INFO] This certificate is valid
Mon Feb  6 20:31:41 2017 [INFO] Chosen certificate #1486397230 is valid from [2017-02-06] to [2017-02-07]
Mon Feb  6 20:31:41 2017 [INFO] Server key fingerprint is C956:2039:DA1D:77A6:BAED:57DF:DB22:F6CE:FD4B:4D44:8F5A:CD5D:ED1A:32BB:663E:EC44
Mon Feb  6 20:31:41 2017 [NOTICE] Proxying from 127.0.0.2:40 to 212.47.228.136:443

I've forwarded this information to the developer of dnsmasq, **may I please ask you to contact him** regarding this problem, that is, if you think my configuration is OK.

Again, thank You for Your time and effort.

**Comment by jedisct1** [comment]
Sorry, I don't use dnsmasq.

Ignoring log entries saying `validation of example.com is abandoned`, can you successfully resolve these names using a regular client?

Can you try with the `hostip` tool or even with a web browser?

**Comment by jedisct1** [comment]
When using TCP, dnsmasq sends multiple queries over the same connection. It doesn't try to open a new connection for the next query if the a connection is closed after a response.

The DNSCrypt protocol requires a new connection (possibly leveraging TFO) for every query.

So, that can't work.
