### ISSUE TITLE
resolver timeout (UDP)

### ISSUE THREAD

**Issue by jpgpi250** [jedisct1/dnscrypt-proxy#588]
I've enabled logging on dnscrypt-proxy by using --logfile=/var/log/dnscrypt-proxy.log and --loglevel=7.
This works great, however:
I've got multiple resolvers running and I'm getting the log entries:
Wed Feb  8 14:30:00 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 14:30:22 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 14:36:33 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 14:36:33 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 14:36:33 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Wed Feb  8 15:01:18 2017 [DEBUG] resolver timeout (UDP)
Would it be possible, in your next release, to specify the resolver that timed out? This would help the debugging process.

Thanks.

**Comment by jedisct1** [comment]
`dnscrypt-proxy` can only handle one resolver.

If you have multiple instances, you can take a look at the PID, or have a different `SyslogPrefix` for each instance.
