### ISSUE TITLE
please remove tracker.* from domains-blacklist-local-additions.txt

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#592]
it block all tracker domains include `tracker.debian.org` in domains-whitelist.txt

**Comment by licaon-kter** [comment]
That's up to the user to setup, it's not loaded by default.

**Comment by jedisct1** [comment]
Yes, you probably shouldn't use that list as-is!

This is the one I use, but you should make your own according to your needs, with or without the example script.
