### ISSUE TITLE
different capebilities on identical systems

### ISSUE THREAD

**Issue by jpgpi250** [jedisct1/dnscrypt-proxy#593]
I have to raspberry pi's, running raspberry jessie lite, version January 2017.
The setup is identical (to the letter), running dnscrypt-proxy v1.9.4
I'm using four (4) resolvers (d0wn-at-ns1, d0wn-nl-ns3, d0wn-de-ns1, d0wn-se-ns1), setup in a way I know you don't like (using systemctl). but the system works, so ...
On the first system, sudo systemctl status -l dnscrypt-proxy@\* reports (identical for all resolvers):
```
Feb 11 20:15:47 raspberrypi dnscrypt-proxy[590]: Sat Feb 11 20:15:47 2017 [INFO] d0wn-nl-ns3 + DNS Security Extensions are supported
Feb 11 20:15:47 raspberrypi dnscrypt-proxy[590]: Sat Feb 11 20:15:47 2017 [INFO] d0wn-nl-ns3 + Namecoin domains can be resolved
Feb 11 20:15:47 raspberrypi dnscrypt-proxy[590]: Sat Feb 11 20:15:47 2017 [INFO] d0wn-nl-ns3 + Provider supposedly doesn't keep logs

```
On the second system however, I'm only getting (identical for all resolvers):
```
Feb 12 01:09:02 raspberrypi dnscrypt-proxy[4305]: Sun Feb 12 01:09:02 2017 [INFO] d0wn-nl-ns3 + DNS Security Extensions are supported
Feb 12 01:09:02 raspberrypi dnscrypt-proxy[4305]: Sun Feb 12 01:09:02 2017 [INFO] d0wn-nl-ns3 + Provider supposedly doesn't keep logs
```
Notice the missing **Namecoin domain** INFO message.
The date is irrelevant, the results are always the same.
I'm updating /usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv daily
How would that be possible?

**Comment by jedisct1** [comment]
Support for namecoin is not printed any more since version 1.6.1. So you're running an old one on the first system.
Maybe you have different versions installed simultaneously?
