### ISSUE TITLE
Resolve DNS Via Socks ?

### ISSUE THREAD

**Issue by satmuts** [jedisct1/dnscrypt-proxy#595]
my socks server runs on 127.0.0.1 port 9951 . is it possible to resolve dns via socks and NOT from the dns servers you provide ? it's not a good idea to have an IP from Country A and dns from Country B many sites don't like that . Proxifier software can resolve that for example but the problem with Proxifier is that it only work on software on local machine . for example it doesn't dns for an android emulator etc

**Comment by jedisct1** [comment]
Unfortunately, it is not possible. `dnscrypt-proxy` can only send queries using secure DNS protocols.
