### ISSUE TITLE
Lot of debug errors

### ISSUE THREAD

**Issue by lopachecoc** [jedisct1/dnscrypt-proxy#595]
I keep getting a lot of these errors:

02/12/17 11:10:21 [DEBUG] recvfrom(client): [Connection reset by peer WSAECONNRESET ]]
02/12/17 11:10:21 [DEBUG] recvfrom(client): [Connection reset by peer WSAECONNRESET ]]
02/12/17 11:10:21 [DEBUG] recvfrom(client): [Connection reset by peer WSAECONNRESET ]]
02/12/17 11:10:21 [DEBUG] recvfrom(client): [Connection reset by peer WSAECONNRESET ]]
02/12/17 11:10:21 [DEBUG] recvfrom(client): [Connection reset by peer WSAECONNRESET ]]
02/12/17 11:10:21 [DEBUG] recvfrom(client): [Connection reset by peer WSAECONNRESET ]]
02/12/17 11:10:56 [DEBUG] resolver timeout (UDP)
02/12/17 11:15:46 [DEBUG] resolver timeout (UDP)
02/12/17 11:15:48 [DEBUG] resolver timeout (UDP)

This is all with ResolverName dnscrypt.org-fr

My internet connection is stable.

**Comment by jedisct1** [comment]
These are DEBUG-level errors, useful for developers to debug the application.
You can ignored them.
