### ISSUE TITLE
Avast give me an alert

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jedisct1/dnscrypt-proxy#599]
I have installed Avast recently, when I reinstall dnscrypt-proxy service on Windows, Avast give me an alert for IDP.Generic.

![screenshot](https://cloud.githubusercontent.com/assets/10364351/23102608/1a238f44-f6e7-11e6-9967-ce1d5613edd3.PNG)

**Comment by licaon-kter** [comment]
Do translate what error is!

Also feel free to report this "false positive" to Avast.

**Comment by jedisct1** [comment]
If you downloaded it from Github or dnscrypt[.]org, this is very likely to be a false positive. The label shows that even Avast doesn't what malware that would be; it just detected something that does network access and that is not a game, so it tags it as malware. 

You can report the false positive here: https://www.avast.com/false-positive-file-form.php
