### ISSUE TITLE
v1.9.4: Sending queries as uid=0 except for the initial cert check

### ISSUE THREAD

**Issue by Safari77** [jedisct1/dnscrypt-proxy#600]
In my case, Fedora 25, initial cert check is using sendto() fd=9 as dnscrypt (uid=1000) but after that it uses fd=7 (uid=0).
I have iptables rules that dnscrypt is allowed to send sport=1024:65535 dport=1-65535 but now I would need to allow uid=0 dport=1-65535 which is a no-no.

So, dnscrypt-proxy should be fixed so that it uses configured User for sending every packet.

**Comment by jedisct1** [comment]
The file descriptors of the listening sockets are set prior to dropping privileges, so that we can bind ports < 1024 on all operating systems.

**Comment by Safari77** [comment]
bind
drop root
listen
...
profit

**Comment by jedisct1** [comment]
or use systemd...

**Comment by jedisct1** [comment]
`evconnlistener_new_bind()` does `bind()+listen()`, and I'm quite reluctant to reinventing this as it's very likely to end up breaking Windows or other non-Linux architectures.

On Fedora, you should probably use systemd socket activation and cgroups anyway.

**Comment by Safari77** [comment]
it uses uid=0 also with systemd

**Comment by jedisct1** [comment]
Using socket activation ?

**Comment by jedisct1** [comment]
A pull request to fix this (that doesn't break any platform) would be welcome.

But since it doesn't solve an actual issue that cannot be solved using cgroups, and since there are kazilion other things I really have work on, this will probably never be addressed if I don't get some help.

**Comment by Safari77** [comment]
well I have now a patch which works with and without systemd.
It uses CAP_NET_BIND_SERVICE in libcap-ng.

Touches only function ```revoke_privileges``` and call to it in ```dnscrypt_proxy_main```.

**Comment by jedisct1** [comment]
Won't work in a docker container, but that can be tried first, and if it fails, fall back to the normal mechanism.
