### ISSUE TITLE
UDP listen on ports: 49423 *:58672 *:55238 *:50711*:60110 *:47536 *:41893

### ISSUE THREAD

**Issue by Veek** [jedisct1/dnscrypt-proxy#605]
Why is dnscrypt listening on all these UDP ports? Here's an example from lsof -ni

```
root@debian:~/dnscrypt-proxy# lsof -ni|grep -v "mdns\|LIS\|ESTA"
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnscrypt- 1066  root   10u  IPv4  16663      0t0  UDP *:41893 
pdnsd     1069 pdnsd    4u  IPv4  16646      0t0  UDP 127.0.0.1:domain 
dnscrypt- 1298  root   10u  IPv4  17105      0t0  UDP *:47536 
dnscrypt- 1520  root   10u  IPv4  19778      0t0  UDP *:60110 
dnscrypt- 1740  root   10u  IPv4  21207      0t0  UDP *:50711 
dnscrypt- 1959  root   10u  IPv4  22180      0t0  UDP *:55238 
dnscrypt- 5289  root   10u  IPv4  29771      0t0  UDP *:58672 
dnscrypt- 6701  root   10u  IPv4  31465      0t0  UDP *:49423 
firefox   8186  veek   39u  IPv4  41494      0t0  TCP 117.192.30.172:43887->34.194.71.174:https (SYN_SENT)
firefox   8186  veek   40u  IPv4  42176      0t0  TCP 117.192.30.172:43888->34.194.71.174:https (SYN_SENT)
firefox   8186  veek   77u  IPv4  41581      0t0  TCP 117.192.30.172:54019->151.101.65.69:http (SYN_SENT)
netcat    8558  root    3u  IPv4  42641      0t0  UDP *:2115 

```

 \* means it's listening on all interfaces - note the netcat (listen) running on port 2115. Why are the ports permanently open and not closed eventually? And how do you turn them off on all interfaces? Additionally what ports do you block inbound and outbound? I tried firewalling all inbound UDP with 
> iptables -A INPiptables -A INPUT -i $iface -p udp -s 0/0 -d 0/0 -j DROPiptables -A INPUT -i $iface -p udp -s 0/0 -d 0/0 -j DROPUT -i $iface -p udp -s 0/0 -d 0/0 -j DROP
Also tried 
> TCPOnly yes

but i get
>  [ERROR] Unable to retrieve server certificates

Also ran with -T enabled and UDP is still being used.

**Comment by jedisct1** [comment]
On Linux, the `ss` command is better a choice for getting informations about opened sockets, and its output is easier to understand. Try `ss -aupn` for example.

`dnscrypt-proxy` only listens to one port. Usually port 53, or whatever port you configured. And it only communicates with one external IP, on one port. This is the resolver you configured.

Of course, when communicating with a remote host, the client has to allocate a local port. But that's not something you have to worry about, any firewall from the past 20 years is stateful, and will do it for you.

The real issue seems to be the fact that you have so many `dnscrypt-proxy` instances running simultaneously. Is that intentional?

**Comment by Veek** [comment]
I tried to check but I'm getting this when I run it manually on cmd line
```
root@debian:~# /usr/local/dnsproxy/sbin/dnscrypt-proxy  -T
Mon Feb 27 22:15:33 2017 [ERROR] Error: no resolver name given, no configuration file either.
```

Tried this:
`root@debian:~# /usr/local/dnsproxy/sbin/dnscrypt-proxy -T  /usr/local/dnsproxy/etc/dnscrypt-proxy.conf 
Mon Feb 27 22:16:06 2017 [ERROR] Error: no resolver name given, no configuration file either.
Mon Feb 27 22:16:06 2017 [ERROR] The easiest way to get started is to edit the example configuration file
`

**Comment by Veek** [comment]
I have TCPOnly yes


```
root@debian:~# ss -aupn
State       Recv-Q Send-Q                      Local Address:Port                        Peer Address:Port 
UNCONN      0      0                               127.0.0.1:5353                                   *:*      users:(("dnscrypt-proxy",pid=6615,fd=9))
UNCONN      0      0                               127.0.0.1:53                                     *:*      users:(("pdnsd",pid=6618,fd=4))
root@debian:~# 

```

It's still running on 5353 UDP port for some reason

**Comment by jedisct1** [comment]
The default port is `53`. So, that port `5353` is probably coming from the configuration file (but `5353` is not the default here either, so you must have changed it).
