### ISSUE TITLE
debug messages

### ISSUE THREAD

**Issue by jpgpi250** [jedisct1/dnscrypt-proxy#606]
I've configured dnscrypt-proxy with the following log settings:
	--syslog-prefix=%i \
	--logfile=/var/log/dnscrypt-proxy.log \
	--loglevel=7
and I'm getting a lot of messages:
Tue Feb 28 13:49:32 2017 [DEBUG] d0wn-de-ns1 resolver timeout (UDP)

Would it be possible to log a message when the proxy recovers from this problem e.g. log a message  when the proxy is able to connect again (only the first successful connection after a timeout)?
It would make it easier to determine if it is only a temporary problem or a long term problem.

**Comment by jedisct1** [comment]
UDP is not a protocol that don't use connections.

Unless there is an actual query from a client, there are no ways to detect that the "connection" is up or down.

And even when a response is not sent by a resolver, it doesn't mean that it's not reachable and working as expected. It may just be that a query was not well-formed, or that the resolver doesn't respond to specific queries.

In any case, debugging information is only intended for debugging. It's not meant to be used for anything else. Anything here can change or be removed anytime.
