### ISSUE TITLE
Command line options cannot be mixed with config file

### ISSUE THREAD

**Issue by Veek** [jedisct1/dnscrypt-proxy#607]
When I run it manually on cmd line

root@debian:~# /usr/local/dnsproxy/sbin/dnscrypt-proxy  -T
Mon Feb 27 22:15:33 2017 [ERROR] Error: no resolver name given, no configuration file either.

Tried this:
root@debian:~# /usr/local/dnsproxy/sbin/dnscrypt-proxy -T /usr/local/dnsproxy/etc/dnscrypt-proxy.conf Mon Feb 27 22:16:06 2017 [ERROR] Error: no resolver name given, no configuration file either. Mon Feb 27 22:16:06 2017 [ERROR] The easiest way to get started is to edit the example configuration file

**Comment by jedisct1** [comment]
Yes, that's how it's supposed to work.

Either pass the options on the command-line, or just give a config file.

Supporting both at the same time would be confusing and incompatible with plugins.
