### ISSUE TITLE
ldns-forwarding plugin stops working occasionally

### ISSUE THREAD

**Issue by mitchelhaan** [jedisct1/dnscrypt-proxy#608]
I'm not sure if this would be considered a bug with ldns itself or the ldns-forwarding plugin. The forwarding resolver state is maintained while dnscrypt-proxy is operating since `forwarder->resolver` is initialized and destroyed with the plugin. Ldns uses this object to determine which servers to query and their reachability state. It will skip over any resolvers marked as unreachable, and it will mark a resolver as unreachable when a query fails. (i.e. temporary network issues or attempts to query before an IP address is obtained). Once all the resolvers have been flagged as unreachable, the plugin can no longer function until dnscrypt-proxy is restarted.
I was able to work around this by checking the resolvers immediately before the [ldns_send call](https://github.com/jedisct1/dnscrypt-proxy/blob/1.9.4/src/plugins/example-ldns-forwarding/example-ldns-forwarding.c#L345), and if the rtt on all servers was set to infinite, I reset all of them to a reachable state again.

**Comment by jedisct1** [comment]
Ah, good catch, thanks!

Would you be able to submit a pull request for this? That would be awesome!
