### ISSUE TITLE
DNSCrypt-proxy user account

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#610]
Running Entware version of dnscrypt-proxy 1.9.1 on an Asus RT-AC88U with Asuswrt-Rmerlin.

When installing dnscrypt-proxy, is it possible to have it not run under the admin account ?

**Comment by jedisct1** [comment]
Sure.

The configuration file include this line (commented by default):

```
# User _dnscrypt-proxy
```

Uncomment it and replace `_dnscrypt-proxy` with the system user name you want it to run as.

**Comment by uihdff** [comment]
@jedisct1 ,

Since Entware packages usually run with root/admin permissions, if another username is specified, does that account need special permissions to be assigned ?

**Comment by uihdff** [comment]
@jedisct1 ,

Which configuration file are you referring to ...  S09dnscrypt-proxy ?

Did you mean to specify the user in the line below ?

`ARGS="--local-address=127.0.0.1:40 --daemonize -R dnscrypt.eu-dk --user=dnscrypt`

**Comment by jedisct1** [comment]
Errrr no, the `dnscrypt-proxy.conf` file.

You don't need to pass all these arguments in the command line. Remove them all, the configuration is now read from a config file (probably in `/etc/dnscrypt-proxy.conf` or `/usr/local/etc/dnscrypt-proxy.conf`.

The configuration file looks like this: https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-proxy.conf

Refer to the documentation for more information: https://github.com/jedisct1/dnscrypt-proxy/wiki

**Comment by uihdff** [comment]
@jedisct1 ,

On Asuswrt-Merlin 380.65, the Entware-NG version of dnscrypt-proxy does not have a dnscrypt-proxy-common.conf file.

Is there a dnscrypt-proxy 2.0 version that has to be compiled for Entware-NG that supports a dnscrypt-proxy-common.conf file ?

**Comment by uihdff** [comment]
When specifying a system account for dnscrypt-proxy to run under, should that account NOT have a password ?

**Comment by jedisct1** [comment]
That account should not be able to log in. So, no shell needed, no password needed.
