### ISSUE TITLE
DNSCrypt-proxy user account permissions

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#614]
Running Entware version of dnscrypt-proxy 1.9.1 on an Asus RT-AC88U with Asuswrt-Rmerlin.

When configuring the DNSCrypt-proxy to use a specific user account, does that account need special permissions to be assigned ?

**Comment by jedisct1** [comment]
Not sure what you mean with "special permissions", but any existing system account is fine. It doesn't need to have a valid shell.
