### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kensfc-23** [jedisct1/dnscrypt-proxy#615]
Hello,

I use Ubuntu 16.10 and dnscrypt-autoinstall from Simon Clausen

https://github.com/simonclausen/dnscrypt-autoinstall

I get this error:
```
endeve0506@eju-deHHd2wC-11:~$ sudo ./dnscrypt-autoinstall
[sudo] password for endeve0506: 
Unit dnscrypt-autoinstall.service could not be found.

Welcome to the dnscrypt-autoinstall script.

This will install DNSCrypt and autoconfigure it to
run as a daemon at start up.

Press any key to continue...
passwd: información de caducidad de la contraseña cambiada.

[long unformatted logs stripped]
```

**Comment by licaon-kter** [comment]
Please post your logs on https://gist.github.com and post that link instead

**Comment by kensfc-23** [comment]
https://gist.github.com/kensfc-23/52a9c1e1ca96268e4c8c3df8b045a59f

**Comment by jedisct1** [comment]
Looks like there are leftovers from a previous version.

Your logfile only compile a couple files instead of the whole package, and displays`crypto_stream_chacha20_vec_implementation` that doesn't exist any more in libsodium 1.0.12.

I don't know how `dnscrypt-autoinstall` works, but you should probably remove all traces from the previous installation before starting over.

**Comment by jedisct1** [comment]
Actually, `dnscrypt-autoinstall` has an `uninstall` option. That should do the trick!

**Comment by kensfc-23** [comment]
I'm a Spaniard ... Sorry for my english

I have actually deinstalled dnscrypt using the uninstall option of dnscrypt-autoinstall

I think the problem is solved.

I have downloaded libsodium from your repository. After that: ./configure ... make && make check, etc

sudo ldconfig ... and I have tried with the autoinstaller again ... All is right now. 

Thank you Frank and licaon-kter

**Comment by jedisct1** [comment]
Awesome, thanks! Glad to hear that it's solved!
