### ISSUE TITLE
Uninstall Android ZIP

### ISSUE THREAD

**Issue by zin105** [jedisct1/dnscrypt-proxy#620]
I flashed the Android zip mentioned in https://dnscrypt.org/ and I was wondering how to uninstall it again?

**Comment by licaon-kter** [comment]
Look in the archive, delete those files from system.

**Comment by zin105** [comment]
Some files aren't there though. I have an init.d folder with some files but the DNScrypt one is missing?

**Comment by zin105** [comment]
Thank you. You can close this "issue" now.
