### ISSUE TITLE
dnscrypt on Win2008 server

### ISSUE THREAD

**Issue by FoLkjF** [jedisct1/dnscrypt-proxy#623]
i use a small win domain at home with a win2008 server and my home devices goto it for DNS.

can i install the windows version of dnscrypt onto this win2008 server so that my dns requests go through dnscrypt?

**Comment by jedisct1** [comment]
Yes, of course!

If you are using dnscrypt-proxy, use:

```
LocalAddress 0.0.0.0:53
```

(or the local IP address) in the configuration file, so that it can be reached from other machines.

SimpleDNSCrypt also includes a simple box you can check in order to make the service accessible to other hosts and devices on the network.

**Comment by FoLkjF** [comment]
thanks for your reply/help!

i'll check out dnscrypt-proxy a bit more. in the meantime i'll install simpleDNSCrypt onto the win2088 server. 

thanks again

**Comment by jedisct1** [comment]
Anytime!
