### ISSUE TITLE
dnscrypt-proxy stops working after resume from suspend

### ISSUE THREAD

**Issue by tanji** [jedisct1/dnscrypt-proxy#624]
I'm using Arch Linux, and each time I resume my system from suspend mode, I have to restart dnscrypt-proxy because it stops replying.

**Comment by jedisct1** [comment]
Probably because the certificate is not valid any more.

Maybe the systemd service can be configured to restart the proxy after resuming from suspend. It probably can. Systemd can do everything. But I don't know how :)

**Comment by tanji** [comment]
True :)

Something like this should work, testing it at the moment:

```
[Unit]
Description=Restart dnscrypt-proxy after suspend
After=suspend.target

[Service]
User=root
Type=oneshot
ExecStart=systemctl --fail --no-block restart dnscrypt-proxy.service
TimeoutSec=0
StandardOutput=syslog

[Install]
WantedBy=suspend.target
```

**Comment by tanji** [comment]
This unit file worked for me:

```
[Unit]
Description=Restart dnscrypt-proxy after suspend
After=suspend.target

[Service]
User=root
Type=oneshot
ExecStart=/usr/bin/systemctl --fail --no-block restart dnscrypt-proxy.service
TimeoutSec=0
StandardOutput=syslog

[Install]
WantedBy=sleep.target
```

**Comment by DistantThunder** [comment]
@tanji 
Thanks a lot for this! I was having this problem and your solution seems to fix it.
