### ISSUE TITLE
portal.azure.com microsoftonline does not resolve

### ISSUE THREAD

**Issue by pmtolk** [jedisct1/dnscrypt-proxy#626]
I cannot reach microsoft websites using dnscrypt

I receive a "login.microsoftonline.com’s server DNS address could not be found."

If I turn off dnscrypt and set to google dns then it works, as soon as I go back to dnscrypt microsoft stops working.

**Comment by licaon-kter** [comment]
On all dnscrypt servers?

**Comment by jedisct1** [comment]
What resolver are you using?

**Comment by pmtolk** [comment]
I have tried cs las vegas  and cs secondary las vegas, and cs arizona. Mostly all the USA based ones. As soon as it tries to route me to login I get the dns error.
1) I am already logged in on portal.azure.com
2) I visit it with dnscrypt and get redirected to
https://login.microsoftonline.com/common/oauth2/authorize?resource=https%3a%2f%2fmanagement.core.windows.net%2f&response_mode=form_post&response_type=code+id_token&scope=user_impersonation+openid&state=OpenIdConnect.AuthenticationPropertiesGIBBERISH&redirect_uri=https%3a%2f%2fportal.azure.com%2fsignin%2findex%2f%3fsignIn%3d1&site_id=501430

This site can’t be reached

login.microsoftonline.com’s server DNS address could not be found.

Also azure.com does not work, probably easier to test with azure.com

This site can’t be reached

azure.microsoft.com’s server DNS address could not be found.

**Comment by licaon-kter** [comment]
Indeed those resolvers that you mentioned fail.

Eg. `d0wn-us-ns1` says:
```
; <<>> DiG 9.10.3-P4-Debian <<>> azure.microsoft.com +multi +dnssec -p 40
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32567
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;azure.microsoft.com.   IN A

;; ANSWER SECTION:
azure.microsoft.com.    3525 IN CNAME azure.microsoft.com.nsatc.net.
azure.microsoft.com.nsatc.net. 225 IN CNAME acom-prod-useast2-01.azurewebsites.net.
acom-prod-useast2-01.azurewebsites.net. 1725 IN CNAME waws-prod-bn1-003.vip.azurewebsites.windows.net.
waws-prod-bn1-003.vip.azurewebsites.windows.net. 225 IN CNAME waws-prod-bn1-003.cloudapp.net.
waws-prod-bn1-003.cloudapp.net. 60 IN A 191.236.192.121
```

While `cs-uswest4` says:
```
; <<>> DiG 9.10.3-P4-Debian <<>> azure.microsoft.com +multi +dnssec -p 41
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3074
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;azure.microsoft.com.   IN A

;; ANSWER SECTION:
azure.microsoft.com.    46 IN CNAME azure.microsoft.com.nsatc.net.

;; AUTHORITY SECTION:
nsatc.net.              46 IN SOA localhost. root. (
                                1          ; serial
                                604800     ; refresh (1 week)
                                86400      ; retry (1 day)
                                2419200    ; expire (4 weeks)
                                604800     ; minimum (1 week)
                                )
```

Did you report this to Cryptostorm?

**Comment by pmtolk** [comment]
I just sent Cryptostorm an email and also confirmed that d0wn-us-ns1 is working.

Thanks!

**Comment by df-cryptostorm** [comment]
Yep, looks like Azure is blocked by the ad/tracker blocking system that we use, for some reason - https://github.com/StevenBlack/hosts

Added nsatc.net, microsoft.com, azurewebsites.net, windows.net, and cloudapp.net to our whitelist.
Should be good now.

**Comment by licaon-kter** [comment]
Yep, the whole "just telemetry" spying thing Windows 10 brings.
