### ISSUE TITLE
How to configure dnscrypt-proxy to use TCP only

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#627]
Running Entware version of dnscrypt-proxy 1.9.1 on an Asus RT-AC88U with Asuswrt-Merlin 380.65. The firewall has connection tracking enabled and iptables rules are allowing connections based on state status.

How do you configure dnscrypt-proxy to use TCP only ?

**Comment by jedisct1** [comment]
Hi!

Just change `TCPOnly no` to `TCPOnly yes` in the config file: https://github.com/jedisct1/dnscrypt-proxy/blob/9eee47477031ad0ffef94160d7370d4dec6f2c3a/dnscrypt-proxy.conf#L104

**Comment by uihdff** [comment]
@jedisct1 ,

The Entware-NG version doesn't appear to have a dnscrypt-proxy-common.conf file.

Where else could that be configured ?

**Comment by jedisct1** [comment]
It's just called `dnscrypt-proxy.conf`.

Or if you really just want to force TCP and stick to command-line options, add `--tcp-only`.

**Comment by uihdff** [comment]
@jedisct1 ,

Do you have any involvement in the Entware-NG build of dnscrypt-proxy ?

**Comment by jedisct1** [comment]
Not at all. I've never used Entware.

The command-line options are documented in the man page, but that's really the old way of configuring it, and I would recommend switching to the configuration file.

**Comment by uihdff** [comment]
How would you install dnscrypt-proxy on an Asus RT-AC88U router running Asuswrt-Merlin 380.65, if not by Entware-NG ?

**Comment by jedisct1** [comment]
Can you compile things on it?

**Comment by uihdff** [comment]
@jedisct1 ,

Not that I know of.

**Comment by jedisct1** [comment]
Precompiled binaries: https://github.com/jedisct1/dnscrypt-proxy-installer
