### ISSUE TITLE
[request] Official dnscrypt-autoinstall from jedisct1 for linux users?

### ISSUE THREAD

**Issue by kensfc-23** [jedisct1/dnscrypt-proxy#630]
Hello,

I install dnscrypt with dnscrypt-autoinstall from Simon cClausen.

It would be nice to have an up-to-date dnscrypt-autoinstall from Frank Denis ;-)

Instructions for ubuntu users, please ... That would be nice too. Arch Linux users don't need instructions ;-)

Sorry for my English

Greetings

**Comment by CNMan** [comment]
official packages for Debian testing and unstable
https://tracker.debian.org/pkg/dnscrypt-proxy
```
apt-get install dnscrypt-proxy dnscrypt-proxy-plugins
```
Ubuntu is based on Debian, maybe you can use these packages.

**Comment by kensfc-23** [comment]
Thank you ... :-)

There are these packages in Ubuntu Gnome 17.04 too. I have seen that.

In three or four months there will be new packages from Frank Denis and the packages in Ubuntu will be outdated :-(

**Comment by jedisct1** [comment]
There are way too many distributions and way too many ways to configure them.
I can't reasonably maintain packages for these.

**Comment by kensfc-23** [comment]
It was worth a try ;-)

Greetings

**Comment by jedisct1** [comment]
https://github.com/jedisct1/dnscrypt-proxy-installer
