### ISSUE TITLE
Feature request: add a "hide" argument to Windows client version

### ISSUE THREAD

**Issue by sam1275** [jedisct1/dnscrypt-proxy#631]
Hello.
I'm trying to run a instance on Windows without showing the CMD window, I tried "start" command, but it just open another window, I also tried "--daemonize", but it's not even recognized on Windows version.
I know installing as service will let it run while hidden, but I think it will be much better if it have a native argument to control this, so we can use it as a un-elevated user.
Thanks.

**Comment by jedisct1** [comment]
I don't even know if this is possible, but this would be redundant with starting the service as a... service.

Support for running the server as a non-privileged user will eventually be added, if that can be done while still listening to port 53.

**Comment by sam1275** [comment]
Thank you.
I didn't mean start service as a service, I mean be able to start a hidden instance manually.
Further more, I found a non-privileged instance can listen on 127.0.0.1 on Windows, but not any other address such as 127.0.0.2.
