### ISSUE TITLE
How to Change Resolver Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Brenneke2** [jedisct1/dnscrypt-proxy#633]
Hi - have successfully installed DNSCrypt and is working perfectly. What is the best way to change the resolver to something other than OpenDNS? Thank you.

**Comment by licaon-kter** [comment]
How do you start it? Edit the systemd unit I guess.

**Comment by Brenneke2** [comment]
If you are referring to dnscrypt the program when you say it, starts on boot.

**Comment by Brenneke2** [comment]
I did find info in the wiki, but do not have dnscrypt-proxy.conf file on my system.

**Comment by jedisct1** [comment]
How did you install it? The original dnscrypt-proxy code doesn't force you to use a specific resolver.

The configuration file was introduced in dnscrypt-proxy version 1.8.0, so maybe your version is older.

**Comment by Brenneke2** [comment]
Installed it with Synaptic package manager, version 1.6.1-1.

**Comment by Brenneke2** [comment]
dnscryt-proxy 1.6.1-1

**Comment by licaon-kter** [comment]
That is old, both code wise and serverlist wise.

Get the packages from 17.04.

**Comment by Brenneke2** [comment]
Old yes, but it works 100% and is dead easy to install as it is in the Ubuntu repository. It would be great if someone could help me with understanding how the program uses the resolver(s) and how I would go about changing reolver(s) to something other than OpenDNS. Thanks.

**Comment by licaon-kter** [comment]
Remember to get the latest resolvers too, as these change pretty often: https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv

**Comment by jedisct1** [comment]
Up-to-date binaries can be installed with https://github.com/jedisct1/dnscrypt-proxy-installer
