### ISSUE TITLE
How to Install DNSCrypt on Ubuntu 16.04 LTS Desktop

### ISSUE THREAD

**Issue by nb5691** [jedisct1/dnscrypt-proxy#634]
I have OpenDNS correctly configured in my desktop Ubuntu 16.04 LTS.

Pls let me know, how to install DNSCrypt under the same platform with steps and also for confirming the same whether DNSCrypt is working with OpenDNS correctly.  This is only a request as I don't find clear instruction for the same.

Also at present I am not able to download latest version of DNSCrypt from https://download.dnscrypt.org/dnscrypt-proxy/ whereas the Ubuntu repository is having only version DNSCrypt 1.6.1

Thanks and Regards

**Comment by licaon-kter** [comment]
Close this and read: https://github.com/jedisct1/dnscrypt-proxy/issues/633

TL;DR: please compile it (and libsodium) yourself or use the 17.04 packgages (if possible)

**Comment by jedisct1** [comment]
I'm thinking about providing precompiled binaries. The main issue is how to reliably change the DNS configuration. This is a big mess with every Linux distro having its own script to generate `/etc/resolv.conf`, and it got worse with systemd being involved as well.

**Comment by Brenneke2** [comment]
That would be awesome if you could do that, thank you.

**Comment by nb5691** [comment]
Thank you.
