### ISSUE TITLE
Just a question: Could resolvers-check.sh be modified to check servers on line, without cert validity

### ISSUE THREAD

**Issue by Zenith-Nadir** [jedisct1/dnscrypt-proxy#636]
Hello,
Is there a dnscrypt-proxy switch which could be used to check which resolvers included in dnscrypt-resolvers.csv are on line (lets say ping check), and not to check for -t <grace period> checks if the certificate will still be valid in <grace period> seconds, since the check with -t takes pretty long time if there are some failing servers (I tried couple of times, and it takes over 4 min, which is too long for router startup script).
I also tried -n 1 switch, but this does not seem to work alone without -t.
Sincerely,
Zenith-Nadir

**Comment by jedisct1** [comment]
Errr... not really. If the cert cannot be retrieved, it's impossible to send authenticated DNS queries.

**Comment by Zenith-Nadir** [comment]
Thank You so much for such an instant response.
This answers my question.
Sincerely,
Zenith-Nadir
