### ISSUE TITLE
Bizarre DNScrypt unreliablity on some networks

### ISSUE THREAD

**Issue by avrildev** [jedisct1/dnscrypt-proxy#637]
It's been my experience that dnscrypt will randomly stop working on our BT-Central-Plus network, giving the following log:

Wed Apr 26 15:29:44 2017 [NOTICE] Proxying from 127.0.0.1:53 to 208.67.220.220:4
43
Wed Apr 26 15:30:16 2017 [DEBUG] resolver timeout (UDP)
Wed Apr 26 15:30:16 2017 [DEBUG] resolver timeout (UDP)
Wed Apr 26 15:30:21 2017 [DEBUG] resolver timeout (UDP)
Wed Apr 26 15:30:21 2017 [DEBUG] resolver timeout (UDP)
Wed Apr 26 15:30:26 2017 [DEBUG] resolver timeout (UDP)
Wed Apr 26 15:30:26 2017 [DEBUG] resolver timeout (UDP)
Wed Apr 26 15:31:26 2017 [DEBUG] resolver timeout (UDP)
...

We also get errors like this:

Wed Apr 26 15:15:42 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Wed Apr 26 15:16:41 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Wed Apr 26 15:16:41 2017 [INFO] Generating a new session key pair
Wed Apr 26 15:16:41 2017 [INFO] Done
Wed Apr 26 15:16:46 2017 [ERROR] Unable to retrieve server certificates
Wed Apr 26 15:16:47 2017 [INFO] Refetching server certificates
Wed Apr 26 15:16:52 2017 [ERROR] Unable to retrieve server certificates
...

This happens _very_ frequently, and we have no idea why, but suspect that there might be some advanced firewall features deliberately interfering with the connection.

I've tried a number of things, including switching to the major openDNS cisco server, and that hasn't yielded any improvement. It's barely possible that it's server side, but it seems more likely that it's either 1) a client software bug, or 2) malicious network features. 

(If it doesn't have to do with DNScrypt itself, it _does_ still affect usability of the software considerably, so I intend to change this issue to a set of feature suggestions to prevent this sort of issue for others. :p )

We are using dnscrypt-proxy 1.9.4, compiled from source on Linux Mint 18.1 Serena.

Our conf file looks like this:

ResolverName cisco
Daemonize no
User dnscrypt-proxy
LocalAddress 127.0.0.1:53
LocalCache on
EphemeralKeys on
LogLevel 7

Anyone have any clues?

Addendum: just to clarify, /etc/resolv.conf is pointing to 127.0.0.1:53. DNScrypt-proxy is the _only_ local DNS server we have. It's not a chain with something like dnsmasq in there.
Also, I have tried disabling ephemeral keys, but dnscrypt-proxy still kept acting like its target server was randomly disappearing from existence.

Addendum 2:
I tried telneting to 208.67.220.220, port 443 both from inside and outside the network.
It worked outside of the network in question, but the server apparently genuinely isn't "available" from within the BT-Central-Plus network. It looks like it might be some dynamic firewall thing. Anyone have any suggestions for more tests to run, or know what the network might be doing behind the scenes to cause this?

**Comment by jedisct1** [comment]
The `DEBUG` lines can be ignored. This is just debugging information, and not something you should consider errors or warning messages.

The fact that certificates cannot be retrieved is more concerning, because it means that normal, unencrypted, unauthenticated queries were blocked. So, BT might be blocking or rate limiting this resolver, or this resolver might be rate limiting BT.

Do you experience the same thing with other resolvers?

**Comment by avrildev** [comment]
@jedisct1 Huh, so it's normal to get constant resolver timeouts? The log was really being spammed with them, which made me think it was a result of losing contact with the server. Also seemed to coincide with the DNS lookups beginning to fail.

Anyway, yeah, the certificate errors happen quite frequently. I have tried several other resolvers, including okturtles and several others I can't remember. It all showed the same behavior, implying it's not a server-specific failure. The fact that I couldn't telnet to the port implies that the server isn't just rate limiting stuff, either. Unless it's blocking some percentage of requests, instead of just throttling traffic, but that would be bizarre to my way of thinking...

My bet is on BT itself doing heuristical traffic blocking based on... something. Dunno what.

**Comment by jedisct1** [comment]
Also check that you don't have an antivirus or proxy that would intercept queries to port 443.

**Comment by avrildev** [comment]
@jedisct1 I can telnet to google.com on port 443, and nmap sees the port as 'open'. Also, I assume blocking outgoing connections on 443 would break a bunch of basic stuff like SSL encrypted web pages? In any case, doesn't seem to be what's happening.

**Comment by avrildev** [comment]
@jedisct1 It looks like the problem might actually be something to do with a race condition between openvpn and dnscrypt-proxy. I probably should have mentioned openvpn. :(

Anyway, I tried scanning 208.67.220.220:443 on the same network, but on a device without openvpn, and it reaches just fine.

I'm strongly suspecting now that a lot of my problems have been due to these two bumping into each other. I assume iptables black magic is required to fix this?

I feel like it might have been better to take this to IRC or something first. It's looking pretty plausible that it has nothing to do with dnscrypt-proxy.

**Comment by jedisct1** [comment]
OpenVPN has an option to avoid changing the DNS settings (don't remember which one, since I don't use it, sorry, but there's definitely one).

**Comment by avrildev** [comment]
@jedisct1 

My current dominant hypothesis is that openvpn is routing the traffic thru tun0.
Now, tun0 relies on openvpn forming the connection with the VPN server, to work as a network device... which in turn requires domain name resolution...

Oopsie. :P

**Comment by jedisct1** [comment]
Maybe that can be solved by adding the relevant addresses to `/etc/hosts`?

**Comment by avrildev** [comment]
@jedisct1 That'd probably work assuming they have static IPs, yeah. I'll try it. :)

**Comment by avrildev** [comment]
It worked for awhile, and then openvpn randomly failed. It didn't even give an error message in the log file. It's just stopped serving requests, oddly enough.

**Comment by jedisct1** [comment]
I can help with anything directly related to dnscrypt-proxy, but not much with software I don't use.

Looks like OpenVPN has support forums; maybe this is the best place to ask: https://forums.openvpn.net/

**Comment by timbowhite** [comment]
I'm seeing very similar behavior and so it may not be related openvpn.

When my internet connection goes down for more than a few seconds, dnscrypt-proxy doesn't seem to reconnect to the remote dnscrypt-server after the WAN connection is established again.

When the connection goes down, I see this in the dnscrypt-proxy log:

```
Thu Apr 27 17:13:12 2017 [DEBUG] resolver timeout (UDP)
Thu Apr 27 17:13:17 2017 [DEBUG] resolver timeout (UDP)
Thu Apr 27 17:13:27 2017 [DEBUG] resolver timeout (UDP)
Thu Apr 27 17:13:32 2017 [DEBUG] resolver timeout (UDP)
Thu Apr 27 17:13:43 2017 [DEBUG] resolver timeout (UDP)
Thu Apr 27 17:13:45 2017 [DEBUG] resolver timeout (UDP)
Thu Apr 27 17:14:46 2017 [DEBUG] resolver timeout (UDP)
Thu Apr 27 17:15:46 2017 [DEBUG] resolver timeout (UDP)
```

Stopping and starting the dnscrypt-proxy daemon doesn't reestablish the connection:

```
Thu Apr 27 17:15:52 2017 [NOTICE] Stopping proxy
Thu Apr 27 17:15:52 2017 [INFO] UDP listener shut down
Thu Apr 27 17:15:52 2017 [INFO] TCP listener shut down
Thu Apr 27 17:15:52 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Thu Apr 27 17:15:52 2017 [INFO] Generating a new session key pair
Thu Apr 27 17:15:52 2017 [INFO] Done
Thu Apr 27 17:16:07 2017 [ERROR] Unable to retrieve server certificates
Thu Apr 27 17:16:08 2017 [INFO] Refetching server certificates
Thu Apr 27 17:16:23 2017 [ERROR] Unable to retrieve server certificates
Thu Apr 27 17:16:26 2017 [INFO] Refetching server certificates
Thu Apr 27 17:16:41 2017 [ERROR] Unable to retrieve server certificates
Thu Apr 27 17:16:47 2017 [INFO] Refetching server certificates
Thu Apr 27 17:17:02 2017 [ERROR] Unable to retrieve server certificates
Thu Apr 27 17:17:11 2017 [INFO] Refetching server certificates
```

But! dnscrypt-proxy daemon suddenly begins to work as soon as I issue a telnet command into the dnscrypt-server IP/port:

```
telnet XXX.XXX.XXX.XXX XX
```

then:

```
Thu Apr 27 17:17:48 2017 [INFO] Server certificate with serial #1493297598 received
Thu Apr 27 17:17:48 2017 [INFO] This certificate is valid
Thu Apr 27 17:17:48 2017 [INFO] Chosen certificate #1493297598 is valid from [2017-04-27] to [2017-04-28]
Thu Apr 27 17:17:48 2017 [INFO] Server key fingerprint is XXX:XXX...........
Thu Apr 27 17:17:48 2017 [NOTICE] Proxying from 192.168.0.10:53 to XXX.XXX.XXX.XXX:XXX
```

Weird.

Environment info:
```
CentOS 6.9
dnscrypt-proxy 1.9.4 (compiled from source)
libsodium 1.0.12 (compiled from source)
dnscrypt-server is running on a non-standard port for TCP/UDP
```

dnscrypt-proxy daemon command:
```
/usr/local/sbin/dnscrypt-proxy --logfile=/path/to/log.log --loglevel=7 --daemonize --local-address=192.168.0.10:53 --resolver-address=XXX.XXX.XXX.XXX:XXX --provider-name=2.dnscrypt-cert.XXX.XXX --provider-key=XXX
```
