### ISSUE TITLE
Add a new resolver

### ISSUE THREAD

**Issue by emitosolini** [jedisct1/dnscrypt-proxy#638]
Hi from Argentina. I'm running a dnscrypt-wrapper with unbound on FreeBSD resolver, is does not log anything, is complete free and open and i hope it can be added to the dnscrypt-resolvers.csv.

I now it is not an issue, but i couldn't create a pull request.

Sorry for the bad english.

Hopefully it is useful.

[dnscrypt-resolvers.zip](https://github.com/jedisct1/dnscrypt-proxy/files/959947/dnscrypt-resolvers.zip)

**Comment by jedisct1** [comment]
```sh
$ drill resolver.dnscrypt.org @127.0.0.1
resolver.dnscrypt.org.	900	IN	A	173.194.91.84
```

https://api.iptoasn.com/v1/as/ip/173.194.91.84 -> `GOOGLE - Google Inc.`

So, it is forwarding everything to Google?

I'm not sure that this can be qualified as "non logging" in this context. Google DNS servers also do rate limiting, with pretty low limits. So things are likely to be unreliable as the number of clients increase.

**Comment by jedisct1** [comment]
Also, DNSSEC validation doesn't seem to work:

```
$ drill -D dnscrypt.org @127.0.0.1
flags: qr rd ra
```
No `ad` flag here...

**Comment by emitosolini** [comment]
Hi @jedisct1 I've been testing this afternoon and made some changes to the config file of unbound. Give it a try and let me know what doesn't work. Attached is the actual config file of unbound.

[unbound.zip](https://github.com/jedisct1/dnscrypt-proxy/files/963284/unbound.zip)
