### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GCRaistlin** [jedisct1/dnscrypt-proxy#642]
I run dnscrypt on Windows Server 2003 R2 SP2 virtual machine (Hyper-V host is Windows Server 2008 R2 SP1). This virtual machine works as Internet gate and runs Kerio Control and OpenVPN client (2 VPN connections are established all the time). All "outer" network adapters (that is, the virtual adapter connected to the WAN physical adapter on the host and OpenVPN adapters) have address 127.0.0.1 as the DNS server.
This configuration works fine except one thing: right after dnscrypt service start the virtual machine demands about 360 MB of memory, in a week - more than 1 GB. Restarting dnscrypt service helps, then the memory leak repeats again.

**Comment by jedisct1** [comment]
What does the memory layout of the `dnscrypt-proxy` process itself look like?

**Comment by GCRaistlin** [comment]
I just restarted dnscrypt service so we have to wait a couple of days. How do I see the memory layout?

**Comment by jedisct1** [comment]
You know Windows way better than I do :)

**Comment by GCRaistlin** [comment]
Something like [that](https://pastebin.com/q6Y3vB31)? It's from Sysinternals VMMap, CSV formatted. May be exported in txt and native mmp formats, also. With (as now) or without free and unusable regions.

**Comment by pysiak** [comment]
Perhaps running from valgrind would be a nice exercise.

Years ago I used it to find memleaks in a C program (a MUD) due to missing
free(), etc.

Not sure if you can do that on Windows though.

**Comment by GCRaistlin** [comment]
Memory leak is here again: https://pastebin.com/cJPRGqGe

**Comment by jedisct1** [comment]
What plugins are you using?

**Comment by GCRaistlin** [comment]
I just downloaded dnscrypt-proxy client for Windows and installed it.

**Comment by jedisct1** [comment]
Did you change anything to the configuration file? Are you using cisco?

**Comment by GCRaistlin** [comment]
I added `LocalAddress 0.0.0.0:53` line.

**Comment by jedisct1** [comment]
As long as Windows explodes before too much leaks, all is fine.  https://groups.google.com/forum/message/raw?msg=comp.lang.ada/E9bNCvDQ12k/1tezW24ZxdAJ

**Comment by jedisct1** [comment]
Can you disable the cache plugin?

**Comment by GCRaistlin** [comment]
My Windows doesn't explode. Because of this memory leak, OpenVPN fails to add routes to the route table on connection establishing.
>Can you disable the cache plugin?
By commenting `LocalCache on`? Done.

**Comment by GCRaistlin** [comment]
Renaming libdcplugin_example_cache.dll causes an error on dnscrypt-proxy service start.

**Comment by jedisct1** [comment]
Of course it does! Don't remove/rename files!

Use `LocalCache off` in the config file.

**Comment by GCRaistlin** [comment]
You said "disable the plugin", not "disable caching", that's why I tried this. Is it on by default? Done anyway.

**Comment by jedisct1** [comment]
0be14092f85859ffb2f78039e5fef311d5577ddf is likely to fix it.

**Comment by jedisct1** [comment]
Should be fixed in version 1.9.5.

Thanks!
