### ISSUE TITLE
Do not start udp/tcp listener unless there is a valid certificate

### ISSUE THREAD

**Issue by chantra** [jedisct1/dnscrypt-proxy#643]
Currently, dnscrypt-proxy will start udp/tcp listeners, drop privilege and then fetch the certs.

unless in test mode, it will hang there in an attempt to get valid certificates.

One of the issue is that if the certs are expired or whatnot, dnscrypt-proxy will be hanging on tight until something valid shows up.

The stub resolver will typically hang until it timeouts and move onto the next nameserver. If the application was not going to listen on the ports, the stub resolver would get an ICMP Port unreachable and move on faster.

Dropping privileges makes this a bit more challenging as first the listeners are started, then privileges dropped and then the cert updater is started.
* One solution would be to start the cert updater earlier, but that would void to some extend the purpose of dropping privileges, or at least would potentially expose the cert updater code to run under privileged users for a period of time.
* Another solution would be to provide a switch that allows exiting if no useable certs is available (like currently done in test mode)
* Finally, maybe was could be the least disruptive is to reply with an empty payload so the stub/client handles it how it pleases. Typically moving onto the next nameserver.

Thoughts?

**Comment by jedisct1** [comment]
3) is probably the best way to go, because temporarily unusable certs can happen anytime, not just at startup.

**Comment by chantra** [comment]
@jedisct1 correct. The original reason this came up was because the server would use an expired cert and new client would fail to get bootstrapped. Existing clients were happily using the expired cert though.
But yeah, I suppose there is a case of the client having a certificate which is not useable anymore along the course of process lifetime (secret change without rotation for instance).

I will look into getting 3) done.

**Comment by chantra** [comment]
I actually wonder if systemd and its notification system would address this as it uses:
```
systemd_notify(proxy_context, "READY=1");
```
to tell when the proxy is ready, which is after it got the certs.

**Comment by jedisct1** [comment]
Only for the small fraction of people using systemd and socket activation.

3) is more universal.

Thanks for your help!

**Comment by chantra** [comment]
Just a quick update here. I will look into this when I have some time for it, or I need to re-prioritize it.
