### ISSUE TITLE
Random numbers and dnscrypt-proxy

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy#644]
How does the quality of entropy with /dev/random and/or /dev/urandom affect dnscrypt-proxy ?

**Comment by jedisct1** [comment]
On Linux `dnscrypt-proxy` actually uses the `getrandom` system call, which under the hood is the same prg as `/dev/urandom`.

If its output is predicable, secret keys are predicable, and the protocol becomes useless.
`dnscrypt-proxy` may only remain useful for its plugins in this context.

**Comment by uihdff** [comment]
If you use rng-tools and/or haveged, does that positively affect dnscrypt-proxy ?

**Comment by jedisct1** [comment]
No. Pretty much the opposite. Only install them as a last resort, if the service cannot start due to the lack of entropy.

**Comment by uihdff** [comment]
Since the type of home routers people might use to run dnscrypt-proxy don't have TRNG, why would running applications to increase the quantity of entropy have a negative effect on dnscrypt-proxy ?

**Comment by jedisct1** [comment]
Haveged relies on jitter between clock measurements. Which may produce predicable results on virtual machines. The kernel combines many more entropy sources. 

`/dev/random` unblocks as soon as enough data has  been collected, no matter what the actual entropy is. So, if your system boots fast enough without adding anything, don't add anything.

**Comment by uihdff** [comment]
I'm running dnscrypt-proxy on an Asus RT-AC88U router using the Asuswrt-Merlin firmware. Virtual machines aren't involved and a TRNG is not currently available.

Your comment makes sense given that later versions of the kernel have made significant improvements in entropy quantity. But since the kernel Asuswrt-Merlin uses is so old (kernel 2.6.36) , `haveged` was installed to reduce the chance of `/dev/random` blocking.

If someone ports your code to Openwrt or Entware-NG, could they change how dnscrypt-proxy interacts with RNG without breaking dnscrypt-proxy or creating a vulnerability ?

**Comment by jedisct1** [comment]
Does the proxy actually have a problem starting on that device? It only requires 80 random bytes once and for all.

Unless it completely prevents the system from booting, there's no reason to add haveged, even on a 2.6 kernel.

**Comment by uihdff** [comment]
It doesn't have a problem starting up.

**Comment by jedisct1** [comment]
So don't installed Haveged :)
