### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by Scorpio479** [jedisct1/dnscrypt-proxy#646]
I just downloaded and installed Simple DNSCrypt and when I click on a network card I get "Exception has been thrown by the target of an invocation" message and the program shuts down. Any help on resolving this issue would be helpful. Thanks

Windows 7 Home Premium Service Pack 1
Comcast Xfinity ISP
Private Internet Access VPN

![capture 2](https://cloud.githubusercontent.com/assets/28404282/25718570/3462d88c-30cc-11e7-989b-482eda43e3f4.JPG)

![capture](https://cloud.githubusercontent.com/assets/28404282/25718491/eedd4518-30cb-11e7-8791-9450db55ef1c.JPG)

**Comment by jedisct1** [comment]
Wrong project!

SimpleDNSCrypt's repository is here: https://github.com/bitbeans/SimpleDnsCrypt
