### ISSUE TITLE
Anyone heard about Babylon Network?

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#648]
I downloaded latest _dnscrypt-resolvers.csv_ (2017-05-06) and noticed 6 new resolvers (3 x IPv4/Ipv6), all depending of **_Babylon Network_** with 2 servers in Quebec, Canada and 4 in Roubaix, France.

The resolvers proprieties display as well all 6 tied to https://babylon.network
That page mentions the site is under construction ... and little, unclear info found on the Web, anyway nothing related to DNS and even les to DNSCrypt-Proxy

So if anyone has information I'd be glad to discover what **is** _Babylon Network_

Thanks

**Comment by jedisct1** [comment]
The under construction page shows a contact address, so this is probably a better way to reach out to them :)

Original pull request was from @tsemeijn: https://github.com/jedisct1/dnscrypt-proxy/pull/647

**Comment by zymase** [comment]
I did send an email to the address provided on the website but for one I still have no echo and for two users' info may prove to be complimentary to whatever the site would answer me.

**Comment by tsemeijn** [comment]
I have replied to your e-mail @zymase and sorry for my lack of information on the website. The website will be finished soon and display all our projects. Feel free to contact me when any questions arise.

**Comment by sergeevabc** [comment]
@tsemeijn, 171 days passed, still under construction. :(

**Comment by tsemeijn** [comment]
I am aware the website is still not up. Personal stuff and regular day job eating all time. I will post an update once the website is up.

**Comment by sergeevabc** [comment]
Perhaps you could reveal some details similarly to [this][1] right here for people who are looking for?

[1]: https://dnscrypt.nl/
