### ISSUE TITLE
dnscrypt-proxy-win64-full-1.9.5.zip is incomplete

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#650]
dnscrypt-proxy-win64-full-1.9.5.zip, 06-May-2017 19:53, 824272b available at https://download.dnscrypt.org/dnscrypt-proxy/ is incomplete and doesn't work out of the box. Should files be copied over the dnscrypt-proxy-win64-full-1.9.5 install? Because as such several dlls are missing (824272 bytes!)

Sorry but I happen to (still) be a Windows user.

**Comment by CNMan** [comment]
same issue windows x86 and x64

copy dlls from v1.9.4 and work fine
```
libcrypto-41.dll
libdcplugin_example_ldns_aaaa_blocking.dll
libdcplugin_example_ldns_blocking.dll
libdcplugin_example_ldns_forwarding.dll
libdcplugin_example_ldns_opendns_deviceid.dll
libdcplugin_example_ldns_opendns_set_client_ip.dll
libldns-2.dll
```

**Comment by zymase** [comment]
OK, @CNMan , that's what I had in mind though I hesitated because up to now DNSProxy for Windows always appeared as full, ready to use, and because I'm not an expert.

Rebuilding dnscrypt-proxy-win64-full-1.9.5.zip by adding to it the files you mention for the sake of a ready-to-use backup.

**Comment by jedisct1** [comment]
Thanks for reporting this. Looks like the ldns library couldn't be built.
AFK for now but I'll take a look as soon as possible.

**Comment by jedisct1** [comment]
Just noticed that crypto.dll in the list. OpenSSL might be the root cause.

**Comment by zymase** [comment]
I've restored dnscrypt-proxy-win64-full-1.9.4.zip files, then copied files from dnscrypt-proxy-win64-full-1.9.5.zip over them, hence replacing available new ones.

Sorry to be closer to cooking than to coding but when you wish to use a tool such as DNSCrypt-Proxy and at the same time happen to be totally technically illiterate in that area you have to think with basic logic.

Anyway proceeding as I mention works and I write here with that arrangement. I hope I'm not missing something.

**Comment by jedisct1** [comment]
So, the problem was in LibreSSL, whose current master branch doesn't include a required file.

The fix, and the correct thing to do no matter what, is to use a release tag, and not the development tree.

New builds in progress!

**Comment by jedisct1** [comment]
New builds uploaded. That was actually a bug in the LibreSSL build system.
Thanks!
