### ISSUE TITLE
Can't make Forward parameter work

### ISSUE THREAD

**Issue by GCRaistlin** [jedisct1/dnscrypt-proxy#654]
I want dnscrypt-proxy to forward queries to certain domain to the different DNS server:
`Forward domains:"rutracker.org rutracker.cr" to:"192.168.100.1"`
This doesn't work: "rutracker.org" should be resolved to the address like "10.x.x.x" but `tracert rutracker.org` reports "195.82.146.214". `tracert 192.168.100.1` completes OK.

**Comment by jedisct1** [comment]
What does the relevant line in the configuration file look like?

**Comment by jedisct1** [comment]
Ok, saw it, sorry. And it looks correct.

The forwarding plugin forwards DNS queries. Not other kind of packets.
So, "tracert" is not the right tool to check that the query is being sent to `192.168.100.1`.

Just use `hostip` to check that `rutracker.org` resolves to the IP sent by `192.168.100.1` and not by the regular resolver.

**Comment by GCRaistlin** [comment]
> "tracert" is not the right tool to check that the query is being sent to 192.168.100.1
I used tracert only to see to which IP address the hostname will be resolved. `hostip rutracker.org` shows the same address.

**Comment by GCRaistlin** [comment]
It works sometimes though, but in a strange way. I noticed that I can't open rutracker.org and rutracker.cr in my browser ("Server not found"). tracert returned an error, too ("Unable to resolve target system name rutracker.org"). It's on my client machine. On the Internet gate, both hostip and tracert was able to resolve rutracker.org - to the address in the local VPN subnet 10.x.x.x, i. e. DNS forwarding was working. In a few minutes, all returned to the working state (or the breaking state - it depends on the point of view): rutracker.org can be resolved on the clients again, as well as on the Internet gate, but to its "native" address - i. e. DNS forwarding stopped working.

**Comment by jedisct1** [comment]
Maybe the VPN software is trying to change the DNS configuration?

Try resolving `resolver.dnscrypt.org`, it returns the IP address of the resolver you are using.

**Comment by GCRaistlin** [comment]
>Maybe the VPN software is trying to change the DNS configuration?

It is unlikely as DNS server is set manually to 127.0.0.1 for all VPN connections.

>Try resolving resolver.dnscrypt.org, it returns the IP address of the resolver you are using.

It is resolved to 93.95.226.165.

Investigating further. I changed forwarding setting - only queries to rutracker.org should be forwarded. Then I restarted dnscrypt-proxy and tried to resolve rutracker.org on the client. No success. On the Internet gate, it was resolved to its native address. rutracker.cr was resolved both on the client and on the Internet gate. So there is certainly a problem with using DNS forwarding option in general and if dnscrypt-proxy is used on a router in particular.

**Comment by GCRaistlin** [comment]
On the other hand, now rutracker.org can be resolved on the client without any issue...

**Comment by GCRaistlin** [comment]
I am very sorry. I found an error in my routing logic that was possibly the reason of "Server not found" error on the client, so it's definitely not a dnscrypt-proxy fault. Though I still can't make DNS forwarding work.

I'm going to explain what I want to get. There are a lot of Internet resources that are banned in Russia, including rutracker.org. To pass the ban around, I used to use a VPN connection (VPN1) and dnscrypt-proxy for DNS resolving. But a few days ago a native blocking was introduced on rutracker.org: some materials are unavailable depending on the country you logged from. This native blocking can be passed around using a special VPN connection (VPN2) - its DNS server (192.168.100.1) resolves banned domain names, e. g. rutracker.org, to the addresses in its local subnet 10.224.0.0, so banned resources will be accessed through VPN2 if their names are resolved by its DNS server. I still want to add routes to the native address of rutracker.org in order to access it through VPN1 if VPN2 fails for some reason.

On my Internet gate, I establish 2 VPN connections - VPN1 and VPN2. Both of them have 127.0.0.1 as the DNS server (it makes a little sense for VPN2 but I want to make sure that the whole IP configuration doesn't know about 192.168.100.1 at all). To forward DNS queries to rutracker.org to 192.168.100.1 I added `Forward domains:"rutracker.org" to:"192.168.100.1"`. `tracert 192.168.100.1` shows that this DNS server is available. All DNS caches (local DNS cache on the client and on the Internet gate, DNS server cache on the domain controller) are cleared many times. dnscrypt-proxy and OpenVPN services are restarted many times. But... `hostip rutracker.org` still returns 195.82.146.214.

I said above that I found the error. There were actually 2 errors: the first one is possible and the second one is unconditional. The first error was that the second DNS server for VPN2 was set to 192.168.100.1 (while the first one was 127.0.0.1). The second error was that I used command like `route rutracker.org` to add routes on establishing VPN1 connection  - and , according to the route table, rutracker.org was being resolved - sometimes! - to the address in 10.224.0.0 and queries to this address were being routed to VPN1 - what of course didn't work. Now I simply add the route to 195.82.146.214.

Sorry for being so verbose.

And another question: what is dnscrypt-proxy supposed to do if the address it forwards certain DNS queries to is not available? Will it pass these queries to the default resolver in this case? In other words, does my double VPN configuration have any sense?

**Comment by jedisct1** [comment]
If you are using the forwarder plugin to use a fixed set of resolvers for some domains, and these resolvers fail, it will not ask the default resolver.

A common use case for the forwarding plugin is to resolver private/internal domains, so these queries should never go to public resolvers.

**Comment by GCRaistlin** [comment]
Just as I suspected. So it has no sense to add the route to the native rutracker.org address to the routing table if I'm using DNS forwarding for rutracker.org - and if it works of course, 'cause it doesn't for now. Or I just do something wrong.

**Comment by jedisct1** [comment]
Sorry, your setup is way too complicated for me to follow.
