### ISSUE TITLE
Feature request: Automatically change to a different random resolver.

### ISSUE THREAD

**Issue by sam1275** [jedisct1/dnscrypt-proxy#655]
Hello.

It will be great if Dnscrypt-proxy can automatically change to a different random resolver, because:
    If it can change to a different random resolver when the current one is not responsive, it will eliminate the need of running multiple instances at the same time.
    If it can change to a different random resolver every X minutes/hours, it will reduce fingerprinting, improve privacy, and make it more difficult to censor Dnscrypt.

You mentioned it's a bad idea in "https://github.com/jedisct1/dnscrypt-proxy/issues/581", why?

Thanks

**Comment by jedisct1** [comment]
This is what the cache or stub resolver in front of it is for.

Detecting DNS failures is complicated and out of the scope of this proxy.

If you want to switch to a different resolvers, maybe you can just set up a cron job that restarts it (and set the resolver name to `random`). Now, multiple people will have a copy of your traffic. I'm not convinced that this is an improvement if privacy is your concern. You'd better use a single resolver you trust, or use your own resolver, hosted at an ISP you trust.

DNSCrypt's purpose is to improve security, not to avoid censorship, or work around restrictions that you are supposed to comply to.
