### ISSUE TITLE
dnscrypt-resolvers.csv corrections

### ISSUE THREAD

**Issue by Zenith-Nadir** [jedisct1/dnscrypt-proxy#658]
Hello,
this is probably very minor, just for consistency; there is inconsistency in the dnscrypt-resolvers.csv file:
soltysiak-ipv6 name entry (close to the end of the file) is missing quotation "" marks in "Full name","Description" fields.
Sincerely,
Zenith-Nadir

**Comment by Zenith-Nadir** [comment]
"Full name","Description","Location" fields

**Comment by jedisct1** [comment]
Thanks!

The quotes are only required for text containing the delimiter (`,`), but you are correct, having them for consistency cannot hurt!

I'm gonna fix that. Thanks!
