### ISSUE TITLE
[Feature Request] Add default rule: block all

### ISSUE THREAD

**Issue by MrSorcus** [jedisct1/dnscrypt-proxy#659]
I want to block all by default, but if domain found in white list - get DNS request for this domain.
Thanks.

**Comment by jedisct1** [comment]
Whitelists work really badly in practice. Today's website rely on load balancers, CDNs, and other pieces of infrastructure dynamically generating DNS names.

Establishing a reliable whitelist for specific services is virtually impossible and requires quite a lot of maintenance.

That can be done, and actually you can just take the current blocking plugin and invert the check, but be prepared for breakage.

**Comment by mariarti** [comment]
> invert the check
how to do it?
how to allow it by the white list?

**Comment by MrSorcus** [comment]
For example, in config file:
```
BlockAllDomains on
WhiteDomainsList: "/etc/domains_white.list"
```
When open example.com, check this domain in white list. If not found - return DNS error code.

**Comment by jedisct1** [comment]
Changing `if (block)` to `if (block == 0)` here: https://github.com/jedisct1/dnscrypt-proxy/blob/4a2e773af9e24413c9ad7c6eee38dc1a781ee944/src/plugins/example-ldns-blocking/example-ldns-blocking.c#L655 should invert the behavior.

**Comment by jedisct1** [comment]
I quickly hacked that thing based on the block plugin: https://github.com/jedisct1/dnscrypt-plugin-whitelist-only

Completely untested, but feel free to give it a spin!

**Comment by MrSorcus** [comment]
Thanks you very much. It's work. I'm happy. :-)
