### ISSUE TITLE
Blocklist rules followed by comment aren't blocked

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#660]
Hi,

I'm encountering a major issue with domain rules followed by a comment which aren't blocked.

i.e.
```
youboranqs01.com #Nice People At Work
*.youboranqs01.com #Nice People At Work
```
are not blocked (I've tested with both independently)

But,
```
youboranqs01.com
*.youboranqs01.com
```
are blocked correctly (I've tested with both independently)

This is truly problematic for me because I have one list in particular where the authors have added I don't know how many comments to their [domain blocklist list ](https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt), list which I merge with others.

I'm mentioning this because as far as I know comments are accepted in DNSCrypt-proxy lists. If not, or if no longer then sorry for the bother.

**Comment by jedisct1** [comment]
Comments are accepted on their own line. They have never been supported on the same line as an element, especially since `#` is a valid character in a host name.

**Comment by jedisct1** [comment]
Are you using the `generate-domains-blacklist.py` script? I think that script strips inline comments.

**Comment by zymase** [comment]
> Comments are accepted on their own line. They have never been supported on the same line as an element, especially since # is a valid character in a host name.

OK. This explains that. Thanks Frank.

I'm on Windows and I have to manage lists concatenation myself.

For downloading the files and merging them I use an application called 'Bat to Exe Converter' which, more thn only converting a bat file to an exe one also has a built-in feature which allows to download files from the desktop. My bat file is as,

```
@echo off

REM downloads for DNSCrypt
%extd% /download "https://ransomwaretracker.abuse.ch/downloads/RW_IPBL.txt" "IMPORT-DC-ADR1.txt"
%extd% /download "https://zeustracker.abuse.ch/blocklist.php?download=badips" "IMPORT-DC-ADR2.txt"
%extd% /download "https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt" "IMPORT-DC-DOM1.txt"
%extd% /download "https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt" "IMPORT-DC-DOM2.txt"
%extd% /download "https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt" "IMPORT-DC-DOM3.txt"
%extd% /download "https://zeustracker.abuse.ch/blocklist.php?download=baddomains" "IMPORT-DC-DOM4.txt"
%extd% /download "https://mirror1.malwaredomains.com/files/justdomains" "IMPORT-DC-DOM5.txt"
REM downloads for PeerBlock
:: %extd% /download "https://pgl.yoyo.org/adservers/iplist.php?ipformat=peerblock&showintro=0&mimetype=plaintext" "IMPORT-PB-LIST1.txt"

REM merge DNSCrypt HOME lists with DNSCrypt IMPORT & NOTRACK lists
TYPE HOME-blacklist-adr.txt IMPORT-DC-ADR*.txt > blacklist-adr.txt
TYPE HOME-blacklist-dom.txt IMPORT-DC-DOM*.txt NOTRACK.txt > blacklist-dom.txt
REM merge PeerBlock HOME list with PeerBlock IMPORT lists
TYPE HOME-blacklist-peer.txt IMPORT-PB-LIST* > blacklist-peer.txt

IF %result% EQU 0  (
	%extd% /messagebox Error "Blocklists-Import : Download failed" 16
) ELSE (
	%extd% /messagebox Done "Blocklists-Import : Download succeeded"
)
```
This way I can download/merge and update, 1- DNSCrtpt-proxy dom and adr files, 2- if applicable PeerNlock lists not available at iblocklist.com. I do that every morning at coffee time.

I've removed the 2 files from NoTrack because they don't get updated more than once a week. rather, I download them manually, clean them up (that darn #) and have a page update site (changedetection.com) check once a day if these files have been updated. 

As you see it's far more cumbersome than if I was using python files, moreover here provided. But I'd have to install the "Python Machine" here on Windows and frankly, considering my low-low level I woldn't use it for anything else than DNSCrypt, so I just do thinhs like in the good old prehistoric times ...

**Comment by jedisct1** [comment]
That's probably something trivial to do with Powershell.

**Comment by zymase** [comment]
Script for script I'd be, basically, more tempted by Python for Windows. But, again, confessing my ignorance would appear as auto-destructive!

I've read an article yesterday over at How-To Geek, [How to Install Python on Windows](https://www.howtogeek.com/197947/how-to-install-python-on-windows/) and, hum... I may very well start moving my brains in order to advance. I'm too much in the "use/think tools you know". If I do install Python on Windows it would really facilitate managing DNSCrypt-proxy, allowing me to use dedicated scripts available here. I'll think about it!
