### ISSUE TITLE
Dnscrypt-proxy - 1.9.4-3 vs 1.9.5-1

### ISSUE THREAD

**Issue by Goro2030** [jedisct1/dnscrypt-proxy#661]
I've noticed that when upgrading to the latest release ( I think from yesterday or today ) , dnscrypt stops working after reboot, if you use any of the options that come commented in the base package. I was using this options:

```
config dnscrypt-proxy ns1
        option address '127.0.0.1'
        option port '5353'
        option resolver 'cisco-familyshield'
        option resolvers_list '/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv'
        # ephemeral keys option requires extra CPU cycles and can cause huge system load
        # option ephemeral_keys '0'
        # more details at https://github.com/jedisct1/dnscrypt-proxy#public-key-client-authentication
        # option client_key '/path/to/client_key'
-->        option syslog '1'
-->        option syslog_prefix 'dnscrypt-proxy'
-->        option query_log_file '/mnt/sda1/dnslogs/dnsqueries.log'
        # enable cache may speed up dnscrypt-proxy, see https://github.com/jedisct1/dnscrypt-proxy/wiki/Go-faster
-->        option local_cache '1'
        # disable IPv6 may also speed up dnscrypt-proxy, see https://github.com/jedisct1/dnscrypt-proxy/wiki/Go-faster
-->        option block_ipv6 '1'
        # Blacklists allow you to block domains, ip, ... see https://github.com/jedisct1/dnscrypt-proxy/wiki/Filtering
-->        list blacklist 'domains:/usr/share/dnscrypt-proxy/dnscrypt-blacklist-domains.txt' 'logfile:/mnt/sda1/dnslogs/dnscrypt-blocked.log'
```

Some of the lines preceded with a --> are the ones that are creating chaos. 

I tried several combinations, and for example , running the latest version ( 1.9.5-1 ) , I was able to enable option syslog '1' and option syslog_prefix, but not the others.

Running a dnscrypt-proxy restart logs in the system log something like "plugins are not implemented", and the router is left with no capability to resolve DNS Addresses ( therefore, the whole network goes down )

I was also unable to make the option to save the blocked queries into the log file... it does save the queries, but not the blocked ones

**Comment by licaon-kter** [comment]
Operating system? Architecture? Package source?

**Comment by jedisct1** [comment]
I've never seen a configuration file that looks like that. It's certainly not something the normal `dnscrypt-proxy` package can load.

There have been no new releases for the past few days either. So I'm not sure what you have installed.

`"plugins are not implemented"` means that support for plugins was disabled when the package was compiled. Plugins have been enabled by default for a long time, so they have been explicitly disabled.

Which means that logging, filtering, IPv6 filtering, etc. cannot work. They are all plugins.

**Comment by Goro2030** [comment]
I'm running on a router using LEDE. Source are:
```
src/gz reboot_core https://davidc502sis.dynamic-dns.net/snapshots/r4114/targets/mvebu/generic/packages
src/gz reboot_base https://davidc502sis.dynamic-dns.net/snapshots/r4114/packages/arm_cortex-a9_vfpv3/base
src/gz reboot_luci https://davidc502sis.dynamic-dns.net/snapshots/r4114/packages/arm_cortex-a9_vfpv3/luci
src/gz reboot_packages https://davidc502sis.dynamic-dns.net/snapshots/r4114/packages/arm_cortex-a9_vfpv3/packages
src/gz reboot_routing https://davidc502sis.dynamic-dns.net/snapshots/r4114/packages/arm_cortex-a9_vfpv3/routing
```

**Comment by jedisct1** [comment]
Since this is completely different from a vanilla installation of dnscrypt-proxy, you should probably report this to the LEDE maintainers.

I'm not familiar with LEDE, but perhaps the plugins are in a different package?

Alternatively you can use [dnscrypt-proxy installer](https://github.com/jedisct1/dnscrypt-proxy-installer) but this requires the ability to write files to `/lib` and I don't know if this is the case on LEDE.

**Comment by Goro2030** [comment]
Frank, thanks! I did report this to the LEDE maintaner already.
