### ISSUE TITLE
dnscrypt.org-fr Can't Resolve 2 Sites Using CNAME At incapdns.net

### ISSUE THREAD

**Issue by vindicatorr** [jedisct1/dnscrypt-proxy#662]
I found that I couldn't connect to the web sites for menards and ncponline.
I thought it was interesting they both used Incapsula (cname to incapdns.net) since both sites are very different from each other.

Google's DNS brought up the web site, but dnscrypt.org-fr did not. I added dnscrypt.eu-nl as another resolver and that DID resolve a usable IP.

I don't know how it all works, but I think Google, dnscrypt-fr, and eu-nl all "drilled" to different IPs for the ncponline domain (maybe something to do with regional CDN?). I'm just not sure why fr couldn't come up with a usable IP.

**Comment by jedisct1** [comment]
Is that `www.ncponline.com`? I just tried without using dnscrypt, just my ISP's DNS, and got an Incapsula page that says "www.ncponline.com - Access Denied - Error code 16 This request was blocked by the security rules".

I don't know what that website is, but maybe they are under attack and Incapsula is blocking queries from some networks.

**Comment by jedisct1** [comment]
The resolver doesn't seem to have any problems returning an IP for that name:
```
hostip -r 127.0.0.1 www.ncponline.com
107.154.115.87
```

That IP properly belongs to Incapsula: https://api.iptoasn.com/v1/as/ip/107.154.115.87

So I don't think there is anything the resolver can do. It already does its job.

The CDN or their customer decided to block some networks or some countries. Or they are having a regional outage. I don't know. Don't even know what this website is. But there's not much I can do.

Maybe they have a status page you can check, or you can contact them on social networks to check what's going on.

**Comment by vindicatorr** [comment]
HA! "contact them"... yes, they have online chat on their main page and it was a joke of an attempt to question the problem.
The chat representative status showed "Sales" so that's probably why they were of no help. Their response was simply:

> Please contact the site admin/owner. I cannot assist in this matter. The site is using our services and is having an error on their side. They should contact our support. Thank you for your understanding.

Can you tell me what browser you used and who your DNS provider is? At least you were redirected to their site which described the issue. I'll take that bit back to them and see what kind of garbage they want to spew this time.

Thanks for checking it out.

**Comment by jedisct1** [comment]
I used Google Chrome and my ISP is Free.fr -- Also tried via an OVH VPN and got the same result.

**Comment by vindicatorr** [comment]
Thanks, I notified both businesses affected. I hope the message gets to the right people.
