### ISSUE TITLE
Dnscrypt-proxy can only listen on 127.0.0.1 on Windows using CMD

### ISSUE THREAD

**Issue by sam1275** [jedisct1/dnscrypt-proxy#663]
There's no problem if installed as service, but when run it from CMD, it cannot listen on anything other than 127.0.0.1.
Is this a known issue?

**Comment by jedisct1** [comment]
What does the configuration file look like?

**Comment by sam1275** [comment]
I didn't use a configuration file, I use "--local-address=127.0.0.x:53" directly in the CMD.
I tested again and this time it works, some dead resolvers maybe to blame (although the log looks fine).
