### ISSUE TITLE
dnscrypt.org confused information

### ISSUE THREAD

**Issue by sam1275** [jedisct1/dnscrypt-proxy#666]
The main site dnscrypt.org have some messed up information: according to github, the latest version is 1.9.5, but dnscrypt.org says "Current stable DNSCrypt client version: 1.9.4" and "[05/06/2017] dnscrypt-proxy 1.6.5 has been released!"
I first thought it's a temporarily mistake, but it remained for many days...

**Comment by jedisct1** [comment]
Updated, thanks!
