### ISSUE TITLE
issue about the last character case of domain names in the log

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#668]
os version: windows server 2012 r2
dnscrypt-proxy version:1.9.5

some uppercase and some lowercase

![2017-05-24_025738](https://cloud.githubusercontent.com/assets/8692234/26371406/339326e4-402d-11e7-91e9-034faeabd2b2.png)

**Comment by jedisct1** [comment]
That's expected. The last character in upper case is for queries requesting DNSSEC signatures.
