### ISSUE TITLE
macOS intermittent failure to resolve DNS

### ISSUE THREAD

**Issue by Offbeatmammal** [jedisct1/dnscrypt-proxy#669]
it seems pretty random but every now and then I get a web page failing to load because of a DNS error. If I disable DNSCrypt (using macOS GUI Client) and hit the page again it works fine.

Sometimes turning it back on again then works fine for that URL, but other times I need to move to a different DNS server before it settles.

I assume there's an issue on the query (timeout? update on DNS server not returning a record? load?)

Not a huge issue (and never happens on Windows 10 that I've seen) but wanted to flag in case there's anything I can do to help debug

**Comment by jedisct1** [comment]
Try using the this project (dnscrypt-proxy) directly, without the UI. The UI is quite sensitive to unstable network configurations.
