### ISSUE TITLE
SEGFAULT on boot when using grsec kernel

### ISSUE THREAD

**Issue by Boruch-Baum** [jedisct1/dnscrypt-proxy#670]
When I boot a debian pre-packaged grsec kernel, kern.log tells me that /usr/sbin/dnscrypt-proxy seg faults.

However, in such cases, the service operates fine when started manually, after boot. When booting a non-hardened kernel, no segfault occurs.

My current guess is that there is something missing from the 'required-start' directive of my init script (not systemd), which currently reads
```
# Required-Start:    $network $local_fs
```

The kern.log message is:
```
kernel: [   49.519590] grsec: Segmentation fault occurred at 000000780000186a in /usr/sbin/dnscrypt-proxy[dnscrypt-proxy:6250] uid/euid:120/120 gid/egid:65534/65534, parent /sbin/init[init:1] uid/euid:0/0 gid/egid:0/0
```

**Comment by jedisct1** [comment]
Can you try the official binaries? https://github.com/jedisct1/dnscrypt-proxy-installer

**Comment by Boruch-Baum** [comment]
No, just the official debian packages, and it happened to me (repeatedly) on a system that I'm not supposed to be continuously taking offline and rebooting. In terms of running up-to-date code, I see that debian still hasn't packaged 1.9.5, although their website indicates it's on their automated todo list, so I'm stuck with their 1.9.4-1.

**Comment by jedisct1** [comment]
Ok, so you're using an outdated distribution-specific package on an unstable distribution on which you changed the kernel and replaced at least the way the server is started with your own.

There's nothing wrong with that, but I can't realistically spend my spare time reproducing this unique setup and investigate why that combination doesn't work.

If you can investigate on your end, confirm that the problem is indeed in the dnscrypt-proxy code, and pinpoint where that problem is, I'd be glad to merge your pull request or help write a fix.

**Comment by licaon-kter** [comment]
> reproducing this unique setup

*grsec* just made their patches subscriber only, you would not be able to repro this setup

**Comment by Boruch-Baum** [comment]
I understand, and it's OK for me.

You did go a bit overboard in your characterization, as I'm running a supported kernel of debian stable, which is also used by all linux distributions based upon debian (that's a lot of linux).

You bring up a good point that I needed to write a SysVinit script for dnscrypt-proxy. Do you want a copy? It's a simple script, and I can point you to other downstream sources with more elaborate versions, if you want to integrate that.

As for what may be the source of the seg fault, I think my initial post was clear that I didn't think your code was at issue, but rather how it plays with grsec protections only upon boot, not when started after init has completed.

I thought you and your user base would be interested because I thought people interested in dnscrypt-proxy would be more likely to be interested in grsec than the average user.

**Comment by Boruch-Baum** [comment]
@licaon-kter: It certainly is reproducable - it's a pre-packaged debian kernel!

@licaon-kter: This is at least the second time that I remember the grsec announced moving to a subscriber only model. Even if this time the decision sticks, the debian grsec kernel is LTS till 2019. Also, grsec subscribers might be just the kind of people interested in dnscrypt-proxy.

**Comment by licaon-kter** [comment]
Now, non-subscribers don't have any sources/packages access whatsoever, and if a subscriber shares his/her own, I don't know what punishment that contract has in store for him/her.


https://www.grsecurity.net/passing_the_baton_faq.php

**Comment by jedisct1** [comment]
A Debian package with a version of dnscrypt-proxy that is not 2 years old is unlikely to be in Debian-stable.
