### ISSUE TITLE
Some names stop being resolved

### ISSUE THREAD

**Issue by GCRaistlin** [jedisct1/dnscrypt-proxy#671]
From time to time I'm experiencing the following issue: some names suddenly stop being resolved. The web browser says "Server not found", nslookup says "Unable to resolve". Restarting dnscrypt-proxy helps. Disabling local cache doesn't.

**Comment by licaon-kter** [comment]
Are you using only dnscrypt-proxy or are you caching it with unbound or anything else?

I ask this because I am seeing it with unbound, resolving via 53 where unbound listens does fail, but resolving directly to the ports that dnscrypt-proxy listens too works. Restart the unbound daemon fixes it, until next time that is.

**Comment by jedisct1** [comment]
I guess that's on Windows?
What did you change to the default configuration file?
What exact queries stop being resolved?

**Comment by GCRaistlin** [comment]
I run dnscrypt-proxy service on my Internet gate that is running Windows Server 2003 R2 SP2. DNS server settings of all outer network adapters are set to 127.0.0.1. The only change to the conf is "LocalAddress 0.0.0.0:53".
I cannot resolve rutracker.org, livesport.ws and a couple of others. I can see it as OpenVPN adds routes on the connection establishing, and it requires the corresponding names to be resolved first; this resolving fails for a lot of names when the issue is arising. But other names can be resolved without any trouble, including those that haven't being recently resolved on the machine, so it's not because of the DNS cache.

**Comment by jedisct1** [comment]
Is it still happening if you don't use any VPN?

**Comment by GCRaistlin** [comment]
Hard to say - a lot of sites ain't available without VPN. It's Russia...
How can VPN influence upon this? Some of the sites that remain available should be accessed via VPN, too. And they can be.

**Comment by GCRaistlin** [comment]
Also, some sites that stop being resolved are accessed directly, not via VPN.

**Comment by licaon-kter** [comment]
Did you try other DNS servers?

**Comment by GCRaistlin** [comment]
What do you mean under other DNS servers? Of course I can use the Google one, and it will work, but what can it give us?

**Comment by jedisct1** [comment]
Other DNSCrypt-enabled servers. Which one are you currently using? Unless it is your own?

**Comment by GCRaistlin** [comment]
It is random, as by default.

**Comment by jedisct1** [comment]
Maybe it picked a resolver which is too far/too slow for your location. Try a non-random one.

**Comment by GCRaistlin** [comment]
OK I did. We'll see. It's strange though that at first any randomly chosen resolver always works OK.
BTW the test command from the docs (`dnscrypt-proxy.exe dnscrypt-proxy.conf --test=0`) doesn't work until --test=0 is removed.

**Comment by GCRaistlin** [comment]
The issue has arisen again. This time restarting dnscrypt-proxy service didn't help, as well as stopping OpenVPN service. I believe it's the chosen resolver fault 'cause changing it to 'random' helps. The only question is what to do further. Restarting the service on a regular basis isn't a nice solution.

**Comment by jedisct1** [comment]
Unless you need features such as blocking IPs/names and logging, using dnscrypt along with a VPN is usually a very bad idea anyway.

**Comment by licaon-kter** [comment]
That site: https://github.com/jedisct1/dnscrypt-proxy/search?q=rutracker&type=Issues&utf8=%E2%9C%93 has issues :)

**Comment by GCRaistlin** [comment]
I use dnscrypt because I need a secure way to resolve names. I don't want my provider or Google to see my activity. Why is it a bad idea to use dnscrypt along with a VPN?

**Comment by jedisct1** [comment]
When you use a VPN, your DNS queries are already encrypted and authenticated. Using dnscrypt instead of your VPN's DNS makes things slower, and now instead of having only the VPN provider know about your activity, an additional copy is sent somewhere else. From a privacy perspective it makes things worse.

**Comment by GCRaistlin** [comment]
A lot of VPN providers offer Google DNS servers to use. And I don't redirect my whole traffic to VPN.

**Comment by jedisct1** [comment]
If they don't even manage to run their own DNS servers, you should not trust them for anything else. Set up your own or use a more serious VPN company...

**Comment by GCRaistlin** [comment]
They work or they don't, it's currently the only thing that is important to me. Anyway, even if the VPN provider offers its own DNS server there's no guarantee that it doesn't keep logs.

**Comment by GCRaistlin** [comment]
I changed the VPN provider. With the previous one, the VPN connection was being closed (and re-established automatically) often because of the inactivity tiemout or something. Sometimes it might happen tens of times successively. With the current one, the VPN connection is stable. Since the change, the issue stops arising.
In my setup, a lot of routes are being added on the VPN connection establishing. It requires the corresponding quantity of names to be resolved.
Can't the dnscrypt resolver consider these repeated queries (at least 60 queries every 10 seconds) as a kind of DDoS and stop resolving queries from me because of that?

**Comment by jedisct1** [comment]
Resolvers can indeed throttle repeated queries. 6 queries per second is not a lot, though. Not saying that this is not enough to avoid triggering a limitation on some resolvers, but the vast majority has higher limits.

**Comment by GCRaistlin** [comment]
Not 6 queries per second but 60 queries per second every 10 seconds.

**Comment by GCRaistlin** [comment]
I'm still experiencing this issue. It happened again just now. No VPN reconnect was performed this time but there was this:

Sun Jun 11 20:32:03 2017 TLS: tls_process: killed expiring key
Sun Jun 11 20:32:12 2017 TLS: soft reset sec=0 bytes=83939/-1 pkts=1220/0
Sun Jun 11 20:32:14 2017 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sun Jun 11 20:32:14 2017 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Sun Jun 11 20:32:15 2017 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Sun Jun 11 20:32:15 2017 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun Jun 11 20:32:15 2017 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Sun Jun 11 20:32:15 2017 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun Jun 11 20:32:15 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 1024 bit RSA

As before, some sites (google.ru, mir.cr) are affected by the issue while others (google.com, github.com, rutracker.org - sic!) are not. Restarting dnscrypt-service helped.

**Comment by jedisct1** [comment]
I don't know what applications these logs come from, but this is certainly not dnscrypt-proxy.

**Comment by GCRaistlin** [comment]
It's OpenVPN log. Right after these events happened dnscrypt stopped resolving some names. Of course it may be a coincidence.

**Comment by GCRaistlin** [comment]
Today I run into the issue again. Even restarting dnscrypt-proxy service didn't help. Then I run it as an app and saw the following:

06/16/17 13:55:49 [ERROR] Unable to retrieve server certificates
06/16/17 13:55:50 [INFO] Refetching server certificates
06/16/17 13:56:05 [ERROR] Unable to retrieve server certificates
06/16/17 13:56:08 [INFO] Refetching server certificates
06/16/17 13:56:23 [ERROR] Unable to retrieve server certificates
06/16/17 13:56:29 [INFO] Refetching server certificates

It was endless. I restarted dnscrypt-proxy again and it helped. Then I started dnscrypt-proxy as a service and it works. Resolver is random.

How could this certificate problem be diagnosed when dnscrypt-proxy runs as a service?

**Comment by jedisct1** [comment]
You didn't even start using the DNSCrypt protocol at this point. Certificates are retrieved using standard, unauthenticated DNS queries.

Check that you don't have something blocking DNS queries. Maybe an antivirus or some firewall rules on your router.

**Comment by GCRaistlin** [comment]
How can something block DNS queries if simple dnscrypt-proxy restart helped?

**Comment by jedisct1** [comment]
Some details are probably missing, but I know for sure that a DNSCrypt session cannot start without certificates, and if only for that reason, DNSCrypt is not used to retrieve certificates.

**Comment by GCRaistlin** [comment]
Certificates are retrieved using dnscrypt-resolvers.csv - DNSCrypt don't need any "general" DNS servers to retrieve them. It sends DNS queries to the IP address from the dnscrypt-resolvers.csv and gets the certificates. But something went wrong. Maybe on the client side, maybe not. DNSCrypt keeps trying with no success, names on the clients can't be resolved, we have no chance to know what's wrong 'cause there's no log, Wouldn't it be better in this case for DNSCrypt to try to reconnect to the chosen resolver or to select another one if set to "random"?

**Comment by jedisct1** [comment]
> Certificates are retrieved using dnscrypt-resolvers.csv - DNSCrypt don't need any "general" DNS servers to retrieve them.

It does.

(PS: I'm the author of the protocol)

The CSV file only includes public keys used to verify the certificates.

**Comment by GCRaistlin** [comment]
That's interesting. DNS server setting of all my outer network interfaces is set to 127.0.0.1. My Internet gate simply doesn't know any DNS servers except DNSCrypt. How can things work at all then?
And, by the way, I see a column with resolvers' addresses in dnscrypt-resolvers.csv. Why does DNSCrypt need a "general" DNS server to work if it gets all it needs from dnscrypt-resolvers.csv?

**Comment by jedisct1** [comment]
The protocol is described here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt

It will connect to the IP of the configured resolver, but in order to send a standard DNS query. It's not going to use dnscrypt at this point.

The query is similar to the one send by this command:
```sh
drill -p 443 txt 2.dnscrypt-cert.fr.dnscrypt.org @212.47.228.136
```

**Comment by jedisct1** [comment]
Still, check that you don't have an antivirus or something similar the would hijack connections to port 443.

**Comment by vdcbb** [comment]
Guys, I've been having this issue too. I've had it for a long time. It crops up every now and then going back to OpenWRT (I use LEDE now) and the way I fix it is to do a reset or reinstall. But then I have to configure all my settings again, which is a pain.

My question is related to this comment by jedisct1: "The CSV file only includes public keys used to verify the certificates."

jedisct1, should the CSV file be uncommented at /etc/config/dnscrypt-proxy? I have always commented out this line. Could this explain why I sometimes have no connectivity with those log entries saying the certificate can't be retrieved?

Here is how my /etc/config/dnscrypt-proxy file looks. Should I uncomment "option resolvers_list"?

    config dnscrypt-proxy ns1
    option address '127.0.0.1'
    option port '5353'
    option resolver 'cisco'
    # option resolvers_list '/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv'

**Comment by vdcbb** [comment]
I was able to produce this just now. I switched to d0wn-us-ns2 and had no connectivity. Logs showed this:

    Sat Jun 17 15:58:07 2017 user.info : dnscrypt-proxy - [d0wn-us-ns2] does not support DNS Security 
    Extensions
    Sat Jun 17 15:58:07 2017 user.info : dnscrypt-proxy + Namecoin domains can be resolved
    Sat Jun 17 15:58:07 2017 user.info : dnscrypt-proxy + Provider supposedly doesn't keep logs
    Sat Jun 17 15:58:07 2017 daemon.notice dnscrypt-proxy[1212]: dnscrypt-proxy Starting dnscrypt-
    proxy 1.9.4
    Sat Jun 17 15:58:07 2017 daemon.info dnscrypt-proxy[1212]: dnscrypt-proxy Generating a new 
    session key pair
    Sat Jun 17 15:58:07 2017 daemon.info dnscrypt-proxy[1212]: dnscrypt-proxy Done
    Sat Jun 17 15:58:10 2017 user.info : dnscrypt-proxy - [d0wn-us-ns2] does not support DNS Security 
    Extensions
    Sat Jun 17 15:58:10 2017 user.info : dnscrypt-proxy + Namecoin domains can be resolved
    Sat Jun 17 15:58:10 2017 user.info : dnscrypt-proxy + Provider supposedly doesn't keep logs
    Sat Jun 17 15:58:10 2017 daemon.notice dnscrypt-proxy[1971]: dnscrypt-proxy Starting dnscrypt-
    proxy 1.9.4
    Sat Jun 17 15:58:10 2017 daemon.info dnscrypt-proxy[1971]: dnscrypt-proxy Generating a new 
    session key pair
    Sat Jun 17 15:58:10 2017 daemon.info dnscrypt-proxy[1971]: dnscrypt-proxy Done
    Sat Jun 17 15:58:49 2017 daemon.err dnscrypt-proxy[1971]: dnscrypt-proxy Unable to retrieve server 
    certificates
    Sat Jun 17 15:58:50 2017 daemon.info dnscrypt-proxy[1971]: dnscrypt-proxy Refetching server 
    certificates
    Sat Jun 17 15:59:05 2017 daemon.err dnscrypt-proxy[1971]: dnscrypt-proxy Unable to retrieve server 
    certificates
    Sat Jun 17 15:59:08 2017 daemon.info dnscrypt-proxy[1971]: dnscrypt-proxy Refetching server 
    certificates
    Sat Jun 17 15:59:23 2017 daemon.err dnscrypt-proxy[1971]: dnscrypt-proxy Unable to retrieve server 
    certificates
    Sat Jun 17 15:59:29 2017 daemon.info dnscrypt-proxy[1971]: dnscrypt-proxy Refetching server 
    certificates
    Sat Jun 17 15:59:44 2017 daemon.err dnscrypt-proxy[1971]: dnscrypt-proxy Unable to retrieve server     
    certificates

**Comment by jedisct1** [comment]
This configuration file is something specific to your distribution, not the documented one which dnscrypt-proxy loads. So I don't know that removing the path to the CSV file does, but I guess it just uses a default value which is the same as the commented example.

Given the log you pasted, it looks like the version of the proxy you are using is old. If you didn't update the CSV file, some entries may not be valid any more. Try to update at least the CSV file.
The source code comes with a script called `dnscrypt-update-resolvers.sh` to do so. I don't know if your distribution has it. If it doesn't, you can download the CSV file manually here: https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv and the signature: https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-resolvers.csv.minisig

**Comment by vdcbb** [comment]
So the main need for the CSV file is if I am running custom resolvers. The CSV file is not needed if, say, I am just using the 'cisco' resolver, correct?

**Comment by jedisct1** [comment]
It’s exactly the opposite :) The CSV file is usually needed if you use a public resolver, and not needed if you run your own server that is not in the list.

**Comment by vdcbb** [comment]
Thanks so much for clearing this up, jedisct1!

So it is important to keep that CSV file uncommented, correct? 

The wikis I have read (like at https://wiki.openwrt.org/inbox/dnscrypt) often show the CSV file commented out, which led me to believe (incorrectly it appears) it was not important for public resolvers.
![screenshot](https://user-images.githubusercontent.com/11015926/27257179-a5f54c1e-539a-11e7-86d1-15b7b56ca643.png)

**Comment by jedisct1** [comment]
The official Wiki is here: https://github.com/jedisct1/dnscrypt-proxy/wiki and the normal configuration file looks like this: https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-proxy.conf

So what you describe is really something specific to your distribution, that hides the actual configuration file.

But in both cases, if the resolvers list is commented out, a default path is added, and is identical to the one from the commented out line.

The proxy doesn't know any information about resolvers without that file, so it won't even start without it.  Unless you manually provide the public key, IP, certificate name, etc.
The file is what allows giving just a resolver name, and having all the related parameters automatically retrieved.

And the default resolver is `random`, which means that it picks a random server every time it is started. But for that to happen, the list also has to be known, so the CSV file is needed :)

Still, the CSV file should be kept up to date, as resolvers come and go, IP addresses changes, and sometimes keys change as well.

**Comment by vdcbb** [comment]
> Still, the CSV file should be kept up to date, as resolvers come and go, IP addresses changes, and sometimes keys change as well.

Unfortunately LEDE doesn't appear to have > dnscrypt-update-resolvers.sh

**Comment by jedisct1** [comment]
Not a big deal, you can still manually download the file and replace the existing `dnscrypt-resolvers.csv` file with it.

Still, it would be probably great to tell the LEDE maintainers about this, and encourage them to automatically update the CSV file (and maybe use the standard config file as well?).

**Comment by vindicatorr** [comment]
I also want to put it out there that I'm having this issue as well: "Unable to retrieve server certificates" for certain resolvers (fvz-anyone, fvz-anytwo, d0wn-us-ns1).
Random was fine though.

Using the package maintained for archlinuxarm which was last updated in March.

I copied the latest github csv to the dnscrypt-resolvers.csv location for archlinux (different than config location) and set the ResolversList value to that file.

When that didn't make any difference, I manually set:
```
ProviderName    2.dnscrypt-cert.dnsrec.meo.ws
ProviderKey     1A6A:D0A3:2B4C:5A61:A695:D153:670D:69AB:1690:3F9E:C3F7:F64F:13E5:35A3:18B2:28A5
ResolverAddress 185.121.177.177
```
but that also can't retrieve the certificates. I noticed the issue when DNS resolving became unbearably slow (drill query says ~8 seconds in one case).

On a different note, are there no multiple resolvers allowed (only one allowed)? Thinking along the lines of failovers in cases like this.

**Comment by licaon-kter** [comment]
For multiple you need Unbound and multiple dnscrypt-proxy instances started.

**Comment by remlei** [comment]
I experienced the same thing, some name just stop resolving all of a sudden, this is why you need a DNS caching at the top of dnscrypt, although the issue fixes it self after 10minutes or so without restarting dnscrypt.

For now I solved it by using nxfilter using a recursive dns with dnscrypt, nxfilter handles all the DNS caching (dnscrypt builtin dns caching doesnt help at all) as well as dns filtering.

**Comment by GCRaistlin** [comment]
Sorry for bothering again, but I still experience the issue from time to time. For example, now:
```
C:\Programs\dnscrypt-proxy-win32>hostip.exe gazeta.ru
81.19.72.3
81.19.72.2
81.19.72.1
81.19.72.0

C:\Programs\dnscrypt-proxy-win32>hostip.exe rutracker.org
[server failed]
```
It happened suddenly and has been repaired with no my interaction a few minutes later (I wrote this comment and was just going to restart the service but found out that all things are working already):
```
C:\Programs\dnscrypt-proxy-win32>hostip.exe rutracker.org
195.82.146.214
```
Nothing can hijack connections on port 443 (they are allowed by firewall rules both to the Intranet and to the Internet), no antivirus installed. It happens suddenly and only for particular hostnames. Very annoying.
Can you please implement the self-restarting feature in case of continuous resolving failures? With "ResolverName random" it would make sense.
Also, I don't quite realize how caching works and if it works at all. In my browser, the tab with the address "rutracker.org" is being updated every 5 mins. That is, the record for "rutracker.org" should be updated in dnscrypt local cache every 5 mins. Then how can it be suddenly lost?
