### ISSUE TITLE
European DNS resolvers dnscrypt v2 up to date 22 12 2018

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#672]
Hi

This is an European dns resolvers list, dnscrypt v2 , DNSSec, no log and no filter.

[dnscrypt v2 - DNSSec -No log - No filter - European servers.txt](https://github.com/jedisct1/dnscrypt-proxy/files/2706049/dnscrypt.v2.-.DNSSec.-No.log.-.No.filter.-.European.servers.txt)

 .toml , conf file

Up to date 22 12 2018

You can verify conformity with official github list:
https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/public-resolvers.md

aZ

**Comment by jedisct1** [comment]
You should add this to the Wiki, provided that you will keep updating that list regularly and forever. Or publish it as a source.

But the `servers_list` is enough. `static` entries in the configuration file are mainly for people running their own private resolver.
