### ISSUE TITLE
Resolvers list download

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [jedisct1/dnscrypt-proxy#672]
Can you provide the list in a downloadable easy-to-read format like pdf?
Or an actual .csv file?

It’s too hard to read on this narrow middle-of-the-page site - gotta continuously scroll side-to-side.

I tried downloading **[dnscrypt-resolvers.csv](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv)**, but it downloads as dnscrypt-resolvers.csv.html.
And when the *.html* extension is removed, it becomes an html mess.

**Comment by licaon-kter** [comment]
Press the RAW button.

**Comment by GitTheHellOutaHere** [comment]
I did - what am I supposed to do with the mess on that page?

Saving it as pdf is pointless.
I downladed it as a webarchive and removed the webarchive ext., but that was useless.

**Comment by licaon-kter** [comment]
What's the use case here exactly? This is not literature!

**Comment by GitTheHellOutaHere** [comment]
I want to view the ENTIRE list at once without having to scroll horizontally to read the different columns.
It takes 6 seconds to scroll the list on this site from left to right on my Mac.

**Comment by jedisct1** [comment]
https://dnscrypt.org/dnscrypt-resolvers.html

**Comment by GitTheHellOutaHere** [comment]
That’s what I wanted!

I saved that page as a pdf before, but today found that since it’s such a wide format most of it was cut off when saved. And I wasn’t sure where I’d got it from.

I’ll have to create a custom paper size to save as pdf again.

Thanks!

**Comment by licaon-kter** [comment]
Be sure to generate a new PDF each time the list updates though, sometimes daily.

**Comment by GitTheHellOutaHere** [comment]
It’s not something I read regularly - only when I’m curious about a server and I want to know where they are or if they keep logs. Only a few keep logs - mostly OpenDNS.

I don’t know if it’s any safer using non-US servers, but I haven’t noticed any difference in speed whether using ones in nearby states, across the country or around the world.
