### ISSUE TITLE
LATEST.tar.bz2 (and gz) not unpacking

### ISSUE THREAD

**Issue by dinaba** [jedisct1/dnscrypt-proxy#673]
Hi I'm using Raspbian Jessie lite (https://www.raspberrypi.org/downloads/raspbian/) and get the following error when trying to unpack https://download.dnscrypt.org/dnscrypt-proxy/LATEST.tar.bz2
>tar -xf LATEST.tar.bz2
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2.
tar: Error is not recoverable: exiting now.

I have all the latest bzip2 packages and libs.  Any suggestions on how to get it to get the file to unpack?  Thanks.

**Comment by jedisct1** [comment]
The file appears to be fine. How did you download it?

What does `file LATEST.tar.bz2` say?

**Comment by dinaba** [comment]
I don't remember the exact verbiage but it said the *.bz2 file is an HTML with ASCII characters and is very long.
Don't know what the issue was but I was able to unpack the LATEST gz file via "tar -xvzf" so I'm good to go.  Thank you.
