### ISSUE TITLE
Compile using ldns installed from source

### ISSUE THREAD

**Issue by lamixer** [jedisct1/dnscrypt-proxy#674]
Hello and thank you for your excellent software. I have been using DNSCrypt-proxy for years. I'm installing fresh on a new OS (Debian 8). I installed some dependencies using apt but I had to compile libsodium, ldns, minisign, and dnscrypt-proxy from source. 

Dnscrypt-proxy installed but did not build the plugins that require ldns. I looked back and the configure said "checking for ldns/ldns.h... no". 

I have ldns.h and a few others (from v 1.7.0) compiled and just sitting in their own folder, not 'installed' anywhere.

Could you please tell me either where I should put ldns.h for dnscrypt-proxy to find when compiling or how to specify a path to it in the configure line.

Apologies for this question, as it represents gaps in my knowledge and not any failure of your software. Thanks!

-- small update

I copied the contents of ldns-1.7.0/ldns to /usr/local/include/ldns  and then configure found ldns.h, but compiling and installing again did not generate any plugins besides example, example-cache, and example-logging.

**Comment by jedisct1** [comment]
ldns is available as a Debian package, so you don't need to compile it from source:

```sh
apt install libldns-dev
```

You can also just install the official precompiled binaries, that include the latest versions of everything: https://github.com/jedisct1/dnscrypt-proxy-installer

**Comment by jedisct1** [comment]
Glad to hear that it works! Enjoy the plugins :)

**Comment by lamixer** [comment]
I am enjoying the plugins! I no longer have to use a complex setup with dnscrypt-proxy in front of Unbound as I did before. But I'm having a little, kind of strange problem. I will open it as a new issue, because maybe it is a real issue, unlike this one!
