### ISSUE TITLE
slow response (sometimes) using Forward Domains

### ISSUE THREAD

**Issue by lamixer** [jedisct1/dnscrypt-proxy#676]
I just switched from a setup with dnscrypt-proxy in front of Unbound on a home dns server (do I mean forwarder?) to using the new version of dnscrypt-proxy 1.9.5 by itself using cache and forward domains plugins. I use forward domains so I can get local dns lookups on my lan, so:

`Forward domains:"home.lan" to:"10.0.1.1"`

If I 'dig' (or hostip -r 127.0.0.1) host.home.lan I get the correct lan IP immediately. But if I ssh host.home.lan I have to wait a little over 10 seconds for it to happen. If I do that, login, then logout and do it again right away, there is the same long long delay. If I ssh direcly to the lan IP there is no long delay in connecting.

If I change resolv.conf to 10.0.1.1 (instead of 127.0.0.1 which is through dnscrypt-proxy) the ssh is immediate.

So, it seems to me like dnscrypt-proxy is causing the delay. It is not only SSH, that's just an example. If I need to open a web interface to a headless server on my LAN it is slow too.

This phenomenon happens both on the machine running dnscrypt-proxy but also another on my LAN using it as the dns server. ( dnscrypt-proxy responding to all on lan via `LocalAddress 0.0.0.0:53` )

Thanks.

**Comment by jedisct1** [comment]
Maybe ssh sends other queries, that your server doesn't respond to.

Did you enable query logging? This may help a lot to pinpoint which exact query doesn't get a response.

**Comment by lamixer** [comment]
Hello Frank:

I just had a little further look, and it seems when I do nslookup or dig of the LAN host it searches only A record (by default) but when I do a lookup for SSH or HTTPS purposes it tries to get the record for A and AAAA. 

So, perhaps your IPv6 lookup blocking (which I am using as I have no IPv6 connectivty sadly) does not affect lookups which are matched by the 'Forward Domains' setting.

```
root@dns:/tmp# nslookup github.com  
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	github.com
Address: 192.30.253.112
Name:	github.com
Address: 192.30.253.113

root@dns:/tmp# nslookup -query=AAAA github.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
*** Can't find github.com: No answer

Authoritative answers can be found from:

```

that all happened fast.

```
root@dns:/tmp# nslookup pve2.home.lan
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	pve2.home.lan
Address: 10.0.1.3

root@dns:/tmp# nslookup -query=AAAA pve2.home.lan
;; connection timed out; no servers could be reached

```

the standard query was fast but the -query=AAAA had the 10 + second delay

```
Sun Jun  4 13:18:19 2017	127.0.0.1	pve2.home.lan	A
Sun Jun  4 13:18:27 2017	127.0.0.1	pve2.home.lan	AAAA
Sun Jun  4 13:18:32 2017	127.0.0.1	pve2.home.lan	AAAA
Sun Jun  4 13:18:37 2017	127.0.0.1	pve2.home.lan	AAAA
```

Can we have an option to make the IPv6 blocking take place before the Forward Zone? Or maybe there's another way to fix it. Thanks!

**Comment by jedisct1** [comment]
Sure. Packets traverse plugins in the order they are loaded.

Just move the `BlockIPv6 yes` line before the `Forward` line.

**Comment by lamixer** [comment]
BAM. Problem solved. Thanks! 

But I would never have guessed the order in the conf file would affect the processing order. Clearly for my case it would help to have the order reversed in the example conf file, though I'm not sure if that would cause problems for other setups.

On another topic, sorry, I also wonder, if people would like to use more RAM to keep a bigger cache, if you could implement an option to configure how much resources are used by caching. I haven't attempted to study my cache hit/miss ratio but I would prefer to use more resources to have more caching if it would improve performance for my LAN's lookups.

**Comment by jedisct1** [comment]
I moved the forwarding section last in the example config file. Not sure that this is a good idea, as being able to use IPv6 on the local network, but not having an IPv6-friendly ISP is probably a common case.

The cache is really just designed to be used locally, not to be a full featured cache like Unbound. Its size is small, but should be enough to avoid repeated queries to resolve name used in common remote API calls.

**Comment by lamixer** [comment]
Maybe you should put the order of the sections the way it makes most sense to you, or the way you think the default will be best for most people. But add a note in there to help people like me who didn't realize the plugins would be processed in the order found in the config file. 

Thanks again for your help and your software.
