### ISSUE TITLE
Exclude local addresses

### ISSUE THREAD

**Issue by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [jedisct1/dnscrypt-proxy#677]
Hello,
how can I exclude the local addresses from being served by the dnscryp-proxy. I want the local addresses served by a local DNS-Server to be able to reach local hosts like printers.
Regards
Andreas

**Comment by jedisct1** [comment]
Hi,

This is exactly what the forwarding plugin does.

See the documentation on exceptions: https://github.com/jedisct1/dnscrypt-proxy/wiki/Exceptions

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
Thank You, fits exactly my needs.
Any idea if it works in the simplednscrypt from bitbeans as well? But not important.
Regards
Andreas

**Comment by jedisct1** [comment]
I don't think the user interface supports it yet, but the plugin can be manually loaded by editing the registry.

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
Good idea, tried it, but no success. Never mind.
Andreas
