### ISSUE TITLE
Issue with latest dnscrypt-resolvers.csv

### ISSUE THREAD

**Issue by zymase** [jedisct1/dnscrypt-proxy#680]
Latest Resolvers list at https://download.dnscrypt.org/dnscrypt-proxy/ includes:

dnscrypt-resolvers.csv - 06-Jun-2017 23:30
dnscrypt-resolvers.csv.minisig - 06-Jun-2017 23:30
dnscrypt-resolvers.csv.sig - 06-Jun-2017 23:30

All 3 are a 54881bytes html file ...

**Comment by jedisct1** [comment]
Indeed, they are Github's maintenance page. Looks like the update happened while Github was down.
Fixed now, thanks!
