### ISSUE TITLE
jabber don't connect

### ISSUE THREAD

**Issue by moiseyyy** [jedisct1/dnscrypt-proxy#681]
Hi. help is needed. I installed dnscrypt on xubuntu 16.04. Everything starts fine. Everything seems to work, but the jabber is not connected. I can not understand the reason. Nor what additional settings dnscrypt did. What could be the reason?

**Comment by licaon-kter** [comment]
What client exactly? Any log files with it failing to connect? What server?

**Comment by moiseyyy** [comment]
client pidgin 2.10.12. server xmpp.jp

**Comment by jedisct1** [comment]
dnscrypt-proxy itself doesn't know anything about Jabber, it just forwards DNS packets.

What resolver are you using?

**Comment by moiseyyy** [comment]
resolvconf
default in /etc/resolv.conf 127.0.0.1   
after start dnscrypt-proxy - 127.0.2.1

**Comment by jedisct1** [comment]
Not your network configuration, but the resolver used by dnscrypt-proxy.

What does your `dnscrypt-proxy.conf` file look like?

What does the `hostip -r 127.0.0.1 resolver.dnscrypt.org` command return?

**Comment by jedisct1** [comment]
Maybe you're using Cisco:

```bash
$ drill xmpp.jp @208.67.222.222
Error: error sending query: Could not send or receive, because of network error

$ hostip -r 208.67.222.222 xmpp.jp
[request timed out]
```

Their resolvers are unable to resolve `xmpp.jp`, with or without dnscrypt.

So, using a different resolver will solve it.

**Comment by moiseyyy** [comment]
yes. i am use Cisco.
# What local IP the daemon will listen to, with an optional port.
# The default port is 53. If using systemd, this is not used and must be
# specified in dnscrypt-proxy.socket.
DNSCRYPT_PROXY_LOCAL_ADDRESS=127.0.2.1:53

# Remote DNS(Crypt) resolver.
# You can find a list of resolvers at
# /usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv.
DNSCRYPT_PROXY_RESOLVER_NAME=cisco

# Extra flags to pass to dnscrypt-proxy
DNSCRYPT_PROXY_OPTIONS=""

what a resolver i can use for xmpp.jp?

**Comment by jedisct1** [comment]
Use anything else. It's the only one that cannot properly resolve that domain.

A list of public resolvers is visible here: https://dnscrypt.org/dnscrypt-resolvers.html

Replace `DNSCRYPT_PROXY_RESOLVER_NAME` with anything from the first column (`Name`), such as `dnscrypt.org-fr`.

**Comment by moiseyyy** [comment]
Thank you. Replaced. Everything is working

**Comment by jedisct1** [comment]
Great!
