### ISSUE TITLE
Public key for client identification

### ISSUE THREAD

**Issue by bialy39** [jedisct1/dnscrypt-proxy#683]
How I can generate public key and use it for '--client-key' option?
I always get an error message:
The client key file doesn't seem to contain a supported key format
Client key file [...] could not be used
Do somebody knows how I can solve this problem?

Regards.

**Comment by jedisct1** [comment]
Hi Bialy,

The client key starts with two bytes describing the key format and the key exchange function.

Currently, these two bytes must be `0x01 0x01`, for X25519.

Then comes the 32 bytes X25519 public key.

Given a random secret key generated for a customer, the public key can be obtained using libsodium's `crypto_scalamult()` function.
