### ISSUE TITLE
Run before stop not respected by HA-Proxy

### ISSUE THREAD

**Issue by Robbie1977** [jedisct1/dnscrypt-proxy#684]
If a single container service is upgraded with run before stop ticked I would expect the proxy to keep routing services to the existing running container until stopped but instead a 503 is returned the second the upgrade starts.

I shouldn't be forced to have multiple containers to ensure continuous service is delivered, I could live with a few seconds but to drop all services immediately on upgrade seems to defeat the purpose of having the start before stop tick-box!?

**Comment by jedisct1** [comment]
haproxy?

**Comment by Robbie1977** [comment]
sorry was searching for existing issue in rancher/rancher and must have stumbled onto your repo before raising issue and noticed the sec I pressed add.
