### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#684]
Hi,

I use w10prox64 uptodate, openvpn last version and dnscrypt proxy2 v2.0.1.9 as well.

i use Lb strategy random. cache max 14400 (4hours)

But sometime, about one time a week, the app crashes during the vpn is connected.

I use it only for outside vpn Dns requests. When the app crashes, i think there is absolutly nothing to resolve.

It disconnect the vpn and the windows Ethernet notification says it's not good, Boy!

The app is running with computer about 15 hours a day.

The app crashes after some hours computer running and after maybe 1hour vpn connected. no auth-nocache (...)

Dnscrypt proxy service is well setted on automatic.

I only have to relaunch all for the issue is fixed.

I haven't this issue without dnscrypt proxy2.

Maybe a fix for this?

*** i actually try without cache

Thanks

**Comment by jedisct1** [comment]
Do you have a stack dump of the proxy when the crash occurs?

**Comment by absynteZero** [comment]
i will look after this next time.

after this, hello jedisct1 !

i created an European dns crypt v2 index.
I dont speak well English, i need really to practice.

I like all communications system from 1996.

I like your app and i think it could be a must have on windows but it need a simple graphic interface and an msi installer for the best.

All need to use this. it's not about money but about all user confidentiality and privacy about their data.

What about this?

Thanks

**Comment by jedisct1** [comment]
There is already a fantastic UI for Windows: https://simplednscrypt.org/
