### ISSUE TITLE
[ERROR] Unable to retrieve server certificates

### ISSUE THREAD

**Issue by zaplo00** [jedisct1/dnscrypt-proxy#686]
This error pops up sometimes (once a week or so) and DNS fails for all requests until socket and service is restarted. It happens with newest resolver list and 'random' server in config. It doesn't happen with single server but only with 'random'.

**Comment by jedisct1** [comment]
Means that the server was temporarily unreachable, or more generally that standard DNS queries didn't get response.

**Comment by jedisct1** [comment]
Try picking a fixed server that works well for you.
