### ISSUE TITLE
Need info about dnscrypt

### ISSUE THREAD

**Issue by parag82** [jedisct1/dnscrypt-proxy#687]
Is dnscrypt supports below rfcs on DNSSEC?
RFC 4033 "DNS Security Introduction and Requirements"
RFC 4034 "Resource Records for the DNS Security Extensions"
RFC 4035 "Protocol Modifications for the DNS Security Extensions"

**Comment by jedisct1** [comment]
dnscrypt wraps DNS packets. So, if your client and your resolver support DNSSEC, or any RFC, past or future, dnscrypt supports it.
