### ISSUE TITLE
dnscrypt-resolvers.csv (mac os)

### ISSUE THREAD

**Issue by idanka** [jedisct1/dnscrypt-proxy#688]
Hi! 
How can I update the file?
I can not find a Mac OS system.

**Comment by jedisct1** [comment]
How did you install dnscrypt-proxy?

The `contrib/dnscrypt-update-resolvers.sh` scripts in the source distribution can be used for that purpose.

If you installed it using Homebrew, it also installs a `dnscrypt-update-resolvers` script.

**Comment by idanka** [comment]
Download dnscrypt-osxclient.dmg
https://github.com/alterstep/dnscrypt-osxclient

**Comment by jedisct1** [comment]
This is a different project, then: https://github.com/alterstep/dnscrypt-osxclient

I don't remember where it stores the CSV file but it's periodically and automatically updated it.

**Comment by idanka** [comment]
I understand, thank you!
