### ISSUE TITLE
Dnscrypt for android readme question

### ISSUE THREAD

**Issue by itspull** [jedisct1/dnscrypt-proxy#689]
Hi @jedisct1

This isnt an "issue" per se, its more a question as to which root dns changer app is recommended to install for switching dns to localhost in the readme, as there is no direct link posted.

the play store has several 'dns changer' apps, so, the question is: do you remember which was the one used for testing as mentioned in the android instructions?

**Comment by alive4ever** [comment]
You don't need any dns changer app. The built-in iptables will do the task well.

You can force all dns traffic to pass via local dns proxy using iptables. Add these lines to [AfWall custom script](https://github.com/ukanth/afwall) or type the commands directly on the terminal emulator / adb shell with root privilege. Assuming that the dns proxy is listening on 127.0.0.1 port 53.
```
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1
iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
```
To remove the dns proxying..
```
iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1
iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
```

**Comment by itspull** [comment]
Okay, thanks for the instructions @alive4ever. But is this not a double rule? it's already inside the init script  provided by dnscrypt. I'm using this on a device with afwall, yes.

So, to be clear that I understand all of this, you're saying that to use a dns changer app within this process is now depreciated?

I'm curious now why the switch in instructions, and, why this isn't documented?

Maybe the readme for android needs an update to include this?

I'd still like to know the app that is mentioned there, if anyone knows and it's not a problem to share a link.

**Comment by itspull** [comment]
I wonder now, since we're on the subject, if I've changed the dns port to something, say 5353, that should reflect in the iptables rule set placed in system/xbin as well as in the init script? So, iptables -t nat blah blah dport 5353 --to-destination 127.0.0.1 in all three? Or leave them alone in system files and use the afwall script for redirection?

This is the line of understanding I'm following: the init script allows dnscrypt on startup, next, the afwall script allows dnscrypt to establish a connection from behind the firewall.

And lastly, the system/xbin file stops/starts the service, example dnscrypt disable, dnscrypt enable.

so again, if I've changed the listen-address port to example 5353, I'll need to change also the port in the system/xbin file, otherwise, if I run into problems with connection maybe caused by dnscrypt, that script won't reflect the change I've made to listen-address, it will still assume dnscrypt is listening on dns 53 and cannot disable/enable it correctly, possibly starting multiple dnscrypt processess.

Do I understand this correctly or is this a display of my ignorance?

**Comment by alive4ever** [comment]
If `dnscrypt-proxy` is listening on another port such as 5353, you just need to pass the port number after ip address in the `--to-destination` parameter.
```
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5353
iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5353
```
With this rule, all dns request are passed to `dnscrypt-proxy` and never go directly to the internet.

Regarding Android way to change dns, there is [ndc resolver](https://github.com/ukanth/afwall/wiki/DNS) command with no clear documentation except from reading the source code.

It's up to you to use any dns-changer app from the store if you prefer easy-to-use rather than using the built-in tool.

**Comment by itspull** [comment]
Okay good, so I was going about the redirection correctly after all, iptables blah blah -dport 53 --to:destination 127.0.0.1:$port, got it.
