### ISSUE TITLE
option doesn't work

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#691]
Hello,

I use dnscrypt proxy as well.

I was using only dnscrypt v2 protocol
i just try too, Doh.

I inform that when i enable or disable dnscryptv2 servers or Doh servers, it doesn't change anything.
All servers are used.

*** i start to use Doh and see there is only two resolvers with chachapoly ec.

**Comment by jedisct1** [comment]
Check that you are editing the correct configuration file. Put random garbage in it. If the server still runs, you didn't edit the right file.

**Comment by absynteZero** [comment]
hi and thanks so much to answer.

yes i maybe done a error...i will verify.

i use a toml file i have edited myself, with your example.

i will try again.

**Comment by jedisct1** [comment]
The `[static]` section should only be used if you are running your own private servers.

Filters such as `require_dnssec` or `doh_servers` don't apply to this.

**Comment by absynteZero** [comment]
Thanks... 

but i dont really understand...

must i delect [static]

where do the filters apply?

**Comment by jedisct1** [comment]
Yes, remove all the `[static]` section.

You can read the documentation here: https://github.com/jedisct1/dnscrypt-proxy/wiki/Configuration
