### ISSUE TITLE
Usage behind proxy

### ISSUE THREAD

**Issue by 4pao** [jedisct1/dnscrypt-proxy#692]
Is there any way to use dnscrypt-proxy behind a proxy???

**Comment by jedisct1** [comment]
Depends on the type of proxy.

A HTTP proxy will perform DNS resolution itself, not giving any chance for the client to do it.

A SOCKS client can be configured to either let the proxy perform DNS resolution, or to keep doing it locally.

**Comment by 4pao** [comment]
Thank you.
