### ISSUE TITLE
Some servers are down?

### ISSUE THREAD

**Issue by licaon-kter** [jedisct1/dnscrypt-proxy#694]
These don't seem to answer to queries (at least via `hostip`):
dnscrypt.eu-dk
dnscrypt.eu-nl
dnscrypt.nl-ns0
dnscrypt.org-fr

**Comment by jedisct1** [comment]
They all seem to be working just fine from here :/

**Comment by jedisct1** [comment]
Had a look at dnscrypt.org-fr and everything looks fine, with DNS traffic flowing in and out.

**Comment by licaon-kter** [comment]
```
> hostip -r 77.66.84.233 dnscrypt.org
[request timed out]
> hostip -r 176.56.237.171 dnscrypt.org  
[refused]
> hostip -r 45.76.35.212 dnscrypt.org
[request timed out]
> hostip -r 212.47.228.136 dnscrypt.org   
[request timed out]
```

Am I doing this wrong?

But
```
> hostip -r 23.226.227.93 dnscrypt.org
37.59.238.213
```

**Comment by jedisct1** [comment]
`hostip` is a regular DNS client; it doesn't use the DNSCrypt protocol.

Some servers may support regular, unauthenticated DNS on port 53 in addition to DNSCrypt on port 443.
But the servers you mentioned only support DNSCrypt.

**Comment by licaon-kter** [comment]
But the question remains, how does one check a DNSCrypt server?

**Comment by jedisct1** [comment]
```sh
dnscrypt-proxy --test 0 --resolver-name=dnscrypt.org-fr
```
