### ISSUE TITLE
dnscrypt v2 VS doh ? and dnscurve?

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#694]
Hi,

i like so much this app and github !! it's a big game! i really need to learn well how to code....

But..

i was trying to find some explanations for difference between dnscrypt v2 and dns-over-https.
There is nothing interesting on the wild.

I understand dnscrypt v2 is the better encryption/latency

but..for privacy to be the best and strong,

Do you think doh is better? with https port and cypher suite?

Second question, sorry if it's stupid but what about dnscurve? it seems very interessting?

**Comment by Mikh-3** [comment]
DNSCurve is old and shouldn't be used.

DNSCrypt is comparable to DoT (DNS-over-TLS) / DoT is standard.

DOH isn't that good

**Comment by jedisct1** [comment]
There is nothing wrong with DNSCurve, except that it doesn't address the same thing as the other protocols. DNSCurve encrypts communications between authoritative servers and recursive servers. Other protocols encrypt communications between recursive servers and clients.

DNSCurve is more of an alternative to DNSSEC. Unfortunately, it isn't deployed anywhere.

DoT was completely flawed from day one. It's a terrible choice for DNS transport, that was only proposed as a standard for political reasons. Band-aids proposed later to address its flaws still doesn't make it compelling. Especially now that DoH is around.

Modern internet is pretty much completely based on HTTP, and this is not going to change.

It's become the universal way to transport anything: small data, huge files, streams, anything. It's by far the only protocol that constantly gets improve and has the best infrastructure and tools. 

Authentication, encryption, reliability, prioritization, caching, roaming, it already includes everything. So using it for DNS to leverage what already exists totally makes sense. It can benefit from all this.

From a security perspective, DoH is good if implemented and deployed correctly. It's easy to write a HTTP client that "works", but is not as secure as a web browser. Most implementations are not as secure as they should.

DNSCrypt was specifically designed for DNS. As a result, it would be a terrible fit for anything else. But it's lightweight, has no insecure options, and gives you the advantages of the future DNS-over-HTTP/3 today with even better privacy.
