### ISSUE TITLE
DNScrypt with iOS without jailbreak

### ISSUE THREAD

**Issue by wangkesen** [jedisct1/dnscrypt-proxy#695]
Hey there I just have a quick question. I was wondering if it’s possible to now use DNScrypt if installed on a VPS, and then using[https://www.dnsoverride.com/](DNSOveride) which basically allows you to select the DNS Provider for both Wifi and cellular traffic. So could we then install DNScrypt on a VPS or server and then select that DNS in the iOS app?

Sorry if it’s an annoying question I’m not super knowledgeable about how the program works I just wanted to give it a shot and ask. Thank you for your time!

**Comment by jedisct1** [comment]
In this scenario, you can install the DNSCrypt *client* on a VPS, and configure that VPS address on your phone. DNS Override is not even required, as you can just create an APN profile to do it.

This won't protect the path between your device and your VPS, though. Having a DNSCrypt client on your phone, and the *server* on your VPS is way more effective.

It currently requires a jailbroken device, but Apple introduced a new API in iOS 11 to make this possible without a jailbreak. Unfortunately nobody has written an app to use this API yet, but I hope this can be the case soon :)

**Comment by primalmotion** [comment]
Would you mind pointing me to this API? Thanks!

**Comment by jedisct1** [comment]
See https://forums.developer.apple.com/thread/83731
