### ISSUE TITLE
better toml editing

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#695]
Hi,

I've got a special question... if possible...

For decrease the time for the app read the toml, must i let blank lines or edit the lines too with # ?

It a technical question. what is the quicker for app reading?
example,

is it better to edit:

1111111111

2222222222

3333333333

or
111111111
"#"
222222222
"#"
333333333

i add "" because if not diese doesn't appear....
???????
Thanks

**Comment by jedisct1** [comment]
The best way is to use a text editor that supports TOML :)

Visual Studio code and many others do.

`#` is for comments. If you need to separate paragraphs, blank lines can be better.

But do whatever you prefer :)

**Comment by absynteZero** [comment]
Thanks :-)
