### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by QRWN1** [jedisct1/dnscrypt-proxy#696]
I have a DNS server (nsd4) already setup currently in use. If I install the dnscrypt server does it affect my current DNS setup or overwrite it in anyway?

What authoritative DNS server does dnscrypt install?
How does it work exactly? Is it an authoritative DNS itself or..?

**Comment by jedisct1** [comment]
It's a proxy for recursive servers and stub resolvers. Not authoritative servers.

See https://dnscrypt.info/faq

**Comment by QRWN1** [comment]
Just to clarify, the dnscrypt server should be fine to run on my VPS with my current setup NGINX/NSD4 and all?
