### ISSUE TITLE
[Android] Dnscrypt stops after start with plugin

### ISSUE THREAD

**Issue by avently** [jedisct1/dnscrypt-proxy#696]
I just compiled Dnscrypt for Android armv8-a with plugins support. I changed nothing in builds's configuration (except plugins support).

I'm starting dnscrypt like this:
 
dnscrypt-proxy --plugin=libdcplugin_example_logging.la,/sdcard/dnslog.txt --daemonize --loglevel=7 --ephemeral-keys --resolver-name="dnscrypt.org-fr" --resolvers-list=/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv --logfile=/sdcard/dns.log

And see this:

Mon Jul 10 12:29:47 2017 [INFO] + DNS Security Extensions are supported
Mon Jul 10 12:29:47 2017 [INFO] + Provider supposedly doesn't keep logs

Here is /sdcard/dns.log:

Mon Jul 10 12:29:47 2017 [NOTICE] Starting dnscrypt-proxy 1.9.5

Then I do this:

su
ps | grep dns

Nothing found. 

If I drop "--plugin..." line everything is working fine. How to enable plugins? I tried full path to plugin. Same result. 

If you can't test on Android device just tell me what to do and I will send logs.

**Comment by jedisct1** [comment]
That's why the build script (and so, the official precompiled binaries) is not compiled with plugin supports.

It doesn't work on Android.

**Comment by avently** [comment]
@jedisct1 so sad. Can I somehow log DNS queries? Maybe with you know another way to do it.

**Comment by licaon-kter** [comment]
What's the use case for logging?

**Comment by avently** [comment]
@licaon-kter I want to check how chromium-based browser is using network. What URLs it's using and then replace those URLs in source code.

**Comment by jedisct1** [comment]
Being able to use the plugins would be definitely useful. Not only for logging, but also for filtering and caching. Open DNS users could also use the accounts they paid for.

Fixing the code is probably trivial, but Android is not really something I know well.

**Comment by licaon-kter** [comment]
The easiest way I got it is by using [NetGuard](https://github.com/M66B/NetGuard) with this (no-root) combo: https://github.com/smarek/android-unbound-dns/issues/18 (ARMv7 apps run seamlessly on your device, right?)

**Comment by avently** [comment]
@licaon-kter I'm fighting with your for about an hour. It keeps stopping after ~2 minutes. I see this:
[1499710224] libunbound[11201:0] error: trust anchor presented twice
[1499710224] libunbound[11201:0] error: could not parse auto-trust-anchor-file root.key line 2
[1499710224] libunbound[11201:0] error: error reading auto-trust-anchor-file: root.key
[1499710224] libunbound[11201:0] error: validator: error in trustanchors config
[1499710224] libunbound[11201:0] error: validator: could not apply configuration settings.
[1499710224] libunbound[11201:0] error: module init for module validator failed
root.key has content
resolve DNSKEY: initialization failure
[1499710224] unbound-control[11206:0] error: connect: Connection refused for 127.0.0.1
[1499710224] unbound[11210:0] notice: init module 0: validator
[1499710224] unbound[11210:0] notice: init module 1: iterator
[1499710224] unbound[11210:0] info: start of service (unbound 1.6.3).


But most of the time I see blank white screen...

**Comment by avently** [comment]
@licaon-kter but thanks, NetGuard do what I need without unbound!

**Comment by licaon-kter** [comment]
Yeah, it takes some force closes and clean data cycles but then it's ok, ignoring the errors it spits. :)

**Comment by avently** [comment]
@jedisct1 so you don't plan to make plugins compatible with Android?

**Comment by jedisct1** [comment]
I don't use Android, I don't know anything about Android. Without any help, it's unlikely to happen.
