### ISSUE TITLE
Tutorial translation

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#698]
Hi,

I'm 38 years old and i'm French.
I'm simple man and i like to do the best for help user.
Im' not engineer but i'm very about communications, technologies and sciences since..more than 20 years.

Ive created a simple tutorial with two configured .TOML files.
https://github.com/jedisct1/dnscrypt-proxy/wiki/%5BSTART%5D-Simple-windows-use-without-powershell

But i need someone to verify what i've done and verify my English Language.

You're welcome to edit the post if needed.

@jedisct1 it will be very nice if you can approved my tuto...? for me it is all i can. I will just update each month the files if too much servers are down and if needed.

Thanks

Regards

**Comment by jedisct1** [comment]
The distribution already includes example files, that should work out of the box for most people, so suggesting people to use completely different example files, especially when they are new to the software, can be quite confusing.

If things need to be changed in the example files, I'd rather see these being updated instead.
