### ISSUE TITLE
SHA or MD5

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#700]
Hi jedisct1

You app is all about security.

Some users will want to verify the download integrity.

Because they have bad connection or because they only want security and it's the way to.

I purpose to add SHA or MD5 of the original file with release download.

Thanks

**Comment by jedisct1** [comment]
Every single file has a digital signature (the `.minisig` file).

https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation#verification-of-downloaded-files

**Comment by absynteZero** [comment]
Ok sorry. Thanks
