### ISSUE TITLE
--resolver-name=random Failure should retry not fail

### ISSUE THREAD

**Issue by GinoM** [jedisct1/dnscrypt-proxy#700]
If I choose resolver name random, and the selected resolver fails, instead of stalling dnscrypt-proxy should try a different random resolver. (after some reasonable timeout)

In order to circumvent this issue I create a systemd init script that attempts a lookup against the dnscrypt-proxy server and if it fails it restarts the service... But this is more of a hack..
I'll attach it below.

This hack is also useful for post sleep issues where the network isn't up yet but the server is attempting to reconnect.

```
[Unit]
Description=A tool for securing communications between a client and a DNS resolver

[Service]
Type=simple
PIDFile=/var/run/dnscrypt-proxy.pid
EnvironmentFile=/etc/conf.d/dnscrypt-proxy
ExecStartPre=/bin/rm -f /var/run/dnscrypt-proxy.pid
ExecStart=/usr/sbin/dnscrypt-proxy \
	--pidfile=/var/run/dnscrypt-proxy.pid \
	--syslog \
	--local-address=${DNSCRYPT_LOCALIP}:${DNSCRYPT_LOCALPORT} \
	--resolver-name=${DNSCRYPT_RESOLVER_NAME} \
	--user=${DNSCRYPT_USER}
ExecStartPost=/usr/bin/host google.com ${DNSCRYPT_LOCALIP} &> /dev/null
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by jedisct1** [comment]
So an active attacker could force you to use a specific resolver.

I'm not fond of the idea.

`random` is  just available so that we can package a sample configuration file that works out of the box. But really no one should use `random` ever after the initial testing is done.

**Comment by GinoM** [comment]
hmm, fair enough. I like random because I have had allot of trouble lately with selecting a single reliable resolver. They seem to go up/ down etc. so I have a modified resolver list .csv that I use.
