### ISSUE TITLE
Problemes disabling DNSCrypt

### ISSUE THREAD

**Issue by warmup72** [jedisct1/dnscrypt-proxy#701]
Hi,
I´m running dnscrypt 1.0.14 on my Mac 10.12.5.
After logging in with a User disabling dnscrypt works fine over the checkbox. 
(The File  /Library/Application Support/DNSCrypt/control/dnscrypt will be removed and dnscrypt turns off.)

If I log in another user and tries disabling another time it works anymore.

Problem seems:
After the first login the the file rights of "dnscrypt" is on the user an the file could be removed. After the secound user is logged in the file rights change to root an the front-end doesn´t work anymore.

**Comment by jedisct1** [comment]
Wrong project.
