### ISSUE TITLE
Dnscrypt doesn't prefer ipv6 on vpn if available.

### ISSUE THREAD

**Issue by MrSorcus** [jedisct1/dnscrypt-proxy#704]
I'm using WireGuard VPN and DNSCrypt, but resources with both addresses (v6 + v4) open only with v4.
Without VPN ipv6 used if available.
Here tcpdump - https://gist.github.com/MrSorcus/e2826ae9b472fe67790864f102cae0fa
I think that something with mtu... But i'm not sure.

**Comment by jedisct1** [comment]
Maybe your VPN provider doesn't support IPv6?

**Comment by MrSorcus** [comment]
Nope. IPv6 working.

**Comment by jedisct1** [comment]
To recap, without the VPN, https://ipv6.google.com loads.
With the VPN turned on, https://ipv6.google.com does... something else (error message? unreachable?)

Looks like a VPN issue, unrelated to DNS.

Also, if you're using a VPN, DNSCrypt is useless.

**Comment by MrSorcus** [comment]
> With the VPN turned on, https://ipv6.google.com does... something else (error message? unreachable?)
Working. Doesn't work only with site that has IPv6 and IPv4...

**Comment by jedisct1** [comment]
Did you try different resolvers? Maybe the one you chose is down?

**Comment by MrSorcus** [comment]
Nothing changed...

**Comment by jedisct1** [comment]
Did you try other resolvers?

**Comment by MrSorcus** [comment]
Yes.

**Comment by MrSorcus** [comment]
@zx2c4 what do you think?

**Comment by zx2c4** [comment]
I think this probably has nothing to do with Frank's code, and probably something to do with the way you've configured your VPN. How about you find me on IRC -- I'm zx2c4 on Freenode -- and I'll try to help you there.

**Comment by jedisct1** [comment]
Oh, wow. Thanks for jumping in, @zx2c4 !

**Comment by zx2c4** [comment]
This had nothing to do with either WireGuard nor Dnscrypt. Totally 100% unrelated.

The reporter was using fc00::/7 IP addresses, which although have a global scope, have a different label, per [rfc6724](https://tools.ietf.org/html/rfc6724):

```
      Prefix        Precedence Label
      ::1/128               50     0
      ::/0                  40     1
      ::ffff:0:0/96         35     4
      2002::/16             30     2
      2001::/32              5     5
      fc00::/7               3    13
      ::/96                  1     3
      fec0::/10              1    11
      3ffe::/16              1    12
```

And in glibc's `/etc/gai.conf` this is actually:

```
#label ::1/128       0
#label ::/0          1
#label 2002::/16     2
#label ::/96         3
#label ::ffff:0:0/96 4
#label fec0::/10     5
#label fc00::/7      6
#label 2001:0::/32   7
```

Adding `label fc00::/7      1` to `/etc/gai.conf` is a work around, if you want for v6 addresses to be preferred over v4 in `getaddrinfo` lookups, even if the source address is in fc00::/7.

Alternatively, just switch to using real internet IP addresses, since you can do that with v6.

**Comment by jedisct1** [comment]
Wow, thanks a lot for having spent time to investigate this!
