### ISSUE TITLE
dnscrypt-proxy keeps trying to load a nonexistent plugin

### ISSUE THREAD

**Issue by CuriousDave** [jedisct1/dnscrypt-proxy#707]
I'm not sure why it won't work but I keep getting this error

sudo dnscrypt-proxy /etc/dnscrypt-proxy/dnscrypt-proxy.conf
Mon Jul 24 21:36:03 2017 [INFO] + DNS Security Extensions are supported
Mon Jul 24 21:36:03 2017 [INFO] + Provider supposedly doesn't keep logs
Mon Jul 24 21:36:03 2017 [INFO] Loading plugin [/usr/lib/i386-linux-gnu/dnscrypt-proxy/libdcplugin_example_ldns_aaaa_blocking.so]
Mon Jul 24 21:36:03 2017 [ERROR] Plugin [/usr/lib/i386-linux-gnu/dnscrypt-proxy/libdcplugin_example_ldns_aaaa_blocking.so] can't be loaded: [No such file or directory]
Mon Jul 24 21:36:03 2017 [ERROR] Unable to load plugins

I checked the folder path and there is no dnscrypt-proxy folder let alone the rest of the directory path. I searched my computer for the example ldns .so file with no luck. It seemed to install correctly and I found the config file. but after searching the internet for a while now I can't find an answer on how to fix this :/

**Comment by jedisct1** [comment]
How did you install dnscrypt-proxy?

It looks like plugins are missing, but you tried to use them in the configuration file.

**Comment by CuriousDave** [comment]
Installed via
sudo apt-get install dnscrypt-proxy

ahh that makes sense looking back at the config file I see they are required for block Ivp6. should I just install through source code? I'm not sure how to verify that I have the right plugins, installing from repository (thru bash anyhow)

**Comment by jedisct1** [comment]
What Linux distribution is that?

Since they should broken/incomplete packages, you can remove them and maybe install this instead: https://github.com/jedisct1/dnscrypt-proxy-installer

**Comment by sparkchaser** [comment]
See if your distribution has a separate "dnscrypt-proxy-plugins" package (I know Ubuntu does).

This probably needs to be added to the "setup" section of the wiki.

**Comment by CuriousDave** [comment]
Sorry for getting back so late, Distro is Parrot OS
@sparkchaser was correct, I hadn't looked thoroughly (because I didn't know there was a plugins package :/) Thank you for your help it works fine now :)
