### ISSUE TITLE
Installation Issue Fedora 26: libsodium >= 0.7.0 not found

### ISSUE THREAD

**Issue by jotyGill** [jedisct1/dnscrypt-proxy#708]
The installation fails.

"configure: error: libsodium >= 0.7.0 not found"

 joty@localhost ~/Downloads/dnscrypt-proxy-1.9.5  sudo dnf install libsodium         
Package libsodium-1.0.12-1.fc26.x86_64 is already installed, skipping.

**Comment by jedisct1** [comment]
Maybe you need a `libsodium-dev` package or something like that?

**Comment by jedisct1** [comment]
Apparently, there's a `libsodium-devel` package for Fedora.

**Comment by jedisct1** [comment]
Alternatively, use https://github.com/jedisct1/dnscrypt-proxy-installer

**Comment by jotyGill** [comment]
Thank You! libsodium-devel was needed.
 I tried dnscrypt-proxy-installer briefly It didn't install it properly (maybe it needed devel as well?).
Thanks for the awesome tool.

**Comment by jedisct1** [comment]
Would you mind reporting what happened with dnscrypt-proxy-installer?

It doesn't require any dependencies.
