### ISSUE TITLE
@jedisct1

### ISSUE THREAD

**Issue by absynteZero** [jedisct1/dnscrypt-proxy#709]
Hi,

First, i'm sorry, my life is very hard but i don't have to disturb with it.
I'm sick and handicaped worker..just i look fine... very hard..
My spirit always and try t understand thing..

so

I like tech and science and will always participate and learn, for life.

I like your app and thank you for help world user to switch off censure.

I use the app from month, alone and with openvpn and vpn servicies on windows.

I like windows interface and the security is at a good level now.

You app (2.0.1.9) is very stable and lightweight.

I just dont understand the "interface".

You give 5 config files.

toml, blacklist, forwarding, cloacking, withlist.

I think it's too much for user and simple use.

What about to add all in the toml file and keep out only the servers list?

The user will have the all servers list and the all option config file. He can share it easily.

It will be very nice for the use.

For my use, the only queries i need to filter is the windows ones the user doesn't need.

I think about a dnscrypt v1/v2 selection option.

Yes the users will use v2 but it's the way no?

Using it, the push the servers admin to use the last security, and create new servers all around the world because of the need.

...The more we use, the more they have to create...

more verbosity level, because user needs to see if options and cipher are applied.

slow down battery and power consumption. 

limit cpu usage for some needs (option).

An other thing for ..some users, they want to connect to dns server the far they can for censure or i don't know, but it's possible.

I purpose to create a new lb strategy for select only the biggest ping^^

an other thing.. for doh, i know google chrome, firefox and other internet explorer can use it.

I think it will be very usefull to hide the user dns queries.

I think about a user with windows, edge or microsoft use.
With dnscrypt proxy, the user hide all his dns queries as a firefox ones, and with linux?

For blacklist and with list i don't understand the need.

The user can select a filtered dns, with familly security.

In case of lan admnistration, the user doesn't need to this files, they will be on the server.
I think it's no interesting to give the files with the download folder.

...thinking i'm a good father. my son or daugther can use the computer , yes! but i don't want they see any violence, religions or sex. can i blacklist "ALL", and set only some ip in withlist?

For v3, it will be very nice to be able to set multi user settings.
One user/one toml file.

I have a last personnal query. Can you delete all my issues post.

I was confused because i loose too many things (...).

Thanks if you can.

At end, it will be very nice to have a part of you app include in openvpn for vpn connection dns queries.

Peace and liberty.

absyntezero simple user.

I ve time, if i can help......

i will not post in this app topic again.

Just i maybe update files in the tuto.

bye guys.

**Comment by Yinchie** [comment]
Separate config files actually make it easier for a normal user than getting through one big file, hard to find a certain section.
Most users don't need to edit more than just the toml file.
