### ISSUE TITLE
What mean is undefined symbol: crypto_box_curve25519xchacha20poly1305_open_easy ?

### ISSUE THREAD

**Issue by joehk2017** [jedisct1/dnscrypt-proxy#710]
Hello , 

I tried to running **dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf** but  the  command linux i saw is 

dnscrypt-proxy: symbol lookup error: dnscrypt-proxy: undefined symbol: crypto_box_curve25519xchacha20poly1305_open_easy

What happened?
Thank

**Comment by licaon-kter** [comment]
How did you install?

**Comment by jedisct1** [comment]
Not sure about how you installed it, but it means that it was compiled using a recent libsodium version, but then you tried to run it on a system with an obsolete libsodium version.

On Linux, I'd recommend using the precompiled binaries: https://github.com/jedisct1/dnscrypt-proxy-installer or the packages provided by your distribution if they are not out of date.

**Comment by joehk2017** [comment]
By now i worked , but have this problem

# dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf

https://ibb.co/nAOrC5

root@debian:~# dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
Tue Aug 1 09:39:55 2017 [INFO] Randomly chosen resolver: [d0wn-it-ns1]
Tue Aug 1 09:39:55 2017 [INFO] + DNS Security Extensions are supported
Tue Aug 1 09:39:55 2017 [INFO] + Provider supposedly doesn't keep logs
Tue Aug 1 09:39:55 2017 [NOTICE] Starting dnscrypt-proxy 1.9.5
Tue Aug 1 09:39:55 2017 [INFO] Loading plugin [/usr/local/lib/dnscrypt-proxy/libdcplugin_example_cache.so]
Tue Aug 1 09:39:55 2017 [INFO] Loaded plugin: [A basic DNS cache]
Tue Aug 1 09:39:55 2017 [INFO] Generating a new session key pair
Tue Aug 1 09:39:55 2017 [INFO] Done
Tue Aug 1 09:39:55 2017 [INFO] Server certificate with serial #1501571761 received
Tue Aug 1 09:39:55 2017 [INFO] This certificate is valid
Tue Aug 1 09:39:55 2017 [INFO] Chosen certificate #1501571761 is valid from [2017-08-01] to [2017-08-02]
Tue Aug 1 09:39:55 2017 [INFO] Server key fingerprint is 2D4A:3CEB:1399:A2BB:AF8D:7AD8:07AE:7F31:7280:ED1E:9E21:1DAB:423D:AA16:0E00:A05A
Tue Aug 1 09:39:55 2017 [NOTICE] Proxying from 127.0.0.1:53 to 31.14.133.188:443

**Comment by licaon-kter** [comment]
apparently, try `dig @127.0.0.1 -p 53 pir.org`

**Comment by jedisct1** [comment]
`dig txt resolver.dnscrypt.org` to check what resolver you are using.

**Comment by joehk2017** [comment]
Sorry guy what is dig ?  
the bash haven't .....................

https://ibb.co/iph9X5

**Comment by joehk2017** [comment]
I know now , i haven't  install dnsutils  now worked 
https://ibb.co/dF5ckQ
 Thank

**Comment by joehk2017** [comment]
But my DNSCrypt Loader can't work !

https://github.com/GortCodex/DNSCrypt-Loader/issues/15

**Comment by joehk2017** [comment]
My all installed file is  default not do anything

**Comment by joehk2017** [comment]
Hello , 

Beacuse can't used DNSCrypt-Loader and can't enable dnscrypt-proxy.service for me i just only manual to set up dnscrypt-proxy server and running ,  not use DNSCrypt-Loader (GUIs) to find public dns server . 

Use online csv to find it https://dnscrypt.org/dnscrypt-resolvers.html / https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

Here is my setting dns 

**Wicd Network Manager setting **
https://ibb.co/cMya5Q

dnscrypt-proxy  configuration file setting i set 
https://ibb.co/fJeRC5

dnscrypt-proxy  server 
https://ibb.co/iX66C5

**Comment by jedisct1** [comment]
DNS leak test displays the IP address of the server you configured. So this looks pretty fine!

**Comment by joehk2017** [comment]
How can i set Preferred DNS Server and Alternate DNS Server?

**Comment by licaon-kter** [comment]
This project does not handle that.
If you are talking about other projects ( DNSLoader or whatever ), please go and ask there.

The simple solution: setup Unbound with [2 forwarders](https://wiki.archlinux.org/index.php/DNSCrypt#Unbound) (2 instances of dnscrypt-proxy on different ports)
