### ISSUE TITLE
 libsystemd-dev depency issuse

### ISSUE THREAD

**Issue by blub4747** [jedisct1/dnscrypt-proxy#712]
Hi guys,
Iam trying to compile dnscryt-proxy on my Xubuntu eg :	
Ubuntu 16.04.2 LTS
Release:	16.04

When I am trying to execute the following instructions from the Wiki
./configure --with-systemd && make
I do get following issues. 

configure: error: systemd expected but libsystemd not found -- maybe you need to install the pkg-config and libsystemd-dev packages
I therefore installed pkg-config .
But when I do try install libsystemd-dev

I get the following error msgs

apt-get install libsystemd-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsystemd-dev : Depends: libsystemd0 (= 229-4ubuntu10) but 229-4ubuntu19 is to be installed
E: Unable to correct problems, you have held broken packages.

How can I please resolve this issue?
thx,blub4747

**Comment by licaon-kter** [comment]
That your package management issue, your system, fix it and retry.

**Comment by jedisct1** [comment]
The first thing the Wiki says is to *not* use systemd unless you have a really good reason to.
