### ISSUE TITLE
https://download.dnscrypt.org/dnscrypt-proxy/ is not reachable.

### ISSUE THREAD

**Issue by Reverendo70** [jedisct1/dnscrypt-proxy#713]
https://download.dnscrypt.org/dnscrypt-proxy/ is not reachable.

~/dnsproxy# wget https://download.dnscrypt.org/dnscrypt-proxy/LATEST.tar.bz2
--2017-08-02 11:58:50--  https://download.dnscrypt.org/dnscrypt-proxy/LATEST.tar.bz2
Resolving download.dnscrypt.org (download.dnscrypt.org)... 37.59.238.213
Connecting to download.dnscrypt.org (download.dnscrypt.org)|37.59.238.213|:443... failed: Connection timed out.
Retrying.

**Comment by licaon-kter** [comment]
Confirmed not working here too.

**Comment by jedisct1** [comment]
Yes, OpenBSD-current has become very unstable when running KVM :(

Unfortunately I can't afford another server.
