### ISSUE TITLE
Precompiled binaries for Linux

### ISSUE THREAD

**Issue by Aparctias** [jedisct1/dnscrypt-proxy#714]
Hi guys,

At least one of your precompiled binaries which resides under [here](https://download.dnscrypt.org/dnscrypt-proxy/binaries/linux/dnscrypt-proxy-x86_64-linux-musl.tar.gz )
has an executable in Mach-0 format (one which is used in MacOs).
Could you please recompile it for linux?

**Comment by jedisct1** [comment]
Oh, that's fun.

I don't know how the cross compilation script ended up building native files.

I removed the files.

Thanks for the heads up!
