### ISSUE TITLE
Move all precomplied binaries into the same path

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jedisct1/dnscrypt-proxy#716]
All the precomplied binaries hosted at download.dnscrypt.org but except files named with LATEST can be move to https://download.dnscrypt.org/dnscrypt-proxy/binaries/

**Comment by jedisct1** [comment]
That would totally make sense.

Unfortunately there are a bunch of tools, scripts and web pages referring to the current location, and that would break them.

**Comment by wulungnet** [comment]
use symbolic link ? most web server support it.

**Comment by jedisct1** [comment]
But they aren't displayed as symbolic links, non-Unix users don't know what they are and will be confused that there are two versions available for download.
