### ISSUE TITLE
What does server hosting consist of?

### ISSUE THREAD

**Issue by Mikewn1** [jedisct1/dnscrypt-proxy#719]
When hosting a dnscrypt server does it also put up a recursive dns resolver?

What does it setup?

**Comment by jedisct1** [comment]
There are different ways to set up a DNSCrypt server.

Unbound is itself a recursive server and supports DNSCrypt as a server. Key management is a bit complicated, though.

[dnscrypt-wrapper](https://github.com/cofyc/dnscrypt-wrapper) is a server-side proxy. It handles the encrypted exchanges, and forwards DNS queries to a resolver. It is not a resolver by itself. But it can work with any resolver.

[dnsdist](https://dnsdist.org/) is also a server-side proxy, that supports DNSCrypt. Like the above, it is not a resolver by itself. But it can work with any resolver.

The easiest way to run a new server is to us the Docker image, as documented [here](https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes).

It includes everything: the dnscrypt-wrapper proxy, a pre-configured resolver, and all the scripts monitoring everything and automatically managing the keys for you.
