### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by fyrekrig** [jedisct1/dnscrypt-proxy#719]
Have installed and are running Simpl;e DNSCrypt.

Services is running and after reboot I have non-ISP DNS Servers  (https://www.dnsleaktest.com/)
However after a while I am getting back to the ISP DNS servers

Why is this happening and how can I stay on the non-ISP DNS Servers?

**Comment by jedisct1** [comment]
Hi!

This is not the right issue tracker :) This one is for [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy/wiki).

The one for Simple DNSCrypt is here: https://github.com/bitbeans/SimpleDnsCrypt

I don't use Windows, so this is just a shot in the dark, but are you using a VPN at the same time? The VPN software might be what resets the DNS settings.

**Comment by fyrekrig** [comment]
Hi,

Thanks your reply. I will put the question to the right forum.

Still, regarding your comment I don't use VPN.

Best regards

Fyr

*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *

Monday, 17/08/07, 17:25, you wrote:

Hi!
 This is not the right issue tracker :) This one is for dnscrypt-proxy.
 The one for Simple DNSCrypt is here: https://github.com/bitbeans/SimpleDnsCrypt
 I don't use Windows, so this is just a shot in the dark, but are you using a VPN at the same time? The VPN software might be what resets the DNS settings.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
     {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jedisct1/dnscrypt-proxy","title":"jedisct1/dnscrypt-proxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jedisct1/dnscrypt-proxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jedisct1 in #719: Hi!\r\n\r\nThis is not the right issue tracker :) This one is for [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy/wiki).\r\n\r\nThe one for Simple DNSCrypt is here: https://github.com/bitbeans/SimpleDnsCrypt\r\n\r\nI don't use Windows, so this is just a shot in the dark, but are you using a VPN at the same time? The VPN software might be what resets the DNS settings."}],"action":{"name":"View Issue","url":"https://github.com/jedisct1/dnscrypt-proxy/issues/719#issuecomment-320627781"}}}

**Comment by licaon-kter** [comment]
@fyrekrig What windows version? Did you search for `windows dns leak` on the internet yet? That might be it.

**Comment by fyrekrig** [comment]
Hi,

Thank you so much for your reply.

I have now tried DNSCrypt on both Windows 10 and Windows 7 PC's and found something
strange.
When the network adapter is set to optain IP automatically my DNS is assigned through
DNSCrypt.

When the network adapter is set to static IP  my DNS is assigned to my ISP DNS

Why is this happening. As we have 8 PC's on the network we prefer to have fixed IP's

Enclosed are some screen shots.

Your comment will be appreciated.


Best regards

Fyr

*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *

Monday, 17/08/07, 20:26, you wrote:

@fyrekrigWhat windows version? Did you search for windows dns leakon the internet yet? That might be it.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
  
     {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jedisct1/dnscrypt-proxy","title":"jedisct1/dnscrypt-proxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jedisct1/dnscrypt-proxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@licaon-kter in #719: @fyrekrig What windows version? Did you search for `windows dns leak` on the internet yet? That might be it."}],"action":{"name":"View Issue","url":"https://github.com/jedisct1/dnscrypt-proxy/issues/719#issuecomment-320662863"}}}
