### ISSUE TITLE
Cannot run dnscrypt-proxy on any port other than 53

### ISSUE THREAD

**Issue by westsuhanic** [jedisct1/dnscrypt-proxy#722]
Hello:

My name is West Suhanic.

I am using dnscrypt-proxy on a hardened gentoo kernel.

The output from uname -ar is:

Linux routerplus 4.8.17-hardened-r2 #1 SMP Wed Aug 2 13:57:31 EDT 2017 i686 AMD Athlon(tm) 64 Processor 3000+ AuthenticAMD GNU/Linux

I am running version v1.9.4 of dnscrypt-proxy.

I am having an issue with dnscrypt-proxy. I can only run it on port 53.
If I put it on for example port 5399 or port 40, name resolution does not work.

There are no error messages in either dmesg or /var/log/dnscrypt-proxy.log when
I run dnscrypt-proxy on either port 40 or port 5399.

I have an older version of dnscrypt-proxy-(v1.6.1) on another machine that allows me to run
on port 40 and function properly.

I have compiled and ran the latest version dnscrypt-proxy-(from source) and I get the same results.

Can you please offer me some suggestions as to what I might be doing wrong?

thank you,

west suhanic

**Comment by licaon-kter** [comment]
DNS queries are send to port 53 every time, so you need something (eg. Unbound or dnsmasq ) to listen on port 53 and forward requests to the dnscrypt-proxy port.

On that other machine what does (running as root): `netstat -tupan | grep 53` output?

**Comment by westsuhanic** [comment]
Hello:

Thank you for  your quick and helpful reply. I did not realize the necessity of having software like unbound listening on port 53 to forward requests to dnscrypt-proxy which is on another port like 5399.
I now realize this and thank you for the tip. This issue is closed.

west suhanic
