### ISSUE TITLE
Client library

### ISSUE THREAD

**Issue by AlexeiScherbakov** [jedisct1/dnscrypt-proxy#723]
I am writing utility which intercepts DNS-requests and route it to dnscrypt server.
Now it simple redirect UDP messages to 127.0.0.1:53 where dnscrypt proxy is located, but where is a client library for dnscrypt?

**Comment by jedisct1** [comment]
This is great! What OS is that for?

There are no libraries yet (except one in Python, and it may not be complete), so one has to be built out of the dnscrypt-proxy code base.

**Comment by AlexeiScherbakov** [comment]
It will be under Windows 7 and up

**Comment by jedisct1** [comment]
[Here](https://github.com/openalias/dnscrypt-python) is the Python implementation I was referring to.

And the protocol is documented here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt
