### ISSUE TITLE
Verizon blocking access to some websites

### ISSUE THREAD

**Issue by Replicant1769** [jedisct1/dnscrypt-proxy#725]
-resolver-address=77.66.84.233:443 --provider-name=2.dnscrypt-cert.resolver2.dns

I've posted about it here:
https://www.facebook.com/groups/majordomo/permalink/10155595235614522/

Facebook and other sites like duckduckogo.s SSL / HTTPS is not working.

Not happening in firefox but Wire messenger also gave me the warning:

"Wire messenger:
"Why do I see "Your connection is not private"?

When you see this message, it means that the TLS connection to Wire servers was interrupted somewhere. This could be due to a restrictive firewall configuration for example.

Since Wire for Desktop cannot establish if it is connecting to the right servers the connection is blocked in this case."

**Comment by licaon-kter** [comment]
Could you show what IP do you get (for the Wire server) when it resolves via dnscrypt-proxy and what do you get when it resolves via OpenDNS ( 208.67.220.220 ) ?

**Comment by jedisct1** [comment]
What does

```
hostip wire.com
```
return?

What does
```
hostip -r 127.0.0.1 wire.com
```
return? (replace `127.0.0.1` with the IP dnscrypt-proxy is listening to, if you changed it)

**Comment by jedisct1** [comment]
Also: check that the clock is correct on your client (the one running the web browser, not the dnscrypt client).

**Comment by Replicant1769** [comment]
"What does

hostip wire.com

return?"

216.239.38.21

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
"What does

hostip -r 127.0.0.1 wire.com

return?"

216.239.32.21 as well

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
So, check the clock/date on your system. TLS certificates are rejected if they are not valid for the current date.

**Comment by Replicant1769** [comment]
How do I do that? Computer says Aug 16, 5:13 AM while phone says 5:17 AM

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
SInce you're probably running Windows, also try to disable your antivirus and other local junk that could do MITM.

**Comment by Replicant1769** [comment]
I set Time and timezones as automatic in system settings and now the time is correct. but the issue still remains.

**Comment by licaon-kter** [comment]
> Facebook and other sites like duckduckogo.s SSL / HTTPS is not working.
> Not happening in firefox 

What do you mean? It happens yet it does not?

**Comment by Replicant1769** [comment]
Possibly an issue with chromium? but odd that wire messenger also warned me and shutdown.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
can you get in touch with that dnscrypt server? have them shutdown and loom through their system for any malicious files?

Meantime any commands you can give me to connect to a different dnscrypt node?
I'm a little rusty on going about that

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
I mean I don't see how it it could be an issue with that dnscrypt server.
Idk I'm totally confused by where this dns hijack is coming from.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
Can you just change your DNS settings to `8.8.8.8` (instead of `127.0.0.1` or whatever it is) and see if it fixes your problem?

**Comment by Replicant1769** [comment]
do you know the command?

I stopped dnscrypt and the problem still occurring.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
sudo dnscrypt-proxy --local-address=8.8.8.8
[sudo] password for alternity:
Wed Aug 16 06:51:00 2017 [ERROR] Error: no resolver name given, no configuration file either.
Wed Aug 16 06:51:00 2017 [ERROR] The easiest way to get started is to edit the example configuration file
Wed Aug 16 06:51:00 2017 [ERROR] and to append the full path to that file to the dnscrypt-proxy command.
Wed Aug 16 06:51:00 2017 [ERROR] Example: dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
Wed Aug 16 06:51:00 2017 [ERROR] The local list of public resolvers is loaded from: [/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv]
Wed Aug 16 06:51:00 2017 [ERROR] Consult https://dnscrypt.org for more information about dnscrypt-proxy.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
No, your system DNS settings.

The `/etc/resolv.conf` file should include something like:

```
nameserver 8.8.8.8
```

But don't modify that file directly, use whatever system administration GUI is installed on your system.

**Comment by Replicant1769** [comment]
It was set for 192.168.10.1

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
It means that you've never been using DNSCrypt.

Try changing it to `8.8.8.8`.

**Comment by Replicant1769** [comment]
sudo systemctl status dnscrypt-proxy
always shown that it was working

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
I changed it.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
sudo systemctl status dnscrypt-proxy
● dnscrypt-proxy.service - A tool for securing communications between a client and a DNS resolver.
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-08-16 06:30:13 EDT; 14s ago
Main PID: 31863 (dnscrypt-proxy)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/dnscrypt-proxy.service
           └─31863 /usr/bin/dnscrypt-proxy --local-address=127.0.0.1:53 --resolver-address=77.66.84.233:443 --provider-name=2.dnscrypt-cert.resolver2.d

Aug 16 06:30:13 alternity-pc systemd[1]: Started A tool for securing communications between a client and a DNS resolver..
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [INFO] Ephemeral keys enabled - generating a new seed
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [INFO] Done
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [INFO] Server certificate with serial '0001' received
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [INFO] This certificate is valid
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [INFO] Chosen certificate #808464433 is valid from [2016-09-10] to [2017-0
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [INFO] The key rotation period for this server may exceed the recommended
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3
Aug 16 06:30:13 alternity-pc dnscrypt-proxy[31863]: Wed Aug 16 06:30:13 2017 [NOTICE] Proxying from 127.0.0.1:53 to 77.66.84.233:443

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
It's always said that.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
Linux can be very confusing, even more with systemd. This started a background service, but your DNS queries never used it.

What does the following command return?

```
dig resolver.dnscrypt.org
```

?

**Comment by jedisct1** [comment]
Or if you don't have the `dig` command:

```
hostip -r 192.168.10.1 resolver.dnscrypt.org
````

**Comment by jedisct1** [comment]
So what do `hostip -r 192.168.10.1 resolver.dnscrypt.org` and/or `dig resolver.dnscrypt.org` return?

**Comment by Replicant1769** [comment]
dig resolver.dnscrypt.org

; <<>> DiG 9.11.2 <<>> resolver.dnscrypt.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25840
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;resolver.dnscrypt.org. IN A

;; ANSWER SECTION:
resolver.dnscrypt.org. 9 IN A 74.125.44.130

;; Query time: 329 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Aug 16 09:20:57 EDT 2017
;; MSG SIZE  rcvd: 66

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
hostip -r 192.168.10.1 resolver.dnscrypt.org
71.250.0.220

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
Ok, so all this time, you've been using Verizon resolvers.
And now you are using Google resolvers.

You never used DNSCrypt.

So, your issue is unlikely to have anything to do with DNSCrypt, or even with DNS at all.

**Comment by jedisct1** [comment]
Now that you are using Google DNS, if you can access these websites, it probably means that Verizon was explicitly blocking these websites.

If this is not you, maybe your parents/wife/school/tenant/whatever used Verizon Parental Control to block these websites.

**Comment by Replicant1769** [comment]
why would the block https for facebook and duckduckgo.com search engine?
How can i use dnscrypt for dns.
that's what i want

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
Talk to whoever is the administrator of your local network (or pay for the internet connectivity) ...

**Comment by Replicant1769** [comment]
that's me. " setup dnscrypt. I thought I was using dnscrypt servers for dns.
dnscrypt is telling me that i am. so i don't know what you're talking about?
resolver-address=77.66.84.233:443 --provider-name=2.dnscrypt-cert.resolver2.dn
 sudo systemctl status  dnscrypt-proxy

● dnscrypt-proxy.service - A tool for securing communications between a client and a DNS resolver.
   Loaded: loaded (/etc/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-08-16 07:36:37 EDT; 2h 12min ago
Main PID: 2493 (dnscrypt-proxy)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/dnscrypt-proxy.service
           └─2493 /usr/bin/dnscrypt-proxy --local-address=127.0.0.1:53 --resolver-address=77.66.84.233:443 --provider-name=2.dnscrypt-cert.resolver2.dn

Aug 16 08:37:48 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 08:37:48 2017 [INFO] This certificate is valid
Aug 16 08:37:48 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 08:37:48 2017 [INFO] Chosen certificate #808464433 is valid from [2016-09-10] to [2017-09
Aug 16 08:37:48 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 08:37:48 2017 [INFO] The key rotation period for this server may exceed the recommended v
Aug 16 08:37:48 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 08:37:48 2017 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3C
Aug 16 09:38:54 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 09:38:54 2017 [INFO] Refetching server certificates
Aug 16 09:38:54 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 09:38:54 2017 [INFO] Server certificate with serial '0001' received
Aug 16 09:38:54 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 09:38:54 2017 [INFO] This certificate is valid
Aug 16 09:38:54 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 09:38:54 2017 [INFO] Chosen certificate #808464433 is valid from [2016-09-10] to [2017-09
Aug 16 09:38:54 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 09:38:54 2017 [INFO] The key rotation period for this server may exceed the recommended v
Aug 16 09:38:54 alternity-pc dnscrypt-proxy[2493]: Wed Aug 16 09:38:54 2017 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3C
lines 1-18/18 (END)

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by jedisct1** [comment]
Please stop copy/pasting this.

Can you access these websites now that you are using Google DNS (`8.8.8.8`)?

**Comment by Replicant1769** [comment]
I have always been able to access the websites. I told you chromium is telling me that the SSL / HTTPS is not valid. Wire messenger also shutdown because it said something was coming between/ compromising TLS.

I want do use DNScrypt dns resolvers. Was I not? If so How do I?
I'm changing 8.8.8.8 back? because I don't want to use google

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by Replicant1769** [comment]
should i change it to 127.0.0.1 ?
Or 127.0.0.1:53

Which is what dnscrypt says is my local address

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by licaon-kter** [comment]
Looks like you've messed up some ideas.

Basically:
* have dnscrypt-proxy running ( you already have this I guess; run as root `netstat -tupan | grep 53` you can see it right? )
* now, you need to tell your Linux to actually use it, so edit `/etc/resolv.conf` to have ONLY: `nameserver 127.0.0.1` and then run `chattr +i /etc/resolv.conf` to write protect that file so DHCP or whatever can't modify it (remember to run `chattr -i /etc/resolv.conf` to be able to edit it in the future
* retest

**Comment by jedisct1** [comment]
And call Verizon to check if/why controls filters have been enabled for your account.

**Comment by Replicant1769** [comment]
Thanks for all your help!

It should be working anyway as I have installed dnscrypt on my open-WRT router.
and that installed automatically without me running terminal commands.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.
