### ISSUE TITLE
Upgrading?

### ISSUE THREAD

**Issue by gerroon** [jedisct1/dnscrypt-proxy#729]
HI

I cant find info on upgrading. I am using 1.6.0 on Debian Wheezy and I am not sure about how to go ahead.

thanks

**Comment by licaon-kter** [comment]
Update packages?

How did you install?

**Comment by gerroon** [comment]
Hi


To be honest I do not remember but I think I used the install script, whatever that was provided back then. It seems like it got some new updates so I am not sure about how to go about it. 

Am I supposed to uninstall? I do not even know how to uninstall, did the script provide uninstall functionalty?

**Comment by gerroon** [comment]
I am guessing that this is how I installed it then

-rwxr-xr-x  1 8.6K Jan  2  2016 dnscrypt-autoinstall.sh

**Comment by CrisBRM** [comment]
https://wiki.installgentoo.com/index.php/DNSCrypt#Building

**Comment by jedisct1** [comment]
Download it again! Looks like there is an uninstall option.

You can then use the up-to-date binaries from https://github.com/jedisct1/dnscrypt-proxy-installer if you like.

**Comment by gerroon** [comment]
Thanks guys trying it now.
