### ISSUE TITLE
Dnscrypt & bit.ly

### ISSUE THREAD

**Issue by Max131** [jedisct1/dnscrypt-proxy#730]
I have a rare issue, all works fine with dnscrypt, except by a thing. When I try to open an url like bit.ly or ow.ly, I get a "Firefox(or opera, etc) can't connect with the bit.ly server". But, if I deactivate dnscrypt and I use a dns like 8.8.8.8 there is no problem. Can someone here help me?

**Comment by jedisct1** [comment]
What resolver are you using?

**Comment by Max131** [comment]
I tried ca-cawest, ca-caeast, ca-fi, ca-usnorth and okturtles

And well, I do not the reason but, now all is working fine. Thank you for try to help :)
