### ISSUE TITLE
resolver timeout (UDP)

### ISSUE THREAD

**Issue by vasek00** [jedisct1/dnscrypt-proxy#731]
```
dnscrypt-proxy --local-address=127.0.0.2:65053 --daemonize dns-payload-size=1252 -R cisco -l /opt/tmp/dnscrypt-proxy.65053.log

dnscrypt-proxy --local-address=127.0.0.2:65153 --daemonize dns-payload-size=1252 -R dnscrypt.eu-dk -l /opt/tmp/dnscrypt-proxy.65153.log

/ # ip ro
default dev ppp0  scope link 
77.66.84.233 dev ppp1  scope link 
...
xx.xx.xx.26 dev ppp1  proto kernel  scope link  src xx.xx.xx.52 
/ #

65153.log
...
Sat Aug 19 15:10:55 2017 [NOTICE] Starting dnscrypt-proxy 1.9.5
Sat Aug 19 15:10:55 2017 [INFO] Generating a new session key pair
Sat Aug 19 15:10:55 2017 [INFO] Done
...
Sat Aug 19 17:12:25 2017 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3C24:BFF3:2BF7:B406:108B:44DA:51FE:3711
Sat Aug 19 17:38:48 2017 [DEBUG] resolver timeout (UDP)
Sat Aug 19 17:38:48 2017 [DEBUG] resolver timeout (UDP)
Sat Aug 19 18:11:30 2017 [DEBUG] resolver timeout (UDP)

```

**Comment by jedisct1** [comment]
That's debugging information.

You can ignore all of these, or try a resolver with a lower latency.

**Comment by vasek00** [comment]
It is clear, but if there was one resolv and it was - dnscrypt.eu-dk, then most likely brakes would be noticeable?

**Comment by jedisct1** [comment]
The connectivity between your client and these servers doesn't seem to be very reliable. Is it a VPN?

Packets are lost, or taking too much time to come back. This probably affects everything not just dnscrypt-proxy.

DNS clients automatically retry after a timeout, so this is usually not a problem.

Enabling the cache can help a little bit: https://github.com/jedisct1/dnscrypt-proxy/wiki/Go-faster

As well as choosing a resolver closer to your internet provider or VPN.

**Comment by vasek00** [comment]
Yes one sits on pppoe (cisco) another on pptp (dnscrypt.eu-dk) channels good and stable, it is possible to connect both to pppoe, I think not in them.
Yes since the beginning there was "cache-size=0" value 1500, there were also these messages.

**Comment by jedisct1** [comment]
You connection might look stable, but it is dropping packets. There's not much that can be done here, you need to investigate why that happens, as it's outside of the scope of dnscrypt-proxy. Maybe network congestion.

Try using TCP, maybe (change `TCPOnly no` to `TCPOnly yes` in the config file).

**Comment by vasek00** [comment]
TCPOnly yes, is aware about this setup. Earlier already I tried, but on speed concedes to UDP to an algorithm. I will try to return once again on this function.

**Comment by jedisct1** [comment]
Also try http://icmpcheck.popcount.org/
