### ISSUE TITLE
Multiple dnscrypt-proxy running as root and as the dnscrypt user

### ISSUE THREAD

**Issue by westsuhanic** [jedisct1/dnscrypt-proxy#732]
Hello:

I am running on gentoo. The command uname -ar yields:

Linux routerplus 4.8.17-hardened-r2 #1 SMP Wed Aug 2 13:57:31 EDT 2017 i686 AMD Athlon(tm) 64 Processor 3000+ AuthenticAMD GNU/Linux
Under gentoo I have modified the startup script /etc/init.d/dnscrypt-proxy to start multiple copies of
dnscrypt-proxy program. In my case I am starting 5 dnscrypt-proxy programs. Everything works except that when I do a ps waux on my machine I see 10 dnscrypt-proxy processes with 5 processes running as root and 5 running as the user dnscrypt. Why are there 5 dnscrypt-proxy running as the user root? Is this normal? Shouldn't the daemonization process kill off the parent process which is the root process and only leave the dnscrypt-proxy programs running as the dnscrypt user? What am I missing?

Here is an example of how the script starts the dnscrypt-proxy:

start-stop-daemon --start --wait 2000 --quiet \
                --exec /usr/sbin/dnscrypt-proxy \
                -- \
                --pidfile="${pidfile}" \
                --loglevel=6 \
                --logfile="${DNSCRYPT_LOGFILE}" \
                --daemonize --user=${runas_user} \
                --local-address=${DNSCRYPT_LOCALIP}:${DNSCRYPT_LOCALPORT_5} \
                --resolver-address=${DNSCRYPT_RESOLVERIP_5}:${DNSCRYPT_RESOLVERPORT_5} \
                --provider-name=${DNSCRYPT_PROVIDER_NAME_5} \
                --provider-key=${DNSCRYPT_PROVIDER_KEY_5}

thank you,

west suhanic

**Comment by jedisct1** [comment]
That's because of the `--pidfile` option. The pid file is owned by root, so there's an extra process spawned that does nothing except remove that PID file when the main process exits.

BTW, you should consider using  configuration files instead of that list of command-line options, especially if you are running multiple instances.
