### ISSUE TITLE
macOS GUI: Is it possible to disable changes to DHCP DNS?

### ISSUE THREAD

**Issue by jeff47** [jedisct1/dnscrypt-proxy#733]
I'm using the macOS GUI - works beautifully, except that I want it to run but leave the assigned DNS server in my network interface alone.  I use dnsmasq locally, which then queries dnscrypt-proxy, and the GUI keeps hijacking this.  

TL;DR:
Is there a way to start dnscrypt-proxy using the GUI without changing interface DNS settings?

**Comment by jedisct1** [comment]
It's a different project, but I think it's designed to only work with DHCP.

If you know how to use the command-line, you don't need the GUI; you can run dnscrypt-proxy directly.
