### ISSUE TITLE
resolve error if  "Server provided by Martin 'd0wn' Albus"

### ISSUE THREAD

**Issue by ducky87h** [jedisct1/dnscrypt-proxy#736]
Hello,

if I am useing server from d0wn, than some websites (e.g. wiki.debian.org) could not resolve. I am useing following setup:
pi-hole on port 53 with server 127.0.0.1#40 and 127.0.0.1#41, dnssec enabled
dnscrypt-proxy port 40 and 41
My local domain is .zz

If I use another server from d0wn, than I have the same problem. If I use a server from another person, that all works fine.

So maybe someone can help me, so that I can use the server from d0wn? 

Sorry If that is the wrong place, it's my first issue.

**Comment by jedisct1** [comment]
Hi,

`debian.org` is signed, and maybe this doesn't work reliably with dnsmasq (or at least with whatever version pi-hole ships with).

Can you resolve `dnscrypt.org`?

**Comment by ducky87h** [comment]
Hey,

that's it! Thank you so much. If I disable dnssec in dnsmasq,  it works and I am able to resolve dnscrypt.org and other signed sites.  Now I try to found the "real" error. Thank you so much!
