### ISSUE TITLE
I can't find dnscrypt-proxy.conf.

### ISSUE THREAD

**Issue by Mafuyu-Desu** [jedisct1/dnscrypt-proxy#737]
Im using Ubuntu 16.04.
Installed Dnscrypt-proxy 1.6.1-1 from official repository.
I can't find my dnscrypt-proxy.conf.
It's not in /usr/local/etc/~ and /etc/~

**Comment by ducky87h** [comment]
Sould be in /etc/dnscrypt-proxy/

**Comment by jedisct1** [comment]
Version 1.6.1 is very old, and configuration files didn't exist back then.

The current stable version is 1.9.5 and it's already been out for a while.

**Comment by jedisct1** [comment]
If you want something less old, uninstall the current package and use https://github.com/jedisct1/dnscrypt-proxy-installer
