### ISSUE TITLE
Can't access manpages.ubuntu.com on system running dnscrypt.

### ISSUE THREAD

**Issue by twisp007** [jedisct1/dnscrypt-proxy#738]
On trying to visit manpages.ubuntu.com, chromium complains:

> This site can’t be reached
> manpages.ubuntu.com’s server DNS address could not be found.
> DNS_PROBE_FINISHED_NXDOMAIN

Tried with following resolvers: d0wn-lv-ns2, soltysiak.

Using the same internet connection, I can visit the website on my phone.

**Comment by jedisct1** [comment]
Are you using dnscrypt-proxy exclusively, or is an obsolete version of dnsmasq (as in pi-hole) sitting between the proxy and your client?

**Comment by jedisct1** [comment]
You didn't mention anything about your environment, but I guess you are running Debian Jessie, or some obsolete Ubuntu distribution.

This is unrelated to dnscrypt. Debian Jessie packages are old and have become incompatible with today's internet, to the point that even ubuntu[.]com cannot be resolved any more.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805596 for example. That's from 2015, but I assume nothing improved since; the situation just got worse.

Either disable dnssec validation in dnsmasq since it doesn't work, or use a more recent version.

**Comment by twisp007** [comment]
On the contrary I am on Manjaro based on Arch Linux; `dnscrypt-proxy` version: `1.9.4-1`

Also I am not using `dnsmasq`, configured dnscrypt with `LocalCache ON`.

**Comment by jedisct1** [comment]
So I have absolutely no idea :(

Can the names be resolved from the command line (using `dig`, `drill` or `hostip`)? If not, what error is being returned?

**Comment by twisp007** [comment]
Using drill:

```
$ drill http://manpages.ubuntu.com/
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 64829
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; http://manpages.ubuntu.com/. IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
.       600     IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2017091102 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 333 msec
;; SERVER: 192.168.1.1
;; WHEN: Tue Sep 12 03:13:59 2017
;; MSG SIZE  rcvd: 120
```

Using hostip:

```
$ hostip manpages.ubuntu.com
91.189.95.15
```

**Comment by jedisct1** [comment]
Can you try this instead?
```sh
drill manpages.ubuntu.com
drill resolver.dnscrypt.org
```
?

**Comment by twisp007** [comment]
**$ drill manpages.ubuntu.com**
```
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 50194
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 6 
;; QUESTION SECTION:
;; manpages.ubuntu.com. IN      A

;; ANSWER SECTION:
manpages.ubuntu.com.    600     IN      A       91.189.95.15

;; AUTHORITY SECTION:
ubuntu.com.     334     IN      NS      ns4.p27.dynect.net.
ubuntu.com.     334     IN      NS      ns2.p27.dynect.net.
ubuntu.com.     334     IN      NS      ns1.p27.dynect.net.
ubuntu.com.     334     IN      NS      ns3.p27.dynect.net.

;; ADDITIONAL SECTION:
ns1.p27.dynect.net.     86116   IN      A       208.78.70.27
ns1.p27.dynect.net.     16      IN      AAAA    2001:500:90:1::27
ns2.p27.dynect.net.     86116   IN      A       204.13.250.27
ns3.p27.dynect.net.     86116   IN      A       208.78.71.27
ns3.p27.dynect.net.     16      IN      AAAA    2001:500:94:1::27
ns4.p27.dynect.net.     86116   IN      A       204.13.251.27

;; Query time: 80 msec
;; SERVER: 139.59.17.152
;; WHEN: Tue Sep 12 14:31:08 2017
;; MSG SIZE  rcvd: 259
```

**$ drill resolver.dnscrypt.org**
```
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 9077
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; resolver.dnscrypt.org.       IN      A

;; ANSWER SECTION:
resolver.dnscrypt.org.  8       IN      A       84.200.70.40

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 2922 msec
;; SERVER: 84.200.70.40
;; WHEN: Tue Sep 12 14:31:40 2017
;; MSG SIZE  rcvd: 55
```

**Comment by jedisct1** [comment]
You are not using DNSCrypt.

The DNS resolver you are using appears to be something called DNSWATCH, and they don't seem to support DNSCrypt.

**Comment by twisp007** [comment]
The top entry on my `resolv.conf` is `127.0.0.1`. There are other `nameserver`s appended at the end. Looks like the top one doesn't get the priority. I have locked down my `resolv.conf` file and everything's working fine now.

**Comment by jedisct1** [comment]
Awesome!
