### ISSUE TITLE
Q: where are the Android instruction screenshots for use behind AdGuard-NetGuard?

### ISSUE THREAD

**Issue by itspull** [jedisct1/dnscrypt-proxy#739]
They're missing in the android instructions. Anyone care to link them here?

**Comment by licaon-kter** [comment]
Android is barely supported, if it works great, if not...
Luckily it works, and you know where to look for instructions.

Pictures for what? Open app, set custom DNS to 127.0.0.1:<port>? dnscrypt-proxy as root or not?

**Comment by itspull** [comment]
@licaon-kter thanks for reaching out.

@Chef-Koch is working on that. It's here #727.
