### ISSUE TITLE
dnscrypt from Cryptostorm vpn

### ISSUE THREAD

**Issue by michael1900** [jedisct1/dnscrypt-proxy#741]
Hi, please can you add all of them from Right list here:

https://t.co/mgkXRz1ynR

?
It's really important for many have these crypto dns always updated ;)
There are all new servers dns updated and also the new last italian dns server.

Thanks

**Comment by jedisct1** [comment]
Can @df-cryptostorm send a pull request to add these to the current list?

**Comment by michael1900** [comment]
No new from df? maybe it's need to contact him on chat

**Comment by df-cryptostorm** [comment]
Pull request submitted - https://github.com/jedisct1/dnscrypt-proxy/pull/748
