### ISSUE TITLE
dnscrypt now working with a specific ISP; says "[ERROR] Unable to retrieve server certificates"

### ISSUE THREAD

**Issue by twisp007** [jedisct1/dnscrypt-proxy#742]
I use mobile broadband and everything works flawless. But then I use home broadband,

`systemctl status dnscrypt-proxy` gives : 

`[ERROR] Unable to retrieve server certificates`
`[INFO] Refetching server certificates`

These error messages just keep repeating.

My `dnscrypt-proxy.conf`

```
...
#https://servers.opennicproject.org/edit.php?srv=ns3.ca.dns.opennic.glue
ProviderName    2.dnscrypt-cert.ns3.ca.luggs.co
ProviderKey     1C19:7933:1BE8:23CC:CF08:9A79:0693:7E5C:3410:2A56:AC7F:6270:E046:25B2:EDDB:04E3
ResolverAddress 142.4.204.111      

ProviderName    2.dnscrypt-cert.ns3.ca.luggs.co
ProviderKey     1C19:7933:1BE8:23CC:CF08:9A79:0693:7E5C:3410:2A56:AC7F:6270:E046:25B2:EDDB:04E3
ResolverAddress 2607:5300:120:a8a:142:4:204:111:443
...
```

What can I do to make dnscrypt work on my home broadband? Is this is `ports` issue? Should I open up / change any ports?

**Comment by jedisct1** [comment]
Never heard about that resolver. Too bad they didn't ask to be added to the list of public resolvers.

Anyway, it seems to work with these parameters. But don't use duplicate keys. Just keep the first instance of `ProviderName`, `ProviderKey` and `ResolverAddress`.

**Comment by jedisct1** [comment]
And if you're blocking ports, you should make sure that port 443/UDP is open.

**Comment by twisp007** [comment]
>But don't use duplicate keys. Just keep the first instance of ProviderName, ProviderKey and ResolverAddress.

But I want a IPv4 and a IPv6 DNS resolver. Because one network is IPv4 and the other is IPv6. How do I do it (use 2) while using custom dns resolvers?

**Comment by jedisct1** [comment]
Run two instances of dnscrypt-proxy instead of one, with different configuration files.

Also the IPv6 address you wrote doesn't match the one of the URL you gave. It should apparently be `2607:5300:120:a8a:142:4:204:111`.  I don't have an IPv6 connection so I can't test if that one works.

**Comment by twisp007** [comment]
>Run two instances of dnscrypt-proxy instead of one, with different configuration files.

Can you point me to a resource that tells me how to do that?

**Comment by jedisct1** [comment]
I don't know, sorry. I use a Mac.
