### ISSUE TITLE
BlockIPv6 Command Line Option

### ISSUE THREAD

**Issue by Fauxsys** [jedisct1/dnscrypt-proxy#743]
BlockIPv6 is available in the configuration file, but it doesn't seem to be an available argument when using systemd unit files. It's also not included in the man pages. I'd be grateful if you can add this as an option.

Thanks!

**Comment by licaon-kter** [comment]
A quick search:
[--plugin=ldns_aaaa_blocking](https://github.com/jedisct1/dnscrypt-proxy/blob/fafe16b2a8733e2a99026142c40377e1e05fe5ce/src/proxy/simpleconf_dnscrypt.h#L35)
also, your systemd unit can't just [use the config file anyway](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy.service.in#L18)?

**Comment by jedisct1** [comment]
Indeed, this is a plugin.

The sample systemd service has been using the configuration file for a long time, and I would encourage anyone still using command-line options to switch to the config file instead.
