### ISSUE TITLE
In openwrt this system doesn't provide enough entropy to quickly generate high-quality random numbers

### ISSUE THREAD

**Issue by peterwillcn** [jedisct1/dnscrypt-proxy#751]
Configuring dnscrypt-proxy.
Sun Oct  8 01:15:14 2017 [WARNING] This system doesn't provide enough entropy to quickly generate high-quality random numbers
Sun Oct  8 01:15:14 2017 [WARNING] Installing the rng-utils/rng-tools or haveged packages may help.
Sun Oct  8 01:15:14 2017 [WARNING] On virtualized Linux environments, also consider using virtio-rng.
Sun Oct  8 01:15:14 2017 [WARNING] The service will not start until enough entropy has been collected.

**Comment by jedisct1** [comment]
Do what the message says?

**Comment by licaon-kter** [comment]
FYI, seeing this on Android too, but it works fine otherwise.
