### ISSUE TITLE
chroot error

### ISSUE THREAD

**Issue by steave-r0gers** [jedisct1/dnscrypt-proxy#753]
If i set option `User _dnscrypt-proxy` in /etc/dnscrypt-proxy/dnscrypt-proxy.conf dnscrypt didn` start:
> [NOTICE] Starting dnscrypt-proxy 1.9.4 
> [INFO] Generating a new session key pair 
> [INFO] Done 
> [ERROR] Unable to chroot to [/run/dnscrypt-proxy]

/etc/passwd : 
`_dnscrypt-proxy:x:114:65534::/run/dnscrypt-proxy:/bin/false`

**Comment by jedisct1** [comment]
Are you starting this as root?

**Comment by steave-r0gers** [comment]
yes, systemctl start dnscrypt-proxy

**Comment by jedisct1** [comment]
Can you try without systemd?

And just start it with `dnscrypt-proxy /etc/dnscrypt-proxy/dnscrypt-proxy.conf`?
