### ISSUE TITLE
Not enough log information to troubleshoot Unable to retrieve server certificates

### ISSUE THREAD

**Issue by neagix** [jedisct1/dnscrypt-proxy#755]
I am plagued by a repeatable but hard to troubleshoot error:
```
Wed Oct 18 09:11:56 2017 [ERROR] Unable to retrieve server certificates
```

This is the only information available in logs with `LogLevel=7` and nothing on server side. I assume the client is having troubles to contact the server, so a network issue. However I do not know specifically:
* which traffic was blocked
* which application-level piece of logic did not succeed

In the next days I am going to dive in the source code to try to figure this out; I am in particular interested in the behavior in case of unreliable networks (although I am using very reliable networks in this case), or if this is caused by some (iptables) firewall issue.

Aside from the actual error itself, would it be considered an improvement if we could add more relevant information to the `ERROR`?

**Comment by jedisct1** [comment]
Sure, that would be great!

Looking forward to your pull requests!

Maybe more dtrace probes could also be useful.

**Comment by neagix** [comment]
Sure, I will. I have a situation where two boxes (same OS, different hardware) on same LAN have one working fine and one suddenly going in an error loop `Unable to retrieve server certificates`.

To add insult to injury, a few pings/`nslookup`s are somehow able to revive functionality and `dnscrypt-proxy` suddenly receives the certificates (reproducible behaviour).

So I am going to try to find out the reason, at least because of curiosity.

**Comment by jedisct1** [comment]
If you are behind a router doing NAT, maybe it's just its state expiring.

**Comment by neagix** [comment]
Can you elaborate on that? Both boxes are in same network topology (behind same NAT)

**Comment by jedisct1** [comment]
That’s on Windows, right?

**Comment by neagix** [comment]
@jedisct1 nope, Linux. Cannot reproduce it anymore though as I changed the network configuration of this failing box radically.
