### ISSUE TITLE
using client keys?

### ISSUE THREAD

**Issue by oddboy** [jedisct1/dnscrypt-proxy#759]
hey gang,

I'm relatively new to dnscrypt.  I'm struggling a little with how to use the --client-key option.

how do you generate a private key for dnscrypt-proxy to use when talking to a dnscrypt-wrapper server?

Thanks!

Joel

**Comment by jedisct1** [comment]
See here: https://github.com/jedisct1/dnscrypt-proxy/issues/683

But dnscrypt-wrapper doesn't support ACLs based on client keys as far as I know.

**Comment by oddboy** [comment]
Thanks.  I saw that one.

Maybe a better way to state my question is:. How do you use client keys to authenticate specific clients on a private dnscrypt server?

**Comment by jedisct1** [comment]
You need to implement it on your server, according to how you store these certificates and what you are doing with client identification.
