### ISSUE TITLE
unbound does not send certs, receives post-modern art in TXT request (0x20 hack gone wrong?)

### ISSUE THREAD

**Issue by neagix** [jedisct1/dnscrypt-proxy#760]
I am finally finding out why unbound with dnscrypt support (**not dnscrypt-wrapper** + unbound, but just unbound compiled `--with-dnscrypt`) does not work.

I believe the problem is on the side of dnscrypt-proxy; for all others that might have issues, you need to increase unbound verbosity to level 4 (`ALGO` level) at least.

This is what you will see with v1.9.5 of dnscrypt-proxy on the client side:
```
[1508857757] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857757] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.dnsCRYpT-Cert.eXAmPle.cOm.
[1508857774] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857774] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.dNscrypT-cERT.ExaMPlE.Com.
[1508857776] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857776] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.DNsCRyPT-cerT.[...]
[1508857780] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857780] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.DnsCrYpt-cERT.[...]
[1508857781] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857781] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.DNsCRyPT-cerT.[...]
[1508857785] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857785] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.DnsCrYpt-cERT.[...]
[1508857787] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857787] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.DNsCRyPT-cerT.[...]
[1508857790] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857790] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.DnsCrYpt-cERT.[...]
[1508857796] unbound[21676:0] debug: handle request called on DNSCrypt socket
[1508857796] unbound[21676:0] debug: dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.DNSCRyPT-CErT.[...]
```
In place of [...] imagine other variations like these.

Could it be that somewhere the `randomize-case` option of libevent is doing the trick? I've read somewhere that this is supposed to be an anti DNS-poisoning technique (0x20 hack), but I think either dnscrypt should not send randomized `TXT` or unbound should accept any case for it.

In the current status of things, latest unbound v1.6.7 and latest dnscrypt-proxy v1.9.5 are broken (IMO).

**Comment by neagix** [comment]
By the way, I do not see the point of randomizing these since we do a PKI verification anyway. It looks to me more like a case of forgotten default

**Comment by jedisct1** [comment]
Unbound shouldn't have any issues with the casing of the query name. If it does, this is a bug in unbound.

**Comment by jedisct1** [comment]
That being said, I'm pretty sure that Unbound was extensively tested with dnscrypt-proxy as a client.

So, the issue (which you didn't describe, except "does not work") is likely to be unrelated to how these exchange certificates.

**Comment by chantra** [comment]
Indeed dnscrypt-proxy was used to test end to end and 0x20 work just fine.

Nea, could you share you unbound config pls.

**Comment by chantra** [comment]
On top of my head, the provider name expect to end with a dot `.` in
unbound config. I have a feeling that this is not the case in your config.
I think this is documented, if not, then it should.

**Comment by chantra** [comment]
unbound doc says:
```
 dnscrypt-provider: <provider name>
              The  provider name to use to distribute certificates. This is of
              the form: 2.dnscrypt-cert.example.com.. The name MUST end with a
              dot.
```

Your logs show:
```
dnscrypt: not TXT 2.dnscrypt-cert.example.com. Receive: TXT 2.dNscrypT-cERT.ExaMPlE.Com.
```
shows that `2.dnscrypt-cert.example.com` is missing the trailing `dot`.
Relevant line of code:
https://github.com/NLnetLabs/unbound/blob/master/daemon/worker.c#L1049
```
"dnscrypt: not TXT %s. Receive: %s %s"
```

**Comment by neagix** [comment]
:man_facepalming: sorry guys, it was indeed the dot...but when I saw the randomized case, I concluded it was that...

Perhaps I'd add quotes to the reported entries to make it more visible what is the mistake (the eye tends to skip dots otherwise).

Something like:
```
dnscrypt: not TXT "2.dnscrypt-cert.example.com." Receive: TXT "2.dNscrypT-cERT.ExaMPlE.Com"
```

**Comment by neagix** [comment]
Proposed patch for unbound:
```diff
Index: daemon/worker.c
===================================================================
--- daemon/worker.c	(revision 4384)
+++ daemon/worker.c	(working copy)
@@ -1046,7 +1046,7 @@
 			strcasecmp(buf,
 			worker->daemon->dnscenv->provider_name) == 0)) {
 			verbose(VERB_ALGO,
-				"dnscrypt: not TXT %s. Receive: %s %s",
+				"dnscrypt: not TXT \"%s\". Receive: %s \"%s\"",
 				worker->daemon->dnscenv->provider_name,
 				sldns_rr_descript(qinfo.qtype)->_name,
 				buf);
```
I am not going to submit it upstream, don't care about credits for such small contribution either, so feel free to pick it if you want.

**Comment by chantra** [comment]
> Perhaps I'd add quotes to the reported entries to make it more visible what is the mistake (the eye tends to skip dots otherwise).

makes sense.

I can take the patch and send it upstream if you want.

**Comment by chantra** [comment]
upstream bug:
https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=1949

**Comment by jedisct1** [comment]
```diff
-				"dnscrypt: not TXT %s. Receive: %s %s",
+				"dnscrypt: not TXT \"%s\". Receive: %s \"%s\"",
```

Did you mean
```
"dnscrypt: not TXT \"%s.\". Receive: %s \"%s\"",
```
?

**Comment by chantra** [comment]
I think
```
"dnscrypt: not TXT \"%s\". Receive: %s \"%s\"",
```

make more sense, it will print 

```
dnscrypt: not TXT "2.dnscrypt-cert.example.com". Receive: TXT "2.dnsCRYpT-Cert.eXAmPle.cOm."
```

in this specific example.

**Comment by neagix** [comment]
@chantra sure, that will be helpful.

I would even go as far as replacing the dot with a semicolon:

```
dnscrypt: not TXT "2.dnscrypt-cert.example.com"; receive: TXT "2.dnsCRYpT-Cert.eXAmPle.cOm."
```

Also, shouldn't `receive` be `received`? But that should be compared to other error messages for consistency.

**Comment by chantra** [comment]
>
>  Also, shouldn't receive be received? But that should be compared to
> other error messages for consistency.
>
Yes spelling is hard :p ... I agree it makes the eyes bleed.

**Comment by neagix** [comment]
Yeah..don't want to touch this, as probably the other debug messages are not any better. I think level 4 is a bit too low. I'd go for showing them with a single `-v` since you need these to troubleshoot client connections, not like development bugs.

To be fair, nobody should go too far and just get inspired by how unit tests show messages:
```
TXT record: got "X", but "Y" was expected
```

No need to get creative :stuck_out_tongue:
