### ISSUE TITLE
Issue | Question about MASKS

### ISSUE THREAD

**Issue by iWARR** [jedisct1/dnscrypt-proxy#763]
I have a question about blocking rules with masks. Can I use masking with more then two masks `*` per one string? Seems like not all mask combinations are working on the one string.

**Examlpe**: I'm going to block all this sister subdomains:

sub-zero.example.com
sub.zero.example.com
sub1-one.example.com
sub1.one.example.com
sub2-1.two.example.com
sub-three.example.com
sub4-four.example.com
sub.five.example.com
sub-6.six.example.com
sub...+100 same sister-domains

- I need to have access to `example.com` fom the browser
- I don't want to block `*sub*` alone, because it may intersect with other words
  (i.e. some-good-**sub**ject.org)
- I want to block all 100+ subdomains with minimum multipurpose rules

Lets suppose `"sub"` will be a point (keyword) for blocking.
Lets take a look at this: 		`sub- | sub. | sub1- | sub2-1 | sub4- | sub-6`
The idea is combine "sub" with signs `.` and `-` to slightly reduce a fail-positive blocking for any other sites may include letters `"sub"` inside the name.

**Questions:**

Why not all variants working?
Are more then two masks `*` allowed per one string? Or `*` inside the name?

`*sub-*`			- working 100%
`*sub.*`			- working 100%

`*sub*.example.*`		- not working ! (have to block all of them at once)

Next variants are not too correct, however all of subdomains have to be blocked with this two rules, but they wasn't.

`*sub*-*`			- not working
`*sub*.*`			- not working

**Comment by jedisct1** [comment]
Hi,

Correct, wildcards can only be at the beginning and/or at the end of a pattern. This restriction is what makes pattern matching extremely fast, even with a very large ruleset.

With inner wildcards would, the complexity can become quadratic, thus very slow.

However, don't forget that you can also match by IP address. Typically, marking/ad host names that match the pattern you describe all resolve to the same IP, or to the same block. So you can block any DNS name resolving to e.g. `192.168.*`, and this will catch all name variants.

**Comment by iWARR** [comment]
With IPs it is much more complicated way. I have to resolve 100+ domains manually. It's not always possible and spend a lot of time. Istead 1 small rule can do all the work.
But thanks for the answer. I think thee masks `*` can be helpful in the most of complex cases (for some domains, not every).

**Comment by iWARR** [comment]
Explain, please, just another one thing to understand more clear.
For example, can I use 2 wildcards like this:

`*fe*.update.microsoft.com`

or I have to use 2 wildcards "at the BEGINNING and/or at the END of a pattern" ONLY, as you said before?

```
*fe1.update.microsoft.*
*fe2.update.microsoft.*
*fe3.update.microsoft.*
```

**Comment by jedisct1** [comment]
Just at the beginning and/or at the end.
