### ISSUE TITLE
SkipLog - Selective Blocking Output option (Enhancement)

### ISSUE THREAD

**Issue by iWARR** [jedisct1/dnscrypt-proxy#764]
Dear author

Can you add an option to skip Logs output for selective blocking entries? For example:

example1.com
`- SkipLog:` example2.com		(per 100+ entries at once)
example3.com

Logs for "example2.com" will not be present in the `DNS.log` , but in `Restricted.log` only.
(per 100+ entries at once, garbage in the log file, hard to troubleshoot other entries, heavy Log files)

Or make a small Log-output time threshhold for reducing of exactly the same entries (combine them into one in the cache/buffer/memory or so...)
(I'm not a programmer, I don't know how hard it is to realize, please, forgive me)

May an setting `LogLevel` be helpful in this situation? (But show all different entries?)

Thank you!

**Comment by jedisct1** [comment]
Standard shell tools are often way more convenient for slicing and dicing log files.

`egrep`, `sort`, `uniq -c` can be used to filter content and immediately spot outliers and heavy hitters.

You can also use the LTSV output to store everything in a database and then run queries against this.
