### ISSUE TITLE
Align LTSV Log Output Issue (Fix)

### ISSUE THREAD

**Issue by iWARR** [jedisct1/dnscrypt-proxy#765]
Can you fix LTSV log output for the last column with `*rule*`? It is not alined as the rest.

Example:

```
00/00/00 00:00:00	127.0.0.1	aaa-bbbbbb-ccc-dddd.example.com *rule*
00/00/00 00:00:01	127.0.0.1	aaa-bbb-ccc-dd.example.com *rule*
```
I think, more available signs per 3-rd column will help (~60-70 symbols).

**Comment by jedisct1** [comment]
LTSV separates fields with a TAB. The intent is to make the output easy to parse: http://ltsv.org/

This format remains easy to read, way easier than JSON, but the intent is the same. If you add extra spaces, these will be considered a part of the string.

**Comment by iWARR** [comment]
Thanks!

Just tell me please, what file I have to change? The rest I'll read by your link.
(I'm on Windows, using *.conf file for install)

**Comment by jedisct1** [comment]
The source code of the logging module is here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/src/plugins/example-logging/example-logging.c

But if you change this, it won't be LTSV any more, so LTSV parsers won't work any more with it.

**Comment by iWARR** [comment]
Unfortunately, I'm not a programmer :( And I leave it as it is.
Anyway, I'm very appreciate you for that great software!
