### ISSUE TITLE
No response from dns

### ISSUE THREAD

**Issue by mur202** [jedisct1/dnscrypt-proxy#766]
Hi. I have tried everything. dnscrypt-proxy, simple dnscrypt etc but it does not work. The problem I am having is that as soon as I put my DNS on 127.0.0.1 I can not connect to any internet websites.

**Comment by jedisct1** [comment]
Try [dnsssec-trigger](https://www.nlnetlabs.nl/projects/dnssec-trigger/). It does the same thing, but using a different protocol.
