### ISSUE TITLE
Too small query header

### ISSUE THREAD

**Issue by neagix** [jedisct1/dnscrypt-proxy#767]
I have been debugging yet another extremely weird issue with dnscrypt-proxy v1.9.5 and unbound v1.6.7.
As usual logging is not there, so I added some more for the calls (in unbound) to `dnsc_find_cert()`, and I found out:
```
[1510087836] unbound[30383:0] debug: handle request called on DNSCrypt socket
[1510087836] unbound[30383:0] debug: dnsc_find_cert: too small query header
```

So now I wonder, how could possibly - and all of a sudden - the client-side start sending too small query headers?

Also: if this query is too short, shouldn't dnscrypt-proxy itself also detect that something is wrong and not even bother sending it?

(I am afraid that here we have some incompatibility due to encryptions being used, since there is no ACK about the type of encryption being used..) Worthy to note that I haven't touched either the server or the client side recently though.

Attachments: [unbound.conf](https://gist.github.com/neagix/14fd4d2845b1e2563380dc6152e4c790)

Version:
```
dnscrypt-proxy 1.9.5

Compilation date: Oct 24 2017
Support for plugins: present
Plugins root directory: [/usr/local/lib/dnscrypt-proxy/]
Support for the XChaCha20-Poly1305 cipher: present
```

**Comment by jedisct1** [comment]
The client always sends the same query. This is a simple TXT query, sent via libevent's DNS API. DNSCrypt is not even used at this point.

Maybe a `tcpdump` could help here? Queries for certificates are not encrypted, so you should see them.

**Comment by neagix** [comment]
Unfortunately I rebuilt with current `stable` libsodium branch and problem went away; I will investigate in that direction if it happens again.

Thanks for the feedback!

**Comment by neagix** [comment]
Btw, could be that the "magic" hash is somewhat garbled (too short/not generated)? Just a thought. In future I am going to print the `DNSCRYPT_QUERY_HEADER_SIZE` on log of both sides to understand what's going on.

**Comment by jedisct1** [comment]
The size of the magic bytes is always the same. But it may not match what the server expects indeed.

Were you using the 1.0.15 release version of libsodium before?

**Comment by chantra** [comment]
@neagix feel free to tag me on those dnscrypt-proxy/unbound issues in the future.

The too small header may happen when the TXT query is received. Data comes through the dnscrypt channel, we will try to uncurve, if it fails, we need to check if it was a legit providername/TXT query.

DNSCRYPT_QUERY_HEADER_SIZE is defined here:
https://github.com/NLnetLabs/unbound/blob/master/dnscrypt/dnscrypt.h#L31

this should account for a normal dnscrypted query.

If you manage to repro, and you can get some log/dumps/repro steps, that would be helpful.

**Comment by neagix** [comment]
@jedisct1 another box, amd64, is using latest tagged version of libsodium and has no problems. So I would exclude it's libsodium, also considering that today without any intervention it stopped working on its own.

I can restart dnscrypt-proxy at will, and it still gives the error fetching and on unbound side I see the too small query header.

Do I have to start thinking about MiTM/ISP modifying UDP packets? Would be weird...I tend to exclude this possibility.

What I can do is print on dnscrypt-proxy side what is sending in the query to check if it's actually the same in length and content.

**Comment by neagix** [comment]
I have a lead. At some point the clock gets set to a past date, and somehow this causes the query to become shorter?

See what happens after clock is fixed:
```
Thu Jun 15 00:29:23 2017 [ERROR] No useable certificates found
Wed Nov  8 21:43:20 2017 [INFO] Refetching server certificates
Wed Nov  8 21:43:20 2017 [INFO] Server certificate with serial #1510086797 received
Wed Nov  8 21:43:20 2017 [INFO] This certificate is valid
Wed Nov  8 21:43:20 2017 [INFO] Chosen certificate #1510086797 is valid from [2017-11-07] to [2017-11-08]
Wed Nov  8 21:43:20 2017 [INFO] Server key fingerprint is 4D7D:BDE0:8FEF:6142:9D78:FAC3:BF4D:095D:[...omissis...]
Wed Nov  8 21:43:20 2017 [NOTICE] Proxying from 0.0.0.0:53 to x.x.x.x:56199
```

If this is true, I think it's a bug. Because time-related validation errors should not cause an empty encrypted/hashed payload but rather an explicit error saying "clock skew" or something along those lines.

I am not familiar with the dnscrypt-proxy codebase to pinpoint where this is though, maybe some of you guys can?

**Comment by jedisct1** [comment]
This doesn't cause the query to become shorter, but certificates have a validity period.  So, if your clock is off, certificates don't validate and are rejected.

**Comment by neagix** [comment]
(my previous comment about clock issues was bogus)

I think it's due to routing. At some point routes get messed up, and somehow only a part of the UDP packet gets there? (this is best theory I came up with so far).

I am going to add debugging on dnscrypt-proxy for this.

**Comment by neagix** [comment]
> This doesn't cause the query to become shorter, but certificates have a validity period. So, if your clock is off, certificates don't validate and are rejected.
@jedisct1 yeah sorry, I deleted that comment. The error is different and clear in case of validity issues. It must be something else.

**Comment by chantra** [comment]
@neagix if you get that to repro in a testing environment, can you provide a tcpdump of when the issue is happening, that would greatly help in debugging.

I assume that in https://gist.github.com/neagix/14fd4d2845b1e2563380dc6152e4c790
somewhere an interface is defined to listen on port 21678 .

Also, just to make sure I understand correctly, dnscrypt is working fine between the client and the server and then after some time:
* it fails and then fail consistently
* even after you restart either dnscrypt-proxy or unbound?
* the certs are not expired when that happen

If the expiration time of the cert involved? newer dnscrypt-wrapper default to 24h cert validity since https://github.com/cofyc/dnscrypt-wrapper/commit/9d0a7931b4dd088600f3843dcd11ae89c97af234

The query you are receiving when the "header is too small" is what seems to be a legit DNS request for the cert:

```
In [1]: s='11330100000100000000000001320D644E5343525970542D636552540A'

In [2]: import binascii

In [3]: binascii.unhexlify(s)
Out[3]: b'\x113\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x012\rdNSCRYpT-ceRT\n'
```

when reconstructing the rest of (what I would expect, e.g adding the trailing example.com + class IN and type TXT) your message, here is what we would get:
```
In [10]: d=dns.message.from_wire(xx)

In [11]: print(d)
id 4403
opcode QUERY
rcode NOERROR
flags RD
;QUESTION
2.dNSCRYpT-ceRT.example.com. IN TXT
;ANSWER
;AUTHORITY
;ADDITIONAL
```

Note: I am guessing you are not using example.com as the trailing '\n' (0x0A) would mean that the label is 10 bytes long, also, the total message is 55 bytes, when the reconstructed one is `len(xx) == 45`, so basically, your provider name may be 10 char more than 2.dNSCRYpT-ceRT.example.com, is this correct?

What we would expect is that unbound will fallback onto serving the cert when such request is received, does it do that? tcpdump should tell.

Also, what is the end date of the cert? it really feels like what you are seeing is that the client can't validate the cert (because it is expired) and it keeps asking it over and over again, with some backoff.

**Comment by neagix** [comment]
> can you provide a tcpdump of when the issue is happening, that would greatly help in debugging.

likely next week as I have easier access to the box; issue is not present at the moment.

> I assume that in https://gist.github.com/neagix/14fd4d2845b1e2563380dc6152e4c790
somewhere an interface is defined to listen on port 21678 .

Yeah, edited out but I have those configured correctly. Updated the gist for reference.

> Also, just to make sure I understand correctly, dnscrypt is working fine between the client and the server and then after some time:
> 
> it fails and then fail consistently
> even after you restart either dnscrypt-proxy or unbound?

Yes.

> the certs are not expired when that happen

No

> If the expiration time of the cert involved? newer dnscrypt-wrapper default to 24h cert validity since cofyc/dnscrypt-wrapper@9d0a793

I can safely exclude this. I have solved the time synchronization issues of the box and I expect issue to happen again. My certs are also 24h valid.

> The query you are receiving when the "header is too small" is what seems to be a legit DNS request for the cert:
> 
> In [1]: s='11330100000100000000000001320D644E5343525970542D636552540A'
> 
> In [2]: import binascii
> 
> In [3]: binascii.unhexlify(s)
> Out[3]: b'\x113\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x012\rdNSCRYpT-ceRT\n'
> when reconstructing the rest of (what I would expect, e.g adding the trailing example.com + class IN and type TXT) your message, here is what we would get:
> 
> [...]
> Note: I am guessing you are not using example.com as the trailing '\n' (0x0A) would mean that the label is 10 bytes long, also, the total message is 55 bytes, when the reconstructed one is len(xx) == 45, so basically, your provider name may be 10 char more than 2.dNSCRYpT-ceRT.example.com, is this correct?

Yeah. It's just my private dnscrypt server, not meant to be shared with the world.

> What we would expect is that unbound will fallback onto serving the cert when such request is received, does it do that? tcpdump should tell.

I think you are ignoring now the findings I gathered with the extra debugging.
 
> Also, what is the end date of the cert? it really feels like what you are seeing is that the client can't validate the cert (because it is expired) and it keeps asking it over and over again, with some backoff.

It's not this. I was confused by wrong time on the box, but it was a red herring (now fixed). Certs are valid 24h. If it were a certificate valid time issue, it would give me the other error that says so (not the generic one you can read in first post); I got that descriptive validation error right after issue was healing, but it wasn't this GH issue.

The problem is that unbound receives a DNScrypt query that is too short (55 instead of 68 bytes). I added debugging to print out that short query that you checked with binascii (for the part I published).

Why would unbound expect 68 bytes instead of 55? That's what I wonder. And also: when everything goes well, are the queries 68 bytes "magically"? I think so, but has to be verified.

My candidate is some routing issue, as this box connects also to OpenVPN so the routes get changed automatically. However I cannot think of a scenario where only a portion of an UDP packet gets delivered; so this might also be unrelated.

I will add debugging to dnscrypt-proxy to see what is sending, but next week.
