### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/dnscrypt-proxy#769]
Hello everyone,

I've been maintaing dnscrypt-proxy for about 6 years now.

Unfortunately, my spare time has become scarse, and I can't make a good job at maintaining too many opensource projects simultaneously.

So, this is a call for new maintainers for dnscrypt-proxy, as well as the dnscrypt[.]org website. I'd be glad to transfer these to whoever can keep the project deliver its promise.

This repository will be definitely archived on November 17.

**Comment by bitbeans** [comment]
I`am not a gifted C developer like you are :(

**Comment by chantra** [comment]
@bitbeans I think a fair amount of help can be provided by helping supporting users with issues. This does not involve coding, but it does involve time.

Code-wise, I think the project, as-is, can happily provide value to people without going through release cycles.

I can't really commit to maintaining dnscrypt-proxy, but I may be able to help every so often when times permit, assuming there is people supporting the community of users.

**Comment by publicarray** [comment]
Just a suggestion but maybe creating a github Organisation let's call it dnscrypt, would allow multiple people to have push rights and let the community grow/contribute. The admin of the group should probably probably someone who has contributed some code to the repo before or if you want, stay as you. Alternatively @PowerDNS or other open source organisation could provide support. Anyway just some ideas.

**Comment by eatdust** [comment]
dnscrypt-proxy is a great project, don't let it die!

**Comment by KrasnayaPloshchad** [comment]
@publicarray I agree with you, in my opinion, both server (e.g. dnscrypt-server-docker) and client codes can be moved to the same organization to let more experienced people maintaing together.

**Comment by battlesd** [comment]
It took me a bit to find this DNScrypt forum/help page.  I tried redddit first, but there apparently not a DNScrypt reddit page there.  I would suggest that one be created.  A pinned message could point to here also.

**Comment by iWARR** [comment]
**jedisct1**, my friend.

I think, DNSCrypt is one of the most powerful and useful software I have on my PC.
There is the place, where our safety and securty begins; the cornerstone of wall in front of the present-day threats. Simple, smart and effective tool that change the game rules.

Don't want to be too pathethic, but this is really true.
I'm very thankful to you for this great thechnology, same as a lot of people over world, who can understand what going on...

Think 10 times and please, look forward carefully, how this task have to be solved.

Good luck!

**Comment by jedisct1** [comment]
Nobody should write C any more. That was a mistake. It will be fixed soon.
