### ISSUE TITLE
Potentially conflicting dnsmasq config [LEDE/OpenWRT]

### ISSUE THREAD

**Issue by b-h-l-c** [jedisct1/dnscrypt-proxy#770]
Hello,

I am running dnscrypt-proxy 1.9.5 on LEDE and wanted to clarify the correct configuration for using the /etc/resolv-crypt.conf file. In the OpenWRT wiki for dnscrypt-proxy, it indicates that when multiple instances are used, you can specify a timeout using the resolv-crypt.conf file, and in that case, the option noresolv should be commented out (or I assume equivalently set to option noresolv 0).

It seems the Luci app is setting option noresolv 1 regardless of whether the /etc/resolv-crypt.conf file is used and regardless if there is one or several instances set up. 

Essentially what I want to confirm is the proper dnsmasq noresolv option when using the /etc/resolv-crypt.conf, since the app's behavior conflicts with the OpenWRT wiki.

Thanks!

**Comment by jedisct1** [comment]
You might have more answers by asking on a LEDE forum...
