### ISSUE TITLE
dnscrypt 1.9.5 does not compile in rasbperry pi 3 gcc 4.9.2

### ISSUE THREAD

**Issue by orestis46** [jedisct1/dnscrypt-proxy#771]
I have two raspberry pi 3 boxes running the same kernel  and almost identical features deployed. I 've managed to compile and run without problems dnscrypt -proxy-1.9.5 in combination with pihole in one of them. My second (almost identical raspberry pi) fails to compile the source code although:

++++++++++++++++++++++
root@LRPB3B:/opt/dnsproxy/dnscrypt-proxy-1.9.5# ./configure --with-systemd
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libsystemd... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/opt/dnsproxy/dnscrypt-proxy-1.9.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
++++++++++++++++++++++

I can see the following error (config.log):
++++++++++++++++++++++
.....
.....
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10) 
configure:4221: $? = 0
configure:4210: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4221: $? = 4
configure:4210: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4221: $? = 4
configure:4241: checking whether the C compiler works
configure:4263: gcc   -DPLUGINS=1  conftest.c  >&5
cc1: internal compiler error: in common_handle_option, at opts.c:1951
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.configure:4267: $? = 1
configure:4305: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "dnscrypt-proxy"
| #define PACKAGE_TARNAME "dnscrypt-proxy"
| #define PACKAGE_VERSION "1.9.5"
| #define PACKAGE_STRING "dnscrypt-proxy 1.9.5"
| #define PACKAGE_BUGREPORT "https://dnscrypt.org"
| #define PACKAGE_URL ""
| #define PACKAGE "dnscrypt-proxy"
| #define VERSION "1.9.5"
| #define HAVE_LIBSYSTEMD 1
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4310: error: in `/opt/dnsproxy/dnscrypt-proxy-1.9.5':
configure:4312: error: C compiler cannot create executables
See `config.log' for more details
.......
.......
++++++++++++++++++++++

I 've checked on the working raspberry pi with DNScrypt installed the related config.log file and does not look similar:
++++++++++++++++++++++
......
......
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10) 
configure:4221: $? = 0
configure:4210: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4221: $? = 4
configure:4210: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4221: $? = 4
configure:4241: checking whether the C compiler works
configure:4263: gcc   -DPLUGINS=1  conftest.c  >&5
configure:4267: $? = 0
configure:4315: result: yes
configure:4318: checking for C compiler default output file name
configure:4320: result: a.out
configure:4326: checking for suffix of executables
configure:4333: gcc -o conftest   -DPLUGINS=1  conftest.c  >&5
configure:4337: $? = 0
configure:4359: result: 
configure:4381: checking whether we are cross compiling
configure:4389: gcc -o conftest   -DPLUGINS=1  conftest.c  >&5
configure:4393: $? = 0
...........
..........
.........
++++++++++++++++++++++

I 've tried upgrading the kernel, install gawk but nothing seems to correct the issue. I haven't tried with a different gcc version (in both cases btw is the same, 4.9.2). What could be the cause of compilation error ?

**Comment by jedisct1** [comment]
` cc1: internal compiler error: in common_handle_option, at opts.c:1951`

The compiler doesn't work on that one. It can't even compile a simple test program without crashing. Maybe due to some data corruption :(

**Comment by orestis46** [comment]
Well it seems that im unable to compile anything related with gcc and C code:

+++++++++++++++++++++++
user@LRPB3B:~ $ hello.c
#include<stdio.h>

main()
{
    printf("Hello World");

}
user@LRPB3B:~ $ gcc hello.c -o cHello
cc1: internal compiler error: in common_handle_option, at opts.c:1951
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
+++++++++++++++++++++++

No problems with gcc and c++ although ....
+++++++++++++++++
user@LRPB3B:~ $ more hello.cc 
#include <iostream>
 
int main()
{
  std::cout << "Hello World!" << std::endl;
  return 0;
}
user@LRPB3B:~ $ gcc hello.cc -o hello -lstdc++
user@LRPB3B:~ $ echo $?
0
user@LRPB3B:~ $ ./hello 
Hello World!
++++++++++++++++++++++++++++++
