### ISSUE TITLE
dnscrypt no longer blocking domains.

### ISSUE THREAD

**Issue by gotenyama** [jedisct1/dnscrypt-proxy#772]
Hi,

Re-opening this since re-generating the file `dnscrypt-blacklist-domains.txt` dnscrypt-proxy has stopped blocking any domains. Also interesting enough I can no longer block any domains even using my old files.

###### Current dnscrypt version:
dnscrypt-proxy 1.9.5
Compilation date: Nov 12 2017
Support for plugins: present
Plugins root directory: [/usr/local/lib/dnscrypt-proxy/]
Support for ldns-based plugins: present
Support for the XChaCha20-Poly1305 cipher: present

###### Current libsodium version
libsodium 1.0.15

###### Current files used for domains blacklsit

[dnscrypt-blacklist-domains.txt](https://gist.githubusercontent.com/anonymous/d8796591287fe859a5d814cb1d3dfb7c/raw/2ae5bf7f56146d9a2314fe3eb27addaa0c8e0c5d/dnscrypt-blacklist-domains.txt)

[domains-blacklist.conf](https://gist.githubusercontent.com/anonymous/1cfe9e50d442c4a3a748f6566e964047/raw/22f6505889ae90aad717592b06a593129ddec534/domains-blacklist.conf)

**Comment by jedisct1** [comment]
Can you confirm that your queries are actually going through the proxy?

Does `resolver.dnscrypt.org` resolve to the IP address of the server you chose?
