### ISSUE TITLE
add quad9.net dns to csv

### ISSUE THREAD

**Issue by pulseone-cp** [jedisct1/dnscrypt-proxy#773]
dns.quad9.net, default port (853)

**Comment by chantra** [comment]
> dns.quad9.net, default port (853)
>
that’s DNS over TLS, not dnscrypt.

>

**Comment by jedisct1** [comment]
They are considering DNSCrypt. But they don't support it yet.

**Comment by snorkasaurus** [comment]
May I ask if Quad 9 would qualify as "no logs" if they were to support DNSCrypt? Their FAQ has statements such as:

> Quad9 gives anonymized telemetry back to the TI providers only for the malicious domains they share with Quad9. This telemetry does not include source IP information of the users.

> When an entity or an individual is using the Quad9 infrastructure, their IP address is not logged in our system. We, however, log the geo-location of the system (city, state, country) and use this information for malicious campaign and actor analysis, as well as a component of the data we provide our threat intelligence partners.

> We store details of the DNS records queried, timestamp, and the city, state, and country from where the query came. We do not store source IP information of end user queries.

While I would agree that their logging appears on the surface to be non-personal, I would not call it "no logs at all".  This might be sufficient privacy for some [or even many] users, but it sounds like it could be a slippery slope of "specific logging", leading up to a point where some line has to be drawn on what qualifies as "no logs".
