### ISSUE TITLE
man in the middle can compromise end-to-end encryption

### ISSUE THREAD

**Issue by ertosns** [jedisct1/dnscrypt-proxy#775]
why first step of generating session pair key isn't done through published certificate, to ensure integrity?
any IRC to discuss the issue?

**Comment by jedisct1** [comment]
The resolver public key is signed; it is part of the certificate. As for integrity the shared secret is required to forge authentication tags. This implies knowing the server secret key or the client secret key. A middlebox can only see public keys.
