### ISSUE TITLE
How to restore default dns

### ISSUE THREAD

**Issue by Drisang** [jedisct1/dnscrypt-proxy#782]
Yelp! I am just a privacy concern end user who just c&p a guide now my internet doesn’t work how do I restore my computer dns settings and get my internet working again?

**Comment by jedisct1** [comment]
What did you install exactly? What operating system are you using?

This project is just a proxy, it doesn't change anything to your DNS settings.

**Comment by snorkasaurus** [comment]
A link to the guide you were using would also be good too.
