### ISSUE TITLE
dnscrypt.org webpage is down?

### ISSUE THREAD

**Issue by Dizirgee** [jedisct1/dnscrypt-proxy#784]
It looks that https://dnscrypt.org/ is down at this time [1.12.17 ~22:00CET] 
Tried various site checkers and everywhere it came as down, so its not just my nw.

Not sure if you have some twitter/fb/etc accounts, I wasn't able to google anything, if you didn't post some outage info there...

Sry to spam it here.

**Comment by jedisct1** [comment]
Yes, it's dead.

**Comment by Dizirgee** [comment]
what is dead? This project? Why not update main page to state such and avoid confusion?

If its dead its a shame, what happened? :(

**Comment by jedisct1** [comment]
The server is dead.
