### ISSUE TITLE
Please add another OpenNIC server

### ISSUE THREAD

**Issue by vp1981** [jedisct1/dnscrypt-proxy#787]
Hello,
according to https://servers.opennic.org/ there is server
`ns7.nh.nl.dns.opennic.glue 146.185.176.36 2a03:b0c0:0:1010::1a7:c001 Famicoman`
that supports opennic and dnscrypt. Please add it to the list 'dnscrypt-resolvers.csv'.

**Comment by jedisct1** [comment]
Can you send a pull request to update the CSV file?

**Comment by vp1981** [comment]
I made pull request #789 .
