### ISSUE TITLE
Help me test dnscrypt.eu-dk

### ISSUE THREAD

**Issue by ajp2k13** [jedisct1/dnscrypt-proxy#791]
i can't get dnscrypt.eu-dk working, could someone please help test it so I know if it's just me or if there's something wrong with the dns server? It doesn't resolve anything when I try...

Thanks!

**Comment by snorkasaurus** [comment]
Here's what I got for dnscrypt.eu-dk:

```
C:\>dnscrypt-proxy-win32-1.9.5>dnscrypt-proxy.exe -R dnscrypt.eu-dk
12/07/17 10:11:31 [INFO] + DNS Security Extensions are supported
12/07/17 10:11:31 [INFO] + Provider supposedly doesn't keep logs
12/07/17 10:11:31 [NOTICE] Starting dnscrypt-proxy 1.9.5
12/07/17 10:11:31 [INFO] Generating a new session key pair
12/07/17 10:11:31 [INFO] Done
12/07/17 10:11:31 [INFO] Server certificate with serial '0001' received
12/07/17 10:11:31 [INFO] This certificate is valid
12/07/17 10:11:31 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
12/07/17 10:11:31 [INFO] Server key fingerprint is D616:D268:09D2:29A7:9457:DE07:3DE8:EBD8:3C24:BFF3:2BF7:B406:108B:44DA:51FE:3711
12/07/17 10:11:31 [NOTICE] Proxying from 127.0.0.1:53 to 77.66.84.233:443
```

And then resolving with it:

```
C:\>nslookup dnscrypt.org 127.0.0.1
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
Name:    dnscrypt.org
Address:  37.59.238.213
```

It seems the trouble you're having might be local.  Are you able to connect to and resolve with other servers?

**Comment by ajp2k13** [comment]
Thanks! I'm able to connect and resolve with other servers (only tried those close to my location). I'm running dnscrypt-proxy on my Netgear R7800 with Voxel firmware so it might not be ideal, not sure how I check the logs either. I just tried it on a Raspberry Pi and it looks like it's working.... very weird. I'll have to check with the firmware author...

**Comment by snorkasaurus** [comment]
Just to clarify...when you say:

> tried it on a Raspberry Pi and it looks like it's working

Does that mean your Pi (which I assume is connecting through your R7800) **can** connect to and resolve with dnscrypt.eu-dk?  If that is what you meant, it certainly would seem like a problem with the R7800.

**Comment by ajp2k13** [comment]
No, I'm using a Pi with dnscrypt installed and I tested it at work so not through the R7800...

**Comment by snorkasaurus** [comment]
I'd suggest trying to connect/resolve from a machine behind the router, which would help determine if the problem is "between you and dnscrypt.eu-dk" or "specifically just that router".

**Comment by ajp2k13** [comment]
I will setup a Pi at home as well and try, thanks for all the help! 👍

**Comment by ajp2k13** [comment]
Hmm, now dnscrypt.eu-dk works on my router as well...hasn’t worked for quite some time.
