### ISSUE TITLE
Cannot change the resolver in the configuration file

### ISSUE THREAD

**Issue by LaTraviata** [jedisct1/dnscrypt-proxy#792]
I am really ashamed to ask this, I know this may seem a stupid question, but I cannot change the resolver in the configuration file. I changed the [CHANGE THIS] part in the configuration file to the [adguard-dns] (is in the resolvers list), yet everytime I run 

`dnscrypt-proxy.exe dnscrypt-proxy.conf`

it chooses random resolvers. Could someone, please, tell me what am I doing wrong?

Thank you in advance.

**Comment by licaon-kter** [comment]
No, that's a comment, all those lines starting with `#` are.

But below you have `ResolverName random` and you change it to `ResolverName adguard-dns` or whatever.

**Comment by LaTraviata** [comment]
Thank you very much, I installed it with the configuration I need. However, when I run 

`hostip -r 127.0.0.1 resolver.dnscrypt.org`

I still don't get the IP of the resolver I chose.

**Comment by licaon-kter** [comment]
```
{ dnscrypt-proxy }  » ./hostip -r 127.0.0.1 resolver.dnscrypt.org
23.226.227.94
```

What do you get? What do you think you should get?

**Comment by LaTraviata** [comment]
I get this:
```
hostip.exe -r 127.0.0.1 resolver.dnscrypt.org 
173.0.140.210
```

Shouldn't I get the IP of the resolver I chose? According to the list it should be 176.103.130.130.

**Comment by licaon-kter** [comment]
No, that's just the IP of the host.

**Comment by LaTraviata** [comment]
So how do I check if the protocol is running fine?

**Comment by licaon-kter** [comment]
You've just proven that it works.

**Comment by LaTraviata** [comment]
Ok, thank you :) Adguard-dns just confirmed that I am using it, so, I guess, everything is working.
