### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by A-L31** [jedisct1/dnscrypt-proxy#793]
![image](https://user-images.githubusercontent.com/34402362/33798305-9bfd2ae6-dd48-11e7-9bc2-80c3e1f89b91.png)

It suddenly happen ... reinstall not working.

Dell Vostro Win10

**Comment by jedisct1** [comment]
Wrong project :)

The one you are looking for is probably https://github.com/bitbeans/SimpleDnsCrypt
