### ISSUE TITLE
dnscrypt-proxy install scripts

### ISSUE THREAD

**Issue by blub4747** [jedisct1/dnscrypt-proxy#794]
Hello,

I noticed that the autoinstall scripts for dnscrypt-proxy are not being mentioned anywhere on the dnscrypt-proxy hp.

Could someone please help me to locate these scripts ?
Thx, blu4747

**Comment by jedisct1** [comment]
Actually, the very first paragraph of the "how to install DNSCrypt" page contains a link to the precompiled packages :) https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-install-DNSCrypt

**Comment by blub4747** [comment]
sorry about that.
I was soo juste to find them links on the main hp and when there was no word of them at all anymore.
I was worried that it was maybe retired.
It be nice too one site with all of them dnscrypt related links on them. Instead of all of them being scattered around.
Thx,blub474
