### ISSUE TITLE
quick question about the output

### ISSUE THREAD

**Issue by blub4747** [jedisct1/dnscrypt-proxy#795]
Hi guys,

I installed dnscrypt-proxy on my ubuntu system by following the instructions from the following site.

http://www.webupd8.org/2014/08/encrypt-dns-traffic-in-ubuntu-with.html

When I run the 
`dig txt debug.opendns.com`
I am missing the entire output section which should look like this
answer section
`;; ANSWER SECTION:`
`debug.opendns.com. 0 IN TXT "server m2.otp"`
`debug.opendns.com. 0 IN TXT "flags 20 0 70 7950800000000000000"`
`debug.opendns.com. 0 IN TXT "originid 0"`
`debug.opendns.com. 0 IN TXT "actype 0"`
`debug.opendns.com. 0 IN TXT "source [REDACTED-YOUR IP]"`
`debug.opendns.com. 0 IN TXT "dnscrypt enabled (717473654A614970)"`

`;; Query time: 31 msec`
`;; SERVER: 127.0.2.1#53(127.0.2.1)`
`;; WHEN: Wed Feb 08 16:46:09 EET 2017`
`;; MSG SIZE  rcvd: 249`

can someone please tell what is going wrong or missing in my version vs the one from the article ?
Thx,

**Comment by jedisct1** [comment]
Do not follow irrelevant/obsolete instructions from some random website.

Instructions are here: https://github.com/jedisct1/dnscrypt-proxy/wiki
