### ISSUE TITLE
Installed on Win10 x64, but cannot change server

### ISSUE THREAD

**Issue by pbbuk** [jedisct1/dnscrypt-proxy#796]
I seem to have installed successfully with an admin command prompt (albeit using an old tutorial: 
https://www.howtogeek.com/203139/how-to-encrypt-your-dns-for-more-secure-browsing/)

See attachments: 1. DNS Installation Sequence.jpg and 2. Correct Server is being used.jpg

However when I try to change the server used I get: 
'Unable to bind (UDP) [Address already in use [WSAEADDRINUSE ]]'
See attachment: 3. Attempt to use random server.jpg

Can someone suggest anything?

PS: I can't get the image upload to work, they're on imgur:
1. https://i.imgur.com/ZhT8kYD.jpg
2. https://i.imgur.com/tBGebmn.jpg
3. https://i.imgur.com/ZUsbWCj.jpg

**Comment by jedisct1** [comment]
The instructions from that website are terrible and can't possibly work.

Forget all your read here, uninstall everything, and just use [simplednscrypt](https://simplednscrypt.org/).

**Comment by pbbuk** [comment]
Thank you for replying.

I took your advice and installed SimpleDNS, but, in spite of it seeming
to have installed successfully, my network adaptor's DNS entry is still
at 8.8.8.8 not 127.0.0.1. If I change it manually, my browsers (and a
command line) can't resolve URLs! The hostip program returns [name does
not exist].

I appear to be caught between two stools.

**Comment by snorkasaurus** [comment]
If you can't resolve names via 127.0.0.1 then it sounds like there is no local proxy software (either dnscrypt-proxy or Simple DNSCrypt) listening on your 127.0.0.1 address.

If you did remove dnscrypt-proxy and installed Simple DNSCrypt, then the folks at [Simple DNSCrypt](https://github.com/bitbeans/SimpleDnsCrypt/issues) are likely better equipped to explain why it isn't listening on 127.0.0.1.  Having said that, my experience with Windows 10 is limited, but I would not be surprised if a firewall (Windows native firewall or an installed firewall application) is keeping you from being able to resolve names via 127.0.0.1.
