### ISSUE TITLE
Makefile.am dnscrypt-resolvers repo edits needed

### ISSUE THREAD

**Issue by glitsj16** [jedisct1/dnscrypt-proxy#797]
Hi, I noticed the recent decoupling of dnscrypt-resolvers related files into a [dedicated repo](https://github.com/dnscrypt/dnscrypt-resolvers). Yet [Makefile.am](https://github.com/jedisct1/dnscrypt-proxy/blob/master/Makefile.am) refers to non-existing files in that context (lines 31 to 35), currently breaking the build from git master:
```
dist_pkgdata_DATA = \
	dnscrypt-resolvers/dnscrypt-resolvers.csv \
	dnscrypt-resolvers/dnscrypt-resolvers.csv.minisig \
	dnscrypt-resolvers/dnscrypt-resolvers.csv.sig \
	dnscrypt-resolvers/minisign.pub
```
If I'm not mistaken (which is very much possible), after [commit](https://github.com/DNSCrypt/dnscrypt-resolvers/commit/40c4c1011147028284d48c6a59ac5b0c848cb47d), these need the 'v1' part, like:

```
dist_pkgdata_DATA = \
	dnscrypt-resolvers/v1/dnscrypt-resolvers.csv \
	dnscrypt-resolvers/v1/dnscrypt-resolvers.csv.minisig \
	dnscrypt-resolvers/v1/dnscrypt-resolvers.csv.sig \
	dnscrypt-resolvers/v1/minisign.pub
```
Just a FYI, regards.

**Comment by jedisct1** [comment]
Indeed, thanks!
