### ISSUE TITLE
Query Log of Forwarded domains should show the DNS used

### ISSUE THREAD

**Issue by physkets** [jedisct1/dnscrypt-proxy#799]
The queries that are logged in `/tmp/dns-queries.log` have a column indicating the IP address that is queried, which is always `127.0.0.1`. But for those domains that are forwarded using the plugin, it would be nice if the log indicated the specific DNS that was used.

**Comment by jedisct1** [comment]
This is a great suggestion, but it's difficult to do since these are two distinct plugins.

Maybe this can be added once this piece of junk has been completely rewritten, since the concept of plugins is unlikely to stay.
