### ISSUE TITLE
Just wondering why Yandex was removed?

### ISSUE THREAD

**Issue by mastad0n** [jedisct1/dnscrypt-proxy#801]
Hey :)

Let me start off by thanking you for your hard work!

I was just wondering why yandex was removed?

I don't really know how to test if it's still working, does it not work anymore?

Thank you!

**Comment by jedisct1** [comment]
Because it didn't work any more. The certificate expired, they didn't renew it and apparently didn't even notice or didn't care.

The list of resolvers has moved here: https://github.com/DNSCrypt/dnscrypt-resolvers
