### ISSUE TITLE
Starting the daemon on Android

### ISSUE THREAD

**Issue by nodje** [jedisct1/dnscrypt-proxy#98]
I know it's unrelated to the project per se,  but would be nice to have a little explanation on how to run dnscrypt-proxy as a persistent daemon on Android.

Cheers

**Comment by Bretos** [comment]
Can't get it to work with Andorid 5.0 Lolipop (Cyanogenmod 12). Could you guys relate if it's lack of my skills, or a common problem?

**Comment by Bretos** [comment]
I've compiled it using [previously posted guide](http://forum.xda-developers.com/showpost.php?p=56068030&postcount=20).
Flashable zip is [here](http://speedy.sh/PgBAD/dnscrypt-android.zip) however I advise to compile dnscrypt on your own. Tested ONLY on Motorola Moto G(falcon) running official CM12 nightly.

**Comment by jedisct1** [comment]
Android 5.x requires the `-pie` flag. The flag was initially removed in order to support older systems, but since Jellybean/platform 16 it's not required any more.
The build scripts have been updated accordingly.
